open-formulieren/open-forms

- package-lock.json
- package.json
- src/openforms/forms/api/serializers.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/templates/admin/forms/form/change_form.html
- src/openforms/forms/tests/test_api.py
- src/openforms/forms/tests/test_models.py
- src/openforms/js/components/admin/form_design/Context.js
- src/openforms/js/components/admin/form_design/Editor.js
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/index.js
Fixes part of #437:
-  Add back the 'Active' checkbox
- Add back the 'is deleted' checkbox (soft-delete)
- Add back the 'maintenance mode' checkbox
- Add a field to update the text displayed in the submission confirmation page.
> Feature #437 - First set of additions

- .bumpversion.cfg
- .readthedocs.yaml
- LICENSE.md
- README.NL.rst
- README.rst
- docs/conf.py
- docs/introduction/index.rst
- docs/introduction/open-source/index.rst
- docs/introduction/team.rst
- publiccode.yaml
> Open source update

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
> [#315] Added support for partial dates in StUF ZDS backend and apply to 'geboortedatum'

- src/openforms/forms/static/forms/scss/components/builder/_admin-fixes.scss
- src/openforms/forms/static/forms/scss/components/builder/_builder.scss
The jumping around input for the select dropdown was ugly because of Django's added styles.
> Fix choices JS styling in admin

- src/openforms/authentication/contrib/digid/tests/data/ArtifactResponse.xml
- src/openforms/authentication/contrib/digid/tests/data/ArtifactResponseCancelLogin.xml
- src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py
- src/openforms/authentication/contrib/digid/views.py
Fixes #518 
This PR requires the following SDK PR: https://github.com/open-formulieren/open-forms-sdk/pull/45
> Issue #518 - Handle DigiD authentication failure

- package.json
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/static/forms/scss/components/admin/_index.scss
- src/openforms/forms/static/forms/scss/components/admin/_sdk-snippet.scss
- src/openforms/forms/templates/admin/forms/form/_snippet.html
- src/openforms/forms/templates/admin/forms/form/change_form.html
- src/openforms/forms/templates/forms/sdk_snippet.html
- src/openforms/forms/tests/test_api.py
- src/openforms/js/components/admin/index.js
- src/openforms/js/components/admin/sdk-snippet.js
Fixes #405
* Copy snippets
* Style snippets as read-only code blocks
> Form snippets - quality of life fixes

- src/openforms/authentication/contrib/digid/mixins.py
- src/openforms/authentication/contrib/digid/views.py
- src/openforms/authentication/contrib/eherkenning/tests/data/ArtifactResponse.xml
- src/openforms/authentication/contrib/eherkenning/tests/data/ArtifactResponseCancelLogin.xml
- src/openforms/authentication/contrib/eherkenning/tests/test_auth.py
- src/openforms/authentication/contrib/eherkenning/views.py
Fixes #527 
Corresponding SDK PR: https://github.com/open-formulieren/open-forms-sdk/pull/47
> Issue #527 - Cancel EHerkenning login

- src/openforms/authentication/api/tests/test_logout.py
- src/openforms/authentication/api/urls.py
- src/openforms/authentication/api/views.py
> Feature #532 - Logout endpoint

- src/openforms/registrations/contrib/stuf_zds/client.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
SOAP-version and other envelope params were not passed correctly to the template.
Also, SOAP 1.1 uses a different Content-Type it seems.
> Fixes passing SOAP-version and content-type

- src/openforms/forms/admin/form_definition.py
- src/openforms/forms/tests/admin/test_form_definition.py
Fixes #542 
**Screenshots**
I had two forms with this in their form steps
> Fix used in attribute

- src/openforms/forms/api/serializers.py
- src/openforms/forms/templates/admin/forms/form/change_form.html
- src/openforms/js/components/admin/form_design/FormMetaFields.js
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/index.js
Fixes #546 
**Screenshots**
Creating a form with no registration backend or options
Adding just the registration backend
Adding both
Changing both
> Add backend registration to react crud

- docs/installation/config.rst
- src/openforms/conf/base.py
Fixes #533
* Defaults have been increased by throttling per hour rather than per
day
* Throttle rates are now configurable through the environment
* Documented the new environment variables
> Tweak throttling configuration

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/FormModal.js
- src/openforms/js/components/admin/Modal.js
- src/openforms/js/components/admin/form_design/AuthPluginField.js
- src/openforms/js/components/admin/form_design/ChangedFormDefinitionWarning.js
- src/openforms/js/components/admin/form_design/FormObjectTools.js
- src/openforms/js/components/admin/form_design/FormStep.js
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/admin/form_design/FormSteps.js
- src/openforms/js/components/admin/form_design/FormStepsNav.js
- src/openforms/js/components/admin/form_design/NewStepFormDefinitionPicker.js
- src/openforms/js/components/admin/form_design/PluginWarning.js
- src/openforms/js/components/admin/forms/Inputs.js
- src/openforms/js/components/admin/forms/SubmitRow.js
- src/openforms/js/i18n-formatter.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
Went through the remaining components and I added translations.
> React CRUD translations

- Dockerfile
Fixes #570 
- Include SDK files from open-forms-sdk, see https://github.com/open-formulieren/open-forms-sdk/pull/40
> Include SDK files, resolves issue: 570

- src/openforms/registrations/api/tests/test_endpoints.py
- src/openforms/registrations/contrib/objects_api/config.py
> Issue #608 - Broken plugin endpoint

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Updated the 2fa package: https://github.com/maykinmedia/django-two-factor-auth/blob/master/CHANGELOG.rst
> Update 2fa package for better UX

- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/tests/test_submission_completion.py
- src/openforms/submissions/utils.py
Fixes #262 
Not sure if we want this merged into master or if I should rebase on `submission-process-tasks-orchestration` and update this PR into that branch?  I guess this code will need to change for that branch but I'm not sure if a better flow is to merge this into master and update it in `submission-process-tasks-orchestration` or rebase on `submission-process-tasks-orchestration` and then merge into that branch.  I'm fine with either flow :) 
**Screenshot**
Mail output from the unit test displayed with an email tester tool from MailChimp
> Add appointment details to confirmation email

- docs/configuration/authentication/index.rst
- docs/configuration/authentication/oidc.rst
- docs/configuration/index.rst
- docs/configuration/payment/index.rst
- docs/configuration/payment/ogone.rst
- docs/configuration/prefill/bag.rst
- docs/configuration/prefill/index.rst
- docs/configuration/registration/email.rst
- docs/configuration/registration/index.rst
- docs/configuration/registration/local.rst
- docs/configuration/registration/objects.rst
- docs/configuration/registration/stufzds.rst
- docs/configuration/registration/zgw.rst
- docs/installation/config.rst
- docs/manual/accounts.rst
- docs/manual/forms/examples/autofill_address.rst
> [#621] Added docs for registration backends, and sectioned configuration docs

- docs/configuration/registration/email.rst
- docs/configuration/registration/local.rst
- docs/configuration/registration/objects.rst
- docs/configuration/registration/stufzds.rst
- docs/configuration/registration/zgw.rst
> Updated objects API docs.

- src/openforms/authentication/contrib/digid/mixins.py
- src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py
- src/openforms/authentication/contrib/eherkenning/tests/test_auth.py
Fixes #675 
Front end: https://github.com/open-formulieren/open-forms-sdk/pull/67
> [#675] Issues reported by logius

- docs/developers/sdk/embedding.rst
- docs/installation/config.rst
- src/openforms/conf/base.py
- src/openforms/forms/context_processors.py
- src/openforms/forms/templates/forms/sdk_snippet.html
Fixes #657 
SDK PR: https://github.com/open-formulieren/open-forms-sdk/pull/71
> [#657] Set up SDK Sentry

- docs/configuration/payment/ogone.rst
- docs/configuration/prefill/bag.rst
- docs/configuration/prefill/haal_centraal.rst
- docs/configuration/prefill/index.rst
- docs/configuration/prefill/kvk.rst
- docs/configuration/prefill/stuf_bg.rst
- docs/configuration/prefill/stufbg.rst
- docs/configuration/registration/objects.rst
- docs/configuration/registration/stufzds.rst
- docs/configuration/registration/zgw.rst
- docs/developers/sdk/embedding.rst
- docs/manual/forms/examples/index.rst
- docs/manual/forms/examples/prefill.rst
> Add prefill backend documentation

- src/openforms/logging/templates/logging/admin_list.html
Fixes third point of #728 
**Screenshot**
> Paginate TimelineLogProxyAdmin list view

- src/openforms/payments/contrib/ogone/client.py
- src/openforms/payments/contrib/ogone/tests/test_plugin.py
> [#756] Hardened Ogone incoming parameters handling to allow additional/ignored params

- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/contrib/jcc/tests/mock/GenericGuidanceSystem2.wsdl
> JCC made isRecurring a required field

- src/openforms/appointments/tests/test_utils.py
- src/openforms/appointments/utils.py
- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_models.py
- src/stuf/stuf_bg/client.py
Fixes #725 
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/83
> [#725] Appointment improvements

- docs/manual/forms/examples/appointment_creation.rst
- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/tests/test_utils.py
- src/openforms/appointments/utils.py
- src/openforms/js/components/admin/form_design/Appointments.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_models.py
> Add phone number to jcc client

- src/openforms/js/components/admin/form_design/RegistrationFields.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/forms/Field.js
- src/openforms/js/components/admin/forms/FormRow.js
- src/openforms/scss/_vendor.scss
- src/openforms/scss/vendor/_rjsf.scss
> [#678] Admin frontend for plugin validation

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#824] Logic checks on nested components

- src/openforms/forms/api/serializers.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/RJSFWrapper.js
- src/openforms/js/components/admin/form_design/DataRemoval.js
- src/openforms/js/components/admin/form_design/PaymentFields.js
- src/openforms/js/components/admin/form_design/RegistrationFields.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/scss/_vendor.scss
- src/openforms/scss/vendor/_tinymce.scss
Fixes #720
* Added the missing tabs
* Refactored some components
> Finalize showing backend validation errors from the backend

- docs/installation/config.rst
- src/openforms/conf/base.py
Fixes #880 (In addition to regenerating the metadata/dienstcatalogus with the right UUIDs and updating the deployment scripts).
> [#880] New eHerkenning/eIDAS settings

- src/openforms/js/components/form/select.js
- src/openforms/js/lang/formio/nl.json
Fixes #198 
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/101
> [#198] Make select widget configurable

- src/openforms/conf/dev.py
See https://github.com/open-formulieren/open-forms/pull/871/files#r744773436
> Optionally disable CSP report endpoint rate limiting

- src/openforms/conf/base.py
- src/openforms/tests/test_celery_beat.py
> [#886] Fixed Celery Beat configuration issue

- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/lang/formio/nl.json
Blocked by 
* https://github.com/open-formulieren/open-forms-sdk/issues/8
* https://github.com/open-formulieren/open-forms-sdk/issues/103
---
Part of #217
> [#217] Enable multiple values for input fields

- src/openforms/forms/admin/form.py
> [#903] Added .internal_name to Form admin search

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/js/components/formio_builder/builder.js
- src/openforms/js/components/formio_builder/customTemplates.js
- src/openforms/js/components/formio_builder/templates/builderSidebar.js
- src/openforms/js/lang/formio/nl.json
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/registration_payment_update_failure.txt
- src/openforms/logging/templates/logging/events/registration_payment_update_skip.txt
- src/openforms/logging/templates/logging/events/registration_payment_update_start.txt
- src/openforms/logging/templates/logging/events/registration_payment_update_success.txt
- src/openforms/payments/services.py
- src/openforms/submissions/tasks/emails.py
- src/openforms/submissions/tasks/registration.py
- src/openforms/submissions/tests/test_tasks_confirmation_emails.py
Fixes #867 
* Override template to add missing translation
* Removed 1 and I from character set for reference generation
* Fixed race condition, now multiple confirmation e-mails should not be sent anymore
* Added extra audit log entries on payment update with the registration backend
> Various small fixes

- src/openforms/registrations/contrib/email/plugin.py
> [#829] Use labels instead of keys in email registration

- src/openforms/registrations/contrib/email/plugin.py
> [#832] Apply local timezone to datetime in email registration

- src/openforms/submissions/templates/report/submission_report.html
> [#879] Fixed forced capitalisation of labels in PDF

- src/openforms/submissions/templates/report/submission_report.html
> [#879] Removed unused mystery headers from PDF

- src/openforms/js/components/admin/form_design/form-creation-form.js
> [#916] Fixed 'reusable' checkbox of selected existing FormDefinition not being selected

- src/openforms/authentication/views.py
> [#911] Allow login even if not required

- docs/configuration/prefill/bag.rst
Update documentation with updated bag config url. 
Fixes #835
> update OAS url in bag config documentation

- src/openforms/forms/api/permissions.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/templates/core/views/form/form_list.html
- src/openforms/forms/tests/test_api.py
- src/openforms/forms/tests/test_views.py
- src/openforms/forms/views/form.py
> [#926] Block form listing in HTML and API if user not staff

- src/openforms/emails/confirmation_emails.py
- src/openforms/emails/tests/test_confirmation_email.py
> [#917] Use django formatting for currency in emails

- src/stuf/stuf_bg/client.py
- src/stuf/stuf_bg/tests/test_client.py
- src/stuf/stuf_zds/tests/test_backend.py
> [#933] Added SOAPAction header to Stuf BG client 

- src/openforms/js/components/form/email.js
- src/openforms/js/lang/formio/nl.json
- src/openforms/translations/views.py
> [#892] Email validation on blur

- src/openforms/js/components/form/date.js
- src/openforms/js/components/form/time.js
- src/openforms/js/lang/formio/nl.json
Fixes #902 
Corresponding frontend PR for the time validator: https://github.com/open-formulieren/open-forms-sdk/pull/109
> [#902] Added min/max date setting

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> [#920] Updated zgw-consumers dependency (with new 'oas_file' field)

- src/openforms/logging/models.py
- src/openforms/prefill/tests/test_prefill_hook.py
- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_admin.py
> [#943] Added filter to hide AVG TimelineLogProxies from Submission change view

- src/openforms/js/components/admin/form_design/DataRemoval.js
- src/openforms/js/components/admin/forms/Inputs.js
- src/openforms/scss/_vars.scss
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/components/builder/_builder.scss
- src/openforms/scss/vendor/_rjsf-field.scss
> [#748] Admin CSS tweaks

- src/openforms/js/lang/formio/nl.json
- src/openforms/submissions/templates/report/submission_report.html
> [#974] Sprint 9 improvements

- src/openforms/forms/models/form_step.py
- src/openforms/forms/tests/test_models.py
> [#935] Improve FormStep.__str__()

- src/openforms/js/components/form/edit/components.js
- src/openforms/js/components/form/number.js
- src/openforms/js/formio_module.js
- src/openforms/js/lang/formio/nl.json
> [#914] Add min/max number field validation

- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_submission_report.py
> Printable data for radio/select components in submission report 

- src/openforms/registrations/contrib/microsoft_graph/plugin.py
- src/openforms/registrations/contrib/microsoft_graph/tests/test_backend.py
> [#980] Handle service not configured in Microsoft graph registration

- docs/configuration/authentication/oidc.rst
> Expand OIDC docs with Azure AD instructions

- src/openforms/forms/api/serializers.py
- src/openforms/forms/tests/test_api_form_logic.py
- src/openforms/js/components/admin/form_design/logic/Trigger.js
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#891] Fix logic selectboxes

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/PaymentFields.js
- src/openforms/js/components/admin/form_design/PriceLogic.js
- src/openforms/js/components/admin/form_design/ProductFields.js
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/data.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/logic-data.js
- src/openforms/js/components/admin/form_design/logic/Trigger.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/scss/components/admin/_logic-action.scss
- src/openforms/scss/components/admin/_logic-rule.scss
- src/openforms/scss/components/admin/_logic-trigger.scss
Partially fixes #235
**Changes**
* Grouped product/payment tab fields into fieldsets
* Added control to toggle between static/dynamic pricing logic (static = use linked product)
* Added pricing rules (if X then price is Y)
> Dynamic pricing UI

- src/openforms/submissions/admin.py
- src/openforms/submissions/apps.py
- src/openforms/submissions/exports.py
- src/openforms/submissions/tests/test_admin.py
> [#242] Added JSON and XML formats to Submission list export

- src/openforms/registrations/contrib/microsoft_graph/plugin.py
- src/openforms/registrations/contrib/microsoft_graph/tests/test_backend.py
> [#981] Fixed MS Graph registration folder name sanitization

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> Bump sqlparse

- src/openforms/logging/models.py
- src/openforms/logging/tests/test_admin.py
- src/openforms/logging/tests/test_models.py
> [#987] Fixed AVG timelinelog admin view

- src/openforms/js/components/form/index.js
- src/openforms/js/components/form/licenseplate.js
- src/openforms/js/components/formio_builder/builder.js
- src/openforms/js/formio_module.js
- src/openforms/js/lang/formio/nl.json
Part of #195
Related frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/123
> [#195] Added license plate component

- src/openforms/appointments/tests/test_endpoints.py
- src/openforms/appointments/views.py
- src/openforms/submissions/query.py
- src/openforms/submissions/tests/test_models.py
- src/openforms/submissions/views.py
> [#957] Re-login when cancelling/updating appointments

- .github/workflows/ci.yml
- src/openapi.yaml
This CI change causes PRs to fail if the OAS is not updated as part of the PR.
Before, we updated the OAS via the CI but this failed (see 2nd commit in this PR...). It's also more clear what changed in the API if the updated OAS is part of a PR.
I still kept the OAS generation inside the test step, and perform the comparison after the tests to prevent creating a whole new app installation just for that.
> Update the OAS and check if OAS is up to date

- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/form/file.js
> [#827] Add validation tab to File field

- src/openforms/submissions/models.py
> Fixes selects rendering in DPF

- src/openforms/scss/_vars.scss
- src/openforms/scss/admin/_admin_theme.scss
> :lipstick: [#1077] Fix admin help text hover

- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/lang/formio/nl.json
> Added several translations.

- src/openforms/registrations/contrib/zgw_apis/service.py
otherwise issues will occur when trying to close related Zaken
> :bug: Set indicatieGebruiksrecht to False for documents

- .gitmodules
- nlx/.env
- nlx/.gitignore
- nlx/README.md
- nlx/docker-compose.override.yml
- nlx/docker-compose.yml
- nlx/init-databases.sh
- nlx/main.py
- nlx/obtain-certs.sh
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Related to #255
This PR scripts the NLX stack as much as possible and includes/documents workarounds. The findings have been reported upstream.
> NLX integration

- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_models.py
- src/openforms/submissions/tests/test_submission_report.py
> [#1075] Fixed datetime and date localisation display in printable data

- docker/camunda/0001-init-db.sh
- docker/camunda/Dockerfile
- docker/camunda/README.md
- docker/camunda/web.xml
- docker/docker-compose.camunda.yml
- docs/configuration/registration/camunda.rst
- docs/configuration/registration/index.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/conf/base.py
- src/openforms/config/templates/admin/config/overview.html
- src/openforms/config/views.py
- src/openforms/fixtures/default_admin_index.json
- src/openforms/registrations/contrib/camunda/__init__.py
- src/openforms/registrations/contrib/camunda/apps.py
- src/openforms/registrations/contrib/camunda/checks.py
- src/openforms/registrations/contrib/camunda/plugin.py
Boilerplate/initial set up for #326 
* Add plugin definition with config self-tests
* Add documentation
* Add tooling for local development/testing
* Added django-camunda dependency
> Camunda integration - adding dependencies/boilerplate

- setup.cfg
- src/openforms/appointments/api/tests/test_endpoints_with_qmatic.py
- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/contrib/qmatic/client.py
- src/openforms/appointments/contrib/qmatic/plugin.py
- src/openforms/appointments/management/commands/appointment.py
Fixes #1109 
Allows you to show, create and cancel appointments from the commandline.
Specifically useful to debug the plugin without using a form.
> Fixed Qmatic issues and added console command

- src/openforms/js/components/admin/form_design/utils.js
- src/openforms/js/components/admin/forms/ComponentSelection.js
> [#939] Added form step name to component selectors

- nlx/README.md
Updated submodule for latest nlx-try-me which negates some of our workarounds
> Use latest nlx-try-me

- src/openforms/utils/email.py
- src/openforms/utils/tests/test_email.py
> [#1081] Modified send_mail_plus() to transparently convert datauri images to related attachments

- setup.cfg
- src/openforms/conf/base.py
- src/openforms/registrations/contrib/camunda/plugin.py
- src/openforms/registrations/contrib/camunda/tests/test_backend.py
- src/openforms/registrations/management/commands/register_submission.py
Relates to #326
**Changes**
* Kick off process instance: latest version (by key) or specific version (by ID)
* Temporary: hardcoded process variables for the Camunda demo app (invoice)
* Error handling
* Small management command to run registration for a submission (dev only)
> Camunda: start process instance with submission data process variables

- src/openforms/appointments/tests/test_endpoints.py
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/transfer_payment_to_submission_copy.txt
- src/openforms/payments/contrib/demo/plugin.py
- src/openforms/submissions/query.py
- src/openforms/submissions/status.py
- src/openforms/submissions/tests/test_submission_status.py
Fixes #1072 
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/131
> [#1072] Payment after appointment

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
> [#1085] Fixed Stuf-ZDS payment processing issue 

- src/openforms/authentication/signals.py
- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/signals.py
- src/openforms/submissions/tests/test_submission_completion.py
> [#1074] Clean auth details on submission complete

- src/openforms/forms/admin/form.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/models/form.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/forms/tests/test_api_formsteps.py
- src/openforms/forms/tests/test_form_admin.py
- src/openforms/forms/tests/test_models.py
- src/openforms/forms/validators.py
- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/tests/test_start_submission.py
> [#991] Aded support for Form._is_deleted 'soft-delete' in admin and API

- src/openforms/registrations/contrib/email/plugin.py
- src/openforms/registrations/contrib/email/tests/test_backend.py
> [#1122] Fixed submission report missing .pdf extension in email registration backend

- src/openforms/prefill/contrib/stufbg/plugin.py
- src/openforms/prefill/contrib/stufbg/tests/test_co_sign.py
- src/stuf/stuf_bg/constants.py
- src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml
- src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponse.xml
- src/stuf/stuf_bg/tests/test_client.py
> [#1082] Added more prefill attributes to Stuf-BG

- src/openforms/accounts/tests/factories.py
- src/openforms/appointments/tests/test_admin.py
- src/openforms/config/tests/test_config_check.py
- src/openforms/forms/api/permissions.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/test_api_form_plugin_options.py
- src/openforms/forms/tests/test_api_form_versions.py
- src/openforms/forms/tests/test_api_formdefinition.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/forms/tests/test_api_formsteps.py
- src/openforms/forms/tests/test_api_import_export.py
- src/openforms/forms/tests/test_formdefinition_admin.py
- src/openforms/registrations/contrib/camunda/tests/test_backend_options.py
Closes #1000
Fixes open-formulieren/security-issues#2
> [#1000] Implemented and applied custom permission for FormAPI viewsets

- docs/developers/index.rst
- docs/developers/roadmap.rst
Tickets are useful, but don't provide overview/go-to area's for challenging parts to tackle.
Some of these will/should be tackled when implementing new stuff for other involved parties so we can clean up some (pending) technical debt.
> Describe technical roadmap topics

- docs/manual/templates.rst
- src/openforms/emails/templates/emails/templatetags/form_summary.txt
> Added template examples.

- src/openforms/payments/models.py
- src/openforms/registrations/contrib/email/config.py
- src/openforms/registrations/contrib/email/plugin.py
- src/openforms/registrations/contrib/email/templates/emails/email_registration.html
- src/openforms/registrations/contrib/email/templates/emails/email_registration.txt
- src/openforms/registrations/contrib/email/tests/test_backend.py
> [#1126] Email registration backend payment update changes

- build/tasks/watch.js
- src/openforms/forms/api/serializers.py
- src/openforms/forms/api/validators.py
- src/openforms/forms/tests/test_api_form_logic.py
- src/openforms/js/components/admin/form_design/Appointments.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/utils.js
#1174
* Fixed advanced logic validation
* Added more tests for advanced/simple logic rule validation
* Fixed appointments configuration tab in form designer
> Backend bug fixes for sprint 11 demo

- nlx/README.md
- nlx/docker-compose.override.yml
Updated to the latest try-me git submodule & adapted our overrides.
> Update NLX sample integration for local development

- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/contrib/qmatic/plugin.py
- src/openforms/submissions/admin.py
- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_submission_report.py
> Fix PDF/e-mail summary formatting issues

- src/openforms/emails/tests/factories.py
- src/openforms/forms/api/serializers.py
- src/openforms/forms/tests/test_api_import_export.py
- src/openforms/forms/utils.py
Fixes #1168
(also refactored mapping in utils.py)
> [#1168] Fixed import with form_specific_email option enabled

- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/lang/formio/nl.json
> [#1019] Add placeholder for text field

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- bin/bumpversion.sh
- docs/developers/index.rst
- docs/developers/releases.rst
- docs/developers/sdk/embedding.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
SDK: https://github.com/open-formulieren/open-forms-sdk/pull/147
> Versioning setup + prepare 1.0.0-rc.0 version

- src/openforms/js/components/admin/form_design/data.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
> [#986] Mark steps/definitions as 'not new' after they are saved

- src/openforms/forms/tests/test_api_import_export.py
- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/utils.py
> [#1217] Fixed import with duplicate Form slug

- src/openforms/prefill/__init__.py
- src/openforms/prefill/tests/test_prefill_hook.py
> [#1212] Handle prefill hook exception more graceful

- src/openforms/js/components/form/fieldset.js
> [#1123] Re-added logic tab to fieldset

- src/openforms/prefill/contrib/stufbg/plugin.py
- src/openforms/prefill/contrib/stufbg/tests/test_plugin.py
- src/openforms/prefill/contrib/stufbg/tests/utils.py
- src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgNoObjectResponse.xml
- src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgNotFoundResponse.xml
> [#1206] Refactored StufBG prefill config check to accept response without proper fault node

- src/openforms/formio/service.py
- src/openforms/formio/tests/test_service.py
- src/openforms/forms/api/serializers.py
- src/openforms/js/components/form/file.js
> [#1208] Implemented dynamic file upload urls in form configurations

- docs/configuration/appointment/jcc.rst
- docs/configuration/appointment/qmatic.rst
- docs/configuration/payment/ogone.rst
- docs/configuration/prefill/bag.rst
- docs/configuration/prefill/haal_centraal.rst
- docs/configuration/prefill/kvk.rst
- docs/configuration/prefill/stuf_bg.rst
- docs/configuration/registration/msgraph.rst
- docs/configuration/registration/objects.rst
- docs/configuration/registration/stufzds.rst
- docs/configuration/registration/zgw.rst
- src/openforms/fixtures/default_admin_index.json
Fixes #1247 
Note: while going through the documentation, I noticed that these parts are not accurate anymore:
- docs/configuration/appointment/jcc.rst:8
- docs/configuration/general/oidc.rst:50
> [#1247] Admin menu too long

- .github/workflows/code_quality.yml
- src/openforms/fixtures/admin_index_unlisted.json
- src/openforms/utils/management/commands/check_admin_index.py
To catch fixture changes, for example https://github.com/open-formulieren/open-forms/pull/1248 skipped the admin-index model check
> Run the 'Code quality' CI job also on .json and .yaml changes

- src/openforms/js/components/formio_builder/builder.js
> [#1243] make onComponentMutated optional

- src/openforms/js/lang/formio/nl.json
> [#1252] Missing translation

- docs/installation/config.rst
- docs/installation/issues/auth.rst
- src/openforms/conf/base.py
Allows you to set signing preference via env vars. Also documented errors related to this.
> Allow for configurable DigiD XML signing

- src/openforms/ui/templates/ui/components/footer/footer.html
- src/openforms/ui/tests/test_footer.py
> [#1291] Configure policy link

- src/openforms/js/components/form/map.js
> [#1288] Fix div notation in map component

- docs/configuration/general/analytics.rst
- docs/configuration/general/cookies.rst
The relation between analytics and cookies was not clear enough.
> Clarified cookies and analytics

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/AuthenticationWarning.js
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
> [#1275] Add warning if no login requried for familyMembers

- src/openforms/forms/admin/form_definition.py
- src/openforms/forms/tests/admin/test_form_definition.py
> [#1258] Dont show deleted forms in FormDefinition Admin

- src/openforms/js/components/form/signature.js
> [#1285] Remove multiple from signature component

- docs/installation/config.rst
- src/openforms/conf/base.py
> [#1269] Added SESSION_EXPIRE_AT_BROWSER_CLOSE env variable

- docs/developers/backend/core/utils.rst
- src/openforms/emails/admin.py
- src/openforms/submissions/admin.py
- src/openforms/utils/admin.py
- src/openforms/utils/apps.py
> [#1273] Readonly logs

- src/openforms/forms/models/form.py
- src/openforms/forms/tests/admin/test_form.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/forms/tests/test_copy.py
> [#1280] Copy forms with non-reusable steps

- src/openforms/emails/templates/emails/templatetags/form_summary.html
- src/openforms/emails/templates/emails/templatetags/form_summary.txt
- src/openforms/registrations/contrib/email/templates/emails/email_registration.html
- src/openforms/registrations/contrib/email/templates/emails/email_registration.txt
- src/openforms/submissions/models.py
- src/openforms/submissions/templates/report/submission_report.html
- src/openforms/submissions/tests/test_models.py
- src/openforms/submissions/tests/test_submission_report.py
> [#1099] Deal with duplicate keys in printable_data

- src/openforms/submissions/exports.py
- src/openforms/submissions/tests/test_admin.py
- src/openforms/submissions/tests/test_admin_export.py
> [#1272] Hardened XML submission export to handle multi-value fields

- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/forms/tests/test_api_formsteps.py
> [#1216] Return deleted forms to staff users

- .gitignore
- docker-compose.yml
- docs/installation/config.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/conf/base.py
- src/openforms/conf/ci.py
- src/openforms/conf/dev.py
- src/openforms/conf/docker.py
- src/openforms/conf/production.py
- src/openforms/conf/staging.py
- src/openforms/conf/test.py
- src/openforms/setup.py
- src/openforms/tests/test_self_signed_certificates.py
- src/openforms/tests/test_setting_modules.py
> [#1251] Use named directory for self_certifi/requests CA bundle instead of mkdtemp()

- src/openapi.yaml
- src/openforms/forms/api/serializers.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/forms/utils.py
Fixes open-formulieren/security-issues#8
> Define public fields in Form serializer

- src/openforms/ui/templates/ui/includes/header.html
Part of #1018
Updated the alt-text for the header image
> [#1018] WCAG accessibility fixes

- docs/installation/config.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/conf/base.py
Part of https://github.com/open-formulieren/open-forms/issues/1265
Pull request for the CLI arguments is here: https://bitbucket.org/maykinmedia/django-digid-eherkenning/pull-requests/20
> Improve eHerkenning/DigiD settings

- src/openforms/js/components/form/columns.js
- src/openforms/js/components/formio_builder/customTemplates.js
- src/openforms/js/components/formio_builder/templates/columns.ejs
- src/openforms/js/formio_module.js
- src/openforms/js/lang/formio/nl.json
- src/openforms/scss/components/builder/_builder.scss
- src/openforms/scss/components/builder/_columns.scss
- src/openforms/scss/components/builder/_index.scss
Fixes #1254 
Front end: https://github.com/open-formulieren/open-forms-sdk/pull/163
> [#1254] Rework Column component

- src/openforms/js/components/form/edit/tabs.js
> [#1337] Component key should be required

- src/openforms/forms/templates/admin/forms/form/import_form.html
- src/openforms/templates/registration/password_change_form.html
Fixes #1349
* Fixed missing import form styling
* Fixed missing password reset form styling
> Fix missing admin-index menu/styling in some templates

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> [#1371] Upgrade django-digid-eherkenning

- src/openforms/formio/formatters/default.py
- src/openforms/formio/formatters/printable.py
- src/openforms/formio/formatters/registry.py
- src/openforms/formio/formatters/service.py
- src/openforms/formio/typing.py
No issue for this, came up during #1301 PR review
> Add more specific Formio component type hints

- src/openforms/prefill/contrib/haalcentraal/constants.py
- src/openforms/prefill/contrib/haalcentraal/tests/files/ingeschrevenpersonen.999990676-full.json
- src/openforms/prefill/contrib/haalcentraal/tests/files/ingeschrevenpersonen.999990676-incomplete.json
- src/openforms/prefill/contrib/haalcentraal/tests/files/ingeschrevenpersonen.999990676.json
> [#1376] Haal centraal attributes issues

- src/openforms/js/components/formio_builder/customTemplates.js
- src/openforms/js/components/formio_builder/templates/component.ejs
- src/openforms/js/lang/formio/nl.json
- src/openforms/scss/_vars.scss
- src/openforms/scss/components/builder/_index.scss
- src/openforms/scss/components/builder/_openforms-component.scss
- src/openforms/ui/static/ui/scss/_settings.scss
> [#1378] Highlight hidden components

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> Replaced django-digid-eherkenning bitbucket dependency with PyPI package

- .github/workflows/ci.yml
- Dockerfile
- docs/developers/extending.rst
- docs/developers/index.rst
- src/openforms/conf/base.py
> [#1336] Demo extension

- src/openforms/appointments/api/views.py
- src/openforms/appointments/utils.py
- src/openforms/contrib/bag/client.py
- src/openforms/contrib/kvk/client.py
- src/openforms/formio/service.py
- src/openforms/forms/custom_field_types.py
- src/openforms/prefill/__init__.py
- src/openforms/submissions/form_logic.py
- src/openforms/validations/registry.py
Added instrumentation/performance tracking on entrypoints to external
services and other suspected areas of performance degradation.
> Fixes #1381 -- add elasticapm instrumentation

- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/parsers.py
- src/openforms/submissions/tests/test_submit_form_step.py
> [#1385] Snake/Camel case issue

- src/openforms/config/admin.py
- src/openforms/config/data.py
- src/openforms/config/forms.py
- src/openforms/config/templates/config/forms/plugin_config_react.html
- src/openforms/config/tests/test_global_configuration.py
- src/openforms/config/widgets.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/i18n.js
- src/openforms/js/components/admin/index.js
- src/openforms/js/components/admin/plugin_configuration/ModulePlugins.js
- src/openforms/js/components/admin/plugin_configuration/PluginConfig.js
- src/openforms/js/components/admin/plugin_configuration/PluginConfiguration.js
- src/openforms/js/components/admin/plugin_configuration/index.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/js/utils/json-script.js
- src/openforms/plugins/registry.py
- src/openforms/scss/components/admin/_index.scss
- src/openforms/scss/components/admin/_plugin-config-react.scss
> Provide user-friendly widget configuration UI

- src/openforms/js/components/form/checkbox.js
- src/openforms/js/components/form/edit/options.js
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/form/file.js
- src/openforms/js/components/form/index.js
- src/openforms/js/components/form/password.js
- src/openforms/js/components/form/radio.js
- src/openforms/js/components/form/signature.js
- src/openforms/js/formio_module.js
Fixes #1333 
:poop: these constants/edit form configurations are not a pretty thing in Formio
> Remove invalid component options

- src/openforms/js/components/form/file.js
- src/openforms/js/lang/formio/nl.json
- src/openforms/utils/context_processors.py
- src/openforms/utils/tests/test_context_processor.py
> [#1398] Max file size as integer

- docs/developers/i18n.rst
- src/openapi.yaml
- src/openforms/js/components/form/edit/options.js
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/lang/formio/nl.json
- src/openforms/submissions/api/validation.py
- src/openforms/submissions/tests/test_submission_completion.py
Fixes #1393 
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/174
> [#1393] Prefilled data check on submission

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/accounts/admin.py
- src/openforms/accounts/apps.py
- src/openforms/accounts/signals.py
- src/openforms/accounts/tests/test_hijacking.py
- src/openforms/conf/base.py
- src/openforms/emails/templates/admin/emails/connection_check.html
- src/openforms/logging/constants.py
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/hijack_ended.txt
- src/openforms/logging/templates/logging/events/hijack_started.txt
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/admin/_hijack.scss
- src/openforms/scss/admin/admin_overrides.scss
- src/openforms/templates/admin/base_site.html
- src/openforms/templates/hijack/notification.html
- src/openforms/templates/master.html
Fixes #840 
Note the 3.x dropped almost all settings.
Styled notification:
> [#840] Updated django-hijack and fixed for OTP/2-factor

- src/openforms/logging/models.py
- src/openforms/logging/tests/test_models.py
Fixes #1408 
(there is no database constraint on generic foreign key)
> [#1408] Hardened TimelineLogProxy against disappeared content object

- src/openforms/submissions/templates/report/submission_report.html
- src/openforms/utils/pdf.py
> Fix pdf generation issues

- src/openapi.yaml
- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_list_submissions.py
- src/openforms/submissions/tests/test_models.py
- src/openforms/submissions/tests/test_read_submission.py
Fixes #1418
SDK part: https://github.com/open-formulieren/open-forms-sdk/pull/178
> [#1418] Implemented Submission.isAuthenticated for LogoutButton visibility

- src/openforms/js/components/form/postcode.js
Fixes #1076 
Add regex to postcode component
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/161
> [#1076] Added regex to postcode component

- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/formio_builder/WebformBuilder.js
> [#1422] Prevent update of custom keys on label changes

- src/openforms/js/components/formio_builder/builder.js
> [#1420] Enabled formio CKEditor settings override and configured link decorator

- src/openforms/emails/templatetags/form_summary.py
- src/openforms/submissions/models.py
- src/openforms/submissions/tests/test_models.py
> [#1433] Fields in confirmation email

- src/openapi.yaml
- src/openforms/forms/api/serializers.py
> [#1436] Submission allowed warning

- src/openforms/js/components/form/email.js
> [#1061] Fixed duplicate 'multiple' checkbox in email component options

- src/openforms/js/components/form/file.js
Fixes #1449 
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/181
> [#1449] Custom setting for max number of files

- src/openforms/js/components/form/edit/options.js
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/form/phoneNumber.js
> [#1452] Regex on telefone field

- docs/developers/versioning.rst
- package.json
- src/openapi.yaml
- src/openforms/authentication/api/tests/test_logout.py
- src/openforms/authentication/api/urls.py
- src/openforms/authentication/api/views.py
- src/openforms/authentication/contrib/digid/plugin.py
- src/openforms/authentication/contrib/digid/tests/test_auth_logout.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_auth_logout.py
- src/openforms/authentication/contrib/eherkenning/plugin.py
- src/openforms/authentication/contrib/eherkenning/tests/test_auth_logout.py
- src/openforms/submissions/tests/mixins.py
Fixes #1441
SDK: https://github.com/open-formulieren/open-forms-sdk/pull/180
> [#1441] Submission specific logout endpoint 

- bin/generate_oas.sh
- setup.cfg
- src/openforms/conf/base.py
- src/openforms/plugins/management/commands/disable_demo_plugins.py
So you don't have to spin up a runserver and go through the admin to re-generate the OAS.
It'd be cool to have it reset it back to what it was, but if you need the demo plugins for a test you'll have a runserver running anyway.
> Added command to disable demo plugins and applied to generate OAS bin script

- requirements/base.in
- requirements/base.txt
- src/openapi.yaml
- src/openforms/conf/base.py
- src/openforms/validations/apps.py
- src/openforms/validations/tests/test_default.py
- src/openforms/validations/validators/formats.py
- src/openforms/validations/validators/tests/test_formats.py
Fixes #1452
SDK PR (with issues at this time): https://github.com/open-formulieren/open-forms-sdk/pull/182
> [#1452] Added phone number validators to API

- src/openforms/registrations/contrib/email/templates/emails/email_registration.html
Fixes #1489
Easy cherry-pick for backport.
> Fixed table for key/values

- src/openforms/js/components/admin/form_design/FormLogic.js
- src/openforms/js/components/admin/form_design/logic/Action.js
- src/openforms/js/components/admin/form_design/logic/ActionSet.js
- src/openforms/js/components/admin/form_design/logic/actions/Action.js
- src/openforms/js/components/admin/form_design/logic/actions/ActionSet.js
- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
- src/openforms/js/components/admin/form_design/logic/actions/types.js
Part of #1472 
Refactor the Action component in the admin.
> [#1472] Refactor Action rendering

- src/openforms/forms/models/form.py
- src/openforms/forms/tests/admin/test_form.py
> [#1493] Fixed form copy admin (bulk/object) actions not copying logic

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
This will surpress yet one other system check warning AND improve some query performance because of the added indices
> Bump django-timeline-logger

- src/openforms/forms/api/serializers.py
- src/openforms/forms/api/validators.py
- src/openforms/forms/constants.py
- src/openforms/forms/tests/test_api_form_logic.py
> [#1472] Improve backend validation of logic rules

- package-lock.json
- src/openforms/js/components/admin/form_design/registrations/camunda/ComplexProcessVariable.js
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/admin/_app_overrides.scss
- src/openforms/scss/components/admin/_edit-panel.scss
- src/openforms/scss/components/admin/_list.scss
- src/openforms/scss/components/admin/_sdk-snippet.scss
- src/openforms/scss/components/builder/_builder.scss
- src/openforms/scss/vendor/_react-tabs.scss
Fixes #1483
This requires some proper testing still in both light and dark mode!
Dashboard:
List:
Form designer:
> Add support for dark theme preferences

- src/openforms/js/components/admin/form_design/FormLogic.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/logic/DSLEditorNode.js
- src/openforms/js/components/admin/form_design/logic/Today.js
- src/openforms/js/components/admin/form_design/logic/Trigger.js
- src/openforms/js/components/admin/form_design/logic/actions/Action.js
- src/openforms/js/components/admin/form_design/logic/actions/ActionSet.js
- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
- src/openforms/js/components/admin/form_design/logic/actions/types.js
- src/openforms/js/components/admin/forms/ErrorList.js
- src/openforms/scss/components/admin/_dsl-editor.scss
- src/openforms/scss/components/admin/_logic-action.scss
> [#1472] Display action errors

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
Fixes #1527
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/192
> [#1527] Hidden fields empty data

- src/openforms/forms/admin/form.py
- src/openforms/forms/admin/tasks.py
- src/openforms/forms/admin/views.py
- src/openforms/forms/forms/form.py
- src/openforms/forms/templates/admin/forms/form/change_list.html
- src/openforms/forms/tests/admin/test_form.py
- src/openforms/forms/tests/admin/test_tasks.py
- src/openforms/forms/tests/admin/test_views.py
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/bulk_forms_imported.txt
> [#1510] Import bulk forms

- src/openforms/payments/constants.py
- src/openforms/payments/contrib/ogone/plugin.py
- src/openforms/payments/contrib/ogone/tests/test_plugin.py
- src/openforms/payments/tests/test_models.py
- src/openforms/payments/tests/test_services.py
>  [#1498] Fixed double emails issue in payment status update 

- src/openforms/logging/models.py
- src/openforms/logging/tests/test_events.py
- src/openforms/logging/tests/test_models.py
> [#1467] Fixed 'None' username showing up in timeline logs

- docs/configuration/prefill/stuf_bg.rst
- docs/configuration/registration/stufzds.rst
> [#932] Updated StUF ZDS and StUF BG docs to new model structure

- src/openforms/js/components/form/content.js
- src/openforms/js/formio_module.js
> [#1540] Updated content component tabs

- src/openforms/js/components/admin/form_design/utils.js
> [#1544] Component selection: added key in brackets

- src/openforms/js/lang/formio/nl.json
> [#1555] Translations for Formio

- docs/configuration/authentication/digid.rst
- docs/configuration/authentication/eherkenning_eidas.rst
- docs/developers/sdk/logic.rst
- docs/installation/self_signed.rst
> [#1564] Document logic rules

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/configuration/authentication/digid.rst
- docs/configuration/authentication/eherkenning_eidas.rst
- docs/installation/self_signed.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
> Prepare release 1.0.7

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#1568] Components in submission mismatch definition

- .github/workflows/ci.yml
- src/openapi.yaml
- src/openforms/submissions/api/views.py
- src/openforms/submissions/tests/test_temporary_uploads.py
> Fix broken delete for fileuploads

- docker-compose.yml
Fixes #1366
**Changes**
* Allow all CORS requests in docker-compose
* Removed SDK container as it's not needed anymore
* Added SMTP container to send outgoing e-mail
> Tweak docker compose

- bin/generate_oas.sh
- package-lock.json
- package.json
- src/openapi.yaml
- src/openforms/api/tests/test_ping_view.py
- src/openforms/api/urls.py
- src/openforms/api/views.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/FormModal.js
- src/openforms/js/components/admin/SessionStatus.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/index.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/js/utils/fetch.js
- src/openforms/js/utils/session-expiry.js
- src/openforms/plugins/management/commands/disable_demo_plugins.py
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/components/admin/_ReactModal.scss
- src/openforms/scss/components/admin/_index.scss
- src/openforms/scss/components/admin/_session-status.scss
- src/openforms/templates/admin/base_site.html
Fixes #1308
**Session expired (timer)**
**Endpoint returned HTTP 401**
> Manage session expiry admin

- src/openforms/forms/tests/test_views.py
- src/openforms/templates/includes/analytics/all_bottom.html
- src/openforms/templates/includes/analytics/all_head.html
> Fix analytics scripts missing csp nonce

- package-lock.json
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/components/builder/_builder.scss
In light mode, the background for dark theme was accidentally used, making the text unreadable.
> Fix dropdown highlight color in light mode

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/tests/test_vanilla_formio_components.py
> [#1594] Fixed file component renderer handling of missing attachments

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> Bump to zgw-consumers with fixes

- src/openforms/emails/templates/emails/templatetags/form_summary.html
- src/openforms/emails/templates/emails/templatetags/form_summary.txt
- src/openforms/registrations/contrib/email/templates/emails/email_registration.html
- src/openforms/registrations/contrib/email/templates/emails/email_registration.txt
> [#1591] Fixed form summary rendering empty steps

- src/openforms/js/components/form/edit/tabs.js
> [#1624] Fixed prefill tab to update available attributes when plugin changes

- src/openforms/scss/pdfs/_page.scss
Related to #1628 
Added some margin-top on pages after the first.
> PDF styling tweaks

- src/openforms/scss/admin/_app_overrides.scss
> [#1621] Sticky CSS for admin buttons .submit-row

- src/openapi.yaml
- src/openforms/forms/api/serializers/form_variable.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/FormStep.js
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/admin/form_design/data.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
- src/openforms/js/components/admin/form_design/variables/constants.js
- src/openforms/js/components/admin/form_design/variables/utils.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
> [#1325] Link form variables to form definition

- .dockerignore
And prevent bytecode cache files from ending up in the docker
image.
> Slim down docker build context

- requirements/ci.txt
- requirements/dev.txt
Only a devtool for us, so no need to issue a hotfix.
> Dependency bump (waitress)

- .github/workflows/code_quality.yml
- src/openforms/config/migrations/0029_rename_design_tokens.py
- src/openforms/config/tests/test_migrations.py
> [#1664] Empty design tokens

- src/openforms/contrib/bag/client.py
Make sure exceptions are logged.
> Log BAG API exceptions.

- .github/workflows/ci.yml
- docs/developers/backend/modules/dmn.rst
- docs/developers/backend/modules/index.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/conf/base.py
- src/openforms/config/views.py
- src/openforms/contrib/camunda/tests/utils.py
- src/openforms/dmn/base.py
- src/openforms/dmn/contrib/camunda/__init__.py
- src/openforms/dmn/contrib/camunda/apps.py
- src/openforms/dmn/contrib/camunda/checks.py
- src/openforms/dmn/contrib/camunda/plugin.py
- src/openforms/dmn/contrib/camunda/tests/test_config_check.py
- src/openforms/dmn/contrib/camunda/tests/test_plugin.py
- src/openforms/dmn/registry.py
- src/openforms/dmn/service.py
- src/openforms/dmn/tests/test_registry.py
- src/openforms/registrations/contrib/camunda/plugin.py
Part of #1680
**Changes**
- Added base DMN python API & registry
- Implemented Camunda DMN plugin
- Added Camunda docker-compose to CI
> Implement base DMN support

- docs/developers/backend/modules/dmn.rst
- src/openforms/dmn/management/commands/dmn_evaluate.py
- src/openforms/dmn/management/commands/dmn_list_definitions.py
- src/openforms/dmn/tests/test_management_commands.py
Related to #1680
--- 
Depends on #1683
---
**Changes**
- Added management to command to list available definitions and their versions
- Added management command to evaluate a particular decision definition with given input vars
> Implement DMN module management commands

- src/openforms/js/components/admin/form_design/variables/utils.js
> [#1695] Dont add FormVariable for content component

- docs/developers/sdk/embedding.rst
> document the CORS policy requirement for font files

- src/openforms/js/components/admin/FormioComponentRepresentation.js
- src/openforms/js/components/admin/form_design/Appointments.js
- src/openforms/js/components/admin/form_design/Context.js
- src/openforms/js/components/admin/form_design/NewStepFormDefinitionPicker.js
- src/openforms/js/components/admin/form_design/PluginWarning.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/logic/StepSelection.js
- src/openforms/js/components/admin/form_design/logic/Trigger.js
- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
- src/openforms/js/components/admin/form_design/useDetectConfigurationChanged.js
- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
- src/openforms/js/components/admin/forms/ComponentSelection.js
Changes:
Before, there were multiple Context Providers wrapping the components used in the `FormCreationForm` component.
Now, these have been merged into one context provider.
> Merge React Context providers into one

- src/openforms/forms/utils.py
> [#1712] Added missing feature flag

- src/openforms/js/components/formio_builder/WebformBuilder.js
> [#1724] Content fields arent automatically marked as required

- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
> [#1475] Don't allow empty option for new attribute value

- .gitignore
- src/openforms/js/lang/formio/nl.json
> Update email translation — [#1737]

- src/openforms/js/components/admin/form_design/RegistrationFields.js
- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/client.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
> Make zaaktype fields optional — [#1723]

- src/openforms/scss/admin/_app_overrides.scss
> Update glyphicon icons (fontawesome update) — [#1678]

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/client.py
- src/stuf/stuf_zds/constants.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/voegZaakdocumentToe.xml
- src/stuf/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/tests/test_client.py
> Stuf ZDS integration creates hardcoded document

- src/openforms/scss/components/admin/_variables-table.scss
> [#1777] Break long variable keys

- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/tests/__init__.py
- src/stuf/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/tests/testcases.py
- src/stuf/stuf_zds/tests/utils.py
- src/stuf/tests/testcases.py
Moved test utilities and base test case with assertions to the stuf
package.
> Refactor/clean up StUF-ZDS test code

- src/openforms/js/components/admin/form_design/variables/utils.js
> [#1772] Copy paste fieldsets creates variables

- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/variables/utils.js
> [#1780] Add FormVariables for reusable FormDefinitions

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/variables/UserDefinedVariables.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
> [#1793] Create user defined variables one at a time

- src/openforms/js/components/admin/form_design/FormLogic.js
- src/openforms/js/components/admin/form_design/FormMetaFields.js
- src/openforms/js/components/admin/form_design/Tab.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/utils.js
- src/openforms/js/components/admin/form_design/variables/VariablesEditor.js
- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
- src/openforms/js/components/admin/forms/Field.js
- src/openforms/scss/components/admin/_icon.scss
- src/openforms/scss/components/admin/_variables-table.scss
- src/openforms/scss/vendor/_react-tabs.scss
> [#1792] Display validation errors for variables

- docs/developers/checklists.rst
- docs/developers/index.rst
- src/openforms/forms/models/form.py
- src/openforms/forms/tests/test_copy.py
> [#1799] Copy variables when copying form

- Dockerfile
- bin/dump_configuration.sh
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes #1781
I think I covered all the config related models.
> Add script to dump the configuration of an instance

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
The new version has a management command to dump the certificate files
Part of #1781
> upgrade zgw-consumers

- src/openforms/config/admin.py
> Add configuration field to admin — [#1784]

- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
> [#1816] Changing data type changes key (variables)

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes #1775 
I made this form as an example of how this works:
[test-issue-1775.zip](https://github.com/open-formulieren/open-forms/files/9199086/test-issue-1775.zip)
**Trigger**:
Always execute the actions since this always evaluates to true.
```
{"==": [1,1]}
```
**Action 1**:
```
{
"+": [
{"var": ["numberA", 0]},
{"var": ["numberB", 0]},
{"var": ["numberC", 0]}
]
}
```
Use `numberA` and if it's not filled / not present use 0 instead (same for other vars). Sum the values.
**Action 2**:
Calculate the denominator (for the average):
```
{
"+": [
2,
{
"if": [
{"and": [{"var": "showNumberC"}, {"!=": [{"var": "numberC"}, null]}]}, 
1, 
0
]
}
]
}
```
The if statement evaluates to 0 if `showNumberC` is false (since `numberC` is hidden) and if `numberC` has not been filled yet. Otherwise it …
> [#1775] Calculations with default values in json logic

- package-lock.json
- package.json
> Fix problems with searching form.io pulldowns — [#1783]

- src/openforms/appointments/tests/test_endpoints.py
- src/openforms/formio/rendering/tests/test_vanilla_formio_components.py
- src/openforms/forms/tests/factories.py
- src/openforms/prefill/tests/test_prefill_variables.py
- src/openforms/registrations/contrib/camunda/tests/test_backend_options.py
> [#1823] Fix generate_minimal_setup factory

- src/openforms/validations/validators/formats.py
- src/openforms/validations/validators/tests/test_formats.py
> [#1828] Phone number validation

- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
> [#1834] Fix action property dropdown

- src/openapi.yaml
- src/openforms/forms/api/serializers/logic/form_logic.py
- src/openforms/forms/api/validators.py
- src/openforms/forms/tests/test_restore_version.py
- src/openforms/forms/tests/variables/test_variables_in_logic_trigger.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/data/complete-form.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/logic/LiteralValueInput.js
- src/openforms/js/components/admin/form_design/logic/OperandTypeSelection.js
- src/openforms/js/components/admin/form_design/logic/Trigger.js
- src/openforms/js/components/admin/form_design/logic/constants.js
- src/openforms/js/components/admin/form_design/variables/constants.js
- src/openforms/js/components/admin/form_design/variables/types.js
- src/openforms/js/components/admin/form_design/variables/utils.js
- src/openforms/js/components/admin/forms/JsonWidget.js
- src/openforms/js/components/admin/forms/VariableSelection.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/js/utils/JsonPropTypeValidator.js
- src/openforms/registrations/contrib/camunda/tests/test_backend_options.py
Fixes #1762 
**Note**
I left the selection of the action "Change the value of a field/component" to use the components instead of the variables, since we will remove this action when the variable feature flag is removed. => https://github.com/open-formulieren/open-forms/issues/1822
> [#1762] Variables in simple logic editor

- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/variables/utils.js
- src/openforms/js/components/formio_builder/WebformBuilder.js
> [#1841] Update variables of saved components

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/submissions/exports.py
- src/openforms/submissions/tests/test_admin_file_uploads.py
- src/openforms/submissions/tests/test_attachment_download_view.py
- src/openforms/submissions/tests/test_temporary_uploads.py
Follow up on Django's CVE-2022-36359
> Security fixes file download attachment

- src/openforms/forms/api/serializers/form_definition.py
- src/openforms/forms/models/form_definition.py
- src/openforms/forms/tests/admin/test_form_definition.py
- src/openforms/forms/tests/test_api_formdefinition.py
- src/openforms/forms/tests/test_models.py
- src/openforms/forms/validators.py
>  Reusable form definition can be marked as non-reusable [#1702]

- src/openforms/appointments/checks.py
- src/openforms/config/data.py
- src/openforms/config/templates/admin/config/overview.html
- src/openforms/config/tests/test_config_check.py
- src/openforms/config/views.py
- src/openforms/contrib/kvk/checks.py
- src/openforms/contrib/kvk/client.py
- src/openforms/payments/contrib/ogone/plugin.py
- src/openforms/prefill/contrib/haalcentraal/plugin.py
- src/stuf/stuf_zds/client.py
> Plugin configuration behavior [#1320] 

- src/openforms/submissions/logic/actions.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#1873] Logic check crash

- src/openforms/forms/api/validators.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
> [#1856] Prevent JsonLogicValidator from causing a 500 error

- src/openforms/js/components/admin/form_design/Confirmation.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/forms/FormRow.js
- src/openforms/scss/components/admin/_confirmation-page.scss
- src/openforms/scss/components/admin/_index.scss
Fixes #1880 
It looks like displaying validation errors was broken also for the form / formstep tabs :thinking: 
This fixes it also for those tabs.
> [#1880] Fix display validation errors

- src/openforms/registrations/contrib/email/tests/test_backend.py
- src/openforms/submissions/exports.py
- src/openforms/submissions/management/commands/render_report.py
- src/openforms/submissions/rendering/renderer.py
- src/openforms/submissions/tests/factories.py
- src/openforms/submissions/tests/renderer/test_formio_integration.py
- src/openforms/submissions/tests/renderer/test_management_command_cli_render.py
- src/openforms/submissions/tests/renderer/test_renderer.py
- src/openforms/submissions/tests/test_exports.py
- src/openforms/submissions/tests/test_variables/test_num_queries.py
- src/openforms/variables/rendering/nodes.py
- src/openforms/variables/tests/test_rendering.py
> [#1579] Variables in registration backend

- src/openforms/locations/api/tests/test_api.py
- src/openforms/locations/api/views.py
Related to #1832
Use the default cache backend to prevent being throttled by the BAG API when looking up addresses by postal code + number.
> Add caching to location autocomplete

- docs/configuration/registration/email.rst
- src/openforms/registrations/api/tests/test_endpoints.py
- src/openforms/registrations/contrib/email/config.py
- src/openforms/registrations/contrib/email/plugin.py
- src/openforms/registrations/contrib/email/tests/test_backend.py
> [#1877] Configurable subject for registration email

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openforms/submissions/tests/form_logic/test_modify_variables.py
Fixes #1838 
I added documentation directly in PR https://github.com/open-formulieren/open-forms/pull/1893 since it's still open.
> [#1838] Fix logic for repeating groups

- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_admin.py
> [#1934] Broken filtering

- src/openapi.yaml
- src/openforms/forms/api/filters.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/variables/test_viewset.py
- src/openforms/js/components/admin/form_design/data/read-form.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
> [#1855] Variables off sync

- src/openforms/authentication/tests/test_static_variables.py
- src/openforms/variables/base.py
- src/openforms/variables/static_variables/static_variables.py
- src/openforms/variables/tests/test_static_variables.py
Fixes #1711
I'll create a separate PR with some minor cleanup/refactor - we can get rid of the `submission` usage in the `forms` app completely.
> Add additional static variables

- src/openforms/js/components/admin/form_design/form-creation-form.js
> [#1951] Get right component key

- src/openapi.yaml
- src/openforms/api/drf_spectacular/hooks.py
- src/openforms/conf/base.py
- src/openforms/middleware.py
- src/openforms/tests/test_middleware.py
> [#1944] Set csrf token header

- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
> [#1964] Don't overwrite initial value if falsy

- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
> Deleted forms show an error — [#1947]

- src/openforms/logging/logevent.py
- src/openforms/submissions/logic/actions.py
- src/openforms/submissions/logic/log_utils.py
- src/openforms/submissions/logic/rules.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
- src/openforms/utils/json_logic.py
> [#1964] Introspect json logic primitives

- src/openforms/middleware.py
I didn't write a test, because I am not really sure what the problem here exactly is / how to reproduce it :disappointed:
> [#1987] Replace check for api endpoints

- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/tests/variables/test_viewset.py
- src/openforms/forms/utils.py
> [#1988] Wrong form resources import order 

- CHANGELOG.rst
> Fix header changelog

- src/openforms/submissions/logic/datastructures.py
- src/openforms/submissions/tests/test_variables/test_model.py
> [#1948] Deal with SubmissionValueVariable not linked to FormVariable 

- src/openforms/forms/tasks.py
- src/openforms/forms/tests/variables/test_tasks.py
> [#1970] Recouple SubmissionValueVariables race condition

- src/openapi.yaml
- src/openforms/api/drf_spectacular/hooks.py
- src/openforms/conf/base.py
- src/openforms/middleware.py
- src/openforms/tests/test_middleware.py
> [#1944] Special header for SDK to navigate between steps

- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_admin.py
> Manually resend failed registrations — [#1957]

- src/openforms/submissions/api/viewsets.py
Using the submission execution state we can both simplify the code and leverage caching of the execution state, which should remove a number of (duplicate) queries.
Checked two cases with django-silk
**`PUT` submission step**
- before this PR: 16 queries, 55ms
- with this PR: 14 queries, 51ms
**`POST` submission step logic check**
- before this PR: 18 queries, 60ms
- with this PR: 14 queries, 49ms
Not terrible, not fantastic - I'm mostly interested in what we'll see in Elastic APM as hints to further optimize.
> Optimize SubmissionStepViewSet queries

- src/openforms/js/components/admin/form_design/variables/VariablesTable.js
> [#2000] Wrong order of prefill columns

- docs/manual/getting_started.rst
- docs/manual/index.rst
- docs/manual/workflows.rst
Fixed #2014 
Documented how to add and edit forms from a production perspective.
> Added publication process

- src/openforms/forms/tests/variables/test_tasks.py
The test did not always trigger the race condition, much like the real race condition that we guard against.
> :art: Improve race condition test determinism

- docs/conf.py
- docs/configuration/authentication/digid.rst
- docs/configuration/authentication/eherkenning_eidas.rst
- docs/manual/forms/basics.rst
- docs/manual/forms/examples/auth_static_variables.rst
- docs/manual/forms/form_fields.rst
- docs/manual/forms/logic.rst
- docs/manual/templates.rst
Fixes #1955 
Also fixed a few issues unrelated to vars.
> Documented variables (as intro) and static variables.

- docs/configuration/general/cms_integration.rst
- docs/developers/sdk/embedding.rst
Fixed #2027 
Documented UTF-8 and more eleborate snippet example.
> Added additional snippet integration docs

- src/openforms/authentication/static_variables/static_variables.py
- src/openforms/authentication/tests/test_static_variables.py
- src/openforms/forms/tests/variables/test_variables_in_logic_trigger.py
> Rename auth identifier — [#2001]

- src/openforms/formio/utils.py
- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/form_logic.py
- src/openforms/submissions/models/submission.py
This should give more insight about where time is spent in the logic check endpoint.
TODO
> :zap: [#1922] -- capture more spans for profiling

- src/openforms/registrations/constants.py
- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/openforms/registrations/contrib/zgw_apis/plugin.py
- src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
- src/stuf/stuf_zds/templates/stuf_zds/soap/includes/verblijfsadres.xml
Fixes #1867
I was not able to add location info as I didn't see any separate location resource/XML-schema. Address information is added though.
> Added more registration fields

- src/openforms/js/lang/formio/nl.json
> Add translation for max files warning in file form

- src/openapi.yaml
- src/openforms/authentication/api/tests/test_logout.py
- src/openforms/authentication/api/urls.py
- src/openforms/authentication/api/views.py
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/api/serializers/logic/form_logic.py
- src/openforms/forms/constants.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
- src/openforms/submissions/utils.py
There was some more stuff to remove that was already marked deprecated.
> Remove deprecated functionality

- src/openforms/payments/contrib/ogone/admin.py
- src/openforms/payments/contrib/ogone/tests/test_admin.py
> [#2011] Don't store request on admin instance

- src/openforms/contrib/bag/client.py
- src/openforms/forms/admin/form.py
- src/openforms/forms/admin/form_definition.py
- src/openforms/submissions/admin.py
Just a bunch of random things that I came across while testing.
> Small fixes to obvious things

- src/openforms/formio/utils.py
- src/openforms/js/components/admin/form_design/utils.js
- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
Fixes #2056
Frontend part:  https://github.com/open-formulieren/open-forms-sdk/pull/237
> [#2056] upload files broken

- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_admin.py
> [#2059] Declutter submission page

- CHANGELOG.rst
- docs/developers/backend/core/variables.rst
- src/openforms/forms/management/commands/check_invalid_field_keys.py
- src/openforms/forms/models/form_variable.py
> [#2055] Management command to check for invalid keys

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
> [#2054] Validation error too soon

- src/openforms/js/components/form/editGrid.js
> [#2083] Add max repeats to editgrid

- src/openforms/templates/admin/base_site.html
- src/openforms/templates/registration/password_reset_complete.html
- src/openforms/templates/registration/password_reset_confirm.html
- src/openforms/templates/registration/password_reset_done.html
- src/openforms/templates/registration/password_reset_form.html
~~We should probably include these templates in django-admin-index :-)~~
Upstream PR: https://github.com/maykinmedia/django-admin-index/pull/80
> Fix layout of password reset pages

- src/openforms/js/components/form/coSign.js
> [#2095] Undefined var in component breaks Formio

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/nodes.py
- src/openforms/formio/utils.py
- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
- src/openforms/typing.py
Backport of https://github.com/open-formulieren/open-forms/commit/587d90d13581a78c13f4f0c603c451147205302c and https://github.com/open-formulieren/open-forms/commit/bdc5a60a58aa5164861d3527f7e4b709618e8e67
> Backport: renderer missing check for frontend logic

- src/openforms/js/lang/formio/nl.json
> Add translations for repeating group component

- src/openforms/logging/logic.py
- src/openforms/logging/tasks.py
- src/openforms/logging/tests/test_tasks.py
> [#2106] Log rules errors

- src/openforms/emails/utils.py
- src/openforms/formio/rendering/tests/test_component_node.py
> [#2154] Coloured links break rendering 

- src/openforms/upgrades/tests/test_checks.py
- src/openforms/upgrades/upgrade_paths.py
> Fix crash when deploying non-semver release tag

- src/openforms/submissions/rendering/renderer.py
- src/openforms/submissions/tests/test_exports.py
Fixes #2117
Different approach based on feedback in #2144
> [#2117] Fixed issue in rendering non-submitted/non-applicable steps

- src/openforms/formio/normalization.py
- src/openforms/prefill/__init__.py
- src/openforms/submissions/api/validation.py
- src/openforms/submissions/tests/test_submission_completion.py
> [#1899] Error readonly formatted fields

- src/openforms/js/components/form/currency.js
- src/openforms/js/components/form/edit/components.js
- src/openforms/js/components/form/number.js
Fixes #1351 
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/266
> [#1351] Configure negative values for number component

- src/openforms/js/components/admin/form-category.js
- src/openforms/js/components/admin/plugin_configuration/index.js
- src/openforms/js/components/admin/selenium.js
- src/openforms/js/components/admin/submissions/filter.js
- src/openforms/js/components/formio_builder/index.js
- src/openforms/js/public.js
- src/openforms/js/utils/dom.js
- src/openforms/templates/master.html
- src/openforms/ui/templates/ui/components/a11y_toolbar/a11y_toolbar.html
- webpack.config.js
> [#2062] Moved the "Print this page" click handler to new public.js exernal javascript bundle to satisfy CSP

- INSTALL.rst
- GNU gettext for i18n
- chromedriver for the selenium tests
> 📝Add missing prerequisites

- src/openforms/forms/api/validators.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
> [#2208] Primitives in logic rules actions

- src/openforms/conf/local_example.py
Eager celery tasks do database queries in these suites.
> Improve example config for future devs

- src/openforms/js/components/form/component.js
- src/openforms/js/components/formio_builder/WebformBuilder.js
- src/openforms/js/formio_module.js
> [#2213] Fix default values

- src/openforms/conf/base.py
Fixes: #2228 
Changes:
* Add settings for i18n
> :wrench: [#2228] Prepare settings for i18n

- src/openforms/conf/base.py
- src/openforms/pre_requests/base.py
- src/openforms/pre_requests/clients.py
- src/openforms/pre_requests/registry.py
- src/openforms/pre_requests/tests/test_clients.py
Part of #2197 
**Changes**
- Add the `pre_requests` registry
- Add a new client which calls the registered pre_requests hooks
- Change the ZGW_CONSUMERS_CLIENT_CLASS setting to point to the new client class
> [#2197] Token authorisation: pre_request hook

- docs/developers/extensions.rst
- docs/developers/index.rst
> [#2197] Developers documentation token exchange

- src/openapi.yaml
- src/openforms/api/urls.py
- src/openforms/conf/base.py
- src/openforms/translations/api/serializers.py
- src/openforms/translations/api/urls.py
- src/openforms/translations/api/views.py
- src/openforms/translations/tests/test_api.py
Unsure about the spec of the 400 on the PUT.  https://docs.geostandaarden.nl/api/API-Strategie-ext/#error-handling-0 is marked not normative and under development.
Closes #2229
> Feature [#2229] Implement api endpoints for i18n

- src/openforms/authentication/utils.py
- src/openforms/conf/base.py
> [#2197] Store access token in FormAuth

- src/openforms/js/components/admin/forms/FormRow.js
> [#2246] Checking error length

- docs/manual/forms/logic.rst
> [#2205] Document unsupported operators

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> [#2165] Upgrade django-simple-certmanager

- requirements/base.in
- requirements/base.txt
- src/csp_post_processor/processor.py
- src/csp_post_processor/tests/test_post_processing.py
- src/openforms/formio/service.py
- src/openforms/formio/tests/test_service.py
Fixes #1901 (the resize operation created an inline style attribute)
> [#1901] Run CSP postprocessor on content component's html to fix inline styles

- .github/workflows/ci.yml
- Dockerfile
- deployment/app.yml
- docker-compose.yml
> [#2166] Modified Dockerfile with Volumes hint to prevent writing to container layer

- src/openforms/config/api/tests/test_views.py
- src/openforms/config/templatetags/privacy_policy.py
- src/openforms/config/tests/test_privacy_policy.py
> [#2245] Changed privacy policy link in summary page to open in new window

- src/openforms/payments/base.py
- src/openforms/payments/contrib/ogone/admin.py
- src/openforms/payments/contrib/ogone/tests/test_admin.py
> [#2277] Fixed Ogone feedback URL

- src/stuf/stuf_zds/constants.py
> [#2148] Changed VertrouwelijkheidsAanduidingen translatable choice labels to Dutch

- src/openforms/authentication/signals.py
- src/openforms/submissions/signals.py
- src/openforms/submissions/tests/factories.py
- src/openforms/submissions/tests/test_resume_form_view.py
- src/openforms/submissions/views.py
Workaround/fix for the time being, relates to #2301 
2.x variant in #2310
> Un-hash identifying attributes

- src/openforms/authentication/signals.py
- src/openforms/authentication/tests/factories.py
- src/openforms/submissions/signals.py
- src/openforms/submissions/tests/factories.py
- src/openforms/submissions/tests/test_resume_form_view.py
- src/openforms/submissions/views.py
Relates to #2301 - 2.x variant of #2309
> Un-hash identifying attributes (2.x variant)

- src/openforms/forms/tests/test_api_forms.py
- src/openforms/translations/tests/test_utils.py
- src/openforms/translations/utils.py
- Adds translation.utils.make_fully_translated Factory decorator
- Adds test cases for Form API endpoint.
Closes #2231
> ✅ [#2231] Adds tests and tools for translated models

- docs/developers/extensions.rst
- src/openforms/authentication/utils.py
- src/openforms/pre_requests/base.py
- src/openforms/pre_requests/clients.py
- src/openforms/pre_requests/tests/test_clients.py
- src/openforms/prefill/base.py
- src/openforms/prefill/contrib/haalcentraal/plugin.py
Part of #2197 
Related changes in extension: https://github.com/open-formulieren/open-forms-ext-token-exchange/pull/1
> [#2197] Add submission to prefill client

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
> Release 1.1.8

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
> :arrow_up: Upgrade python3-saml version and lxml

- src/openforms/formio/rendering/conf.py
- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/tests/test_component_node.py
- src/openforms/formio/rendering/tests/test_vanilla_formio_components.py
- src/openforms/submissions/models/submission.py
- src/openforms/submissions/rendering/constants.py
- src/openforms/submissions/tests/renderer/test_form_nodes.py
- src/openforms/submissions/tests/renderer/test_submission_step_nodes.py
> [#2244] Fixed 'content' component and components not marked as `showInSummary` showing up in server rendered summary

- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/openforms/registrations/contrib/zgw_apis/plugin.py
- src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
- src/stuf/stuf_zds/templates/stuf_zds/soap/includes/bezoekadres.xml
> [#2289] Niet natuurlijk persoon in registration

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/csp_post_processor/__init__.py
- src/csp_post_processor/processor.py
- src/csp_post_processor/tests/test_post_processing.py
- src/openforms/formio/service.py
- src/openforms/submissions/api/serializers.py
> [#2329] Added Bleach to CSP post-processor

- .github/workflows/ci.yml
- .github/workflows/code_quality.yml
Following the actions/setup-python examples, let's see how this performs.
> :construction_worker: Add pip cache to CI

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
Changelog updated and version number bumped.
> Bugfix release 2.0.1

- src/openforms/submissions/api/permissions.py
- src/openforms/submissions/tests/form_logic/test_endpoint.py
> [#2400] Erratic behaviour of applicable steps

- docs/installation/config.rst
- docs/installation/form_hosting.rst
> [#2394] remove digid/eherkenning envvars config from docs

- docs/configuration/registration/objects.rst
- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/nodes.py
- src/openforms/formio/rendering/structured.py
- src/openforms/formio/rendering/tests/test_utils.py
- src/openforms/formio/rendering/utils.py
- src/openforms/registrations/contrib/objects_api/plugin.py
- src/openforms/registrations/contrib/objects_api/tests/test_backend.py
> [#2402] Structured data for Object API registration

- src/openforms/formio/components/custom.py
- src/openforms/formio/components/np_family_members/tests/test_family_members.py
> Prevent hard crash for familymembers component without bsn

- docs/installation/config.rst
- docs/installation/index.rst
- docs/installation/security.rst
Addresses findings from some penetration test reports
> Provide best-practices for secure OF installations

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/openforms/registrations/contrib/zgw_apis/plugin.py
- src/openforms/submissions/models/submission.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
> [#1862] Create ROL for registration medewerker in StufZDS

- Dockerfile
Fixes #2312
Verified with `docker-compose` that it all seems to work still.
> Upgrade docker base image to bullseye

- src/openforms/emails/confirmation_emails.py
- src/openforms/submissions/models/submission_report.py
- src/openforms/submissions/templates/report/submission_report.html
- src/openforms/submissions/tests/factories.py
- src/openforms/submissions/tests/test_factories.py
- src/openforms/submissions/tests/test_submission_report.py
- src/openforms/submissions/tests/test_tasks_confirmation_emails.py
- src/openforms/submissions/utils.py
> Render PDF reports and confirmation emails in submission language

- src/openforms/forms/tests/test_migrations.py
- src/openforms/forms/utils.py
Fixes #2398
- `openforms.forms.utils.parse_trigger` produced an error when migrating from 1.1.x to 2.0.1 if the migration contained forms which referenced non-existing elements (e.g. because they had been removed)
- the fix adds a check to `parse_trigger` to ensure that elements which trigger logic actions are actually present
- the test only checks that no error occurs on retrieval of formdefinitions after migrating
> [#2398] fix parse_trigger

- src/openforms/js/lang/formio/nl.json
> [#2463] Improve error message

- src/openapi.yaml
- src/openforms/authentication/api/serializers.py
- src/openforms/authentication/base.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py
- src/openforms/authentication/tests/test_registry.py
Part of #2447
Related frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/313
> [#2447] Add info to plugins about gemachtigde

- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/tests/test_import_export.py
> [#2432] Fix converting URL to UUID in logic rule

- src/openforms/js/components/admin/form_design/Confirmation.js
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/admin/forms/Field.js
- src/openforms/js/components/admin/forms/Inputs.js
- src/openforms/scss/admin/_admin_theme.scss
Fixes #2418
UI with disabled fields:
> Fix disabled states in translations UI

- src/openforms/config/translation.py
- src/openforms/forms/models/utils.py
- src/openforms/forms/tests/test_api_forms.py
> :bug: [#2484] Disable fallbacks for modeltranslations

- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/utils.py
- src/openforms/js/components/admin/tables/ChangelistColumn.js
- src/openforms/js/components/admin/tables/ChangelistTable.js
Fixes #1790
This PR also fixes an import bug that I noticed while trying to import a form to reproduce the original issue.
> Fix modal crash

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/nodes.py
- src/openforms/submissions/logic/datastructures.py
- src/openforms/submissions/tests/renderer/test_submission_summary.py
> [#2449] Rendering repeating groups logic

- src/openforms/js/components/form/map.js
> [#2373] Remove multiple option for map component

- src/openforms/registrations/constants.py
- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
Fixes #2494 ~~(partially as of now)~~
> Send person details for non-authenticated users to StUF/ZGW

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
This should be okay to release as is.
> Bump version to 1.1.9 and update changelog

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
> Bump version to 2.0.2 and update changelog

- src/openforms/config/templatetags/privacy_policy.py
> [#2377] Remove white space after link

- src/openforms/js/components/admin/form_design/variables/utils.js
- src/openforms/js/components/formio_builder/WebformBuilder.js
Fixes #2120
Don't mark layout components as validate.required.
> Fix layout components validation injection in form builder

- src/openforms/js/components/formio_builder/WebformBuilder.js
> Exclude editgrid in validate.required default tweaking

- src/openforms/ui/templates/ui/includes/header.html
> [#2550] remove role=img from logo in header

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/csp_post_processor/drf/spectacular.py
- src/csp_post_processor/tests/test_schema_generation.py
- src/openapi.yaml
- src/openforms/api/serializers.py
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/api/viewsets.py
- src/openforms/payments/views.py
- src/openforms/submissions/api/renderers.py
- src/openforms/translations/api/views.py
- src/openforms/translations/views.py
- src/openforms/utils/api/views.py
One schema regression to fix w/r to the dynamic translation serializers.
> :arrow_up: Bump drf-spectacular to latest version

- src/openforms/ui/static/ui/scss/components/cookie-notice/_index.scss
Increase banner distance on bottom for all screen sizes.
Fixes  open-formulieren/open-forms#2549
> :lipstick: increase bottom banner

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openapi.yaml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
> Prepare 2.0.3 release

- src/openforms/js/components/form/edit/validationEditFormUtils.js
- src/openforms/js/lang/formio/en.json
- src/openforms/js/lang/formio/nl.json
Fixes #2273 
(Accessibility - Understandable - Assistance with input / error identification)
> :wheelchair: [#2273] assist inputs with error identification messages

- .github/workflows/ci.yml
- docs/developers/backend/index.rst
- docs/developers/backend/tests.rst
- package-lock.json
- package.json
- src/openforms/forms/forms/form_definition.py
- src/openforms/forms/tests/selenium_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/Context.js
- src/openforms/js/components/admin/form_design/FormStep.js
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/admin/form_design/FormSteps.js
- src/openforms/js/components/admin/form_design/data/steps.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/types/FormStep.js
- src/openforms/js/components/admin/form_design/types/index.js
- src/openforms/js/components/admin/form_design/utils.js
- src/openforms/js/components/form/content.js
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/form/edit/validationEditFormUtils.js
- src/openforms/js/components/formio_builder/builder.js
- src/openforms/js/components/formio_builder/constants.js
- src/openforms/js/components/formio_builder/index.js
- src/openforms/js/components/formio_builder/translation.js
- src/openforms/js/components/formio_builder/translation.spec.js
- src/openforms/scss/components/builder/_builder.scss
- src/openforms/tests/selenium_tests/base.py
- src/openforms/tests/selenium_tests/test_admin_js.py
Fixes #2478 
TODO:
- seems that edit_step only has the full config (not updated) and triggers way too often 
- customDefaultValue only runs on opening the modal
- cannot really update the step.componentTranslations state, because there is a chance the changes aren't saved
- ~~implement deleting?~~
- ~~getValuesForField -> why does it return arrays?~~
**Test/edge cases**
- Explore if we can get drag and drop working (!)
- Otherwise just start with a configuration and edit that
> Improve UX for editing component translations

- src/openforms/formio/dynamic_config/date.py
- src/openforms/formio/dynamic_config/tests/test_date_component.py
- src/openforms/submissions/models/submission_value_variable.py
- src/openforms/submissions/tests/test_get_submission_step.py
- src/openforms/submissions/tests/test_variables/test_model.py
- src/openforms/utils/date.py
- src/openforms/variables/utils.py
> [#2581] Inconsistent dates / datetimes

- src/openforms/forms/tests/selenium_tests/test_form_designer.py
- src/openforms/js/components/formio_builder/builder.js
> [#2635] Fix broken form editor

- src/openforms/utils/json_logic/descriptions.py
- src/openforms/utils/json_logic/introspection.py
- src/openforms/utils/tests/test_json_logic.py
Fixes #2643 
Todo: rebase once https://github.com/open-formulieren/open-forms/pull/2630 is merged
> [#2643] Add empty var description and support map

- src/openforms/emails/tests/test_validators.py
- src/openforms/emails/validators.py
> [#2641] Deal with URLs with subdomains

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> Bump cryptography and PyOpenSSL

- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/utils.py
> [#2669] Missing backport

- src/openforms/templates/includes/cookie-notice.html
- src/openforms/templates/master.html
- src/openforms/ui/static/ui/scss/components/cookie-notice/_index.scss
- src/openforms/ui/static/ui/scss/components/cookie-notice/_vars.scss
- src/openforms/ui/static/ui/scss/components/view/_view.scss
- src/openforms/ui/templates/ui/views/abstract/base.html
Closes #2549
Screencasts:
* Desktop width: https://watch.screencastify.com/v/TFMreUkJYFrC5gzYOlyb
* Mobile: https://watch.screencastify.com/v/6QUXNVC699vAmcxjr17D
> Fix cookie-banner styles/markup to not overlap other elements

- bin/lint_dependencies.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openapi.yaml
- src/openforms/registrations/contrib/camunda/serializers.py
> use PyPI version of drf-polymorphic

- src/openforms/formio/components/custom.py
- src/openforms/formio/dynamic_config/date.py
- src/openforms/formio/dynamic_config/tests/test_datetime_component.py
- src/openforms/js/components/form/date.js
- src/openforms/js/components/form/datetime.js
- src/openforms/js/components/form/edit/date-edit-form.js
> [#2682] Fix min/max datetime in editor

- src/openforms/formio/utils.py
- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
> [#2699] Uploads in repeating group

- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
Fixes #2699
I... hope this is the correct approach?
Tested manually - I can see the attachments in the admin and they are referenced in the confirmation PDF too
> Handle nested fields and repeating groups (2.0.x backport)

- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
> [#2699] Fix broken submission of form step

- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/test_read_submission.py
- src/openforms/submissions/tests/test_submission_completion.py
- src/openforms/submissions/utils.py
Fixed the logic evaluation not happening in a consistent manner.
Backport-Of: open-formulieren/open-forms#2726
> Backport of 2726

- src/openforms/scss/_vendor.scss
- src/openforms/scss/vendor/_django-two-factor-auth.scss
Fixes #2671 
*patched CSS for QR code by adding white background
> [#2671] fix QR code

- .github/workflows/ci.yml
- Dockerfile
Closes #2748
Pinned Python to a particular patch version for these tests in combination with coverage. Next, we'll have to keep an eye open on the upstream bug and hopefully it'll get fixed in 3.10.11.
> Pin to Python 3.10.9

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/form/file.js
> [#2742] File key not automatically updated

- docs/manual/forms/form_fields.rst
- docs/manual/forms/logic.rst
> :memo: [#2696] Add reference to dynamic Form options in form fields docs

- src/openforms/submissions/models/submission_files.py
The same pattern was repeated over and over again, which makes more sense to implement as a utility and configure it on the model instead.
> :art: DRY the formio-component configuration reading

- src/openforms/formio/utils.py
- src/openforms/forms/api/serializers/form_definition.py
- src/openforms/forms/api/serializers/form_step.py
- src/openforms/forms/tests/test_api_formdefinition.py
- src/openforms/forms/tests/test_api_formsteps.py
- src/openforms/forms/validators.py
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
Backport-Of: open-formulieren/open-forms#2765
> Detect duplicate keys in edit grid [backport]

- src/openforms/scss/_vendor.scss
- src/openforms/scss/vendor/_django-two-factor-auth.scss
- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/form_logic.py
Some more backports that need to be included in 1.1.10
> Backports of fixes to 1.1.x

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
Fixes #2781 
Needs backporting to stable 2.0.x and 1.1.x
> [#2781] Fix hiding nested components

- src/openforms/submissions/logic/datastructures.py
- src/openforms/submissions/tests/form_logic/test_modify_step.py
> [#2759] Create data diff correctly for nested components

- .storybook/preview-head.html
- src/openforms/js/components/admin/forms/ActionButton.stories.mdx
- src/openforms/js/components/admin/forms/ArrayInput.stories.mdx
- src/openforms/js/components/admin/forms/ButtonContainer.stories.mdx
- src/openforms/js/components/admin/forms/ErrorList.js
- src/openforms/js/components/admin/forms/ErrorList.stories.mdx
- src/openforms/js/components/admin/forms/Field.stories.mdx
- src/openforms/js/components/admin/forms/Fieldset.stories.mdx
- src/openforms/js/components/admin/forms/FormRow.stories.mdx
- src/openforms/js/components/admin/forms/Inputs.stories.mdx
- src/openforms/js/components/admin/forms/JsonWidget.stories.mdx
- src/openforms/js/components/admin/forms/RadioList.stories.mdx
- src/openforms/js/components/admin/forms/Select.stories.mdx
- src/openforms/js/components/admin/forms/SubmitRow.stories.mdx
- src/openforms/js/components/admin/tables/ChangelistTable.js
- src/openforms/js/components/admin/tables/Tables.stories.mdx
& separate standard + custom components a bit better.
Logical grouping:
> Document additional admin components

- src/openforms/validations/validators/formats.py
- src/openforms/validations/validators/tests/test_formats.py
> [#2786] Better errors for phone number validation

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/js/components/formio_builder/WebformBuilder.js
- src/openforms/js/components/formio_builder/builder.js
- src/openforms/js/utils/hooks.js
> [#2770] Fix non-unique keys across steps

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js
- src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js
Fixes #2805
We need some TypeScript :grimacing:
> Fix dragging component into new form step

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/form/edit/options.js
- src/openforms/js/components/formio_builder/builder.js
- src/openforms/js/components/formio_builder/translation.js
> [#2798] Update options values automatically

- docs/developers/backend/core/utils.rst
- src/openforms/emails/confirmation_emails.py
- src/openforms/submissions/models/submission.py
- src/openforms/submissions/tests/test_submission_confirmation.py
- src/openforms/variables/utils.py
> [#2804] Static vars in submission confirmation  template

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/form/map.js
> [#2821] Fix edit form map

- src/openforms/forms/management/commands/scan_component_usage.py
- src/openforms/forms/tests/commands/test_scan_component_usage_command.py
We can use this on instances to quickly get some information about how often certain component types are used.
> :sparkles: Add management command to check component usage

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/js/components/form/password.js
- src/openforms/js/components/formio_builder/translation.js
- src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py
- src/openforms/variables/models.py
> 🌐[#2819] Fix translations for password field.

- src/openforms/scss/pdfs/_submission-step-row.scss
> [#2971] Add word-break to CSS

- src/openforms/formio/utils.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#2838] Fix validation appearing too soon

- .prettierignore
- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- public/mockServiceWorker.js
- src/openforms/js/components/admin/modals/Modal.js
- src/openforms/scss/components/admin/_ReactModal.scss
* Large modal variant
* MSW mocks in storybook
> Cherry picked features from #2690

- package-lock.json
- package.json
- src/openforms/js/components/admin/forms/ArrayInput.js
- src/openforms/js/components/admin/forms/ArrayInput.stories.mdx
- src/openforms/js/components/admin/forms/MappingArrayInput.js
- src/openforms/js/components/admin/forms/MappingArrayInput.stories.mdx
Taken from PR open-formulieren/open-forms#2690
> :sparkles: [#2661] -- implement a mapping input widget

- src/openforms/logging/models.py
- src/openforms/logging/tests/test_admin.py
> [#2850] Broken log page

- src/openforms/config/models.py
- src/openforms/forms/tests/admin/test_form.py
- src/openforms/forms/utils.py
- src/openforms/translations/utils.py
- src/openforms/utils/translations.py
> [#2851] Fix translation import

- src/openforms/analytics_tools/contrib/google_analytics/csp_headers.json
- src/openforms/analytics_tools/contrib/matomo/csp_headers.json
- src/openforms/analytics_tools/contrib/piwik_pro/csp_headers.json
- src/openforms/analytics_tools/tests/test_google_analytics.py
- src/openforms/analytics_tools/tests/test_matomo.py
- src/openforms/analytics_tools/tests/test_piwik_pro.py
Fixes #2842 
Not sure if we need a backport?
> [#2842] Remove connect-src

- src/openapi.yaml
- src/openforms/forms/api/serializers/form.py
- src/openforms/forms/tests/test_api_forms.py
> [#2789] Improve text modal

- src/openforms/logging/logevent.py
- src/openforms/logging/logic.py
- src/openforms/logging/tasks.py
- src/openforms/submissions/logic/actions.py
- src/openforms/submissions/logic/log_utils.py
- src/openforms/submissions/logic/rules.py
- src/openforms/submissions/logic/service_fetching.py
- src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
> Add logging to service fetch action

- src/stuf/stuf_zds/templates/stuf_zds/soap/updateZaak.xml
Changes T(oevoegen) to W(ijzigen).
Tested on Djuma for SED
> Fix updateZaak

- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
> [#2888] Fix combination of file attachment and hidden repeating group

- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
> [#2888] Fix combination of attachments and numbers in repeating groups

- src/openapi.yaml
- src/openforms/api/serializers.py
- src/openforms/api/utils.py
- src/openforms/api/validators.py
- src/openforms/forms/api/serializers/form_variable.py
- src/openforms/forms/tests/variables/test_viewset.py
- src/openforms/variables/api/serializers.py
- src/openforms/variables/api/validators.py
- src/openforms/variables/models.py
- src/openforms/variables/tests/test_views.py
- src/openforms/variables/validators.py
> Allow inline service fetch configuration on form variable serializer

- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/tests/test_submission_suspension.py
> [#2785] fix attribute hashing on submission suspend

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/form-creation-form.js
> Backport of #2945 to stable/2.1.x

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
Following a dependabot alert.
I don't believe we actively use the async/await flavours of redis, but it's probably better to err on the safe side.
> Bump redis-py

- src/openforms/js/components/admin/form_design/form-creation-form.js
> Backport of #2945 to stable/2.0.x

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
* Fixes #2877 
* Based on maykinmedia/zgw-consumers#63
> [#2877] bump zgw_consumers to 0.26.0

- docs/manual/forms/export_import.rst
- src/openforms/forms/tests/test_import_export.py
> Test and document import export missing service fetch configs

- src/openforms/formio/utils.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#2900] Frontend logic checkboxes

- package-lock.json
- package.json
- src/openforms/config/forms.py
- src/openforms/config/tests/e2e_tests/test_organization_configuration.py
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/design_token_values/DesignTokenValues.js
- src/openforms/js/components/admin/design_token_values/index.js
- src/openforms/js/components/admin/index.js
- src/openforms/js/components/admin/plugin_configuration/index.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
- src/openforms/scss/_vendor.scss
- src/openforms/scss/components/admin/_ReactModal.scss
- src/openforms/scss/components/admin/_column-field-value.scss
- src/openforms/scss/components/admin/_index.scss
- src/openforms/scss/vendor/_design-token-editor.scss
Closes #2957 
The JSON field in the admin is now enhanced with a button to open a user-friendlier editor in a modal.
> Use design token editor in admin

- src/openforms/registrations/contrib/objects_api/plugin.py
- src/openforms/registrations/contrib/objects_api/tests/test_backend.py
Backport of https://github.com/open-formulieren/open-forms/pull/2981/commits
> [#2980] Backport fix

- src/openapi.yaml
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/tests/admin/test_form.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
> [#2849] Fix import error of forms with old logic rules

- docs/configuration/registration/email.rst
- docs/manual/templates.rst
- src/openforms/conf/tinymce_config.json
- src/openforms/js/components/admin/RJSFWrapper.js
- src/openforms/js/components/admin/form_design/RegistrationFields.js
- src/openforms/js/components/admin/form_design/registrations/index.js
- src/openforms/scss/vendor/_rjsf-field.scss
Fixes #2872 (last PR! :open_mouth:)
> [#2872] Documentation + improved UI

- src/openforms/registrations/contrib/objects_api/tests/test_backend.py
- src/openforms/submissions/attachments.py
- src/openforms/submissions/tests/test_submission_attachment.py
Fixes #2980 
For a description of the problem, see https://github.com/open-formulieren/open-forms/issues/2980#issuecomment-1511269630
Needs backport to 2.1.x
> [#2980] Object API registration of file inside fieldset goes wrong

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
Bumped version, updated changelog
~~Blocked by #2980~~
> Release 2.1.2

- .github/workflows/ci.yml
> :green_heart: #3016 - Fix the (macOS) ci build.

- src/openapi.yaml
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
> Backport of #3007

- src/openforms/authentication/tests/test_signals.py
- src/openforms/authentication/utils.py
Backport of https://github.com/open-formulieren/open-forms/pull/3024
> [#1959] Backport to 2.0.x

- src/openforms/authentication/signals.py
- src/openforms/authentication/tests/test_signals.py
- src/openforms/authentication/utils.py
Backport of https://github.com/open-formulieren/open-forms/pull/3024
> [#1959] Backport to  2.1.x

- CONTRIBUTING.md
As discussed in refinement, we documented how small textual changes should be handled as well as refactoring code.
> Added note on refactor and small changes

- src/csp_post_processor/processor.py
- src/openforms/formio/dynamic_config/__init__.py
- src/openforms/formio/dynamic_config/tests/test_dynamic_options.py
> [#2895] fix admin inline colors

- src/openforms/js/components/form/editGrid.js
> [#2343] Hide repeating group label

- src/openapi.yaml
- src/openforms/api/views/mixins.py
- src/openforms/contrib/kvk/validators.py
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/validations/api/serializers.py
- src/openforms/validations/api/views.py
- src/openforms/validations/registry.py
- src/openforms/validations/tests/test_api.py
- src/openforms/validations/tests/test_registry.py
- src/openforms/validations/validators/formats.py
Closes #1879 
* updated existing tests to reflect changes
> [#1879] display only relevant validation plugins

- src/openforms/forms/tests/e2e_tests/test_form_configuration.py
- src/openforms/js/components/form/file.js
- src/openforms/js/lang/formio/en.json
- src/openforms/js/lang/formio/nl.json
Fixes #3040 
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/407
> [#3040] Improve error messages for file components

- src/openforms/submissions/tests/test_start_submission.py
Fixes 4 failing tests in #2999
> :green_heart: [#2999] fixed test isolation that was caused by prefill logging

- src/openforms/scss/admin/_app_overrides.scss
- src/openforms/scss/vendor/_rjsf-field.scss
Fixes #3031 
Added css to increase specific input fields based on class and id
> :art: [#3031] made object api registry plugin fields wider

- src/openforms/config/tests/test_config_check.py
fixes test_disabled_plugins_are_skipped issolation #2999
> :green_heart: [#2999] mock GlobalConfiguration for test_disabled_plugins_are_skipped

- src/openforms/conf/base.py
Closes #3068
* Added setting for celery hard time limit
* Made both hard and soft time limits configurable from env (deliberately undocumented)
> :sparkles: [#3068] -- add setting for celery task hard time limit

- docs/installation/config.rst
- src/openforms/analytics_tools/models.py
- src/openforms/analytics_tools/tests/mixin.py
- src/openforms/analytics_tools/tests/test_google_analytics.py
- src/openforms/analytics_tools/tests/test_matomo.py
- src/openforms/analytics_tools/tests/test_piwik.py
- src/openforms/analytics_tools/tests/test_piwik_pro.py
- src/openforms/analytics_tools/tests/test_site_improve.py
- src/openforms/analytics_tools/utils.py
Closes #2651
I'm drawing up a bit of a refactor which will go in a separate PR too
> Fix cookies receiving wrong domain information

- src/openforms/formio/components/vanilla.py
- src/openforms/formio/dynamic_config/tests/test_file_component.py
> [#3040] Improve error messages when allowed types are configured in the General config

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
Closes #2879 
updated zgw-consumers version
> :arrow_up: [#2879] updated zgw-consumers

- src/openforms/validations/validators/formats.py
- src/openforms/validations/validators/tests/test_formats.py
> [#3097] correct phone numbers in error messages

- src/openforms/forms/tests/test_import_export.py
Fixes test_import_export in #2999
> :green_heart: [#2999] added order_by id to retrieval of form_logic

- src/openforms/authentication/utils.py
- src/openforms/submissions/forms.py
- src/openforms/submissions/templates/submissions/find_submission_for_cosign.html
- src/openforms/submissions/tests/test_views.py
- src/openforms/submissions/urls.py
- src/openforms/submissions/views.py
Fixes #1530 
Depends on https://github.com/open-formulieren/open-forms/pull/3085
> [#1530] Part 4 - Backend view for finding submission

- src/openapi.yaml
- src/openforms/authentication/api/serializers.py
- src/openforms/authentication/tests/test_utils.py
- src/openforms/authentication/utils.py
- src/openforms/forms/api/serializers/form.py
- src/openforms/forms/tests/test_serializers.py
- src/openforms/submissions/tests/test_views.py
- src/openforms/submissions/views.py
> [#1530] Part 5 - Pass details to frontend for cosign button

- src/openforms/authentication/signals.py
- src/openforms/authentication/templates/of_authentication/logout_confirmation.html
- src/openforms/authentication/tests/test_views.py
- src/openforms/authentication/urls.py
- src/openforms/authentication/views.py
- src/openforms/submissions/templates/submissions/find_submission_for_cosign.html
- src/openforms/submissions/tests/test_views.py
> [#1530] Part 9 - Logout button

- src/openforms/submissions/api/permissions.py
- src/openforms/submissions/models/submission.py
- src/openforms/submissions/tests/form_logic/test_side_effects.py
- src/openforms/submissions/tests/test_models.py
> [#3114] Backport to 2.0.x

- src/openforms/submissions/api/permissions.py
- src/openforms/submissions/models/submission.py
- src/openforms/submissions/tests/form_logic/test_side_effects.py
- src/openforms/submissions/tests/test_models.py
> [#3114] Backport 2.1.x

- package-lock.json
- package.json
- src/openforms/authentication/forms.py
- src/openforms/scss/components/_form-choices.scss
- src/openforms/submissions/forms.py
- src/openforms/templates/includes/forms/field_wrapper.html
- src/openforms/utils/templates/of_utils/widgets/radio.html
- src/openforms/utils/templates/of_utils/widgets/radio_option.html
- src/openforms/utils/widgets.py
> Fix styling Django pages after NLDS migration

- src/openforms/config/tests/test_migrations.py
- src/openforms/emails/migrations/0010_add_cosign_templatetag.py
- src/openforms/emails/tests/test_migrations.py
> Template migration translations

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/data/complete-form.js
Fixes #3132 
Needs backport to 2.2.x, 2.1.x, 2.0.x
> [#3132] Replace form definition

- src/openforms/js/components/form/coSignOld.js
> [#1508] Add hidden option to deprecated cosign component

- src/openforms/emails/api/serializers.py
- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/utils.py
Fixes #3182 
Needs backport to 2.2
> [#3182] Import forms without cosign template tag

- src/openforms/formio/typing/base.py
- src/openforms/js/components/form/currency.js
> [#1882] Configure min/max on currency component

- package-lock.json
- package.json
- src/openforms/formio/formatters/tests/files/appointments_components.json
- src/openforms/formio/variables.py
- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/form/cosign.js
- src/openforms/js/components/form/edit/options.js
- src/openforms/js/components/form/edit/tabs.js
- src/openforms/js/components/form/editGrid.js
- src/openforms/js/components/form/fieldset.js
- src/openforms/js/components/form/map.js
- src/openforms/js/components/form/select.js
- src/openforms/submissions/tests/test_get_submission_step.py
> Enable tooltips

- src/openforms/analytics_tools/templates/analytics_tools/piwik_pro.html
> [#3211] Added missing nonce in Piwik Pro tag

- src/openforms/analytics_tools/templates/analytics_tools/piwik_pro.html
> [#3211] Backport 2.1.x - Added missing nonce in Piwik Pro tag

- src/openforms/analytics_tools/templates/analytics_tools/piwik_pro.html
>  [#3211] Backport 2.0.x - Added missing nonce in Piwik Pro tag

- src/openforms/analytics_tools/templates/analytics_tools/piwik_pro.html
> [#3211] Backport 2.2.x - Added missing nonce in Piwik Pro tag

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️  [#3049] -- upgrade to django-hijack 3.4.1

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️  [#3049] -- upgrade to django-redis 5.3.0

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️  [#3049] -- upgrade to django-filter 23.2

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️  [#3049] -- upgrade to elastic-apm 6.17.0

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️  [#3049] -- upgrade to sentry-sdk[django] 1.27.1

- .github/workflows/ci.yml
- dotenv.example
- src/openforms/appointments/contrib/qmatic/tests/test_plugin.py
- src/openforms/setup.py
Related to #3242
Enabled on Github actions and opt-in for development environments.
> Set up a CI profile for hypothesis

- requirements/ci.txt
- requirements/dev.txt
A QOL upgrade; the old pytest in the requirements is fighting with my
pytest-plugins. And we're in the process of updating real requirements,
so I keep breaking my test runner.
> Upgrade pytest

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openforms/fixtures/default_admin_index.json
Fixes #3030 
Related to https://github.com/maykinmedia/django-admin-index/pull/88
> [#3030] Add translations to admin tabs

- package-lock.json
- package.json
> :arrow_up: Bump to formio-builder 0.6.0

- src/openforms/submissions/api/views.py
- src/openforms/submissions/tests/test_temporary_uploads.py
> [#3219] Remove uploads from registration if deleted

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openforms/js/initTinymce.js
> ⬆️  [#3049] -- updated to django-tinymce 3.6.1

- src/openforms/js/components/form/edit/components.js
- src/openforms/js/components/form/number.js
Fixes: #3045 
- added suffix to number component
> :sparkles: [#3045] added suffix to number formio component 

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/openforms/registrations/contrib/stuf_zds/utils.py
Fixes #3238 
It looks like the user defined vars were already present in the request.
>  [#3238] User defined variables in StUFZDS

- src/openforms/prefill/contrib/haalcentraal/constants.py
> [#3258] Fix Haal centraal naming attributes

- src/openforms/prefill/contrib/haalcentraal/client.py
- src/openforms/prefill/contrib/haalcentraal/plugin.py
- src/openforms/prefill/contrib/haalcentraal/tests/test_config_check.py
> [#3166] Add tests for HC connection for v1 and v2

- src/openapi.yaml
- src/openforms/authentication/api/serializers.py
- src/openforms/authentication/api/tests/test_endpoints.py
- src/openforms/authentication/base.py
- src/openforms/authentication/contrib/outage/plugin.py
- src/openforms/js/components/admin/form_design/AuthPluginField.js
- src/openforms/js/components/admin/form_design/FormConfigurationFields.js
- src/openforms/js/components/admin/form_design/types/AuthPlugin.js
> [#3189] Clean up provides_auth types

- src/openforms/prefill/contrib/haalcentraal/client.py
- src/openforms/prefill/contrib/haalcentraal/plugin.py
- src/openforms/prefill/contrib/haalcentraal/tests/test_client.py
- src/openforms/prefill/contrib/haalcentraal/tests/test_plugin.py
Reallized this after discussing #3272 with Vasileios
> Fix broken pre-request context in HaalCentraal prefill plugin

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/nodes.py
- src/openforms/registrations/contrib/email/tests/test_backend.py
> Missing links to attachments in fieldsets

- src/stuf/stuf_bg/client.py
- src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml
- src/stuf/stuf_bg/tests/test_client.py
- src/stuf/stuf_bg/xsd/bg0310/bag/bg0310_ent_bag.xsd
- src/stuf/stuf_bg/xsd/bg0310/entiteiten/bg0310_simpleTypes.xsd
- src/stuf/stuf_bg/xsd/bg0310/mutatie/bg0310_ent_mutatie.xsd
- src/stuf/stuf_bg/xsd/bg0310/prs/bg0310_ent_prs.xsd
- src/stuf/stuf_bg/xsd/bg0310/prs/bg0310_simpleTypes_prs.xsd
> Implement inp.heeftAlsKinderen StUF-BG request

- .github/workflows/ci.yml
- src/openforms/appointments/contrib/qmatic/tests/test_plugin.py
- src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
- src/openforms/tests/utils.py
And tweak the profiling output to declutter the stdout output in CI.
> [#3242] Profile more failing tests

- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/contrib/jcc/tests/test_plugin.py
> Use naive datetimes for JCC

- docs/manual/forms/examples/dynamic_options_2.rst
- docs/manual/forms/examples/index.rst
> Document how to use `current_year` to populate select.

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆[#3319] Upgrade django-digid-eherkenning to 0.8.1

- docs/manual/templates.rst
- src/openforms/forms/tests/test_api_formdefinition.py
- src/openforms/template/backends/sandboxed_django.py
- src/openforms/utils/templatetags/utils.py
- src/openforms/utils/tests/test_templatetags.py
> [#3277] Add template tag to get dictionary value

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
This release fixes a bug of duplicated log entries when using multiple requests in a single requests session.
> :arrow_up: Bump django-log-outgoing-requests

- src/openforms/appointments/base.py
- src/openforms/appointments/contrib/demo/plugin.py
- src/openforms/appointments/contrib/jcc/plugin.py
- src/openforms/appointments/contrib/jcc/tests/test_plugin.py
- src/openforms/appointments/contrib/qmatic/plugin.py
- src/openforms/appointments/core.py
- src/openforms/appointments/tests/test_booking_appointment.py
- src/openforms/appointments/utils.py
Closes #3286
Generic solution for normalization of data, which is plugin specific
> Ensure customer detail data is normalized

- README.rst
- docker/ci/dockerhub_readme.md.j2
- docs/index.rst
- docs/installation/config.rst
- publiccode.yaml
- src/openforms/js/lang/formio/nl.json
- src/openforms/urls.py
https://theoatmeal.com/comics/ie
> ✏️A Fix misuses of i.e. where e.g. was meant

- src/openforms/appointments/contrib/qmatic/plugin.py
- src/openforms/appointments/contrib/qmatic/tests/test_plugin.py
Closes #3299 - note that there is an SDK PR to make the "amount" field readonly when multiple products is not supported
This ensures that Qmatic works in single-product, single-customer mode with the new appointment flow. It also deprecates the entire plugin as it appears that this particular plugin is not currently used.
We can revert on the deprecation if a stakeholder steps up.
> Ensure QMatic works with new-style appointments

- src/openforms/prefill/contrib/stufbg/tests/test_co_sign.py
- src/stuf/stuf_bg/client.py
- src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponse.xml
- src/stuf/stuf_bg/tests/test_client.py
Closes #3368
Don't know if the type annotations make backporting harder. Sorry, not sorry. 😜
> 🐛[#3368] Remove nil values from stuf bg responses

- src/openforms/submissions/models/submission_report.py
- src/openforms/submissions/templates/report/submission_report.html
- src/openforms/submissions/tests/test_tasks_pdf.py
> 🐛[#3320] Add appointment info to summary pdf

- .github/workflows/ci.yml
- docker/ci/config.json
- docs/developers/extending.rst
- requirements/extensions.in
- requirements/extensions.txt
> [#3185] Add prefill extension to image

- .github/workflows/build-image.yml
- .github/workflows/ci.yml
- docker/ci/config.json
Fixes #3389 
Depends on:
https://github.com/open-formulieren/demo-extension/pull/5
https://github.com/open-formulieren/open-forms-ext-token-exchange/pull/13
> [#3389] Do not build test images anymore

- .github/workflows/ci.yml
> Forgot to remove docker push action for test image

- src/openapi.yaml
- src/openforms/api/drf_spectacular/hooks.py
- src/openforms/middleware.py
- src/openforms/tests/test_middleware.py
Fixes #3139 
- removed IS_FORM_DESIGNER_HEADER_NAME when user isn't authenticated
> :bug: [#3139] fixed bug that superusers/designers could not work on forms that are in maintenance mode

- docs/developers/extending.rst
- docs/developers/extensions.rst
> Documentation Haal centraal HR + extensions CI

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
fixes #3393 
updated dependency off django-digid-eherkenning who now have distinct instance field verbose names
> :arrow_up: [#3393] updated dependecy of django-digid-eherkenning

- docs/configuration/appointment/index.rst
- docs/configuration/appointment/jcc.rst
- docs/configuration/appointment/qmatic.rst
- docs/manual/forms/basics.rst
- docs/manual/forms/examples/appointment_creation.rst
- docs/manual/forms/examples/appointment_form.rst
- docs/manual/forms/examples/index.rst
- src/openforms/js/components/admin/form_design/FormConfigurationFields.js
- src/openforms/js/components/admin/form_design/FormDetailFields.js
* Updated the documentation for appointments
* Tweaked the form designer to hide irrelevant form fields when a form is in appointment mode
> Appointments non-functionals

- src/openforms/forms/tests/test_copy.py
- src/openforms/forms/tests/test_import_export.py
- src/openforms/forms/utils.py
- src/openforms/variables/tests/factories.py
> Fix 500 on import with service fetch logic.

- src/openforms/authentication/contrib/digid/tests/test_signicat_integration.py
> 🩹 Rename test and set record mode to none

- docs/developers/backend/core/testing-tools.rst
- src/openforms/appointments/contrib/qmatic/tests/test_products_list.py
- src/openforms/authentication/contrib/digid/tests/test_signicat_integration.py
- src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py
- src/openforms/conf/dev.py
- src/openforms/utils/tests/vcr.py
Moved to generic test utils package and documented the usage.
> Make VCRMixin reusable

- docker-compose.yml
- docker-nginx-default.conf
- src/openforms/forms/forms/form.py
> [#3421] Bulk import configuration problems

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/FormLogic.js
- src/openforms/js/components/admin/form_design/StepSelection.js
- src/openforms/js/components/errors/ErrorBoundary.js
- src/openforms/js/components/errors/ErrorMessage.js
- src/openforms/scss/components/admin/_error-message.scss
- src/openforms/scss/components/admin/_index.scss
- src/openforms/scss/components/admin/_logic-rule-error.scss
- src/openforms/scss/components/admin/_logic-rule.scss
> [#3422] Prevent broken logic rule to break admin

- package-lock.json
- package.json
Adds support for:
* Number
* Email
* Date
Component types.
> Bump formio-builder to 0.7.2

- src/openforms/forms/models/form.py
- src/openforms/forms/tests/admin/test_form.py
> [#3378] Fix formstep url in logic rules of copied form

- requirements/ci.txt
- requirements/dev.txt
- src/openforms/submissions/models/submission_report.py
- src/openforms/submissions/tests/test_models.py
- src/openforms/submissions/tests/test_submission_report.py
- src/openforms/submissions/tests/test_tasks_pdf.py
> [#3470] Handle large form names which contain special characters

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> Bump to django-log-outgoing-requests 0.5.2

- src/openforms/emails/apps.py
- src/openforms/emails/constants.py
- src/openforms/emails/signals.py
- src/openforms/emails/tests/test_send_mail_html.py
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/email_status_change.txt
> [#3402] Add support for logging status changes in yubin emails

- src/openforms/emails/apps.py
- src/openforms/emails/constants.py
- src/openforms/emails/signals.py
- src/openforms/emails/tests/test_send_mail_html.py
- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/email_status_change.txt
- src/openforms/registrations/contrib/email/plugin.py
- src/openforms/registrations/contrib/email/tests/test_backend.py
> [#3402] Add extra headers to email registration

- docs/developers/backend/core/utils.rst
- src/openforms/admin/decorators.py
- src/openforms/appointments/admin.py
- src/openforms/appointments/contrib/jcc/tests/test_admin.py
- src/openforms/appointments/contrib/qmatic/tests/test_admin.py
- src/openforms/registrations/contrib/zgw_apis/admin.py
- src/openforms/registrations/contrib/zgw_apis/tests/test_admin.py
- src/openforms/registrations/contrib/zgw_apis/tests/test_zgw_api_config.py
- src/openforms/scss/admin/admin_overrides.scss
- src/openforms/scss/admin/widgets/_error-widget.scss
- src/openforms/scss/admin/widgets/_index.scss
- src/openforms/utils/tests/test_decorators.py
Closes #3279 
Backport of decorator from main branch
> Backport: suppress requests errors

- src/zgw_consumers_ext/api_client.py
> Specify `auth` as a `ZGWAuth` field with `init=False`

- docker/ci/requirements.txt
- package-lock.json
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/CreateAppointmentTests/CreateAppointmentTests.test_create_appointment_multi_product_multi_customer.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/CreateAppointmentTests/CreateAppointmentTests.test_create_appointment_single_product_single_customer.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_listing_dates_single_product_multiple_customers.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_listing_dates_single_product_single_customer.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_multiple_products_multiple_customers.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableProductsTests/ListAvailableProductsTests.test_listing_products_with_location_and_product_constraint.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableProductsTests/ListAvailableProductsTests.test_listing_products_without_location_with_product_constraint.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableProductsTests/ListAvailableProductsTests.test_listing_products_without_other_product_constraint.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_listing_times_single_product_multiple_customers.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_listing_times_single_product_single_customer.yaml
- src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_multiple_products_multiple_customers.yaml
- src/openforms/appointments/contrib/qmatic/tests/test_appointment_create.py
- src/openforms/appointments/contrib/qmatic/tests/test_products_list.py
- src/openforms/appointments/contrib/qmatic/tests/test_times_list.py
- src/openforms/contrib/kvk/tests/files/vcr_cassettes/KVKProfilesClientTests/KVKProfilesClientTests.test_client.yaml
- src/openforms/contrib/kvk/tests/files/vcr_cassettes/KVKProfilesClientTests/KVKProfilesClientTests.test_client_404.yaml
- src/openforms/contrib/kvk/tests/files/vcr_cassettes/KVKProfilesClientTests/KVKProfilesClientTests.test_client_vve.yaml
- src/openforms/contrib/kvk/tests/files/vcr_cassettes/KVKSearchClientTests/KVKSearchClientTests.test_client.yaml
- src/openforms/contrib/kvk/tests/files/vcr_cassettes/KVKSearchClientTests/KVKSearchClientTests.test_client_404.yaml
Following @dependabot alerts.
None of the vulnerabilities seem actually exploitable, so low severity assumed.
> Bump dependencies

- src/openforms/forms/tests/e2e_tests/test_form_designer.py
- src/openforms/js/components/admin/form_design/FormStepDefinition.js
- src/openforms/scss/components/admin/_edit-panel.scss
Fixes #3188 
added warning for when there are components with duplicate keys
added test to see if warning shows if duplicate keys are pressent
> :sparkles: [#3188] added duplicated keys warnings in form

- src/openforms/forms/api/serializers/form_variable.py
* remove a comment symbol that lost the way
* remove __init__ that only calls super __init__
> :art: Small code cleanups

- src/openforms/js/components/form/file.js
Closes #3557 
Stumbled upon this when trying to reverse engineer The Thing for the new form builder.
Fix confirmed with a real Open Zaak connection.
> :bug: Don't re-nest item, but prop spread it

- requirements/extensions.txt
> [#3435] Upgrade the token exchange dependency

- Dockerfile
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
Closes #3644
Uses more :wheel_of_dharma: too in installation, so the build is faster and safer
> Upgrade weasyprint

- src/openforms/submissions/tests/test_resume_form_view.py
- src/openforms/submissions/views.py
> [#3613] Fix resuming submission when form does not require login

- src/openforms/submissions/tests/test_resume_form_view.py
- src/openforms/submissions/views.py
Fixes #3613 
Backport of https://github.com/open-formulieren/open-forms/pull/3642
> Backport of #3613 to 2.1.x

- src/openforms/submissions/tests/test_resume_form_view.py
- src/openforms/submissions/views.py
Fixes #3613 
Backport of https://github.com/open-formulieren/open-forms/pull/3642/commits
> Backport of #3613 to 2.2.x

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> Update to django-digid-eherkenning 0.10.0

- docs/configuration/authentication/digid.rst
> [#3452] Document DigiD configuration

- src/openforms/contrib/objects_api/rendering.py
- src/openforms/registrations/contrib/objects_api/plugin.py
Needed by https://github.com/open-formulieren/open-forms/pull/3658 and https://github.com/open-formulieren/open-forms/pull/3663
> :recycle: Refactor utilities for dealing with JSON templates

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> :arrow_up: [#3707] Upgrade mozilla-django-oidc-db

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
> :speech_balloon: [#3201] Replace a last 'optioneel' with 'niet verplicht'

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Fixes #3702 
I changed the translations, not sure if making the email configurable should be taken up as part of this ticket. It is also mentioned in this other meta issue: https://github.com/open-formulieren/open-forms/issues/3149
> :speech_balloon: [#3702] Updated dutch translations regarding co-sign

- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid/test_auth_procedure.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid_machtigen/test_auth_procedure.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_auth_procedure.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning_bewindvoering/test_auth_procedure.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/views.py
- src/openforms/authentication/contrib/org_oidc/tests/test_auth_procedure.py
Fixes #3692  
Based on #3656 so it needs first to be merged.
> [#3692] Fix next url when authenticated user cancels login

- src/openforms/submissions/models/submission.py
- src/openforms/submissions/tests/test_models.py
> [#3705] Fix `__str__` datetime representation of `Submission`

- package-lock.json
- package.json
- src/openforms/js/components/formio_builder/WebformBuilder.js
Now with the (deprecated) password component
> :arrow_up: Bump to formio-builder 0.12.0

- src/openforms/formio/tests/search_strategies.py
- src/openforms/formio/tests/test_search_strategies.py
- src/openforms/formio/tests/test_utils.py
- src/openforms/formio/typing/vanilla.py
- src/openforms/tests/search_strategies.py
> :hammer: [#2958] Define formio-component specific search strategies

- .github/workflows/ci.yml
- src/openforms/submissions/api/serializers.py
- src/openforms/tests/e2e/base.py
- src/openforms/tests/e2e/test_resume_form.py
Fixes #3626
Add an E2E test for the resume flow, so that we can catch problems earlier in the future.
> [#3626] Test resume flow

- src/openforms/frontend/frontend.py
- src/openforms/payments/contrib/demo/plugin.py
- src/openforms/payments/contrib/demo/tests/test_plugin.py
- src/openforms/payments/contrib/ogone/plugin.py
- src/openforms/payments/contrib/ogone/tests/test_plugin.py
- src/openforms/payments/tests/test_e2e.py
Fixes #3726 (partially)
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/628
> [#3726] Payment views rework

- Dockerfile
- bin/report_component_problems.py
Probably good to have this script at-hand so we can run it in existing environments.
> Add script to detect component issues

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> :arrow_up: [#3743] Upgrade ZGW consumers

- package-lock.json
- package.json
> :arrow_up: [#3761] Fixed duplication bug in builder package

- src/openforms/prefill/contrib/stufbg/plugin.py
- src/openforms/prefill/contrib/stufbg/tests/test_plugin.py
- src/stuf/stuf_bg/constants.py
- src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml
- src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponse.xml
> [#2710] Add prefill for initials

- src/openforms/fixtures/admin_index_unlisted.json
- src/openforms/fixtures/default_admin_index.json
> [#3779] Cleanup forms admin tab

- CHANGELOG.rst
Can be merged when the following PRs are merged (and tagged):
* #3770
* #3771
* #3772
> Add release notes from patch releases

- docs/developers/releases.rst
- src/openforms/utils/tests/vcr.py
Following some PR feedback about VCR.
> :pencil: Improve documentation for release process

- src/openforms/prefill/__init__.py
> [#3752] Improve clarity in `prefill` module

- package-lock.json
- package.json
> [#3774] Update to `formio-builder@0.13.3`

- docs/configuration/validation/brk.rst
- docs/configuration/validation/index.rst
> [#3758] Add docs regarding the BRK validation plugin

- src/soap/tests/data/vcr_cassettes/ClientTransportTests/ClientTransportTests.test_it_can_build_a_functional_client.yaml
- src/suwinet/tests/data/vcr_cassettes/SuwinetKadasterTests/SuwinetKadasterTests.test_persoons_info_bsn_111111110.yaml
- src/suwinet/tests/data/vcr_cassettes/SuwinetKadasterTests/SuwinetKadasterTests.test_persoons_info_bsn_444444440.yaml
- src/suwinet/tests/data/vcr_cassettes/SuwinetRDWDossierDigitaleDienstenTests/SuwinetRDWDossierDigitaleDienstenTests.test_test_bsns.yaml
- src/suwinet/tests/factories.py
- src/suwinet/tests/test_client.py
Need to test this still while re-recording the VCR cassettes
> :art: Make factory more DRY and use deep context from factory boy

- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_admin.py
> [#3809] Fix change view of submission

- .gitignore
- docker/docker-compose.embedding.yml
- docker/embedding/README.md
- docker/embedding/default.conf
- docker/embedding/query-params.html.template
- docs/configuration/general/cms_integration.rst
- docs/developers/csp.rst
- docs/developers/embedding.rst
- docs/developers/index.rst
- docs/developers/sdk/index.rst
- docs/installation/form_hosting.rst
- docs/installation/security.rst
~~Pause-and-resume *does not work properly* yet.~~
Closes #3616
Closes #3709
> :whale: [#3616] Add docker-compose setup for embedding testing

- src/openforms/appointments/base.py
- src/openforms/appointments/contrib/demo/plugin.py
- src/openforms/appointments/templates/appointments/appointment__pdf.html
- src/openforms/appointments/tests/test_pdf.py
> [#3616] Fix PDF template of submission appointment

- src/openforms/js/components/formio_builder/translation.js
- src/openforms/js/components/formio_builder/translation.spec.js
> [#3382] Translation warnings for date,datetime placeholders

- src/openforms/plugins/registry.py
This is a simple follow up of https://github.com/open-formulieren/open-forms/pull/3630/.
This isn't a perfect solution either, but got hit by this when dealing with such code:
```python
plugin = ObjectsAPIRegistration("...")  # ObjectsAPIRegistration is a subclass of the base plugin class
reveal_type(plugin)  # "BasePlugin", should be "ObjectsAPIRegistration"
```
so I was missing the specific attributes of `ObjectsAPIRegistration`.
The only downside of this change is that a registry could register a plugin that does not inherit from the correct base, although this isn't a big concern I think
> 🏷️ Improve generic type hinting of registry

- package-lock.json
- package.json
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.mdx
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/constants.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/types.js
- src/openforms/js/components/admin/form_design/mocks.js
- src/openforms/js/components/admin/form_design/story-decorators.js
Fixes #3730 (partially)
Screenshot from storybook:
> [#3730] Part 2 - DMN config panel

- src/openforms/authentication/service.py
- src/openforms/authentication/tests/test_utils.py
- src/openforms/authentication/utils.py
- src/openforms/forms/tests/e2e_tests/test_form_configuration.py
- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/tests/test_on_cosign.py
- src/openforms/submissions/tests/test_submission_co_sign.py
- src/openforms/submissions/tests/test_views.py
- src/openforms/submissions/views.py
fixes #3680 
Not sure how i managed to miss these...
> [#3680] Missed references to authPlugin

- src/openapi.yaml
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/logic/actions/Action.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/ActionSet.js
- src/openforms/js/components/admin/form_design/logic/actions/Actions.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js
- src/openforms/js/components/admin/form_design/logic/constants.js
- src/openforms/scss/components/admin/_index.scss
- src/openforms/scss/components/admin/_mappings.scss
> [#3730] Part 3 - Logic action tab

- src/openforms/forms/api/parsers.py
- src/openforms/forms/api/viewsets.py
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js
- src/openforms/submissions/logic/actions.py
- src/openforms/submissions/tests/form_logic/test_modify_variables.py
> [#3730] Forgot to update variable mappings everywhere

- package-lock.json
- package.json
> [#3727] Update formio builder to 0.16.0

- src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml
> [#3863] Fix order of stuf BG request payload

- src/openforms/conf/base.py
- src/openforms/formio/tests/test_api_fileupload.py
- src/openforms/submissions/api/viewsets.py
- src/openforms/submissions/utils.py
Closes #3858
70506fad8f5faef05282558db932725a94062e76 has the full gory details about what and how
This issue affects all supported branches.
> Fix concurrency issue with bulk-uploads

- docker/docker-compose.objects-apis.yml
- docker/objects-apis/README.md
- docker/objects-apis/docker-init-objecttypes-api-db.sql
- docker/objects-apis/fixtures/objecttypes_api_fixtures.json
Part of #3688
To be resolved:
- https://github.com/open-formulieren/open-forms/pull/3847#discussion_r1483118292
>  [#3688] Phase 1 - Add docker compose for objecttypes API

- src/openforms/scss/_vars.scss
- src/openforms/scss/admin/_admin_theme.scss
- src/openforms/scss/admin/_app_overrides.scss
- src/openforms/scss/admin/themes/_dark.scss
- src/openforms/scss/admin/themes/_light.scss
This is in preparation for the actual changes in Django 4.2.
Part of #3049 
This setup should also be applied to default project.
> Restructure code for admin light/dark themes

- src/openforms/forms/admin/form_version.py
> [#3822] Fix searching in formversion

- src/openapi.yaml
- src/openforms/registrations/api/urls.py
- src/openforms/registrations/contrib/objects_api/api/serializers.py
- src/openforms/registrations/contrib/objects_api/api/urls.py
- src/openforms/registrations/contrib/objects_api/api/views.py
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_list_objecttype_verions_unknown_objecttype.yaml
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_list_objecttype_versions.yaml
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_staff_user_required.yaml
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesAPIEndpointsTests/ObjecttypesAPIEndpointsTests.test_list_objecttypes.yaml
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesAPIEndpointsTests/ObjecttypesAPIEndpointsTests.test_staff_user_required.yaml
- src/openforms/registrations/contrib/objects_api/tests/test_api_endpoints.py
Part of #3688
This is the one that was already reviewed and merged back in the original PR.
>  [#3688] Add Objecttypes API endpoints 

- src/digid_eherkenning_oidc_generics/admin.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid/test_admin.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_admin.py
> Ensure all configuration options are exposed in the admin

- .github/workflows/ci.yml
- src/openforms/conf/base.py
- src/openforms/utils/tests/cache.py
> Address broken test isolation

- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
> [#3855] Automatically select DMN plugin

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/constants.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.mdx
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNParametersForm.js
- src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js
- src/openforms/js/components/admin/form_design/mocks.js
Fixes #3855 (partially)
depends on https://github.com/open-formulieren/open-forms/pull/3886
> [#3855] Select DMN variables in config (frontent)

- src/openforms/formio/service.py
- src/openforms/formio/utils.py
- src/openforms/formio/variables.py
- src/openforms/submissions/tests/form_logic/test_fetching_form_variable_values_from_services.py
- src/openforms/variables/models.py
> [#3672] Allow access to data as list, dict in service fetch

- src/openforms/submissions/logic/actions.py
- src/openforms/submissions/tests/form_logic/test_cache_dmn_requests.py
Fixes #3855 (partially)
Do we want a customisable timeout?
> [#3855] Cache DMN requests results

- src/openforms/payments/tasks.py
- src/openforms/registrations/tasks.py
- src/openforms/submissions/admin.py
- src/openforms/submissions/tests/test_post_submission_event.py
> [#3924] Don't set retry flag when payment is completed successfully

- src/openforms/forms/templates/admin/forms/form/change_list.html
- src/openforms/js/components/admin/form-category.js
> :sparkles: [#3885] add open/collapsed for form categories

- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js
- src/openforms/scss/components/builder/_builder.scss
> :lipstick: Display errors above input field

- src/openforms/formio/rendering/nodes.py
- src/openforms/formio/rendering/tests/test_component_node.py
> [#3890] Allow hidden fields to be sent to registration systems

- CHANGELOG.rst
- docker/ci/config.json
Ready to be merged when 2.2.10 is on Docker Hub.
> Add patch release notes

- src/openforms/js/components/admin/form_design/registrations/handlers.js
- src/openforms/js/components/admin/form_design/registrations/index.js
> [#3909] Update eigenschappen mappings in ZGW when a form definition is modified

- src/openforms/contrib/zgw/clients/documenten.py
- src/openforms/contrib/zgw/service.py
- src/openforms/registrations/contrib/objects_api/plugin.py
- src/openforms/registrations/contrib/zgw_apis/plugin.py
> [#851] Clean up DocumentenClient

- docs/configuration/general/external_services.rst
- docs/configuration/general/index.rst
- docs/manual/forms/examples/service_fetch.rst
- docs/manual/forms/form_fields.rst
- docs/manual/templates.rst
Closes #3879
Closes #3823 
* Added documentation for service fetch service configuration
* Added documentation for service/soap service configuration
* Added documentation for regexes
* Added documentation for template filters
> Add more documentation

- src/openapi.yaml
- src/openforms/api/urls.py
- src/openforms/fixtures/default_groups.json
- src/openforms/forms/api/public_api/permissions.py
- src/openforms/forms/api/public_api/viewsets.py
- src/openforms/forms/api/serializers/category.py
- src/openforms/forms/api/viewsets.py
- src/openforms/forms/tests/test_api_categories.py
> [#3825] Public categories endpoint

- docs/developers/extensions.rst
> Update documentation about pre-request clients

- src/openforms/contrib/digid_eherkenning/constants.py
- src/openforms/contrib/digid_eherkenning/tests/test_csp_update.py
> [#3950] Add CSP headers eHerkenning

- src/openforms/scss/admin/themes/_dark.scss
- src/openforms/scss/admin/themes/_light.scss
- src/openforms/scss/components/builder/_builder.scss
> :lipstick: [#3958] removed styling for the read-only field

- src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py
- src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py
- src/openforms/authentication/contrib/eherkenning/tests/test_eidas_auth.py
- src/openforms/emails/tests/test_confirmation_email.py
- src/openforms/emails/tests/test_send_mail_html.py
- src/openforms/forms/tests/test_api_forms.py
- src/openforms/submissions/tests/form_logic/test_fetching_form_variable_values_from_services.py
- src/openforms/submissions/tests/test_variables/test_model.py
- src/openforms/translations/tests/test_utils.py
- src/stuf/stuf_bg/tests/test_client.py
> 🗑️ Update deprecated unittest methods

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> ⬆️ Update `django-log-outgoing-requests` to `0.6.1`

- README.rst
- docs/developers/versioning.rst
> :memo: [#3838] Document Public API

- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiSummaryHandler.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js
https://github.com/open-formulieren/open-forms/pull/3982/ will handle the backend part
> [#3688] Add option to map var to geometry attribute

- src/openforms/js/components/admin/form_design/form-creation-form.js
- src/openforms/js/components/admin/form_design/registrations/index.js
- src/openforms/js/components/admin/form_design/registrations/stepEditHandlers.js
- src/openforms/js/components/admin/form_design/registrations/userDefinedVariableEditHandlers.js
> [#3688] Handle mutations/deletions of variables

- src/openforms/registrations/contrib/objects_api/json_schema.py
- src/openforms/registrations/contrib/objects_api/tests/test_json_schema.py
Part of #3688.
Hopefully the JSON Schemas used by municipalities have the spec provided.
> [#3688] Fix issue when no JSON Schema spec is provided

- src/openforms/submissions/api/validation.py
- src/openforms/submissions/tests/test_submission_completion.py
> Apply formio component validations during submission complete

- src/openforms/submissions/models/submission.py
- src/openforms/submissions/tests/test_models.py
Fixes https://github.com/open-formulieren/open-forms/issues/3705, take two.
> [#3705] Fix submission `__str__` again

- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js
- src/openforms/scss/admin/themes/_dark.scss
> [#3688] Small fixes in frontend

- bin/report_kvk_gateways.py
> [#4006] Add KVK gateway detection script

- docker/docker-compose.objects-apis.yml
- docker/objects-apis/README.md
- docker/objects-apis/docker-init-objects-apis-db/0001-docker-init-objects-apis-db.sql
- docker/objects-apis/docker-init-objects-apis-db/0002-extensions.sh
- docker/objects-apis/fixtures/objects_api_fixtures.json
Part of #3688.
Not tested yet, but do not hesitate to let me know if things need to be changed
> [#3688] Add docker configuration for Objects API

- src/openforms/registrations/tasks.py
- src/openforms/registrations/tests/test_registration_hook.py
> [#4022] Fix crash when registering after payment

- docs/manual/forms/basics.rst
- src/openforms/submissions/models/submission_value_variable.py
- src/openforms/submissions/tests/form_logic/test_submission_logic.py
- src/openforms/variables/static_variables/static_variables.py
- src/openforms/variables/tests/test_static_variables.py
Closes #2827
Closes #2828 (due to added isinstance checks)
Another one for the types big topic :)
> :bug: [#2827] Fix crash when assigning variable now to a field

- src/openforms/registrations/contrib/objects_api/checks.py
- src/openforms/registrations/contrib/objects_api/tests/test_config_checks.py
Fixes https://github.com/open-formulieren/open-forms/issues/4007
> Fix config checks for Objects API plugin

- docker/objects-apis/fixtures/objecttypes_api_fixtures.json
- src/openforms/registrations/contrib/objects_api/plugin.py
- src/openforms/registrations/contrib/objects_api/registration_variables.py
- src/openforms/registrations/contrib/objects_api/submission_registration.py
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIPaymentStatusUpdateV2Tests/ObjectsAPIPaymentStatusUpdateV2Tests.test_update_payment_status.yaml
- src/openforms/registrations/contrib/objects_api/tests/test_update_payment_status_v2.py
> [#3688] Fix payment updates: use PATCH, represent payment as float

- src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.spec.js
> Support filtering for GeoJSON-compatible schema properties

- src/openforms/registrations/contrib/objects_api/submission_registration.py
- src/openforms/registrations/contrib/objects_api/tests/test_backend.py
>  [#4041] Improve API documents registration robustness 

- src/openforms/formio/serializers.py
- src/openforms/formio/tests/validation/test_textfield.py
- src/openforms/tests/e2e/test_input_validation_regressions.py
> Fix hidden component validation blocking submission completion

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> Bump to maykin-python3-saml patch release

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
> [#3878] Update some dependencies

- src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py
- src/openforms/authentication/contrib/eherkenning/tests/test_eidas_auth.py
- src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py
- src/openforms/contrib/digid_eherkenning/tests/test_csp_update.py
> [#3950] Support multiple LoAs for eHerkenning/eIDAS

- .github/workflows/ci.yml
Backport of 26940bbb3fef1b54f946d91dc559121f27d0c87e
> Backport 2.4.x: Use docker compose V2 in CI

- .github/workflows/ci.yml
Backport of 26940bbb3fef1b54f946d91dc559121f27d0c87e
> Backport 2.5.x: Use docker compose V2 in CI

- src/openforms/formio/serializers.py
- src/openforms/formio/tests/validation/test_editgrid.py
- src/openforms/formio/utils.py
- src/openforms/submissions/api/validation.py
Related to #3977 and #4068 
Taiga DH issue 667
> Fix input validation regression for edit grids

- src/openforms/formio/serializers.py
- src/openforms/formio/tests/validation/test_radio.py
> [#4096] Fix validation of hidden radio component 

- src/openforms/submissions/tests/form_logic/test_fetching_form_variable_values_from_services.py
- src/openforms/variables/models.py
- src/openforms/variables/validators.py
> [#4015] Fix possible traversal attack in service fetch

- .github/actions/report-flaky/.gitignore
- .github/actions/report-flaky/action.yml
- .github/actions/report-flaky/package-lock.json
- .github/actions/report-flaky/package.json
- .github/actions/report-flaky/report_flaky.js
- .github/workflows/ci.yml
- .gitignore
- requirements/ci.txt
- requirements/dev.txt
- requirements/test-tools.in
- src/openforms/conf/base.py
- src/openforms/conf/utils.py
- src/openforms/formio/tests/test_api_fileupload.py
- src/openforms/tests/utils.py
* Add retry behaviour
* Log that test if flaky
* Ensure that flaky tests get reported in github annotations
How it looks in Github:
> Deal with flaky test

- src/openforms/formio/tests/test_api_fileupload.py
The flakiness handling was a bit bugged in itself :clown_face:
> Further improvements to flaky test

- src/openforms/js/components/admin/form_design/registrations/stepEditHandlers.js
>  [#4134] Fix admin crash on component key edit 

- Dockerfile
Shaves off about ~2 minutes of the docker build time :)
> :whale: Use uv to install dependencies in docker build

- src/openforms/accounts/tests/factories.py
- src/openforms/admin/tests/test_admin_login.py
- src/openforms/admin/views.py
Closes #4072
Needs backporting to 2.6.x
> Fix MFA recovery token flow

- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/tests/form_logic/test_side_effects.py
- src/openforms/submissions/tests/test_submit_form_step.py
- src/openforms/tests/e2e/input_validation_base.py
> Apply partial input validation on submission step put

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/stuf/stuf_zds/client.py
- src/stuf/stuf_zds/tests/test_backend.py
> [#4145] Fix payment status for StUF ZDS backend

- src/openforms/emails/tasks.py
- src/openforms/emails/templates/emails/admin_digest.html
- src/openforms/emails/tests/test_tasks.py
- src/openforms/logging/service.py
Partly fixes #3725 
This PR handles the prefill plugins (second subtask)
> [#3725] Add prefill failures to email digest

- src/openforms/formio/components/vanilla.py
- src/openforms/formio/tests/validation/test_selectboxes.py
- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/tests/test_submission_step_validate.py
- src/openforms/submissions/tests/test_submit_form_step.py
Partly closes #72
Closes #4151
> Validate selectboxes

- src/openforms/payments/tests/test_views.py
- src/openforms/payments/views.py
Fixes #4052
This fixes the issues that multiple emails are sent if a payment is cancelled.
It does NOT fix the fact that if you complete the payment successfully you get both an immediate email and one after the timeout.
> [#4052] Don't trigger 'on completion' task chain if payment was unsuccessful

- src/openforms/js/components/admin/form-category.js
Fixes #4124 
Probably this would benefit from a E2E test
> [#4124] Fix list display of forms when pagination is involved

- src/openforms/emails/templates/emails/admin_digest.html
- src/openforms/logging/service.py
Updates #3725
This is mainly adding a hint to the email in case there is an error in the extra_data dictionary.
> [#3725] Update registration failures email with the possible errors

- src/openforms/logging/logevent.py
- src/openforms/logging/templates/logging/events/confirmation_email_scheduled.txt
- src/openforms/submissions/tasks/emails.py
- src/openforms/submissions/tests/test_email_scheduling.py
> [#4052] Fix emails being sent too many times

- .github/workflows/ci.yml
- .github/workflows/code_quality.yml
> Switch to UV in CI

- README.NL.rst
- docs/developers/versioning.rst
- docs/introduction/index.rst
- docs/introduction/versions.rst
Following some internal discussions
> Update versioning policy

- package-lock.json
- package.json
Contains bugfixes for a number of tickets:
* #4084
* #4155
* #3964
> :arrow_up: Upgrade to formio-builder 0.18.2

- docker/objects-apis/fixtures/objects_api_fixtures.json
- docker/objects-apis/fixtures/objecttypes_api_fixtures.json
- src/openforms/registrations/contrib/objects_api/submission_registration.py
- src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_layout_components.yaml
- src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py
>  [#4141] Fix Objects API registration crash with fieldset 

- src/openforms/formio/utils.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#3964] Bandaid to fix old forms with simple conditionals

- src/openforms/submissions/api/validation.py
- src/openforms/submissions/tests/test_submission_completion.py
> [#4187] Evaluate logic before formio validation on submission completion

- src/openforms/registrations/contrib/objects_api/submission_registration.py
- src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py
>  [#4202] Fix Objects API registration v2 crash with hidden fields 

- src/openforms/formio/management/commands/formio_makemessages.py
- src/openforms/formio/service.py
- src/openforms/formio/utils.py
- src/openforms/forms/api/validators.py
- src/openforms/payments/management/commands/checkpaymentemaildupes.py
- src/openforms/prefill/management/commands/generate_prefill_from_spec.py
- src/openforms/prefill/tests/test_prefill_hook.py
- src/openforms/prefill/tests/test_prefill_variables.py
- src/openforms/registrations/contrib/objects_api/migrations/0011_create_objecttypesypes_service_from_url.py
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
- src/openforms/submissions/logic/rules.py
- src/openforms/submissions/mapping.py
- src/openforms/submissions/utils.py
- src/openforms/template/backends/sandboxed_django.py
- src/stuf/tests/testcases.py
Things I noticed over the weeks
> Some lints

- src/openforms/registrations/contrib/objects_api/submission_registration.py
Backport-of: #4203
I haven't added the test as some refactoring was done afterwards.
> [#4202] Fix Objects API registration v2 crash with hidden fields

- src/openforms/formio/typing/base.py
- src/openforms/formio/typing/custom.py
- src/openforms/formio/typing/dates.py
- src/openforms/tests/e2e/test_input_validation.py
It was part of the closed #4063 PR (no explicit ticket)
> Improve formio date component types

- docs/configuration/registration/zgw.rst
- src/openforms/formio/utils.py
- src/openforms/submissions/tests/form_logic/test_modify_components.py
> [#3964] Backport to 2.4.x

- src/openforms/forms/models/form.py
- src/openforms/forms/tests/test_copy.py
> [#4173] Include registration backends when copying a form

- src/openforms/formio/components/custom.py
- src/openforms/formio/formatters/custom.py
- src/openforms/formio/tests/validation/test_cosign.py
- src/openforms/tests/e2e/test_input_validation.py
> [#72] Add backend validation for cosign component

- docs/conf.py
- requirements/ci.txt
- requirements/dev.txt
- requirements/docs.in
Partly closes #3878
**Changes**
Update doc dependencies
**Checklist**
> [#3878] Update docs dependencies

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py
Closes https://github.com/open-formulieren/open-forms/issues/4219
> ⬆️ Update `django-digid-eherkenning` to `0.13.1`

- src/openforms/formio/components/vanilla.py
- src/openforms/formio/tests/validation/test_password.py
- src/openforms/tests/e2e/test_input_validation.py
> [#72] Add backend validation for password component

- docs/conf.py
- docs/developers/backend/core/_assets/forms-models.mmd
- docs/developers/backend/core/formio.rst
- docs/developers/backend/core/index.rst
- requirements/ci.txt
- requirements/dev.txt
- requirements/docs.in
Fixes #4044, replaces https://github.com/open-formulieren/open-forms/pull/4058
> [#4044] Improve dev documentation regarding forms and submissions

- src/openforms/forms/models/form.py
- src/openforms/forms/tests/test_copy.py
Closes #4184
**Changes**
- Added a regression test
- Update form copy flow in order to have the correct (new) formstep UUID in the logic rule's actions
**Checklist**
> [#4184] Update formstep uuid in logic rules after form copy

- CHANGELOG.rst
- docker/ci/config.json
- docs/archive/changes-v2.rst
**Changes**
* Added final patch release notes
* Moved 2.3.x release notes to archive
* Updated DockerHub description generation config to remove 2.3.x
> Archive Open Forms 2.3.x

- src/openforms/submissions/form_logic.py
- src/openforms/submissions/logic/rules.py
Some more things I came across when preparing the DMN demo.
**Changes**
* Removed some dead code for logic rule evaluation logging (which was removed in an earlier PR)
**Checklist**
> Random minor cleanup

- package-lock.json
- package.json
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/fixtures/cookie_consent.json
- src/openforms/js/public.js
- src/openforms/templates/includes/cookie-notice.html
**Changes**
* Upgraded to latest django-cookie-consent, which adds unique constraints to some fields (they were missing)
* Updated fixture to use natural primary/foreign keys
* Include the JS from the npm package instead of dynamically loading the module via staticfiles
**Checklist**
> Upgrade django cookie consent

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
Closes #4285
- Upgraded library to latest version (2024.5.3)
> [#4285] Upgrade schwifty to latest version

- src/openforms/emails/digest.py
> :art: Simplify variable collection code

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
> 🔖 Bump version to 2.6.7 and update changelog

- src/openforms/js/components/admin/form_design/logic/Trigger.js
Closes #4291
**Changes**
- Convert user defined boolean variables values from string to boolean type
**Checklist**
> [#4291] Fix logic triggers with boolean user defined variables

- docs/manual/forms/basics.rst
Closes #...
**Changes**
**Checklist**
> Typefout verwijderd.

- docs/manual/forms/logic.rst
Closes #...
**Changes**
**Checklist**
> Typefout verbeterd.

- src/openforms/conf/tinymce_config.json
Closes #4368
**Changes**
* Fix broken URLs on same domain in tinymce
**Checklist**
> :bug: [#4368] Fix broken URLs on same domain in tinymce

- CHANGELOG.rst
Release notes from patch releases
> :pencil: Added patch release notes

- src/openforms/scss/pdfs/_submission-step-row.scss
previously, empty values did not take up any space, breaking the submission PDF layout if any fieldsets were used or if fields did not have data
Closes #4403 
**Changes**
* Fix submission PDF layout for empty values
**Checklist**
> :bug: [#4403] Fix submission PDF layout for empty values

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
Closes #4379
**Changes**
Upgraded to patched version of OIDC library
**Checklist**
> Fix error on logout because of malformed redirect URL in response

- package-lock.json
- package.json
- src/openforms/js/components/formio_builder/WebformBuilder.js
Closes #4051
**Changes**
**Checklist**
> [#4051] Update `@open-formulieren/formio-builder` to `0.22.0` and support dark mode

- src/openforms/forms/tests/test_import_export.py
> :thread: Fix filesystem race condition in import/export tests

- src/openforms/authentication/static_variables/static_variables.py
- src/openforms/authentication/tests/test_static_variables.py
Closes #4475
**Changes**
* Added `language_code` static variable
* Added `submission_id` static variable
**Checklist**
> Add submission UUID and language code static variables

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
Partly closes #4267
**Checklist**
> [#4267] Clear variables mapping when changing Objects API configuration

- package-lock.json
- package.json
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js
- src/openforms/js/lang/nl.json
Partly closes #4486
**Changes**
* Updated backend translations
* Updated frontend translations
There will be some more changes in the formio-builder, but that's just re-compiling the translations and ship-it to be done :)
**Checklist**
> Update translations for 2.7 release

- src/openforms/authentication/admin.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/submissions/admin.py
Partly closes #4505
**Changes**
* Ensure that the authentication info inline in the submission admin properly displays all the context
* Grouped fields/information in a more logical way in the submission admin as it was extremely cluttered
**Checklist**
> Submission admin improvements

- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/forms/tests/test_api_form_logic_bulk.py
Stumbled upon this while implementing the JSON editor
> Fix validation crash

- docker/open-zaak/fixtures/open_zaak_fixtures.json
Partly closes #4267
**Checklist**
> [#4267] Update OZ fixtures

- pyright.pyproject.toml
- src/openforms/payments/models.py
- src/openforms/registrations/base.py
- src/openforms/registrations/contrib/email/config.py
- src/openforms/registrations/contrib/email/models.py
- src/openforms/registrations/contrib/email/plugin.py
- src/openforms/registrations/contrib/email/tests/test_backend.py
- src/openforms/submissions/exports.py
- src/openforms/submissions/models/submission.py
- src/openforms/submissions/query.py
Noticed type errors and mismatches in the type definition vs. serializer while working on #4549, so this follows that PR.
> Add a generic type var for registration plugin options

- src/openforms/forms/api/serializers/form_variable.py
- src/openforms/forms/tests/variables/test_viewset.py
Closes #4555 remark
**Changes**
* Added some missing backend validation leading to database errors due to failing check constraints.
**Checklist**
> Fix integrity error crash by using proper validation

- .github/workflows/ci.yml
- bin/check_zgw_groups.py
- src/openforms/registrations/contrib/zgw_apis/models.py
Closes #4584 
* Added CI check so that our upgrade checks run before publishing a release
* Patched the check script crash that happens in 2.7.3
> :construction_worker: Set up CI job to test upgrade checks

- CHANGELOG.rst
- docs/archive/changes-v2.rst
Move the 2.4.x release notes to the archive.
> :pencil: Archive 2.4.x release notes

- package-lock.json
- package.json
- src/openforms/formio/components/custom.py
- src/openforms/formio/tests/validation/test_addressnl.py
- src/openforms/formio/typing/base.py
Closes #4420 partly
**Changes**
* Implement backend validation for AddressNL components
**Checklist**
> ✨ [#4420] Backend validation for AddressNL components

- src/openapi.yaml
- src/openforms/submissions/api/serializers.py
- src/openforms/submissions/api/urls.py
- src/openforms/submissions/api/views.py
- src/openforms/submissions/tests/test_email_verification.py
Closes #4542 partially - ~~requires #4615 to be merged first~~
**Changes**
* Added endpoint to verify the code obtained via the verification email
**Checklist**
> Add endpoint to verify an email address

- docs/configuration/general/analytics.rst
Closes #4671
**Changes**
Added entry to docs
> Add KLANTINFOCUS to analytics docs.

- .github/workflows/code_quality.yml
- src/openforms/fixtures/default_admin_index.json
> Fix code quality CI workflow

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
**Changes**
* Bumped version number
* Updated changelog
> :bookmark: Bump version to 2.7.7 and update changelog

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
Hotfix release for issue in 2.7.7
> :bookmark: Bump version to 2.7.8 and update release notes

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
Closes #4733 
**Changes**
- Updated simplejson library
**Checklist**
> [#4733] Fix segmentation fault due to simplejson library

- .github/workflows/ci.yml
Cache workflow taken from their README and tweaked a little bit.
> :construction_worker: Address trivy-action rate limit issues

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
> Release 2.8.1

- docs/manual/forms/logic.rst
Logic rules did not work
Closes #...
**Changes**
Fixes the logic rules regarding "duration" which did not work.
**Checklist**
> Fix duration logic in docs

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Simplified the language down to B1 level.
Needs to be backported to 2.7.x too!
> :children_crossing: [#4320] Use more accessible language

- src/openforms/ui/static/ui/scss/components/_page-footer.scss
- src/openforms/ui/static/ui/scss/components/_page-header.scss
- src/openforms/ui/static/ui/scss/components/_page.scss
Related to #3283
**Changes**
Removing deprecated and old backwards compatible styling.
**Checklist**
> Removing old/deprecated design tokens

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/RegistrationFields.stories.js
- src/openforms/js/components/admin/form_design/SubmissionFields.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
Part of #4920
**Changes**
* Updated Dutch JS translations
* Updated Dutch backend
**Checklist**
> Update translations for 3.0

- docker/ci/config.json
**Changes**
- Updated docker config file concerning the new supported tags (v3.0.0). 
**Checklist**
> Update supported tags for v3 in docker json config file

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
This release has extra options for eherkenning/eidas metadata configuration.
Closes #4785
**Changes**
Upgraded to new release of django-digid-eherkenning package which provides the required configuration options.
**Checklist**
> Bump django-digid-eherkenning

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
Partly closes #5055
**Changes**
**Checklist**
> Prepare patch release 3.0.2

- docs/configuration/registration/index.rst
- docs/configuration/registration/json-dump.rst
No related issue
**Changes**
Add documentation for JSON dump registration plugin 
**Checklist**
> Add documentation for JSON dump registration plugin

- package-lock.json
- package.json
Closes #5025 partially
**Changes**
- Upgraded form builder to v0.37.0
**Checklist**
> Bump form builder to v.0.37.0

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Partly closes #5126
**Changes**
Patch release for 2.8.6. Updated backend translations and changelog, and bumped version.
**Checklist**
> Patch release 2.8.6

- package-lock.json
- package.json
- src/openforms/ui/static/ui/scss/_nlds.scss
Part of open-formulieren/open-forms-sdk#445 (updating dependencies)
**Changes**
* Updated to latest @utrecht/components
* Updated to compatible design-tokens package
Note that this package is no longer being published in favour of individual components - that's going to be another undertaking for some future day.
**Checklist**
> Upgrade utrecht components

- src/openapi.yaml
- src/openforms/forms/api/serializers/logic/action_serializers.py
- src/openforms/js/components/admin/form_design/FormLogic.stories.js
- src/openforms/js/components/admin/form_design/logic/actions/ActionSet.js
- src/openforms/submissions/logic/actions.py
Closes #5040
**Changes**
Added a unique key to the Action component.
**Checklist**
> Add unique key to Action component

- src/openforms/logging/logevent.py
- src/openforms/logging/models.py
- src/openforms/prefill/sources.py
- src/openforms/prefill/tests/test_prefill_hook.py
Closes #5188 
**Changes**
* Added regression test
* Added type hints to allow us to reason about the code/expected arguments
* Fixed the logging call arguments
:warning: This does *NOT* fix existing data.
**Checklist**
> Fix broken attribute logging

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
Contains further tweaks to the DigiD/eHerkenning SAML metadata generation.
**Checklist**
> Bump to django-digid-eherkenning 0.21.0

- src/openforms/forms/statistics.py
Closes #5203
**Changes**
Added explicit sheet title for both kinds of submission (completed-registered) in the export file.
**Checklist**
> [#5203] Fixed sheet title in the submissions export file

- docker/docker-compose.open-zaak.yml
**Changes**
Disable 2FA for Open Zaak docker container
**Checklist**
> Disable 2FA for Open Zaak docker container

- src/openforms/forms/tests/test_json_schema.py
No related issue
**Changes**
Perform a set comparison in `GenerateJsonSchemaTests.test_correct_variables_included_in_schema`
**Checklist**
> Fix test flakiness

- docs/manual/forms/form_fields.rst
Added some minimal documentation to the manual.
> Add reference lists documentation

- src/openforms/js/components/admin/form_design/registrations/objectsapi/AddressNlObjectsApiVariableConfigurationEditor.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/MapObjectsApiVariableConfigurationEditor.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js
- src/openforms/js/components/admin/form_design/registrations/objectsapi/SelectboxesObjectsApiVariableConfigurationEditor.js
- src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
Closes #5207 partly
**Changes**
- Removed geometry field from variables configuration when component is selectboxes
**Checklist**
> [#5207] Remove geometry field from variables configuration (`selectboxes`)

- src/openforms/forms/api/viewsets.py
Closes #5238
**Changes**
- Added ordering to the serializer. 
Tried to find a less "expensive" way to do that (and basically didn't see any difference after the ordering) but didn't.
**Checklist**
> [#5238] Order by datetime Form version list

- docker/keycloak/README.md
- docker/keycloak/import/test-realm.json
- src/openforms/authentication/contrib/org_oidc/plugin.py
- src/openforms/authentication/contrib/org_oidc/tests/base.py
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/EmployeeAuthContextTests/EmployeeAuthContextTests.test_record_auth_context_employee.yaml
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/OrgOIDCCallbackTests/OrgOIDCCallbackTests.test_failing_claim_verification.yaml
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/OrgOIDCCallbackTests/OrgOIDCCallbackTests.test_logout_clears_session.yaml
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/OrgOIDCCallbackTests/OrgOIDCCallbackTests.test_redirects_after_successful_auth.yaml
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/OrgOIDCInitTests/OrgOIDCInitTests.test_start_flow_logs_out_existing_user.yaml
- src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/OrgOIDCInitTests/OrgOIDCInitTests.test_start_flow_redirects_to_oidc_provider.yaml
- src/openforms/authentication/contrib/org_oidc/tests/test_auth_context_data.py
- src/openforms/authentication/contrib/org_oidc/tests/test_auth_flow_callbacks.py
- src/openforms/authentication/contrib/org_oidc/tests/test_auth_flow_init.py
- src/openforms/tests/data/vcr_cassettes/OIDCRegistratorSubjectHaalCentraalPrefillIntegrationTest/OIDCRegistratorSubjectHaalCentraalPrefillIntegrationTest.test_flow.yaml
- src/openforms/tests/test_registrator_prefill.py
Closes #5214
**Changes**
- Added employeeID to the auth context for org_oidc when it's present
**Checklist**
> [#5214] Add employeeID to the auth context for org_oidc when it's present

- Dockerfile
- bin/docker_start.sh
- bin/uwsgi.ini
- docker-compose.yml
- docker/docker-compose.observability.yaml
- docker/observability/README.md
- docker/observability/promtail/config.yml
- docs/conf.py
- docs/installation/index.rst
- docs/installation/observability.rst
- src/openforms/setup.py
- src/openforms/wsgi.py
Closes #5285 (partly)
[skip: e2e]
**Changes**
* Ensure as much uwsgi logs as possible are structured logs
* Test setup in docker image/container
* Provide pointers for SRE/devops that have to integrate OF into their observability stack
Tested against Promtail/Loki/Grafana - once merged, I'll set up a real, proper dashboard for Maykin SAAS on our Grafana.
**Checklist**
> Infrastructure structured logging

- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
- src/openforms/js/components/admin/form_design/variables/prefill/constants.js
- src/openforms/js/components/admin/form_design/variables/prefill/family_members/ChildrenFiltersFields.js
- src/openforms/js/components/admin/form_design/variables/prefill/family_members/FamilyMembersFields.js
- src/openforms/js/components/admin/form_design/variables/prefill/family_members/PersonsFields.js
- src/openforms/js/components/admin/form_design/variables/prefill/family_members/constants.js
- src/openforms/js/lang/en.json
- src/openforms/js/lang/nl.json
Closes #5254 partly
**Changes**
**Requirements**
**Checklist**
> [#5254] Implement family members frontend configuration

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/configuration/general/styling.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
Partly closes #5330
**Changes**
:up: 
**Checklist**
> Release 3.0.8

- src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py
> :rotating_light: Don't complain about coverage in unreachable code

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/tests/test_custom_formio_components.py
**Changes**
- Some final tweaks for the PartnersNode (after the email registration PR for the Partners was merged)
**Checklist**
> Additional tweaks for the PartnersNode

- docs/changelog-nl.rst
**Changes**
Updates the dutch version of the changelog for the 3.2.0 release.
[skip: e2e]
> [#5398] Update dutch changelog for 3.2.0

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
- src/openforms/fixtures/admin_index_unlisted.json
Closes #5356
**Changes**
Upgraded to library version that has the feature.
~~Note: the styling of the dropdown is off, it's not high enough.~~
**Checklist**
> Upgrade django-digid-eherkenning with mock UX improvements

- CHANGELOG.rst
- docs/developers/releases.rst
> [#5462] update changelog

- docs/installation/ansible.rst
- src/openforms/emails/tests/test_digest_functions.py
- src/openforms/utils/json_logic/datastructures.py
Closes #5271 (backport for 3.2.x)
> Backport 3.2.x/5271 digest logic accumulator

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- docs/developers/releases.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Changes required for the `3.1.6` release.
> Release 3.1.6

- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- pyproject.toml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Changes required for the `3.2.1` release.
> Release 3.2.1

- CHANGELOG.rst
Adds the changelog entries for the latest patch releases
[skip: e2e]
> Add changelog entries for latest patch releases

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
Closes #5206
**Changes**
**Checklist**
> :arrow_up: [#5206] bump django-digid-eherkenning to 0.24.0

- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_cannot_resume_someone_elses_submission.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_login_with_a_high_loa_succeeds.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_login_with_too_low_a_loa_fails.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_raising_loa_requirements_fails_in_flight_authentications.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_resuming_a_suspended_submission.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_resuming_checks_loa_too.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_resuming_checks_with_current_loa_of_form.yaml
- src/openforms/authentication/contrib/digid/tests/data/vcr_cassettes/SignicatDigiDIntegrationTests/test_test_key_material_is_not_fishing_bait.yaml
- src/openforms/authentication/contrib/digid/tests/test_signicat_integration.py
- src/openforms/authentication/contrib/eherkenning/tests/data/vcr_cassettes/SignicatEHerkenningIntegrationTests/test_cannot_resume_someone_elses_submission.yaml
- src/openforms/authentication/contrib/eherkenning/tests/data/vcr_cassettes/SignicatEHerkenningIntegrationTests/test_key_material_is_not_fishing_bait.yaml
- src/openforms/authentication/contrib/eherkenning/tests/data/vcr_cassettes/SignicatEHerkenningIntegrationTests/test_login_with_a_high_loa_succeeds.yaml
- src/openforms/authentication/contrib/eherkenning/tests/data/vcr_cassettes/SignicatEHerkenningIntegrationTests/test_resuming_a_suspended_submission.yaml
- src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py
[skip: e2e]
The screens changed because of adding Yivi identity provider, forcing a selection.
> Re-record signicat cassettes

- src/openforms/registrations/contrib/stuf_zds/plugin.py
- src/openforms/registrations/contrib/stuf_zds/tests/files/vcr_cassettes/StufZDSPluginPartnersComponentVCRTests/test_only_relevant_variables_are_taken_into_account.yaml
- src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py
Closes #5572
**Changes**
- Added regression test
- Filter the variables on the specific form and type of family members
**Checklist**
> [#5572] Fix StUF-ZDS registration for partners causing a `KeyError`

- src/openforms/payments/contrib/ogone/admin.py
- src/openforms/payments/contrib/ogone/migrations/0003_ogonewebhookconfiguration_ogonemerchant_api_key_and_more.py
- src/openforms/payments/contrib/ogone/models.py
- src/openforms/payments/contrib/ogone/tests/test_admin.py
Partially closes #5580 
**Changes**
3.2.x changes from previously merged https://github.com/open-formulieren/open-forms/pull/5589.
**Checklist**
> [#4879] payment admin improvements 3.2.x

- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- pyproject.toml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
**Changes**
Adds changes for the `3.2.3` release.
**Checklist**
> Release 3.2.3

- .bumpversion.cfg
- CHANGELOG.rst
- README.NL.rst
- README.rst
- package-lock.json
- package.json
- publiccode.yaml
- src/openforms/__init__.py
- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
**Changes**
Adds changes for the `3.1.8` release.
**Checklist**
> Release 3.1.8

- docs/configuration/registration/stufzds.rst
Old branch, still relevant/useful?
[skip: e2e]
> :memo: Document SOAP operations for StUF-ZDS

- src/openforms/authentication/api/tests/test_logout.py
- src/openforms/authentication/api/views.py
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/data/vcr_cassettes/DigiDLogoutTests/test_logout_after_form_submission.yaml
- src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/test_auth_flow_logout.py
- src/openforms/authentication/signals.py
- src/openforms/authentication/tests/test_views.py
- src/openforms/authentication/utils.py
Closes #5095
**Changes**
**Checklist**
>  [#5095] logout from oidc digid after the form is submitted 

- .github/ISSUE_TEMPLATE/prepare-release.md
**Changes**
Updates the list of VCR cassettes.
**Checklist**
> Update release template

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/extensions.txt
- requirements/type-checking.txt
- src/openforms/conf/base.py
- src/openforms/emails/tasks.py
- src/openforms/emails/tests/test_tasks_integration.py
This reverts the local workaround from #5376 after contributing the patch upstream.
[skip: e2e]
> Bump to latest django-yubin patch release

- src/openforms/conf/locale/nl/LC_MESSAGES/django.po
- src/openforms/js/compiled-lang/nl.json
- src/openforms/js/lang/nl.json
- src/openforms/payments/contrib/worldline/plugin.py
- src/openforms/payments/contrib/worldline/tests/test_plugin.py
- src/openforms/payments/contrib/worldline/tests/vcr_cassettes/test_plugin/WorldlinePluginTests/test_custom_descriptor_allowed_characters.yaml
**Changes**
Updates the helptext for the `descriptor` field (in the Worldline configuration options) in the form admin.
**Checklist**
[skip: e2e]
> Update descriptor helptext

- src/openforms/formio/rendering/default.py
- src/openforms/formio/rendering/tests/test_custom_formio_components.py
Closes #5646
**Changes**
- Removed message for "no information provided" when it's not needed
**Checklist**
> [#5646] Family members styling enhancements

- package-lock.json
- package.json
- src/openforms/js/compiled-lang/en.json
- src/openforms/js/compiled-lang/nl.json
Bump to latest formio-builder package
**Checklist**
> :arrow_up: [#5191] Upgrade formio-builder

- CHANGELOG.rst
- docs/changelog-nl.rst
Include the benchmark results in the release notes.
[skip: e2e]
> Add 3.3.0 upgrade benchmarks to the release notes

- docker/ci/config.json
**Changes**
Updates the supported versions now that `3.3.0` was released. 
**Checklist**
> Update supported versions in dockerhub

- src/openforms/prefill/tests/test_prefill_hook.py
These tests were failing because #5665 was merged without a rebase
[skip: e2e]
**Changes**
**Checklist**
> :green_heart: Fix CI
