open-formulieren/open-forms

src/openforms/validations/api/views.py
Needed for #463 which is essentially just a front end ticket.
Without this line the SDK gets a CSRF error when calling to validate.
=> Do not require a csrf

.gitignore, docs/installation/config.rst, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/openforms/celery.py, src/openforms/conf/base.py, src/openforms/utils/tasks.py
Fixes #504
* Added celery beat entry for e-mail sending (django yubin management command), every 20 seconds by default
* Added celery-once to prevent long-running jobs from being scheduled at the same time. E.g. the queue is so full that e-mail sending takes 25s, but after 20s the second send-job would've been scheduled and processing the queue as well. This is prevented by using celery-once.
=> Ensure e-mails from the queue are send periodically via celery beat

src/openforms/registrations/tasks.py, src/openforms/registrations/tests/test_registration_hook.py
=> Mark submission registration status as complete when form has no registration backend

src/openforms/forms/tasks.py, src/openforms/forms/tests/test_configuration_error_detection.py, src/openforms/forms/tests/test_remove_key_from_dict.py, src/openforms/forms/utils.py
Fixes https://github.com/open-formulieren/open-forms/issues/513
The cause of the bug is that FormIO uses `time_24hr` in it's configuration.
The `camelize` function does accept `ignore_fields` but this only works if the field is a dictionary so we could just ignore the `widget` dictionary but I think this will ignore too much.
=> Fix adding date field

src/openforms/prefill/contrib/stufbg/plugin.py, src/openforms/prefill/contrib/stufbg/tests/test_plugin.py, src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml, src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponseMissingSomeData.xml, src/stuf/stuf_bg/tests/test_client.py
Fixes #567 
The cause of the bug was that the xml template used when making request had the conditional `{% if voornaam %}` while the attribute was named `voornamen` so even when voornamen was an attribute the conditional would always be false and so it was not added.
**Screenshot** 
Added every possible Stuf-BG attribute and they all prefilled.  This address does not have a house letter or house number addition which is why these fields are blank.
=> Ensure voornamen attribute is in request soap when it's an attribute

src/openforms/submissions/models.py, src/openforms/submissions/templates/report/submission_report.html, src/openforms/submissions/tests/test_models.py
Fixes #575 
In the same way that the files attachment have a special treatment for rendering them in the report, now also the select boxes have a special treatment.
I also updated the submission report template to prevent the table with the form data to run outside the page.
Note: If the label/value from a field are an extremely long word, this will still render in an ugly way. It is due to this bug in weasyprint: https://github.com/Kozea/WeasyPrint/issues/36
=> Issue #575 - Select boxes rendering

src/openforms/appointments/base.py, src/openforms/appointments/contrib/jcc/plugin.py, src/openforms/appointments/contrib/jcc/tests/mock/GetAppointmentQRCodeTextResponse.xml, src/openforms/appointments/contrib/jcc/tests/mock/getGovAppointmentDetailsResponse.xml, src/openforms/appointments/contrib/jcc/tests/mock/getGovLocationDetailsResponse.xml, src/openforms/appointments/contrib/jcc/tests/mock/getGovProductDetailsResponse.xml, src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/plugin.py, src/openforms/appointments/contrib/qmatic/tests/mock/appointment.json, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py, src/openforms/appointments/templates/appointments/appointment_details.html, src/openforms/appointments/tests/test_base.py, src/openforms/appointments/tests/test_utils.py, src/openforms/appointments/utils.py, src/openforms/conf/base.py
Groundwork for #262 
* Adds retrieving appointment details for both JCC and Qmatic.
* Adds QR code for appointment if present.
* Adds HTML snippet to show appointment details (to be used in confirmation email).
=> Appointment details and JCC QR-code

src/openforms/submissions/admin.py, src/openforms/submissions/models.py, src/openforms/submissions/tests/test_models.py
Fixes #578
Also renamed 'get_merged_data_with_component_type' to 'get_ordered_data_with_component_type'
=> [#578] Fixed order of printable merged data

src/openforms/appointments/service.py, src/openforms/appointments/tests/test_utils.py, src/openforms/appointments/utils.py
I believe this is all that should be needed to get the current appointment booking to work with the new task orchestration.
Now the util function will raise the exception on a failure (after creating the Appointment Info instance) so the task will can then handle the retrying.  In the case of a success or missing information where we don't want to retry the util function simply returns which should mark the task as successful.
=> Get booking appointment working within task orchestration

src/openforms/js/components/admin/form_design/utils.js
The `getFormComponents` was set to not include layout components.
Fixes #637
=> Include content components in logic

src/openforms/forms/api/serializers.py, src/openforms/forms/tests/test_api_form_logic.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/tests/form_logic/test_modify_components.py, src/openforms/submissions/tests/test_get_submission_step.py, src/openforms/submissions/tests/test_list_submissions.py, src/openforms/submissions/tests/test_read_submission.py
**Problem 1**
The problem was that creating a logic action such as:
```
{
"formStep": "",
"component": "surname",
"action": {
"type": "value",
"property": {},
"value": {"var": "name"},
},
}
```
was raising a validation error because the form step is empty (while it is expected to be empty).
**Problem 2**
the function `evaluate_form_logic` was expecting form_step as a UUID but this had been changed to a URL, so was failing.
**Problem 3**
The actions of type 'value' were not changing the value of the concerned fields. This is because the configuration was being updated but not the FormIO submission data. So now the `evaluate_logic_check` sends the step data back to the front end which then also updates the submission data.
=> Logic actions bugs/improvements

.github/workflows/ci.yml, Dockerfile, INSTALL.rst, bin/compile_dependencies.sh, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Fixes #662 
The unsafe options will be default later anyway, as per pip-compile's help text:
```
--allow-unsafe / --no-allow-unsafe
Pin packages considered unsafe: distribute,
pip, setuptools.
WARNING: Future versions of pip-tools will
enable this behavior by default. Use --no-
allow-unsafe to keep the old behavior. It is
recommended to pass the --allow-unsafe now
to adapt to the upcoming change.
```
=> Fix setuptools pinning

.github/workflows/ci.yml, .readthedocs.yaml, Dockerfile, INSTALL.rst, requirements/setuptools.txt
It seems the order in which deps are executed can differ. Made it explicit now.
Centralized setuptools version in requirements/setuptools.txt
Here it can be seen for RTD: https://readthedocs.org/projects/open-forms/builds/14721302/
=> Pin setuptools for RTD and other areas

src/openforms/scss/components/builder/_builder.scss
Fixes #643 
This reason for it not scrolling was that `form-row` css class for the django admin has `overflow: hidden;` but this causes the `position: sticky` in the Formio css to not work properly.  If we `unset` the `overflow` property for this field then things work as expected.
I also added the `top: 100px` so that the header bar in the django admin doesn't start to overlap part of the Formio components when scrolling.
**Screenshots**
=> Fix scss that conflicts between django admin and formio builder

src/openforms/appointments/tests/test_utils.py, src/openforms/appointments/utils.py, src/openforms/submissions/models.py, src/openforms/submissions/tests/test_models.py
Changes needed for points
- Should have human readable values in summary page. Will need a way to save these human readable values after they have been selected.
- On the overview page, the appointment details are rendered weirdly
of #597 
Related SDK Pull Request: https://github.com/open-formulieren/open-forms-sdk/pull/58
The cause of the displaying of Products and Locations is that we were only saving the id and not the name/human readable value so we could only display the id back at a later point.  Now both will be stored with a dash between the id and name.
One additional positive of this is that in the submission data you will now see both the id and name instead of just the id.
=> Handle new format coming from SDK

src/openforms/appointments/tests/test_utils.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/validation.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/models.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/test_submission_completion.py
Fixes #225 
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/73
Note: 
If the appointment fields are spread over multiple form steps and some of the steps are applicable and some not, when submitting the form there will be an error that the appointment data is not valid.
=> [#225] Skip not applicable steps

src/openforms/scss/components/builder/_builder.scss
Fixes #732 
The reason for the issues is that Django has a styling that sets the width of `.aligned label` https://github.com/django/django/blob/main/django/contrib/admin/static/admin/css/forms.css#L70 and since our FormIO builder in the admin is within `<fieldset class="module aligned">` then this styling was affecting the labels of our FormIO components.
Within the preview and SDK the width of the label is not set so setting it now to `width: initial` should mean that is acts the same way in all places.
**Screenshots** 
Note only the non-preview admin is changed.  I'm just showing the SDK and admin preview as a comparison.
Admin (non-preview)
Preview Admin
SDK
=> Fix label width

src/openforms/forms/admin/form.py, src/openforms/forms/admin/form_definition.py
Fixes #736 
Also added it to the form definitions since it seems like it'd be useful there as well.
**Screenshot**
There are 3 forms.  This shows the search functionality working as expected.
=> Add search functionality for forms

src/openforms/scss/components/builder/_builder.scss
Fixes #731 
The cause of the bug is that we're setting the z-index of the FormIO popup to be higher than what the ckeditor was using for it's popup and so the 'add link' popup would be behind the FormIO popup.  By setting them to the same value the bug no longer occurs.
I also looked to see if any other options would be affected but I don't see any popups in this component or other ones.
**Screenshot**
=> Fix z-index for adding a link

.github/workflows/ci.yml
Fixes #726 
Following the last `Note` from https://drf-spectacular.readthedocs.io/en/latest/client_generation.html#client-generation I've added the optional arguments so that if there are warnings then this job will fail and the build itself will fail as well.
=> Update generate schema command to fail on warnings

src/openforms/submissions/models.py, src/openforms/submissions/tests/test_models.py
Partiall fixes #750 
The ordering is fixed in the SDK.
=> [#750] Fixed display of labels for submitted data in PDF and summaries on backend

src/openforms/registrations/contrib/email/config.py, src/openforms/registrations/contrib/email/constants.py, src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/submissions/exports.py
fixes: #757 
* Adds the option to choose export formats for the submission data (`csv`, `xlsx`, `pdf`) that will be attached to the email registration
=> :sparkles: [#757] Add submission export to email registration

src/openforms/forms/models/form.py
Fixes #847 
I went for showing "-" instead of "(geen)" so that it is consistent with the payment backend and the authentication backend
=> [#847] Changed admin registration backend label

src/openforms/js/components/form/edit/tabs.js, src/openforms/js/components/form/fieldset.js, src/openforms/js/formio_module.js
Fixes part #824 
The problems I saw while fixing #824 are:
- Field sets have both a 'legend' and a 'label' field. The label should be automatically populated to be equal to the legend, but this doesn't seem to work in Formio 4.13.x. Therefore, all fieldsets have the label 'Field Set'.
- The 'key' of a fieldset has to be updated manually in the API tab (instead of being automatically generated from the label like in other components). If one doesn't do this, the all the fieldsets have the same key 'fieldSet'
So the changes are:
- I changed the display tab so that it has a 'label' field and a 'key' field like for the other components. The legend field is automatically changed to equal the label (since the legend is the field that is actually used to make the 'title' of the component that is …
=> [#824] Update fieldset edit form

src/openforms/scss/components/builder/_builder.scss
This was hidden because of higher z-indices from django apps.
=> Fixes #863 -- fix date-picker z-index

src/openforms/js/components/form/password.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/js/formio_module.js
Resolves #197 
Related SDK PR: https://github.com/open-formulieren/open-forms-sdk/pull/106
As discussed in Slack this will store the password in plain text as FormIO does not do any password encryption and we aren't adding our own.  This will mean in the admin screen, PDF download, etc. you can see the password that the user entered.
**Screenshots**
=> Add password component to form builder

src/openforms/scss/components/builder/_builder.scss
Traced this down to a difference in Formio 4.12 (sdk) and 4.13 (backend),
which explains why the same flatpickr init code works on the SDK but
doesn't in the backend.
The cause of our bug is that the `flatpickr.min.css` stylesheet is not loaded
in the backend, which causes the DOM element to be visible and SVGs to not
have any dimension information. This stylesheet is loaded in the SDK however,
via the `FormIO.requireLibrary` function.
This function loads the library from Formio's CDN _if it's not present in the
global scope yet_. This works different for flatpickr in 4.12 and 4.13:
* 4.12 loads it with `flatpickr-css` as property name (see
https://github.com/formio/formio.js/blob/4.12.x/src/widgets/CalendarWidget.js#L144)
* 4.13 loads it with `flatpickr` as property name (see …
=> Fixes #937 -- include flatpickr styles in bundle

src/openforms/emails/context.py, src/openforms/emails/templates/emails/wrapper.html
Partially fixes #974 
* Limit logo size to 50px height by default
* Default header background is now white
* Align the content to the left
* Add grey border all around to not blend too much with the mail app
* Allow mobile devices to shrink the width of the inner table to scale the content
=> [#974] Fix email layout

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Dependabot had a django-tinymce alert open for a while now, there's finally a fix.
=> Bump versions of some libraries

src/openforms/forms/admin/form_definition.py, src/openforms/forms/tests/test_formdefinition_admin.py
fixes: https://github.com/open-formulieren/open-forms/issues/998
Relatively minor issues, only occurred for staff users with readonly access
=> :bug: Fix FormDefinition admin for readonly access

docs/conf.py, src/openforms/authentication/__init__.py, src/openforms/authentication/apps.py, src/openforms/authentication/constants.py, src/openforms/authentication/contrib/eherkenning/tests/test_integration.py, src/openforms/authentication/registry.py, src/openforms/authentication/signals.py, src/openforms/prefill/contrib/kvk/tests/test_plugin.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/signals.py
Relates to #977
1. Authentication flow sets _some_ key in the session (`bsn` or `kvk`, soon (through #957) `form_auth`)
2. On submission start, these keys are checked and persisted on the `Submission` record
3. Refactored into signals so that it's more pluggable and decoupled & we can install a generic handler.
=> Fix and refactor setting auth information from session

src/openforms/config/__init__.py, src/openforms/config/templates/admin/config/overview.html, src/openforms/config/tests/test_config_check.py, src/openforms/config/urls.py, src/openforms/config/views.py, src/openforms/emails/tests/test_check_email.py, src/openforms/fixtures/default_admin_index.json, src/openforms/plugins/exceptions.py, src/openforms/registrations/base.py, src/openforms/registrations/contrib/demo/plugin.py, src/openforms/registrations/contrib/email/checks.py, src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/microsoft_graph/plugin.py, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/stuf_zds/plugin.py, src/openforms/registrations/contrib/zgw_apis/checks.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/urls.py
Fixes #941
* Adds ZGW and e-mail config tests
* All other plugins still need a `check_config` and `get_config_actions` implementation.
Initial work:
=> [#941] Added plugin config tests

src/openforms/forms/admin/form.py, src/openforms/forms/models/form_definition.py, src/openforms/forms/tests/admin/test_form.py, src/openforms/forms/utils.py
fixes: #1043
Adds a warning message to the FormAdmin in case there are any duplicate keys used in multiple form definitions
=> :sparkles: [#1043] Add warning in formbuilder for duplicate keys in formdefs

src/openforms/setup.py, src/openforms/tests/test_self_signed_certificates.py
Detection of REQUESTS_CA_BUNDLE is broken on runserver since the module
global mutation is not picked up in the runserver thread. This is now fixed
by looking at os.environ which is a mutable dict.
=> Fix self-certifi flow with runserver

src/openapi.yaml, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/RJSFWrapper.js, src/openforms/js/components/admin/form_design/RegistrationFields.js, src/openforms/js/components/admin/form_design/constants.js, src/openforms/js/components/admin/form_design/registrations/camunda.js, src/openforms/js/components/admin/form_design/registrations/index.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/registrations/api/urls.py, src/openforms/registrations/api/views.py, src/openforms/registrations/contrib/camunda/api.py, src/openforms/registrations/contrib/camunda/plugin.py, src/openforms/registrations/contrib/camunda/tests/test_api_endpoints.py, src/openforms/registrations/contrib/camunda/tests/test_checks.py
Related to #326 
**Changes**
* Added API endpoint for staff members to read the available process instances
* Added custom, dynamic registration backend options form in UI to select a process definition
* Optionally, a specific version (i.e. - not the "latest") can be selected
=> Camunda process selection + registration backend core

src/openforms/conf/base.py
The DigiD-eHerkenning library now supports this and according to the DigiD deployment docs it needs to be enabled.
=> Set signed assertions for DigiD to True

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/debug/index.js, src/openforms/js/components/admin/json_editor/TypeRepresentation.js, src/openforms/js/components/admin/json_editor/ValueRepresentation.js, src/openforms/js/components/admin/json_editor/edit_panel/EditPanel.js, src/openforms/js/components/admin/json_editor/edit_panel/EditVariable.js, src/openforms/js/components/admin/json_editor/edit_panel/InterpolatedVariable.js, src/openforms/js/components/admin/json_editor/edit_panel/VariableSourceSelector.js, src/openforms/js/components/admin/json_editor/types.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/registrations/contrib/camunda/complex_variables.py, src/openforms/registrations/contrib/camunda/constants.py, src/openforms/registrations/contrib/camunda/serializers.py, src/openforms/registrations/contrib/camunda/tests/test_backend.py
Related to #326 
This is another step in the direction of allowing generic JSON logic expressions.
The UI is workable and an MVP approach - in the future, we can make this prettier using an editor-builder like Draft.js, but that was too much to get into. This replaces the existing prototype functionality where django templates can be used in the form of:
```django
Inzending
Contactpersoon: {{ contactName }}
```
which is used as values for JSON keys, for example.
TODO
=> Camunda integration: allow for strings with interpolated form fields

src/openapi.yaml, src/openforms/api/drf_spectacular/hooks.py, src/openforms/api/tests/test_schema_generation.py, src/openforms/conf/base.py, src/openforms/middleware.py, src/openforms/tests/test_session_expiry.py
#1155
Expose the session expiry as a response header on every (API) call. The frontend can process this header and calculate the timestamp of expiry relative to its own time. This will allow proper interpretation and handling of HTTP 403 responses due to expired sessions.
=> Expose session expiry information

src/openforms/templates/includes/analytics/google.html
This snippet is used for UA and G-tags alike. Tested and works.
Created #1180 because measurements are not really useful.
=> Updated Google Analytics tag code

bin/celery_beat.sh
Fixes #1182
Normally, celery beat cleans up the pidfile on exit (even if it
crashes), but there are code paths with python stdlib crashes that
apparently aren't expected.
This crash happens when the broker/redis server goes away while beat
is running - which would typically happen during a reboot or deploy
when redis is restarted. On startup, beat starts gracefully with
exponential backoff if the connection is not available (yet), so that's
not the cause.
This patch instructs beat to NOT use a pidfile, which should not have
impact on normal operation. On crashes/restarts, beat should
succesfully restart since there's no pidfile left in the modified
container filesystem.
=> do not create a pidfile for celery beat

src/openforms/forms/tests/admin/test_form.py, src/openforms/forms/tests/test_import_export.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/tests/form_logic/test_endpoint.py
Fixes #1083
The issue was that when the `.to_representation()` of the `SubmissionSerializer` was re-running the logic using the data saved in the submission instead of the new data entered by the user (not saved yet).
=> [#1083] Update is_applicable label after data change

src/openforms/js/components/form/date.js, src/openforms/prefill/__init__.py, src/openforms/prefill/tests/test_prefill_hook.py
Fixes #1213
Changes:
- In the form builder in the admin, the date field also has a tab to configure a prefill
- When prefill values are processed, there is a check to see if the field is a date field. If it is, then the date is formatted to "YYYY-MM-DD" (expected by the json-logic-py package).
=> Date prefill

.github/workflows/ci.yml, Dockerfile, src/openforms/templates/admin/base_site.html
Fixes #1237 
Note this also sets the docker label like the open-forms example.
=> [#1237] Set RELEASE environment var from Git tag in CI and use for django admin and docker image

src/csp_post_processor/tests/test_schema_generation.py
Related to #807
Added schema generation extension to automatically include the request header in the api schema. This is in preparation for when we put this functionality in its own package.
=> DRF spectacular schema generation for csp_post_processor

.github/workflows/ci.yml, Dockerfile, docker-compose.yml
The SDK statics are embedded in the backend build for convenience, but the version should
match the version of the backend too.
COPY --from= does not allow build args inline, we can work around this by defining a separate
stage which does support build args.
Vaguele related to Taiga 380 which saw a deploy with pinned versions and incorrect paths.
=> Ensure embedded SDK build is pinned to same release

src/openforms/logging/logevent.py, src/openforms/logging/models.py, src/openforms/logging/tests/test_models.py, src/openforms/submissions/models.py, src/openforms/submissions/tests/test_models.py
=> [#944] Display submission authentication information in logevent logging 

src/openforms/js/components/form/edit/tabs.js, src/openforms/js/components/form/fieldset.js, src/openforms/js/lang/formio/nl.json
Fixes #1127 
Add the field `clearOnHide` to the configurations in the builder, so that the value of hidden fields can be included in the submission.
=> [#1127] Configuration hidden fields

src/openforms/js/components/admin/form_design/FormLogic.js, src/openforms/js/components/admin/form_design/PriceLogic.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/utils/random.js
Fixes #1222
The UI now correctly renders the state when you delete a logic rule
other than the last one.
This was caused by React's key prop functionality combined with a bad
choice for the key value. React does not re-render a component if the
key has not changed, even if other props have changed (!).
Logic rules used their Array index as key value, so unless you delete
the last logic rule, the visual state will update incorrectly.
Deleting a logic rule removes it from the the Array - causing all
following rules to get an index value of  - 1. From
React's perspective, the keys have not changed - only there is now one
element less in the Array so the last rule is instead removed.
The internal state (for API calls) was correctly updated, however the
visual representation of this state was …
=> Fix visual state when deleting logic rules

docs/configuration/registration/email.rst, src/openforms/accounts/tests/factories.py, src/openforms/emails/templatetags/form_summary.py, src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/email/presentation.py, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/submissions/models.py, src/openforms/submissions/tests/factories.py, src/openforms/submissions/tests/test_attachment_download_view.py, src/openforms/submissions/tests/test_submission_attachment.py, src/openforms/submissions/urls.py, src/openforms/submissions/views.py, src/openforms/templates/403.html, src/openforms/utils/apps.py, src/openforms/utils/tests/auth_assert.py
Partially solves #1193
* End-user uploads are no longer added as attachment to the email
* Instead, HTML mails have a clickable link and plain text emails have a link that can be copy-pasted
* The link points to a "standard" django view to download a submission attachment, using sendfile to optimize file IO/serving
* Access control on the view consists of:
* user must be logged in
* user must be staff user (as the admin login page is the configured login page)
* user must have the `submissions.view_submissionfileattachment` permission, included in the groups fixture with the "Behandelaars" group
As part of this PR, some more refactoring was done to the displaying of form values in e-mails, it now checks if the rendering is set to text mode or not (if no information is available, the …
=> Deal with file upload "attachments"

bin/celery_beat.sh, bin/celery_flower.sh, bin/celery_worker.sh, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/setuptools.txt
Fixes #1299 
Flower does not work with Celery 5 in version 1.0.0 (latest version on PiPy). It should be supported from version 1.0.1.
=> [#1299] Celery 5 update

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/AuthenticationWarning.js, src/openforms/js/components/admin/form_design/ChangedFormDefinitionWarning.js, src/openforms/js/components/admin/form_design/FormLogic.js, src/openforms/js/components/admin/form_design/FormStepDefinition.js, src/openforms/js/components/admin/form_design/LogicWarning.js, src/openforms/js/components/admin/form_design/PluginWarning.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/logic/LiteralValueInput.js, src/openforms/js/components/admin/form_design/logic/Trigger.js, src/openforms/js/components/admin/form_design/logic/hooks.js, src/openforms/js/components/admin/form_design/useDetectSimpleLogicErrors.js, src/openforms/js/components/admin/form_design/utils.js, src/openforms/js/components/admin/form_design/warnings/MessageList.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Fixes #1330 
Fixes #1296
**Changes**:
- Added a hook that checks whether the components used in 'simple logic' rules exist and shows a warning if they don't.
- When the key of a component is changed, the logic rules in 'the other tab' are updated to use the new key. 
- Show error returned by the backend when a logic rule is invalid.
=> [#1330] Warn user about logic errors

docs/developers/index.rst, docs/developers/releases.rst, docs/developers/sdk/embedding.rst, docs/developers/versioning.rst, src/openapi.yaml, src/openforms/api/utils.py, src/openforms/conf/base.py, src/openforms/submissions/api/validation.py, src/openforms/submissions/api/viewsets.py
Closes #1264
* Boils down to SEMVER
* Documented SDK <-> API compatible ranges
* Added escape hatch through "experimental features" -> can be marked in code/API schema
* Documented which API version is implemented in which Open Forms version
=> Versioning policy proposal

src/openforms/js/components/form/fieldset.js, src/openforms/js/components/formio_builder/customTemplates.js, src/openforms/js/components/formio_builder/templates/fieldset.ejs, src/openforms/js/lang/formio/nl.json
Fixes #1391 
Front end PR: https://github.com/open-formulieren/open-forms-sdk/pull/173
**Changes**
- It is now possible to configure whether the header of the fieldset will be visible in the form
- Before the 'legend' property of the fieldset was used in the header. This was automatically changed to match the label. Now the label is used instead in the header, so we don't need to update the legend under the hood
=> Enable hiding fieldset header

src/openapi.yaml, src/openforms/authentication/contrib/demo/plugin.py, src/openforms/authentication/contrib/demo/tests/test_plugin.py, src/openforms/authentication/contrib/digid_mock/tests/test_plugin.py, src/openforms/authentication/signals.py, src/openforms/authentication/tests/mocks.py, src/openforms/authentication/tests/test_signals.py, src/openforms/authentication/tests/test_views.py, src/openforms/authentication/views.py
Fixes #1322 
* Added staff user checks for demo plugins in start/return auth flow
* Added staff user check for demo plugins in submission start signal handler
* Reverted #805 and documented reasoning
=> Require admin user for demo auth plugins

src/openforms/forms/admin/form.py, src/openforms/forms/tests/admin/test_form.py
Fixes #988
For both bulk (from list page) and detail (from edit page, currently not exposed in React):
* First time deleting a form just marks it as deleted and keeps the related steps/form definitions
* Second time deleting permanently removes the form from the database, cascading the form steps. Single-use form definitions are also cascade-deleted, form definitions that are marked as re-usable are kept.
=> Permanently delete forms

src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models.py, src/openforms/submissions/tasks/__init__.py, src/openforms/submissions/tasks/cleanup.py, src/openforms/submissions/tests/factories.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/tests/test_tasks_cleanup.py
Fixes #1395
Ensure that the attributes are only hashed when the registration has succeeded, as
they may be/are used during the registration stage.
=> Move identifying attributes hashing to on_completion cleanup stage

src/openforms/emails/templates/emails/templatetags/form_summary.html, src/openforms/emails/templatetags/form_summary.py, src/openforms/emails/utils.py, src/openforms/emails/views.py, src/openforms/formio/formatters/default.py, src/openforms/formio/formatters/registry.py, src/openforms/formio/formatters/service.py, src/openforms/formio/formatters/tests/test_default_formatters.py, src/openforms/scss/pdfs/_submission-step-row.scss, src/openforms/submissions/models.py, src/openforms/submissions/report.py
Fixes #1293 
Building on top of #949, the formio formatters gained a "as_html" rendering mode. This allows us to output HTML image tags for the signature.
The e-mail rendering is more complex as it relies on `Submission.get_printable_data` which in the old variant has no idea about text/HTML rendering. So I decided to only support an actual image if the new Formio formatters are used, otherwise the bland text version is rendered.
=> Fix signature display in pdf & email

src/openapi.yaml, src/openforms/forms/templates/core/views/form/form_detail.html, src/openforms/submissions/api/viewsets.py
Fixes #1410
Depends on https://github.com/open-formulieren/open-forms-sdk/pull/176
The admin auth was not recognized because of the missing `authentication_classes = (SessionAuthentication,)`, and adding this in turn activates the CSRF machinery. CSRF mechanisms have been added to the SDK with a hook for the backend to be able to set the value of the token.
We only set the value (and activate the CSRF machinery) if we're dealing with admin users, as that's the scope of the demo authentication plugins.
=> Fix broken admin authentication for demo plugins

src/openforms/scss/admin/_admin_theme.scss
Django 3.2 added a bunch of CSS vars, allowing us to cut down on a lot of override rules. This should also make supporting dark mode easier.
=> Refactor hardcoded CSS colors to use CSS variables

src/openforms/authentication/fields.py, src/openforms/payments/fields.py, src/openforms/registrations/fields.py
This was only relevant when building a Django form field for the
respective custom fields, but we don't render Django forms anymore
after removing the enable_react_form feature flag in #1414
=> Delete dead code on custom fields

src/openforms/scss/admin/_app_overrides.scss
Should fix this missing padding:
=> Fix header padding on login page

.github/workflows/ci.yml, package-lock.json, package.json, src/openforms/js/components/admin/BooleanIcons.js, src/openforms/js/components/admin/constants.js, webpack.config.js
Upgrade from webpack 4, which removed the NodeJS api ('process' in particular).
This is the only path forward to fix dependabot alerts in the webpack chain.
=> Upgrade to Webpack 5

docs/configuration/registration/zgw.rst, src/openforms/formio/formatters/default.py, src/openforms/formio/formatters/tests/test_issues.py
Fixes #1466
Dynamic typing was a mistake.
=> Ensure value type is string before finding a match to find the label from the available options

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Added templates for issues to streamline issues.
The label "triage" is added to indicate issues that have not been checked yet by us. You can remove that label once it's checked.
=> Updated issue templates

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
This version supports models.JSONField, so it's one less system check
warning in Open Forms.
=> Bump mozilla-django-oidc-db version

bin/docker_start.sh, requirements/base.txt, requirements/ci.txt, requirements/dev.txt
The master process is required for proper concurrency, as this process
monitors the worker processes and restarts them if they die (
unexpectedly).
=> :bricks: Ensure uwsgi runs in master process mode

src/openforms/formio/rendering/__init__.py, src/openforms/formio/rendering/conf.py, src/openforms/formio/rendering/constants.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/registry.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/submissions/tests/renderer/test_renderer.py
Related to #1451
This adds a specialized Formio component node subclass, capable of emitting its own child nodes (if present) and formatting label/value appropriately.
On top of that, it puts the registry in place to register specific subclasses for formio components, and sets up the Formio component properties to control output in different render modes. This includes setting a default value for existing forms that don't have these keys defined (yet).
Commented out code and TODOs are still intentional and will follow in later PRs.
=> Set up plumbing for FormIO in submission rendering

src/openforms/conf/utils.py, src/openforms/tests/test_filesize_cast.py
Fixes #1492 
This allows for both 5MB and '5 MB' to be allowed input.
=> allow spaces in filesize definitions

docs/developers/backend/core/submission-renderer.rst, src/openforms/conf/base.py, src/openforms/formio/rendering/__init__.py, src/openforms/formio/rendering/apps.py, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/formio/rendering/tests/test_vanilla_formio_components.py
Relates to #1451
This PR builds on top of #1554 and implements component-type specifics for Formio components.
**Changes**
- Fieldset and columns type implemented: only render output if there are visible children.
- WYSIWYG: in non-HTML mode, output a plain-text variant of the HTML, and only output HTML in PDF render mode (for a complete summary of the entire form)
- Columns: never output a label
=> Implement specific formio type nodes

docs/conf.py
Looks like github made some changes on their end, as these are passing again (locally) without any changes
=> Remove docs.github.com from linkcheck ignore list again

src/openforms/submissions/models/__init__.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/models/submission_files.py, src/openforms/submissions/models/submission_report.py, src/openforms/submissions/models/submission_step.py, src/openforms/tests/test_csp.py
The `models.py` in the submission module was getting huge. So I moved the models to a `model` folder.
=> Refactored submission models in multiple files

src/openforms/js/lang/formio/nl.json
Fixes #1344
Formio runs both the multiple and required validators, leading to
multiple error messages being shown, which is not ideal.
=> add translation for validation error key

src/openforms/submissions/tests/test_attachment_download_view.py, src/openforms/submissions/views.py
=> [#1584] Use the original filename when downloading submission attachments

deployment/templates/file-uploads.conf.tpl
Fixes #1593
The #1453 fix/refactor moved the endpoint to be Formio specific,
which was forgotten in the nginx config.
=> update nginx location rules for fileuploads

src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/tests/form_logic/test_side_effects.py
Fixes #1480
Modified the `PUT` handling to also apply side-effects to subsequent steps. Some considerations:
* we cannot do this as part of the `_complete` endpoint, as data that may be stored can be relevant for logic in other steps, unexpectedly modifying other steps
* letting the frontend make the decision would require the frontend to keep track of all n/a steps and if they have data, + make extra API calls to reset the data. From a performance and DB transaction point of view, handling this all in the backend is preferred.
=> Reset data if a step becomes not-applicable due to logic

src/openforms/conf/base.py, src/openforms/middleware.py
=> [#1574] Dropped Django 2.x SameSiteNoneCookieMiddlware

src/openforms/formio/typing.py, src/openforms/formio/utils.py, src/openforms/prefill/__init__.py, src/openforms/prefill/tests/test_prefill_hook.py
Fixes #1560
Refactored prefill extract/set-values to use `openforms.formio.utils.iter_components` so that we get all components in the tree (and thus all layout variants).
=> Fix prefill fields in columns not working

src/openapi.yaml, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/tests/test_submission_suspension.py
Fixes #1627
We avoid CSRF checks by disabling authentication on the suspend/complete endpoints for a submission. Other endpoints are not affected, as they are PUT/DELETE methods instead of POST.
=> Avoid CSRF error on form complete when authenticated (in the admin)

src/openforms/conf/base.py
Fixes #1646
If you don't specify NUM_PROXIES and the derived AXES_PROXY_COUNT,
then attackers could spoof the X-Forwarded-For header on misconfigured
infrastructure. By specifying the number of reverse proxies deployed,
this can be prevented (spoof attemts result in ip-address None being
detected and prevents them from iterating to generated IP addresses).
=> make django axes config more strict

src/openforms/js/components/form/edit/tabs.js, src/openforms/js/components/form/textarea.js
=> [#1643] Set default value for text validate.maxLength in Form Designer

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Fixes #1655
Django admin can't handle `gettext_lazy` in some places apparently.
=> Bump zgw-consumers version

package-lock.json
This release has the BEM mixins and fixed the `/` div deprecations which will be removed in dart-sass 2
=> Bump to microscope-sass 1.1.0

src/openapi.yaml, src/openforms/api/drf_spectacular/functional.py, src/openforms/api/mixins.py, src/openforms/api/tests/utils.py, src/openforms/api/urls.py, src/openforms/dmn/api/serializers.py, src/openforms/dmn/api/urls.py, src/openforms/dmn/api/views.py, src/openforms/dmn/tests/test_api.py
Related to #1680
**Changes**
- Added API endpoint to obtain a list of enabled/available plugins/engines
- Added API endpoint to get a list of available definitions for a given engine
- Added API endpoint to get a list of available versions for a given engine/definition
- Added API endpoint to retrieve the DMN XML for a given engine/definition
=> Implement DMN API endpoints

src/openforms/registrations/contrib/stuf_zds/management/commands/stuf_zds_test_stp.py, src/openforms/registrations/contrib/stuf_zds/plugin.py, src/stuf/stuf_zds/client.py, src/stuf/stuf_zds/tests/test_backend.py, src/stuf/stuf_zds/tests/test_client.py
Fixes #1681
I'm not sure how to write tests for this, and I think I'd rather do #388 first, because there is now a lot of code and template duplication between stuf-bg and stuf-zds.
=> Use a unique reference number every time for StUF-ZDS requests

src/openapi.yaml, src/openforms/api/exception_handling.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/attachments.py, src/openforms/submissions/tests/test_submission_attachment.py, src/openforms/submissions/tests/test_submission_step_validate.py, src/openforms/submissions/tests/test_submit_form_step.py
Fixes #1687
**Changes**
* Added endpoint for explicit validation of submission step data
* Modified step serializer to run upload validation
* Refactored function to attach files to submission step to use common generator
* Fixed camelizing `data.foo_bar` in validation errors
* Fixed error messages being improperly serialized
=> Emit step submission validation errors

src/openapi.yaml, src/openforms/forms/api/serializers/logic/action_serializers.py, src/openforms/forms/constants.py, src/openforms/forms/tests/test_api_form_logic.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/Context.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/logic/AdvancedTrigger.js, src/openforms/js/components/admin/form_design/logic/actions/Action.js, src/openforms/js/components/admin/form_design/logic/actions/Actions.js, src/openforms/js/components/admin/form_design/logic/constants.js, src/openforms/js/components/admin/forms/JsonWidget.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/form_logic/test_modify_variables.py, src/openforms/submissions/tests/renderer/test_renderer.py, src/openforms/submissions/tests/test_variables/test_update_with_logic.py, src/openforms/submissions/utils.py
Part of #1325 
**Changes**
- In the admin form editor, for the actions there is a new type available, which is "variable". It gives the possibility to use JsonLogic to calculate the new value of a component. I think this will replace the action "value" once variables become the default.
- During logic evaluation, the value of the variables is updated.
Thing that currently happens if one uses a variable action: 
- User changes value of a field that triggers the update of a variable
- POST to `_check_logic` updates the step data with the new variable of the user defined variable
- I think the update of the step data triggers another POST to `_check_logic`
- The last POST to `_check_logic` updates the configuration with the data of the variables calculated in the first POST to …
=> [#1325] Modify variables with logic

src/openforms/formio/normalization.py, src/openforms/formio/service.py, src/openforms/formio/tests/test_conform_to_mask.py, src/openforms/formio/tests/test_normalization.py, src/openforms/formio/utils.py, src/openforms/prefill/__init__.py, src/openforms/prefill/tests/test_prefill_hook.py, src/openforms/prefill/tests/test_prefill_variables.py
... before they are passed to Formio.
Fixes #1693
This patch respects the input mask configured on a formio component (for postcode type components) and adds the machinery to perform normalization for other compnent types in a pluggable way.
=> Ensure postal code field prefill values are normalized

src/openforms/js/components/formio_builder/WebformBuilder.js
Fix error that `this.editForm.events._events['formio.change'][existingOnChangeHandlers.length - 1] is undefined`
=> Fix error in console caused by fix for issue 1422

.gitignore, src/openforms/scss/pdfs/_header.scss, src/openforms/scss/pdfs/_vars.scss, src/openforms/submissions/templates/report/submission_report.html
Fixes #1715
Input image:
> JPEG image data, JFIF standard 1.02, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=5, xresolution=206, yresolution=214, resolutionunit=2], baseline, precision 8, 4000x4000, components 3
=> Fix logo sizing for PDFs — [#1715]

package-lock.json, package.json
This resolves the last deprecation warnings about using slash for
division instead of math.div, which will be removed in dart-sass v2.
=> :arrow_up: Upgrade microscope-sass to 1.1

src/openforms/forms/tests/admin/test_form.py, src/openforms/forms/tests/factories.py, src/openforms/forms/tests/test_api_form_logic.py, src/openforms/forms/tests/test_api_form_versions.py, src/openforms/forms/tests/test_import_export.py, src/openforms/submissions/tests/form_logic/factories.py, src/openforms/submissions/tests/form_logic/test_endpoint.py, src/openforms/submissions/tests/form_logic/test_modify_components.py, src/openforms/submissions/tests/form_logic/test_modify_variables.py, src/openforms/submissions/tests/form_logic/test_side_effects.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/renderer/test_renderer.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/tests/test_variables/test_num_queries.py, src/openforms/submissions/tests/test_variables/test_update_with_logic.py
The model is defined in the forms app, so that's where the factory
model belongs too.
=> :truck: Move FormLogicFactory from submissions to forms app

src/openforms/formio/formatters/registry.py, src/openforms/formio/utils.py, src/openforms/forms/models/form_variable.py, src/openforms/forms/tests/factories.py, src/openforms/forms/tests/variables/test_initial_values.py, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/variables/constants.js, src/openforms/js/components/admin/form_design/variables/utils.js, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/form_logic/test_modify_variables.py, src/openforms/submissions/tests/test_get_submission_step.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/tests/test_submit_form_step.py, src/openforms/submissions/tests/test_variables/test_num_queries.py, src/openforms/submissions/tests/test_variables/test_update_with_logic.py, src/openforms/submissions/utils.py
Fixes #1747 
**Changes**
- Before, all variables related to a step were included in the step data with their default value at the beginning of the step.
Now, if a variable is not in the configuration (i.e. its hidden) then it is not added to the data.
- The component without an explicit default value have a corresponding component variable with `initial_value=None`.
- The function `bulk_create_or_update_from_data` deletes any saved variables which are no longer present in the data.
- User defined variables are initialised (saved) at the beginning of filling out the form (after prefills).
=> [#1747] Bugs default values with variables

.github/workflows/ci.yml, .github/workflows/code_quality.yml, .github/workflows/fe-code-quality.yml, src/openforms/scss/admin/_app_overrides.scss
The backend code quality is only triggered on backend-related files, which is why a code style violation managed to slip through the cracks.
This sets up js/scss checks with prettier in a separate workflow. Additionally, the node-version stuff is handled properly with the github action `node-version-file` option.
=> Move frontend code quality checks to separate workflow

src/openforms/js/components/admin/form_design/FormMetaFields.js, src/openforms/js/components/admin/form_design/data/complete-form.js, src/openforms/js/components/admin/form_design/data/index.js, src/openforms/js/components/admin/form_design/data/logic.js, src/openforms/js/components/admin/form_design/data/plugins.js, src/openforms/js/components/admin/form_design/data/read-form.js, src/openforms/js/components/admin/form_design/data/steps.js, src/openforms/js/components/admin/form_design/data/variables.js, src/openforms/js/components/admin/form_design/data/versions.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/utils/exception.js, src/openforms/js/utils/fetch.js, webpack.config.js
This refactor was overdue and is necessary to sort out #1611 without (too) ugly hacks.
**Changes**
* All of the actual data loading when opening/starting a (new) form is contained in the `data/` package, with a module per "topic"
* All of the API calls that need to be made for saving a form are also contained in this package.
* Validation (and other 4xx) errors are now thrown by the unsafe API calls (post, put, delete...) and caught by the callers where they are collected for display
Since we optimize a bunch of things by making API calls in parallel (for both loading and persisting data), we need to be able to distinguish between succeeded and failed calls. For succeeded calls, the state needs to be update (so that we don't create the same object _again_ after correcting validation …
=> Refactor form-saving machinery in admin

src/openforms/prefill/contrib/stufbg/plugin.py, src/openforms/prefill/contrib/stufbg/tests/test_plugin.py, src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponseOnvolledigeDatum.xml
Fixes #1617
Crash is caused by different return value in xmltodict when the XML element has attributes:
```
<foo>bar</foo> -> {"foo": "bar"}
```
while
```
<foo attribute="baz">bar</foo> -> {"foo": {"#text": "bar", "@attribute": "baz"}}
```
We get both complete/incomplete dates, so we need to be able to handle both of them.
=> Fix StUF-GB onvolledige datum crash

docs/developers/backend/core/utils.rst, src/openforms/prefill/contrib/stufbg/plugin.py, src/openforms/utils/xml.py
This was just an example and has been deprecated for a while now.
=> :rotating_light: Do not use deprected defusedxml.lxml anymore

src/openforms/forms/tests/test_import_export.py, src/openforms/forms/utils.py
Fixes #1774
Category information is discarded during import - end users are
responsible for assigning the form to the appropriate category after
import, just like they have to publish them explicitly.
=> :bug: don't crash form import on non-existent categories

src/openforms/forms/api/serializers/form_variable.py, src/openforms/forms/tests/variables/test_viewset.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/variables/StaticData.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.js, src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/js/components/admin/form_design/variables/constants.js, src/openforms/js/components/admin/form_design/variables/types.js, src/openforms/js/components/admin/form_design/variables/utils.js, src/openforms/js/components/admin/forms/Field.js, src/openforms/js/components/admin/forms/Select.js, src/openforms/js/components/admin/forms/ValidationErrors.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Fixes #1697 
The cases that I tested are:
- Create 2 form components with same keys
- Create a user defined var and then a component with the same key
- Create a form component with key 'now' (clash with static variable)
- Create a user defined var with key 'now' (clash with static variable)
=> [#1697] Deal with duplicate keys in variables and form components

src/openforms/logging/tests/test_admin.py, src/openforms/logging/tests/test_events.py, src/openforms/submissions/admin_views.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/tests/test_admin.py
Fixes #1798 
I ended up adding the possibility to remove logs from the admin for the users with the right permissions. 
The removal of the objects through the admin is logged in the `LogEntry` model ([here](https://github.com/django/django/blob/main/django/contrib/admin/options.py#L948) ) by default.
=> [#1798] Delete submissions forms from admin

src/openforms/js/components/form/editGrid.js
Fixes #1839 
The text wasn't too long, but for some reason, double quotes inside single quote were closing the string. So the tooltip were displaying the string until the double quotes.
=>  Help text in repeating groups is too long

src/openforms/formio/utils.py, src/openforms/forms/models/form_variable.py, src/openforms/logging/logevent.py, src/openforms/logging/tests/test_events.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/logic/actions.py, src/openforms/submissions/logic/datastructures.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/form_logic/test_evaluation_determinism.py, src/openforms/submissions/tests/form_logic/test_modify_components.py, src/openforms/submissions/tests/form_logic/test_modify_variables.py, src/openforms/submissions/tests/test_admin.py, src/openforms/submissions/tests/test_variables/test_static_data.py
Related to #1708
Refactored the logic evaluation algorithm so that now we first work towards resolving the variable state (logic actions can change variable values), and then we apply the dynamic formio configuration using this resolved state/values.
The logic actions have been split up in a new interface so that we can clean up the code and side-effects applied from logic actions. This also all makes it a bit more logging friendly to get insight on what is happening when.
=> Refactor logic evaluation implementation

src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/utils.js
Fixes #1806
Component key references were correctly updated already when a Formio
component key changes, however, the variable references in logic
actions weren't yet.
This patch ensures that the variable references are also updated, and applies the same logic when (user-defined) variable keys change.
=> Ensure that logic variable references are updated

src/openforms/prefill/contrib/stufbg/tests/test_plugin.py, src/stuf/stuf_bg/client.py, src/stuf/stuf_bg/tests/test_client.py
Fixes #1842 - closes #1852
This patch is two-fold:
* ensure that StUF-BG errors bubble up so that `openforms.prefill._fetch_prefill_values` can handle them (which logs it using `logevent.prefill_retrieve_failure` in case of unexpected errors)
* handle missing keys/data graciously, so we keep noise out of Sentry (we only want to catch programming errors, not logical errors because there just isn't any data to prefill)
=> Handle stuf bg prefill error on empty antwoord

docs/developers/backend/core/index.rst, docs/developers/backend/core/templating.rst, docs/developers/backend/core/testing-tools.rst, docs/manual/templates.rst, src/openforms/formio/service.py, src/openforms/formio/tests/assertions.py, src/openforms/formio/tests/test_assertions.py, src/openforms/formio/tests/test_variables_injection.py, src/openforms/formio/utils.py, src/openforms/formio/variables.py, src/openforms/forms/tests/factories.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/logic/datastructures.py, src/openforms/submissions/tests/renderer/test_formio_integration.py, src/openforms/submissions/tests/test_variables/test_variable_injection.py, src/openforms/template/__init__.py, src/openforms/template/backends/sandboxed_django.py, src/openforms/typing.py
Related to #1708 
**Changes**
* Added isolated django template backend instance for user-input rendering
* Added formio test utils/assertions to verify component properties
* Added service function to inject variables values into formio configuration (using the django template engine)
* Hooked up variable injection into the form logic evaluation function
=> Insert variables in formio config

src/openforms/analytics_tools/tests/mixin.py
Not sure of the reason but it seems that with --keepdb, the CookieGroup is deleted at one point while we run all project's tests
=> Fix cookie tests running with --keepdb option

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/logic/LiteralValueInput.js, src/openforms/js/components/admin/form_design/logic/Trigger.js, src/openforms/js/components/admin/form_design/logic/actions/ActionSet.js, src/openforms/js/components/admin/form_design/logic/actions/Actions.js, src/openforms/js/components/admin/form_design/logic/constants.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/scss/components/admin/_logic-trigger.scss
Fixes #1845 
I am not really convinced that having a dropdown for the checkboxes in the action is a good idea, because:
- the backend expects JSONLogic for the `value` field (so I used the `{"!!": [true]}` and `{"!": [true]}` for the dropdown options)
- One might want to use a more complex JSONLogic expression to assign the variable bool value (with and, or... operators) 
- The other fields with types that are not string (datetimes, times, ...) could also end up having a result of wrong type, but for those we don't have a mechanism to avoid this error.
=> [#1845] Display improvements

src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/tests/test_component_node.py
If a component is hidden/visible because of frontend logic, render appropriately.
=> Renderer should check front end logic

src/openforms/js/components/admin/form_design/variables/VariablesTable.js
Changes:
- Removed the form definition drop down for the user defined variables
- Removed the "format" column (possibly should also be removed in the backend, we don't currently use it, but maybe in the future?)
- Replaced the input field to specify the initial value to be of the right type for the variable type
=> Clean up variables editor

src/openforms/authentication/tests/test_static_variables.py, src/openforms/forms/api/serializers/form_variable.py, src/openforms/forms/api/validators.py, src/openforms/forms/models/form_variable.py, src/openforms/forms/tests/variables/test_variables_in_logic_trigger.py, src/openforms/forms/tests/variables/test_viewset.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/variables/service.py, src/openforms/variables/tests/test_views.py, src/openforms/variables/views.py
Instead of `FormVariable.get_static_data` (and leaking `Submission` objects into the `forms` app), we can now use `openforms.variables.service.get_static_variables` for a better separation of concerns.
=> Refactored the public API for (static) variables 

src/openforms/js/components/admin/forms/JsonWidget.js
Fixes #1896 
The json-logic-js function `is_logic` only accepts objects: https://github.com/jwadhams/json-logic-js/blob/master/logic.js#L176 (while if we enter primitive values/arrays in the [play-with-it page](https://jsonlogic.com/play.html) these are accepted).
=> [#1896] Primitives and arrays are valid jsonLogic

src/openforms/forms/models/form_variable.py, src/openforms/forms/tests/variables/test_model.py
Part of #1964 
What was happening, is that file uploads with multiple value needs the initial value `[]`. This was correctly set when the form was built. But the function `get_initial_value` of the form variable was doing:
```
def get_initial_value(self):
return self.initial_value or None
```
which for the empty array was returning None. 
This was then causing the submission endpoint to fail when dealing with the attachments:
```
TypeError: 'NoneType' object is not iterable
...
File "openforms/submissions/attachments.py", line 279, in resolve_uploads_from_data
for info in upload_info:
```
=> [#1964] File upload broken

src/openforms/logging/logevent.py, src/openforms/logging/tests/test_events.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/logic/rules.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/test_admin.py
Fixes #1913
We have two variants of logic checks:
1. Running explicitly in the context of a form step
2. Running on the submission as a whole
The second one did not take into account recent features such as:
* variables (static, user defined)
* logic actions changing values of variables that are used in other rules' trigger
* disabling of step-submission
**TODO**
Refactor the code to avoid the repetition and properly abstract this away:
- handle logging the evaluation
- handle skipping certain logic actions (formio configuration is not relevant for flavour 2)
=> Making different logic checks/evaluations consistent

src/openforms/api/exceptions.py, src/openforms/authentication/models.py, src/openforms/authentication/tasks.py, src/openforms/authentication/tests/test_tasks.py, src/openforms/forms/models/form.py, src/openforms/forms/validators.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/validators.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/exceptions.py, src/openforms/submissions/templates/submissions/resume_form_error.html, src/openforms/submissions/tests/test_disabled_forms.py, src/openforms/submissions/tests/test_start_submission.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/utils.py, src/openforms/submissions/views.py, src/openforms/variables/rendering/nodes.py
Contributes to #1967
This PR implements the API behaviour that can be detected by the SDK to display appropriate error messages.
**Progress**
=> Explicit handling of deactivated/maintenance forms

src/openforms/forms/templates/core/views/form/form_detail.html
=> [#1944] Remove CSRF token setting for embedded forms

src/openforms/js/components/admin/form_design/FormStepDefinition.js, src/openforms/js/components/admin/forms/ErrorList.js, src/openforms/js/components/admin/forms/Field.js, src/openforms/scss/components/admin/_edit-panel.scss
Fixes #2008 
The problem was that the checkboxes were not wrapped with the `Field` component.
Now the error shows:
The padding for the other fields remains:
=> [#2008] Error for checkbox not shown

src/openforms/formio/constants.py, src/openforms/js/components/admin/form_design/variables/constants.js
Noticed that the repeating groups had data type 'string' while they are arrays
=> Add datatype for repeating group component

src/openforms/conf/dev.py, src/openforms/formio/dynamic_config/date.py, src/openforms/forms/models/form.py, src/openforms/forms/tests/factories.py, src/openforms/registrations/contrib/microsoft_graph/tests/test_backend.py, src/openforms/registrations/contrib/objects_api/tests/test_backend.py, src/openforms/submissions/api/permissions.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/rendering/renderer.py, src/openforms/submissions/tests/factories.py, src/openforms/submissions/tests/renderer/test_renderer.py, src/openforms/submissions/tests/test_get_submission_step.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/tests/test_resume_form_view.py, src/openforms/submissions/tests/test_variables/test_num_queries.py, src/openforms/variables/rendering/nodes.py
A combination of analysis using Elastic APM and django-silk to figure out the origin of excessive queries, followed by some workarounds to remove the queries that are not absolutely needed.
* Logic check endpoint with test case used for profiling: 18 -> 11 queries
* Renderer with variables node: 8 -> 3 queries
Let's get this merged and tested on our test environment, so we can check again with APM what the new situation is (and run the profiling benchmark again).
=> :zap: Optimizing API endpoints

src/openforms/api/fields.py, src/openforms/api/tests/test_fields.py, src/openforms/forms/api/serializers/form_variable.py, src/openforms/forms/api/viewsets.py, src/openforms/forms/tests/variables/test_viewset.py, src/openforms/forms/utils.py
Related to #1922
Performance improvement variables bulk update, for a case with 30 component variables and 20 user defined variables:
* before: 84 queries
* after: 5 queries
**Variables list**
* Removed unnecessary prefetch/select_related from variables-list endpoint
* Added select_related on variables-list endpoint for variable form and form-definition
* Variables-list endpoint now has a fixed number of queries: 2 (+ session/middleware queries etc.)
**Variables bulk update**
Every form variable was being validated individually, meaning that a FK lookup was performed for the form and the (optional) form definition, giving a complexity somewhere between `O(n)` and `O(2*n)` with n the number of form variables.
The form validation/lookup is not needed in the first place, since the endpoint …
=> :zap: [#1922] -- Optimize the bulk form variables endpoints

src/openforms/analytics_tools/models.py, src/openforms/logging/logevent.py, src/openforms/logging/logic.py, src/openforms/logging/tasks.py, src/openforms/logging/tests/test_events.py, src/openforms/prefill/__init__.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/test_admin.py, src/openforms/submissions/tests/test_variables/test_num_queries.py
The processing and queries are now done in the celery tasks, making the logic check endpoint a bit faster.
=> :zap: [#1922] -- move logic evaluation logging to celery

src/openforms/js/components/admin/form_design/NewStepFormDefinitionPicker.js
Requested by @joeribekker 
Description:
> can you make the list of FormDefinitions that is shown when creating a form in the admin, and you want to add a form step, alphabetical?
> ![image](https://user-images.githubusercontent.com/58147939/190440012-d2117a45-98d5-4fa2-8a6e-8490d0f9e05c.png)
=> Sort formdefinition choices

src/openforms/conf/base.py, src/openforms/conf/dev.py, src/openforms/utils/apps.py, src/openforms/utils/cache.py, src/openforms/utils/tests/test_cache.py
Relates to #2042
From APM we can see that we have a lot (tens to hundreds) calls to `GlobalConfiguration.get_solo()` (or other solo models) within a single request-response cycle. The places where this applies is (non-exhaustive list):
* form-step list endpoint to get the next/previous/save literals, falling back to the global configuration
* form/submission detail, which uses the same serializers as above
* plugin registries to check if (demo) plugins are enabled/should be included
* middleware to limit the session TTL (admin vs. anon user)
These calls rack up and actually bombard APM, making it impossible to see what other stuff is happening in the request that is slowing things down.
This patch introduces a cache backend that fetches its data from another cache, and stores it in a …
=> Implement a thread-local request-scoped proxy cache

src/openforms/js/components/form/coSign.js, src/openforms/js/components/form/edit/options.js, src/openforms/js/components/form/edit/tabs.js, src/openforms/js/components/form/editGrid.js
Fixes #2078 
Note: because #1391 fieldset component can have empty labels
So I also left that columns and content components can have empty labels.
=> [#2078] Make field label compulsory

src/openapi.yaml, src/openforms/formio/rendering/default.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/tests/renderer/test_submission_summary.py
Part of #2058 
To do backend:
To do frontend https://github.com/open-formulieren/open-forms-sdk/pull/238
=> [#2058] Summary page data from backend

CHANGELOG.rst, README.NL.rst, README.rst, src/openforms/upgrades/upgrade_paths.py
* Added changelog entries from 1.0.14 and 1.1.6
* Fixed mistake in version range (1.0.16 does not exist, 1.0.14 does)
* Added 2.0.0-beta.0 as a supported version range to update from
* Moved 1.0.x links to "unsupported versions" section
Tomorrow (Sept. 29th) we will release the new stable versions, 2.0.0 will follow next week hopefully.
=> Update 2.0.0 changelog

src/openapi.yaml, src/openforms/api/authentication.py, src/openforms/api/drf_spectacular/__init__.py, src/openforms/api/drf_spectacular/extensions.py, src/openforms/appointments/api/views.py, src/openforms/formio/api/views.py, src/openforms/submissions/api/views.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/tests/test_csrf.py, src/openforms/validations/api/views.py
The CORS policy + CSRF_TRUSTED_ORIGINS does a great deal of protecting against CSRF attacks, and most of our endpoints use PUT/DELETE calls, but there are a number of POST calls that benefit from extra CSRF protection.
=> Tighten CSRF validation for anonymous users

src/openforms/js/components/form/columns.js, src/openforms/js/lang/formio/nl.json, src/openforms/scss/components/admin/_edit-panel.scss, src/openforms/scss/components/builder/_builder.scss, src/openforms/scss/components/builder/_columns.scss
Fixes #2113 
* The (nested) boxes for columns now stretch to look more like a grid
* The labels of components are now limited to a single line (only in the builder!) and truncated with an ellipsis
=> Columns options in form builder

src/openforms/api/serializers.py, src/openforms/forms/api/datastructures.py, src/openforms/forms/api/serializers/logic/form_logic.py, src/openforms/forms/api/serializers/logic/form_logic_price.py, src/openforms/forms/api/validators.py, src/openforms/forms/api/viewsets.py, src/openforms/forms/tests/test_api_form_logic_bulk.py, src/openforms/forms/utils.py
Form logic endpoints had some terrible performance due to:
* validation of `form` FK (1 query per rule)
* validation of referenced variables in trigger (1-2 queries per variable per rule)
* insertion calculating + setting the rule for every rule (2 queries per rule)
So the number of queries was (worst case) `O(3n + 2m)` with `n` the number of rules and `m` the number of `{"var": "foo"}` references in the logic triggers.
This PR optimizes that to:
* no additional queries for `form` FK validation
* 1 query to prefetch all the form variables for trigger validation
* 2 queries for bulk insertion of the rules
This results in a fixed number of queries: `O(3)`
=> Improve performance form logic endpoints

src/openforms/formio/normalization.py, src/openforms/formio/service.py, src/openforms/prefill/__init__.py, src/openforms/submissions/api/validators.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/test_submission_step_validate.py
Fixes #1899 for 2.0
The flow is a bit different from 1.1.x:
- On create submission, variables are prefilled (no normalisation, because no component)
- On logic check, default values are injected in the configuration by get_dynamic_configuration (which takes the values from the filled variables). Here there is normalisation.
- On saving a submission step, the prefill data is validated. This takes the values of the prefilled variables (not normalised) and compares it to the incoming data (normalised).
- The variables are updated with the normalised value.
**Changes**
In the validation step, the prefill values are normalised before comparing them to the incoming data
=> [#1899] Normalisation step when checking prefill data

src/openforms/formio/datastructures.py, src/openforms/formio/dynamic_config/service.py, src/openforms/formio/dynamic_config/tests/test_date_component.py, src/openforms/formio/normalization.py, src/openforms/formio/service.py, src/openforms/formio/tests/test_service.py, src/openforms/formio/tests/test_variables_injection.py, src/openforms/formio/utils.py, src/openforms/formio/variables.py, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/models/form_definition.py, src/openforms/forms/tests/test_api_formdefinition.py, src/openforms/prefill/__init__.py, src/openforms/prefill/tests/test_prefill_hook.py, src/openforms/prefill/tests/test_prefill_variables.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/logic/actions.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/test_get_submission_step.py, src/openforms/utils/date.py
Related to #2042
Performance test run results on a simple form. A more complex form had hundreds of `iter_components` calls
| **Metric**              | Before | After |
|-------------------------|--------|-------|
| Avg latency (ms)        | 479    | 278   |
| 90 percentile (ms)      | 886    | 420   |
| # iter_components calls | 45     | 6     |
Note that I attribute the speedup mostly to the reduced APM overhead (implicit result by removing `iter_components` calls)
=> Reduce the amount of (unnecessary) iter_components calls

src/openforms/urls.py, src/openforms/utils/tests/test_sdk_urls.py, src/openforms/utils/views.py
Fixes #2141 
This relies on uwsgi passing the URL down to the application if the file is not found in the `--static-map` endpoint (see https://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html#mode-3-using-static-file-mount-points)
The generic URLs in the shape of `/static/sdk/open-forms-sdk.js` work now, independently of which SDK version is actually deployed. No changes are needed for existing clients.
=> Implement stable SDK URLs

src/openforms/forms/admin/form.py, src/openforms/forms/tests/admin/test_form.py, src/openforms/forms/utils.py
Fixes #2221 
I think we forgot to remove the warning once the variables became the default (since the test was skipped).
=> [#2221] Remove code for warning double keys

src/openforms/scss/components/builder/_builder.scss
The content component and the file component in the Form Definition change page still had dark text when in dark mode.
=> One more dark theme fix

src/openforms/scss/screen.scss, src/openforms/templates/master.html
Fixes #2225
Unless another theme is explicitly specified, emit the openforms-theme class for the design tokens and include the theme-scoped design token CSS variables rather than overriding the :root selector.
Newer SDK builds specify design token values for components other than our own --of prefix, which breaks themes other than our own.
=> :bug: emit openforms-theme as default theme

src/openforms/authentication/signals.py, src/openforms/authentication/tests/test_signals.py, src/openforms/authentication/views.py
Part of #1297
**Changes**
- Added `openforms.authentication.signals.authentication_success`
=> [#2197] Token authorisation: auth successful signal

requirements/ci.txt, requirements/dev.txt, requirements/test-tools.in, src/openforms/forms/tests/test_management.py, src/openforms/payments/tests/test_views.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/tests/test_submission_suspension.py, src/openforms/submissions/tests/test_temporary_uploads.py
Django 3.2+ has it built in, so the third party package is no longer needed.
=> :heavy_minus_sign: Drop django-capture-on-commit-callbacks

Dockerfile, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt
This is in preparation to upgrading python3-saml and then lxml to their latest versions.
lxml breaks on some edge cases becaues it was statically built against a different libxml2 than *other* xml-based tooling using at runtime ( because that's dynamically linked), causing some tree lookups to fail.
* python3-saml issue: https://github.com/onelogin/python3-saml/issues/292
* upstream bug: https://bugs.launchpad.net/lxml/+bug/1960668
=> :pushpin: Pin lxml to not use binary wheels

src/openforms/submissions/admin.py, src/openforms/submissions/tests/test_admin.py
Fixes #1957
(see the additional comment https://github.com/open-formulieren/open-forms/issues/1957#issuecomment-1290439854)
=> [#1957] Fixes admin retry_processing_submissions() action to reset Submission.registration_attempts

src/openforms/emails/context.py, src/openforms/emails/templates/emails/wrapper.html
The design-token values have CSS units, which don't work as HTML height/width attribute in every client (or browser yubin preview)
Fixes #2219
Note this was reported on 1.1.7 (branch with backport https://github.com/open-formulieren/open-forms/tree/fix/2219-email-logo-size-token-11x)
=> [#2219] Fixed CSS-unit issue with design-tokens in email header logo

src/openforms/prefill/__init__.py, src/openforms/prefill/tests/test_prefill_hook.py
Fixes #2337 
Not sure  if this will require backport, because the commit that added this code is present in 1.5 and master (not 1.7 or 2.0 :thinking: )
https://github.com/open-formulieren/open-forms/commit/d176eb04c0c0e5a8baf7e91ac369ab1654578620
=> [#2337] Catch KeyError for prefills

src/openforms/forms/api/viewsets.py
* Prefetch related form categories and products to avoid N+1 queries on these related resources
* Select related email confirmation template (o2o field, so prefetch wouldn't help/reduce data)
=> :zap: Optimize form list endpoint

src/openforms/forms/migrations/0033_formvariable_datamigration.py, src/openforms/forms/models/form_variable.py, src/openforms/forms/tests/test_data_migrations.py
Fixes #2262 
- add parameter to create_for_form to log and patch invalid plugin config
- add test to reproduce migration failure and check patch
=> fix migration failure

src/openapi.yaml, src/openforms/api/drf_spectacular/hooks.py, src/openforms/api/drf_spectacular/plumbing.py, src/openforms/conf/base.py, src/openforms/forms/api/serializers/__init__.py, src/openforms/forms/api/serializers/form.py, src/openforms/forms/api/viewsets.py, src/openforms/forms/tests/test_api_forms.py
Related to #2255
After some discussion with Chris about the impact on the SDK and in light of #2351, relying on the HTTP headers will reduce the amount of API calls needed to make.
Changing the client language is no server state change, so that side-effect can be performed inside the GET form-detail call.
=> Convey language information via HTTP headers

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
This allows us to use modern setuptools versions as the dependency is no longer required by Celery.
The flower containers are now broken with our current image build(s).
=> Bump Celery to latest patch release

README.NL.rst, README.rst
Updates both the Dutch and English readme, fixing the link to open-forms-sdk.
=> Fix docs typo resulting in 404

src/openforms/formio/tests/assertions.py, src/openforms/formio/utils.py, src/openforms/forms/api/serializers/form_variable.py, src/openforms/forms/models/form_variable.py
Related to #2042
We're factoring out get_component usage in favour of a caching datastructure, which should boost performance a bit on the python level.
=> replace get_component usage with configuration_wrapper

src/openforms/emails/context.py, src/openforms/emails/templates/emails/wrapper.html, src/openforms/emails/tests/test_send_mail_html.py
Fixes #2219.
- the original fix no longer works for the latest version of MS Outlook's desktop client
- the update adds the logo height/width as HTML tags with the unit removed (or an empty string if the unit is anything other than "px")
=> [2219] update fix for CSS-unit issue with design tokens in email header logo

src/openforms/authentication/contrib/org_oidc/plugin.py
The violation results in this error upon consumption in the SDK:
Warning: Failed prop type: The prop `form.loginOptions[0].logo.title` is marked as required in `App`, but its value is `undefined`.
=> 🩹 Fix OAS violation

src/openforms/formio/datastructures.py, src/openforms/formio/utils.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py
Bandaid fixes #2340
Note: this causes problems for logic rules that rely on the values of these hidden fields - we can tackle that when we get to #2409
=> Clear data from fields if they are nested within a hidden component

src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py, src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml, src/stuf/stuf_zds/templates/stuf_zds/soap/includes/bezoekadres.xml, src/stuf/stuf_zds/templates/stuf_zds/soap/includes/verblijfsadres.xml
Fixes #2422 
* Fixes postcodes with spaces to not have spaces
* Fixed inclusion templates for address accessing wrong context data, leading to data not being included at all
Definitely needs backporting to 2.0.x, possibly to 1.1.x as well.
=> StUF postcode format fixes

src/openforms/analytics_tools/templates/analytics_tools/google.html, src/openforms/analytics_tools/templates/analytics_tools/matomo.html, src/openforms/analytics_tools/templates/analytics_tools/piwik.html, src/openforms/analytics_tools/templates/analytics_tools/piwik_pro.html, src/openforms/analytics_tools/templates/analytics_tools/siteimprove.html, src/openforms/analytics_tools/tests/test_analytics_rendering.py
Fixes #2250
- all analytics tools (except Google Analytics) failed to render because the wrong property was tested in the templates
- fixed the templates
- added integration tests for the rendering of analytics snippets
=> [#2250] fix broken analytics tools

src/openforms/submissions/exports.py, src/openforms/submissions/tests/test_exports.py
Adds "Taalcode" field to submission exports for forms with `translation_enabled`.
Closes #2389
=> ✨[#2389] Add language code to submission exports

src/openforms/js/components/admin/form_design/data/complete-form.js
Related to #2418
The old state was being reset which still contained validation errors from the previous save attempt.
=> :bug: [#2418] -- fix duplicated validation errors

docs/developers/roadmap.rst
- "To provide" is more specific than "in light of"
- Down the drain is not the direction we hope to be going. 😉
- … vs ... 🤷 my editor told me, and I kept it in the commit.
=> 📝 Fix typo and apply tiny stylistic changes.

src/openforms/config/admin.py
Fixes #2428 
- a field entry in the admin was missing (probably deleted during rebasing)
=> [#2428] fix admin

src/openforms/appointments/management/commands/appointment.py
I noticed that if you have no configuration set up, it fails with hard to interpret errors.
This gives at least some more pointers, and also before starting the process.
=> Catch invalid appointment configs in command

.github/workflows/ci.yml, .gitignore, .readthedocs.yaml, INSTALL.rst, docs/index.rst
At some point it was mentioned the SDK changelog should also be published on readthedocs.
This approach includes it via symlink while keeping the source data in the respective repository.
=> Add SDK changelog to RTD/Sphinx documentation

src/openapi.yaml, src/openforms/forms/api/viewsets.py
The sentence could be read that the listed fields were only for non-staff users, while it's the other way around.
Came up while discussing another issue with Paul.
=> Remove ambiguity in endpoint documention

src/openapi.yaml, src/openforms/conf/base.py, src/openforms/forms/api/filters.py, src/openforms/forms/api/viewsets.py, src/openforms/forms/tests/test_api_formdefinition.py, src/openforms/js/components/admin/form_design/data/index.js, src/openforms/js/components/admin/form_design/data/supporting-data.js, src/openforms/js/components/admin/form_design/form-creation-form.js
Fixes #2504
Finally renamed the `pluginsToLoad` misnomer now I had to touch this code anyway.
=> Reduce data loaded from API in form designer

src/openforms/templates/500.html, src/openforms/templates/503.html
The bootstrap JS and CSS were being loaded in the error templates, and most of it was dead weight:
* JS was not used at all
* Many of the custom styles referred to headers/footers that weren't present in the first place
* Most of the bootstrap bloat was unused
So all in all - there was little reason to actually use these assets (from a CDN or elsewhere). The CSS was updated so the page layout remains the same with only the styles needed.
=> :lock: Addressed some minor security concerns

src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py, src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
Fixes #2494 
- details of the verblijfsadres were missing from the template for non-natural persons without auth
=> [#2494] fix XML template

docker-compose.yml, docs/installation/index.rst, docs/installation/redis.rst
Fixes #2198 
**Celery late acknowledgement:**
In celery, workers acknowledge messages to signify that a message has been handled. Failing to acknowledge the message will cause it to be redelivered. We use late acknowledgement, which means that the task (delivered as a message) is acknowledged _after_ being executed (so if the worker dies while executing, the message is redelivered).
**Celery prefetch limit:**
The prefetch limit is the maximum number of unacknowledged messages that a worker can prefetch. The setting `worker_prefetch_multiplier` is the number of messages to prefetch per process per worker. We have it set to 1, which means that the worker process can hold at most 1 task in addition to the one that's executing.
**Redis snapshotting:**
Redis by default runs with snapshotting …
=> [#2198] Add AOF persistence to Redis container

src/openforms/upgrades/tests/test_upgrade_paths.py, src/openforms/upgrades/upgrade_paths.py
Closes #2519 
* If the current version matches a loose match to the target version, it is implied you already passed those checks before and we don't need to run them again.
=> :sparkles: [#2519] -- skip upgrade checks in some cases

src/openforms/api/utils.py, src/openforms/forms/tests/test_api_forms.py, src/openforms/js/components/admin/form_design/form-creation-form.js
Fixes #2396
One of the API form tests (`test_deleting_a_confirmation_email_template_through_the_api`) had to be modified to avoid breaking as a result of the code change.
=> [#2396] fix auto_login_backend bug

src/openforms/utils/json_logic/descriptions.py, src/openforms/utils/tests/test_json_logic.py
Fixes #2542 
Formatting of JSON logic descriptions involving `rdelta` operations now works with varying numbers of arguments.
=> [#2542] fix description formatting

docs/developers/backend/core/templating.rst, src/openforms/authentication/contrib/tests/saml_utils.py, src/openforms/conf/base.py, src/openforms/config/models.py, src/openforms/config/templatetags/privacy_policy.py, src/openforms/emails/utils.py, src/openforms/submissions/models/submission.py, src/openforms/template/__init__.py, src/openforms/template/backends/sandboxed_django.py
Closes #1904
This still uses the Django template engine, but instead uses sandboxes that don't allow using non-public custom tags and/or include files from our source code.
=> Replace Template(...).render(...) usage with openforms.template.render_from_string

src/openforms/js/components/admin/form_design/FormLogic.js, src/openforms/js/components/admin/form_design/logic/LogicDescription.js
Fixes #2569
* Limit the user input to max 100 chars
* Automatically truncate server-side generated description to 100 chars
=> Truncate logic descriptions that are too long

.github/workflows/ci.yml, Dockerfile, requirements/setuptools.txt
The version of setuptools was unpinned anyway and the library that required this has been updated a while ago. We also have a pinned setuptools version in the requirements.
=> :fire: requirements/setuptools.txt not needed anymore

src/openforms/formio/dynamic_config/date.py, src/openforms/formio/dynamic_config/tests/test_date_component.py, src/openforms/js/components/form/date.js
Fixes #2525 
There were 2 problems:
- When removing the validation method in the edit form, the mode was saved as an empty string in the configuration. The backend was only considering the possibility of the mode being `None` for empty values.
- The edit form showed the default value even if the `mode` was `""`. This is also shown in the json, even though when looking at the configuration saved, this was the empty string. 
*Changes*:
- Backend skips updating the configuration if mode is `""` in addition to `None`
- Default value is now `""` for the `mode`
=> [#2525] Crash validation date

src/openforms/js/components/admin/form_design/utils.js
Fixes #2541 
Tested on:
`{"and":[{"==":[{"var":"selectBoxes.a"},true]},{"==":[{"var":"selectBoxes.b"},true]}]}`
`{"==":[{"var":"selectBoxes.a"},true]}`
=> [#2541] Handle selectboxes key change in logic

.github/workflows/ci.yml
Proves that dev deps can be installed on _a_ MacOS version & ensures we don't accidentally break this in the future.
It also documents some possibly necessary workarounds/manual actions.
=> :construction_worker: Add CI job to install dev deps on MacOS

src/openforms/prefill/tests/test_admin.py, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/registrations/contrib/stuf_zds/tests/test_failure_modes.py
=> [#2622] Fix Heisenbugs

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/stuf/admin.py
Closes #2601 (partly; see the complementing [PR](https://github.com/maykinmedia/django-camunda/pull/9) for [django-camunda)](https://github.com/maykinmedia/django-camunda) 
* Disable autocomplete for username/password fields in Stuf services
=> [#2601] disable autocomplete for username/password in admin

src/openforms/forms/admin/form.py, src/openforms/forms/templates/admin/forms/form/change_form.html, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/Context.js, src/openforms/js/components/admin/form_design/FormStepDefinition.js, src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js, src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/js/components/formio_builder/translation.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Fixes #2493 
This doesn't include warnings for missing translations in the global config, that should probably implemented on the backend
=> [#2493] :sparkles: Warnings for missing translations in admin

.storybook/main.js, .storybook/preview-head.html, .storybook/preview.js, src/openforms/scss/components/admin/_button.scss
Closes #2666
Fixed for both dev server and static build on a subpath.
* Emit the own CSS into a subpath matching the real structure
* Load the Django/library CSS via preview-head instead of adding it to the webpack toolchain. This simplifies things a lot.
=> Fix static asset serving with storybook

docs/installation/config.rst, src/openforms/conf/base.py, src/openforms/tests/test_x_forwarded_host.py
Discussed with Sergei:
* Django only uses this header if the setting is explicitly enabled
* Only a single value is supported. This header can occur as
comma-separated list if multiple upstream proxies are used. It's up to
your infrastructure to ensure only a single value is passed to Django.
Use this if you cannot set the `Host` header (for example, using istio
in Kubernetes).
=> enable opt-in to use X-Forwarded-Host headers

src/openforms/conf/base.py, src/openforms/middleware.py, src/openforms/tests/test_session_expiry.py, src/openforms/translations/middleware.py, src/openforms/translations/tests/test_admin_language_decoupling.py, src/openforms/typing.py, src/openforms/utils/tests/test_urls.py, src/openforms/utils/urls.py
Closes #2685
This makes it so the admin uses the browser language preferences instead of the language cookie.
I will create a separate PR/feature so that admin users can manage their (language) preferences.
=> Decouple admin localisation from public UI

package-lock.json, package.json
To align the version with the version used in the SDK.
=> :arrow_up: Bump design tokens to 0.23.0

src/openforms/formio/dynamic_config/date.py, src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/form/edit/date-edit-form.js
Fixes #2769
The layout component keys are not used as intermediate steps like with data containers, so the full namespaced path needs to be provided to the keys that actually write some configuration.
=> Fix date/time min/max validation configuration not saving correctly

src/openforms/formio/tests/test_utils.py, src/openforms/tests/search_strategies.py, src/openforms/variables/tests/test_validators.py
Closes #2814
The possible combinations of the 'conditional' component key are now parametrized via hypothesis, with an example as seen to be crashing in Sentry.
The actual fix was already included in 9c00f7f4cb4079d4949105faec76c77f68d6d3fd so no further action is required.
=> Add additional robustness tests with hypothesis

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/admin/form_design/FormStep.js, src/openforms/js/components/admin/form_design/FormStepDefinition.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/types/FormStep.js, src/openforms/js/components/form/content.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/js/utils/hooks.js
Fixes #2820 
Notes:
- I don't seem to be able to reproduce the original issue anymore (the content component not saving the translations). But I wrote a playwright test and it still seems to show that it doesn't work.
- What seems to happen now is that if you: 
1. create a component and add some translations
2. save the component
3. Open the component to edit it
4. click X in the top right of the modal to close without any changes
5. Open the component again
then the translations have vanished.
=> [#2820] Translations in edit form are not working properly yet

src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/tests/e2e/base.py
* Fixes the initial key getting a suffix due to unsaved component
* Fixes the UI not properly showing the underlying updated key (the data actually seemed fine)
* Now tests locally also use a 100ms delay, which made the test failing on CI but passing locally (because the JS itself didn't fully complete and there was a small flicker where the UI was as expected)
This mutable refs + formio state + react state is a _horrible_ combination and would definitely benefit from a react-based form builder to get some sanity back.
=> Fix broken component key flow

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/formio_builder/builder.js
After checking customer instances and getting in touch with customers, it turns out nobody is actually using this component. Given that the data is stored in plain text and pre-existing security/expectation concerns, it is decided to not invest any more effort but instead move the component to the deprecated group.
In the future we'll probably convert any possible existing components to textfields and remove it alltogether.
=> :wastebasket: Deprecate the password field

src/openforms/api/tests/test_validators.py, src/openforms/api/validators.py, src/openforms/emails/api/serializers.py, src/openforms/emails/tests/test_api_serializers.py, src/openforms/forms/tests/test_api_forms.py
* Fixes drop in test coverage due to the `ModelValidator`
* Added explicit tests for the `AllOrNoneRequiredFieldsValidator` which was drive-by coverage from other tests
=> Add tests for openforms.api.validators

src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/js/components/formio_builder/translation.js, src/openforms/js/components/formio_builder/translation.spec.js
Fixes #2819 (better fix)
Fixes #2889
Fixes #2840
Essentially this moves the translation hooks into the custom WebformBuilder class which seems to solve a number of problems:
* Initialize the translations before any change event fires when the modal to edit the component opens
* Do tap into the change events to keep track of literals (which is now done on the `editForm` instance instead of a React ref)
* Fix a bug in formio where the `key` configuration/component is not re-rendered after setting a unique value (original issue is #2819)
* This patch *accidentally* fixes the form builder dismissal removing the translations state (#2840)
We are no longer relying on obscure `onChange` options of the formio form class (and having to call the original parent methods etc.), but instead limit this …
=> Fix focus shift/flicker in form builder

src/openforms/forms/api/serializers/logic/action_serializers.py, src/openforms/forms/api/validators.py, src/openforms/forms/tests/test_serializers.py, src/openforms/forms/tests/variables/test_variables_in_logic_trigger.py
Fixes #2826
* values for date variables in logic rules should be specified in ISO 8601fomat
* removed `JsonLogicActionValueValidator` since it's no longer needed and replaced with basic `JsonLogicValidator`
=> [#2826] validate date value in logic rules

docs/developers/releases.rst
* Documented git tag annotations for backports
* Documented translations process as part of release
=> :pencil: Add more details to release flow and backporting

src/openforms/formio/api/validators.py, src/openforms/formio/tests/test_validators.py
Part of a fix for #2911 
heif is a container format. heic is a heif file with a certain type of compressed file in there.
libmagic doesn't recognize all heics as such, nor can PIL/pillow in dialogue with the product owner, this solution suffices for the usecase.
Alternative would be to do all of the following:
- add heif explicitly to the allowed filetype options which isn't great UX;
- install extra dependency (like wand or a pillow file reader) to inspect the whole file.
=> Assume image/heif and image/heic are the same.

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Updated per https://docs.sentry.io/platforms/python/guides/django/ and dependabot alert
(we don't use `send_default_pii=True` so the dependabot alert is not really relevant, but our SDK version was lagging behind a lot anyway)
=> :arrow_up: Upgrade sentry-sdk version to latest

src/openforms/formio/tests/test_utils.py, src/openforms/forms/tests/test_serializers.py, src/openforms/tests/search_strategies.py
All strategies in hypothesis are callable. This turns all our own into callables too, even if they don't have parameters. Less to think about. A refactor in the strictest sense of the word: no change of functionality at all, just an ergonomic rephrasing.
=> ♻ Make all search strategies callable

src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py, src/openforms/variables/models.py
Fixes #2694 
Based on https://github.com/open-formulieren/open-forms/pull/2836, should be merged first
Regarding only allowing variable interpolation within header/query param values, I made a note for this in a separate issue https://github.com/open-formulieren/open-forms/issues/2884 (since there is no documentation yet to begin with)
=> :recycle: [#2694] Switch to double bracket interpolation format for service fetch params

src/openforms/logging/logevent.py, src/openforms/logging/logic.py, src/openforms/logging/tasks.py, src/openforms/submissions/logic/actions.py, src/openforms/submissions/logic/log_utils.py, src/openforms/submissions/logic/rules.py, src/openforms/submissions/logic/service_fetching.py, src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/utils/json_logic/datastructures.py, src/openforms/variables/tests/test_validators.py
Closes #2893
Good news: this doesn't crash the actual logic evaluation
Bad news: crashes do happen in the celery tasks and not only for non-primitive JSON types.
=> Fix logic crashes in celery task

src/openforms/authentication/contrib/demo/tests/test_plugin.py, src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py, src/openforms/authentication/contrib/digid_mock/tests/test_plugin.py, src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py, src/openforms/authentication/contrib/eherkenning/tests/test_eidas_auth.py, src/openforms/authentication/tests/mocks.py, src/openforms/authentication/tests/test_views.py, src/openforms/authentication/views.py, src/openforms/submissions/report.py, src/openforms/submissions/serializers.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/tests/test_tasks_pdf.py
Closes #2716 
* the identifier (bsn) of form co-signers is included in the submission report, alongside first + last name
=> [#2716] include co-sign identifier (bsn) in submission report

src/openforms/data_removal/tests/test_tasks.py, src/openforms/submissions/models/submission_step.py
Fixes #2632 
* Currently this patch not a real fix, it merely circumvents the `RecursionError` without addressing the root problem
=> [#2632] fix recursion error

src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/tests/test_backend.py
Fixes #2980 
Needs backport to 2.1.x
=> [#2980] Use component overwrites for documents in Object API registration

src/stuf/stuf_zds/client.py, src/stuf/stuf_zds/tests/test_backend.py
Fixes #2983
Short summary: our tests (and other integrations apparently) do return the following structure:
```
Envelope
Header
Body
```
which the destructuring accepts, as the root element only has two children.
However, for this particular bug, the response has the structure:
```
Envelope
Body
```
which breaks unpacking.
Unpacking was never intentional here, so that that's being fixed and a regression test is added without the header element.
=> Fix broken StUF registration for some integrations

src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py, src/stuf/stuf_zds/templates/stuf_zds/soap/includes/bezoekadres.xml, src/stuf/stuf_zds/templates/stuf_zds/soap/includes/verblijfsadres.xml
Fixes #2977 
Modified existing test ([src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py](https://github.com/open-formulieren/open-forms/blob/e2a78dfaebb18f057ee184e4b3862fd0529d0471/src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py#L454)) to reflect changes. See #2422
=> [#2977] enforce stuf postcode uppercase

src/openforms/authentication/signals.py, src/openforms/authentication/tests/test_signals.py, src/openforms/authentication/tests/test_utils.py, src/openforms/authentication/utils.py
Fixes #1959 
Should be backported to 2.0.x and 2.1.x
=> [#1959] Reset `attribute_hashed` when setting info on AuthInfo from the session

src/openforms/submissions/tests/test_resume_form_view.py, src/openforms/submissions/views.py
Fixes #3025 
Should be backported to 2.1.x
=> [#3025] Invalid redirect url when resuming form

docs/manual/templates.rst, src/openforms/conf/tinymce_config.json
Fixes #3015 
Configuration documentation for tinymce 5: [link_assume_external_targets](https://www.tiny.cloud/docs/plugins/opensource/link/#link_assume_external_targets)
Now, instead of getting the protocol automatically appended, there is a prompt asking if you want to append it:
Should be backported to 2.0.x and 2.1.x
=> [#3015] Don't automatically add protocol to URL

package-lock.json, package.json
By relying on browserslist information to figure out which JS features are natively supported in browsers, we can remove some polyfills and cut down the bundle size about 11% (from 3.46 MiB to 3.07 MiB).
---
Command used to emit production bundle.
```bash
npm run build
```
| Bundle       | baseline    | optimized (0.2% share)   | optimized (0.5% share) |
|--------------|-------------|--------------------------|------------------------|
| core-js.js   | 3.46 MiB    | 3.47 MiB                 | 3.07 MiB               |
| core-css.css | 224 KiB     | 231 KiB                  | 223 KiB                |
| public.js    | 4 KiB       | 4 KiB                    | 4 KiB                  |
* targetting 0.2% browser share as minimum makes bundle sizes slightly worse
-> amongst others, this includes …
=> Optimize JS bundle sizes

src/openforms/tests/test_registrator_prefill.py
fixes OIDCRegistratorSubjectHaalCentraalPrefillIntegrationTest  test_flow test isolation for #2999
=> :green_heart: [#2999] added _create_log mock for test_flow test

docs/developers/sdk/embedding.rst, docs/installation/config.rst
Closes #2940
I am correcting some factual mistakes in the ticket itself too, there really isn't more to do than documenting the behaviour here.
* Elaborate on how IS_HTTPS is used
* Make it clear that embedding is not possible in an HTTP context
* Break up CORS settings in recommended/dangerous sections
* Document which settings should be typically specified to enable embedding
=> Flesh out SDK embedding configuration documentation

src/openforms/formio/api/validators.py, src/openforms/formio/tests/test_api_fileupload.py, src/openforms/formio/tests/test_validators.py
Fixes #2808
- overflow is prevented by removing the second occurrence of the filename from the error message (the filename is already displayed, hence the second occurrence is redundant)
- existing tests modified to reflect changes
=> [#2808] fix overflowing filenames

src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/email/templates/emails/email_registration.html, src/openforms/registrations/contrib/email/templates/emails/email_registration.txt, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/setup.py
Closes #3077 (partly)
Complement to PR #3093
=> [#3077] use public form name for form_name variable

src/openforms/formio/datastructures.py, src/openforms/formio/service.py, src/openforms/formio/tests/test_datastructures.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/logic/datastructures.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/form_logic/test_modify_components.py, src/openforms/variables/utils.py
Closes #2784
Adds a datastructure to deal with the formio keys that can contain periods (`.`) which expand into nested objects.
There are now some chained calls that convert between `FormioData` <-> `dict` that would probably benefit from changing their signature to accept `FormioData`, but I'm not sure how troublesome that will be if we need to do backportable fixes in those areas :thinking: Let's discuss?
=> Introduce FormioData data structure

src/openforms/js/components/admin/form_design/PluginWarning.js
Closes #3112
The new form builder normalizes the schema and this means text fields always have a 'prefill' object in their configuration, with plugin and attribute set to null if there's no prefill.
The warning now checks the behaviour only if a plugin is configured using the operator to shortcut if parts are missing in the nested object lookup.
=> Fix prefill plugin check in warning (new form builder)

.github/workflows/ci.yml
Closes #2999
This fails some tests because they or for some reason not isolated.
Unit tests should be able to run in random order.
=> 🧪 Runs tests in reverse order in CI

src/openforms/forms/models/form.py, src/openforms/forms/tests/admin/test_form.py
This pull request fixes #3070 by erasing `self.confirmation_email_template.pk` and updating the relation to `copy` so its added as a new row with the correct foreign key.
=>  copy the "Bevestingsmailsjabloon" when a form is copied

docs/conf.py, docs/developers/backend/tests.rst, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/log_outgoing_requests_ext/__init__.py, src/log_outgoing_requests_ext/tasks.py, src/log_outgoing_requests_ext/tests/test_tasks.py, src/openforms/conf/base.py, src/openforms/conf/ci.py, src/openforms/conf/dev.py, src/openforms/fixtures/default_admin_index.json, src/openforms/scss/admin/_app_overrides.scss
Closes #2762 (partly)
~~Depends on [maykinmedia/django-log-outgoing-requests](https://github.com/maykinmedia/django-log-outgoing-requests/pull/4)~~
- add settings for saving request & response body
- add celery task + schedule for cleaning up logs
=> [#2762] update settings: log outgoing requests

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Bumped PyOpenSSL to be able to bump cryptography to 41.0.0+
See also: maykinmedia/django-digid-eherkenning#31
=> Upgrade dependencies

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
This version is Django 4.2 compatible
Part of #3049
=> :arrow_up: Bump to cookie-consent 0.4.0

src/openforms/forms/migrations/0079_replace_cosign_component.py, src/openforms/forms/tests/test_migrations.py
Fixes #1530 
Remove the migration that was meant to convert the old cosign component to the new cosign component. We decided later that the old flow should be kept.
=> [#1530] Remove migration

src/openforms/formio/components/np_family_members/haal_centraal.py, src/openforms/formio/components/np_family_members/stuf_bg.py, src/openforms/formio/components/np_family_members/tests/test_family_members.py, src/openforms/prefill/contrib/haalcentraal/tests/test_client.py, src/openforms/prefill/contrib/haalcentraal/tests/test_plugin.py
I noticed test failures again via #3167 and managed to reproduce it locally.
* Ensure the zds client oas cache is cleared between tests
* Update tests to use unittest.mock approach for django-solo models
* Replace old-style file handling with pathlib for mock data
=> :art: Fix test isolation issue and clean up test code

src/openforms/js/components/admin/form_design/variables/utils.js, src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/components/utils.js
Closes #3128
See description in https://github.com/open-formulieren/open-forms/issues/3128#issuecomment-1598864509
Basically:
* Frontend code set `defaultValue: null` for file field
* This is stored in the `FormVariable.initial_value` as `None`
* Logic check compares that the expected default value for file field (`[]`) != `None`
* Logic check emits `data: {"fileField": []}` to correct this
* which triggered the client-side form.io validation
Backporting #2436 fixes the client-side admin code, which results in the correct `FormVariable.initial_value` and makes the problem go away.
=> Fixed hidden file field triggering validation

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Closes #3103
This version prepends the XML declaration as part of metadata generation.
=> :arrow_up: [#3103] -- bump django-digig-eherkenning to 0.8.0

src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid_machtigen/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning_bewindvoering/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/views.py, src/openforms/authentication/contrib/org_oidc/tests/test_auth_procedure.py, src/openforms/authentication/contrib/org_oidc/views.py
The OpenID Connect standard prescribes nothing about having to support HEAD requests, so we can't be certain that all OIDC providers support this, nor can we make a reasonable demand to support this at the infrastructure level.
This replaces the HEAD requests with a GET, which should be guaranteed to work.
=> :ambulance: Replace HEAD calls with GET for OIDC auth endpoint

src/openforms/formio/components/custom.py, src/openforms/formio/components/vanilla.py, src/openforms/formio/dynamic_config/date.py, src/openforms/formio/dynamic_config/tests/test_date_component.py, src/openforms/formio/dynamic_config/tests/test_datetime_component.py, src/openforms/formio/typing/__init__.py, src/openforms/formio/typing/base.py, src/openforms/formio/typing/custom.py, src/openforms/formio/typing/dates.py, src/openforms/formio/typing/vanilla.py
The Form.io base component type is now more realistic with the totality set to False, meaning that any key in the dict may be absent. This matches Form.io's own typescript definitions.
Additionally, the types are centralized in a typing package where (relative) imports don't cause circular import issues - they are now truly standalone. The runtime code that had type definitions now imports them from the top-level entry point.
This change allows us to more strictly type individual component types, while having the type checker help accounting for possible Form.io JSON weirdness.
Needed for the #3139 PR which makes use of these types.
=> :label: Refactor formio types in backend

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
This version supports Django 4.2. Thanks to @ErhanCitil for doing the research.
=> :arrow_up: Upgrade to django-autoslug 1.9.9

src/openforms/forms/models/form_definition.py, src/openforms/forms/tests/test_formdefinition_admin.py, src/openforms/utils/helpers.py, src/openforms/utils/tests/test_helpers.py
=> [#3130] Fix copying form definitions with long names

src/openforms/appointments/api/fields.py, src/openforms/appointments/api/views.py, src/openforms/appointments/base.py, src/openforms/appointments/contrib/demo/plugin.py, src/openforms/appointments/contrib/jcc/plugin.py, src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/plugin.py, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py, src/openforms/appointments/utils.py, src/openforms/emails/tests/test_confirmation_email.py
This clears up the namespace for models that will have similar names.
=> :recycle: Rename dataclasses to remove redundant prefix

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/admin/form_design/data/complete-form.js, src/openforms/js/components/admin/form_design/form-creation-form.js
Partly fixes #2471
A bunch of fields/tabs are not relevant for appointment fields, such as registration and payment but even the individual form steps as they are hard-coded.
=> Disable more (irrelevant) form configuration for appointment forms

.storybook/main.js
Sets more specific path glob pattern to find stories, mine was picking
up sdk stories that somehow found their way into my sdk build.
=> 🩹 Fix storybook build

src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py, src/openforms/authentication/contrib/digid/views.py
Closes #3278
The Signicat borker [sic!] has shown to send nameid's in artefact
responses that don't contain the sector code for BSN (even in their production
environment)
We assume BSN there... I don't know what this means for the 500 people
named F. Vogelpest in Heerlen that share the same SOFI.
=> Handle DigiD SAML Artefact with missing sector code

src/openforms/forms/models/form.py, src/openforms/forms/models/form_definition.py, src/openforms/forms/tests/test_form_admin.py, src/openforms/forms/tests/test_formdefinition_admin.py
=> [#3223] Translate name when copying a form or a formdefinition

src/openforms/submissions/attachments.py, src/openforms/submissions/tests/test_submission_attachment.py
Fixes #3302
Prevent the celery worker from picking up the attachment image resize task before the DB transaction is committed. Celery workers run in different processes and thus different database transactions. The database record must be committed before the worker can look it up to start processing.
=> Fixed race condition between celery worker and DB transaction

.github/workflows/ci.yml, Dockerfile
This was originally pinned due to a threading shutdown bug in CPython, see #2748. Since then Python 3.10.11 and 3.10.12 have been released, containing security fixes.
Not specifying the patch version in docker images and CI pipelines grabs the latest patch version for the minor version, which gives us the latest bug fixes 'for free'. This is preferrable over the risk of new bugs breaking our application like in #2748.
=> :pushpin: Unpin Python from 3.10.9 to 3.10

src/openforms/prefill/contrib/stufbg/plugin.py, src/stuf/stuf_bg/templates/stuf_bg/tests/responses/StufBgResponse.xml, src/stuf/stuf_bg/tests/test_client.py
- assert validity of mock response
- 🔥 remove test_address, moved useful assertions elsewhere
- it wasn't testing getting an address
- it was patching and mocking things it wasn't asserting
- it was asserting the same thing twice
- test the Client.get_values which is the actual api of the class
TODO:
- do the same for the other xml responses in tests/responses
- test the failure modes of get_values
- rename get_values_for_attributes to \_get_values_for_attributes
if it's really just a private helper
=> Cleanup StUF-BG tests a bit

src/openforms/appointments/models.py, src/openforms/appointments/renderer.py, src/openforms/appointments/service.py, src/openforms/appointments/tests/factories.py, src/openforms/appointments/tests/test_confirmation_emails.py, src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/emails/confirmation_emails.py, src/openforms/emails/templates/emails/templatetags/appointment_information.html, src/openforms/emails/templates/emails/templatetags/appointment_information.txt, src/openforms/emails/templatetags/appointments.py, src/openforms/emails/templatetags/form_summary.py, src/openforms/formio/registry.py, src/openforms/formio/rendering/nodes.py, src/openforms/submissions/models/submission.py
Closes #3321
- The form summary rendering is now empty for appointment forms (there are no steps or formio forms to render)
- The contact details submitted (dynamic, depending on the selected product(s)) are now included
- The setting to not send a confirmation email is respected
- Restructured some code to move more responsibility into the appointments app/module
=> Update confirmation email sending for new appointments

src/openapi.yaml, src/openforms/appointments/api/serializers.py, src/openforms/appointments/api/views.py, src/openforms/appointments/base.py, src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/tests/test_api_endpoints.py, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py, src/openforms/appointments/tests/test_api_products.py
Partly closes #3332
Passing the IDs of the products allows the plugin to retrieve other products in that context, as certain products can not be selected in combination with other products.
Backend aspect - SDK needs to take the selected products into account.
=> Support passing already selected product IDs in products list endpoint

src/openapi.yaml, src/openforms/contrib/kadaster/api/serializers.py, src/openforms/contrib/kadaster/api/urls.py, src/openforms/contrib/kadaster/api/views.py, src/openforms/contrib/kadaster/search.py, src/openforms/contrib/kadaster/tests/test_api_latlng_search.py
fixes #2174 
- Added api call that returns location name based on the latitude and longitude
- Added unit tests to test the correct behavior for the newly added api call
=> :sparkles: [#2174] added api call for the pdok locatie server reverse lookup

src/openforms/appointments/contrib/jcc/plugin.py, src/openforms/appointments/contrib/jcc/tests/mock/getGovAppointmentDetailsMultipleProductsResponse.xml, src/openforms/appointments/contrib/jcc/tests/mock/getGovProductDetailsNoDescriptionResponse.xml, src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/core.py, src/openforms/appointments/utils.py
Depends on #3330, related to #3321
Ensure that we correctly interpret the product count when retrieving appointment details from JCC.
Implemented based on documentation, as I'm still waiting for support/help from JCC to figure out the appointment booking issues.
=> Correctly report product amount when fetching JCC appointment details

src/openforms/appointments/registry.py, src/openforms/authentication/base.py, src/openforms/authentication/registry.py, src/openforms/authentication/tests/test_registry.py, src/openforms/dmn/registry.py, src/openforms/formio/registry.py, src/openforms/formio/rendering/registry.py, src/openforms/forms/validation/registry.py, src/openforms/payments/base.py, src/openforms/payments/registry.py, src/openforms/payments/tests/test_registry.py, src/openforms/plugins/registry.py, src/openforms/plugins/tests/test_registry.py, src/openforms/pre_requests/base.py, src/openforms/pre_requests/registry.py, src/openforms/prefill/registry.py, src/openforms/registrations/registry.py, src/openforms/variables/base.py, src/openforms/variables/registry.py
This uncovered a couple of bugs too where plugins were being yielded rather than their identifiers.
=> Make the base registry class a generic type

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Django yubin before 2.0.1 would discard custom headers and incorrectly reconstruct message attachments, as well as losing other headers like the Reply-To value.
See APSL/django-yubin#66 for details.Django yubin before 2.0.1 would discard custom headers and incorrectly reconstruct message attachments, as well as losing other headers like the Reply-To value.
See APSL/django-yubin#66 for details.
Ideally we would backport this, but due to the breaking changes in 2.0 this is not easily done.
=> Bump to django-yubin 2.0.1

src/openforms/variables/static_variables/static_variables.py, src/openforms/variables/tests/test_static_variables.py
Closes #1889
Having current_year available as a variable solves the problem of
Haarlemmermeer of not being able to "block"/validate based on an integer
relative to the current year. They can adapt their current forms to use
this, so they won't need to change the forms on each January 1st
anymore.
I think the wish for a picker is a distraction from this core problem.
But should one really feel the need for a year picker, with this
`current_year` one can construct a one with a Select component with
variable options with an option expression like this:
```json
{
"merge": [
{ "-": [{ "var": "current_year" }, 3] },
{ "-": [{ "var": "current_year" }, 2] },
{ "-": [{ "var": "current_year" }, 1] },
{ "var": "current_year" },
{ "+": [{ "var": "current_year" }, 1] },
{ "+": [{ "var": "current_year" …
```
=> Add current_year static variable

package-lock.json, package.json, src/openforms/scss/components/_form-choices.scss, src/openforms/templates/includes/forms/field_wrapper.html, src/openforms/templates/includes/forms/radio.html, src/openforms/utils/templates/of_utils/widgets/radio.html, src/openforms/utils/templates/of_utils/widgets/radio_option.html, src/openforms/utils/widgets.py
Closes #3327
Closes #3207
Note that open-formulieren/open-forms-sdk#529 is required for the correct background styles of the radio options.
=> Fix radio field markup in Django templates

src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py, src/openforms/variables/models.py
The serializer enforces qs params to have the form
`{'param': ["{{value}}"]}` but the template rendering code would send
this as:
https://example.com/api?param=["valueofvalueincontext"]
https://example.com/api?param="valueofvalueincontext"
There's a to be implemented test for the explode and form style OAS
variants of the spec. The httpbin OAS has no such endpoint.
=> 🐛 Fix passing querystring params to service fetch

src/openforms/appointments/renderer.py, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/formio/rendering/tests/test_vanilla_formio_components.py, src/openforms/formio/typing/__init__.py, src/openforms/formio/typing/vanilla.py, src/openforms/formio/utils.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/rendering/base.py, src/openforms/submissions/rendering/renderer.py
Closes #3406
The Formio `ComponentNode` essentially only required access to a `SubmissionStep` instance to read the data/values for each component. So, the data (and translation machinery) has been lifted up to the parent that is responsible for yielding `ComponentNode`'s so that the dependency on `SubmissionStep` can be removed.
This in turn makes it possible for the appointment data renderer class to re-use the `ComponentNode` for the contact details data, which is recorded as formio component definitions and stored in a similar way, but crucially does not make any use of `FormStep` or `SubmissionStep`.
Finally - my editor was showing many red squiggly lines so I tweaked the type hints in `openforms.formio.utils` a bit. It's definitely not complete yet, but I think it's more correct …
=> Refactor formio/appointment render nodes

.github/workflows/ci.yml
In the docs, it says:
_The first time you run the command openapi-generator-cli the last stable version of OpenAPITools/openapi-generator is downloaded by default._ 
In the latest stable version csharp-netcore was renamed to csharp.
So here I:
- set which version we want to use 
- Removed the csharp-netcore step (since we already had another csharp step)
=> Fix the version of openapi-generator

src/openforms/forms/tests/e2e_tests/test_translation_warnings.py, src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js
fixes #3375 
- Added code to display translation warning only when not all filled in.
- Added playwright tests to test the translation warnings.
=> :bug: [#3375] fixed issue that would not show explanation template translation warnings

src/openforms/appointments/renderer.py, src/openforms/appointments/service.py, src/openforms/appointments/templates/appointments/appointment__pdf.html, src/openforms/appointments/tests/test_confirmation_emails.py, src/openforms/appointments/tests/test_pdf.py, src/openforms/appointments/utils.py, src/openforms/emails/templatetags/appointments.py, src/openforms/submissions/models/submission_report.py, src/openforms/submissions/report.py, src/openforms/submissions/templates/report/submission_report.html, src/openforms/submissions/tests/test_tasks_pdf.py
Closes #3416
The idea is that a renderer should behave a like a Django Form does.
i.e. render the default representation when used as `{{ appointment }}`
No effort has been put (yet) into the getattr side of that API.
So within the submission_report template you can't access the
appointment attributes, the way you can access Django form fields.
=> ♻[#3416] Refactor rendering appointment data

src/openforms/js/components/form/map.js
fixes #3445 
added decimalLimit of 7 for the lat and long fields in the map.js
=> :bug: [#3445] upped the map lat and long field decimal limit to 7

src/openforms/appointments/contrib/qmatic/tests/factories.py, src/openforms/contrib/bag/tests/base.py, src/openforms/contrib/kvk/tests/base.py, src/openforms/formio/components/np_family_members/tests/test_family_members.py, src/openforms/forms/tests/variables/test_viewset.py, src/openforms/pre_requests/tests/test_clients.py, src/openforms/prefill/contrib/haalcentraal/tests/test_client.py, src/openforms/prefill/contrib/haalcentraal/tests/test_co_sign.py, src/openforms/prefill/contrib/haalcentraal/tests/test_config_check.py, src/openforms/prefill/contrib/haalcentraal/tests/test_models.py, src/openforms/prefill/contrib/haalcentraal/tests/test_plugin.py, src/openforms/prefill/tests/test_prefill_variables.py, src/openforms/registrations/contrib/objects_api/tests/factories.py, src/openforms/registrations/contrib/zgw_apis/tests/factories.py, src/openforms/services/tests/test_api_list.py, src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py, src/openforms/submissions/tests/test_variables/test_fetch_with_logic.py, src/openforms/tests/test_registrator_prefill.py, src/openforms/variables/tests/factories.py, src/zgw_consumers_ext/factories.py
We were now duplicating these factories in multiple places and importing them from weird places.
=> :truck: Move service factory to more general purpose location

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/admin/form_design/NewStepFormDefinitionPicker.js
fixes #3187 
- added line of code in the filtering of the selectbox options to filterout selected form definitions
- added playwright tests
=> :sparkles: [#3187] prevent selecting duplicate form definitions

src/openforms/appointments/contrib/qmatic/client.py, src/openforms/appointments/contrib/qmatic/plugin.py, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/CreateAppointmentTests/CreateAppointmentTests.test_create_appointment_multi_product_multi_customer.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/CreateAppointmentTests/CreateAppointmentTests.test_create_appointment_single_product_single_customer.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_listing_dates_single_product_multiple_customers.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_listing_dates_single_product_single_customer.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableDatesTests/ListAvailableDatesTests.test_multiple_products_multiple_customers.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_listing_times_single_product_multiple_customers.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_listing_times_single_product_single_customer.yaml, src/openforms/appointments/contrib/qmatic/tests/data/vcr_cassettes/ListAvailableTimesTests/ListAvailableTimesTests.test_multiple_products_multiple_customers.yaml, src/openforms/appointments/contrib/qmatic/tests/test_api_endpoints.py, src/openforms/appointments/contrib/qmatic/tests/test_appointment_create.py, src/openforms/appointments/contrib/qmatic/tests/test_dates_list.py, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/tests/test_products_list.py, src/openforms/appointments/contrib/qmatic/tests/test_times_list.py, src/openforms/appointments/contrib/qmatic/tests/utils.py, src/openforms/appointments/management/commands/appointment.py
Closes #3456
Customer details are duplicated for the product with the largest amount. Qmatic considers customers independently from their services (where JCC simply duplicates the product ID for every occurrence).
This means that 2 different products, one with amount 1 and the other amount 3 makes 3 customers in total, and the 3 customers is also applied to product 1. This can lead to some undesired wasted time, for which I will create a Taiga issue with the stakeholder.
=> Support multi product / multi customer appointments in Qmatic

src/openforms/authentication/contrib/digid/tests/test_signicat_integration.py, src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py
Story time!
A couple of signicat integration tests were failing locally but not in CI. This is/was weird, because the tests were just replaying the VCR cassettes and the behaviour should be the same on both environments!
However, after much investigation, it was clear that the tests were crashing because the ACS (redirected) view was eventually returning an HTTP 403 (with dev settings), while returning an HTTP 200 (as expected) with ci settings. Tracing the origin of that 403 revealed that it was the nature of the submission resume URL/view being used was the culprit - this relies on cryptographically secure tokens to automatically let resumption (and other state changes) be time-limited and reduce the risk of replay attacks.
Now, looking at the tokens generated, it was clear with the CI …
=> :green_heart: Fix tests failing with dev-settings

src/openforms/pre_requests/clients.py, src/openforms/pre_requests/tests/test_clients.py, src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py, src/openforms/utils/tests/nlx.py, src/zgw_consumers_ext/api_client.py, src/zgw_consumers_ext/nlx.py, src/zgw_consumers_ext/tests/test_nlx_rewriting.py
Partially closes #3489, depends on #3507
---
* Added tests and improved NLX support for current situation
* Updated test to make use of new client approach
* Added NLX support to new client approach
=> API clients rework: establish NLX integration

docs/developers/backend/core/utils.rst, src/openforms/admin/decorators.py, src/openforms/appointments/admin.py, src/openforms/appointments/contrib/jcc/tests/test_admin.py, src/openforms/appointments/contrib/qmatic/tests/test_admin.py, src/openforms/registrations/contrib/zgw_apis/admin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_admin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_zgw_api_config.py, src/openforms/scss/admin/admin_overrides.scss, src/openforms/scss/admin/widgets/_error-widget.scss, src/openforms/scss/admin/widgets/_index.scss, src/openforms/utils/decorators.py, src/openforms/utils/tests/test_decorators.py
fixes #3279 
Made a decorator that wraps a try, catch around a function and either returns it normally or returns a default value with a django message error
todo:
- write a nice explanation what the decorator does and should be used
- look into where we need to use it for now
- look into which exceptions the function should handle per usecase
- look into nice, understandable and none incriminating error messages
=> Catch errors in the admin for fields making outgoing requests

src/openforms/formio/components/translations.py, src/openforms/formio/components/vanilla.py, src/openforms/formio/dynamic_config/__init__.py, src/openforms/formio/registry.py, src/openforms/formio/service.py, src/openforms/formio/tests/test_component_translations.py, src/openforms/formio/typing/__init__.py, src/openforms/formio/typing/base.py, src/openforms/formio/typing/vanilla.py, src/openforms/tests/search_strategies.py
Partly fixes #2958
This sets up a mechanism for component-level translations.
Translation aspects:
=> Component level translations

docs/manual/forms/logic.rst, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/submissions/tests/form_logic/test_modify_variables.py
=> [#2953] Support date periods

bin/check_non_unique_steps.py, src/openforms/upgrades/upgrade_paths.py
=> Backport: duplicated form steps check

Dockerfile, patches/README.md, patches/apply.sh, patches/yubin_001.patch, patches/yubin_002.patch, patches/yubin_003.patch
Closes #3448
This includes the relevant git commits as `.patch` files and applies them in the backed image build to the installed django-yubin package.
Backporting needed to Open Forms 2.3.x, older is not affected due to yubin v1 being used there.
=> Backport yubin patches

src/openforms/appointments/contrib/qmatic/client.py
=> 🩹 Raise a custom exception instead of `RuntimeError`

docs/manual/forms/form_fields.rst, src/openforms/contrib/haal_centraal/clients/brp.py, src/openforms/contrib/haal_centraal/tests/test_brp_clients.py, src/openforms/js/components/form/np-family-members.js, src/openforms/js/lang/formio/nl.json
=> [#3524] Ignore family members without BSN

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/js/components/admin/RJSFWrapper.js, src/openforms/js/components/admin/forms/Field.js, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_validators.py
Fixes #3553.
After taking a look at the test environment, I found at when a non field validation error was raised, it would not show up in the admin.
This fix switches the validation error to a specific field:
(validation error later attached to the `roltype`).
This also allows for non field errors to be displayed:
=> 🐛 Switch ZGW registration backend to a field error

Dockerfile, patches/README.md, patches/apply.sh, patches/yubin_001.patch
Closes #3585
Backport of https://github.com/APSL/django-yubin/pull/73
=> Backport yubin patch

src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
I assume `gorOpenbareRuimteNaam` is semantically the same as streetname.
This fixes the reported bug. But doesn't test against the spec.
Closes #3580
=> 🐛[#3580] Fix zrc rol_create

docs/manual/forms/examples/form_with_geometry.rst, docs/manual/forms/examples/index.rst, docs/manual/templates.rst, src/openforms/forms/models/form.py, src/openforms/registrations/contrib/objects_api/templatetags/registrations/contrib/objects_api/json_tags.py, src/openforms/registrations/contrib/objects_api/tests/test_templatetags.py
=> ✨ [#3573] Add a new template tag `as_json`

src/openforms/conf/base.py
This configuration was missing (but as a workaround it can be added through the admin interface). Now we include it, which restricts some functionality (which was not intended in the first place).
The envvar lookup/fallback allows an escape hatch for those who are making use of object and embed tags.
=> :lock: Add CSP object-src directive to settings

.github/workflows/ci.yml, Dockerfile
Closes open-formulieren/security-issues#10
Second attempt to add non-intrusive image scanning.
=> Add image scanning

src/openforms/plugins/registry.py
A small improvement regarding type checking of the `BaseRegistry` class:
```python
a = register("coSign")
reveal_type(a)  # Revealed type is "def (type[Any]) -> type[Any]"
b = a(...)
reveal_type(b)  # Revealed type is "Any"
a = register("coSign")
reveal_type(a)  # Revealed type is "def a(type[BaseValidator]) -> type[BaseValidator]"
b = a(...)
reveal_type(b)  # Revealed type is "type[BaseValidator]"
```
I think it doesn't make sense to have a type alias to `type[PluginType_co]` outside any definition, because `PluginType_co` isn't bound to any generic class/function yet.
Only downside here is that in `Callable[[type[PluginType_co]], type[PluginType_co]]`, `type[PluginType_co]` should also be a `TypeVar` bound to `type[PluginType_co]`, but typevars bound to other typevars are not allowed.
=> 🏷️ Fix generic type hinting of registry

src/openforms/formio/components/np_family_members/tests/responses/stuf_bg_2_children.xml, src/openforms/formio/components/np_family_members/tests/test_family_members.py, src/stuf/stuf_bg/client.py
Fixes #3625.
In the altered xml file test response, `heeftAlsKinderen` is converted to a `list` by `xmltodict`, and `_remove_nils` would skip this branch. Tests didn't catch this as no null value was set, hence the altered test to show this.
cc @CharString
=> [#3625] Fix handling of null values when parsing Stuf responses

src/openforms/conf/base.py
The configuration of CSP frame-ancestors conflicted with the X-Frame- Options header configuration (set to DENY). We do not support using frames of any kind (frame, iframe, object, embed) and thus X_FRAME_OPTIONS is set to DENY. This results in the X-Frame-Options HTTP response header, which is obsoleted by the Content Security Policy frame-ancestors directive. The equivalent configuration to block all frames is to set it to 'none' rather than 'self'.
For more context, see:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
=> :bug: [DH#606] Update CSP frame-ancestors directive

docs/configuration/registration/zgw.rst, src/openforms/contrib/zgw/clients/documenten.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
Fixes #3649 
For compatibility with the RXMission API (for which this field is required and `null` values are not accepted).
=> [#3649] Add bestandsomvang field

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Fixed the pip warning:
> DEPRECATION: o365 2.0.18 has a non-standard dependency specifier tzlocal<3.*,>=1.5.0. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of o365 or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Fixing the same warning for the django-2fa library fork is a lot more involved, see also #3049 which is blocked by solving this MFA issue.
=> Update dependencies to resolve pip warning.

src/openforms/forms/models/__init__.py
I don't really know how Django was still able to take this model into account, but according to docs:
https://docs.djangoproject.com/en/5.0/topics/db/models/#organizing-models-in-a-package
> You must import the models in the `__init__.py` file.
=> Add missing `FormsExport` import

setup.cfg
CI runs `flake8 src`, but I got flake8 errors when running locally without specifying a path. It's a shame that you can't configure `include` paths in configuration file.
=> Update `flake8` exclusion list

src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid_machtigen/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/views.py
Fixes #3656 
- After investigation we found out (@SilviaAmAm helped with debugging) that OIDC returns an error (required) and an error_description (optional) as query parameters `error=access_denied&error_description=The user cancelled` . 
That's why we explicitly return a message according to DigiD and Logius specs instead of the generic one.
References:
- https://openid.net/specs/openid-connect-core-1_0.html#AuthError
- https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2.1
In order to test this you will have to set up DigiD-OIDC in the admin so let me know and I will provide you with the needed settings.
=> [#3656] OIDC-DigiD return proper message after login cancellation

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openapi.yaml
Nothing seems to be breaking, but this is without OAS 3.1 enabled.
=> Update to latest `drf-spectacular`

package-lock.json, package.json, src/openforms/js/components/form/columns.js
Partly closes #3733
* Fixed crash due to validation of `column.size` which was string and should be number
- The rendering crash on object instead of string for validation error is fixed internally in the builder library
* Upgraded builder library version to get the bugfixes applied in there
=> Fix bugs in new formio builder

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
to allow disabling of group assignment by leaving groups_claim empty
=> :arrow_up: Upgrade mozilla-django-oidc-db to 0.14.1

src/openforms/contrib/brk/tests/test_integration.py, src/openforms/contrib/brk/tests/test_validators.py, src/openforms/contrib/brk/validators.py, src/openforms/contrib/kvk/tests/test_validators.py, src/openforms/contrib/kvk/validators.py, src/openforms/payments/tests/test_registry.py, src/openforms/plugins/registry.py, src/openforms/registrations/registry.py, src/openforms/validations/api/views.py, src/openforms/validations/base.py, src/openforms/validations/registry.py, src/openforms/validations/tests/test_api.py, src/openforms/validations/tests/test_registry.py, src/openforms/validations/validators/formats.py, src/openforms/validations/validators/tests/test_formats.py
Cherry picked from https://github.com/open-formulieren/open-forms/pull/3701
=> Refactor validation plugins

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml, src/openforms/__init__.py
There is no new SDK version for this release.
After merging, make sure to tag the merge commit with `2.3.6`.
=> Prepare release 2.3.6

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml, src/openforms/__init__.py
There is no new SDK version for this release.
After merging, make sure to tag the merge commit with `2.2.8`.
=> Prepare release 2.2.8

src/openforms/formio/rendering/default.py, src/openforms/submissions/tests/renderer/test_management_command_cli_render.py, src/openforms/submissions/tests/renderer/test_submission_summary.py
Fixes #3778 
Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/635
=> [#3778] Render empty label for content component

package-lock.json, package.json, src/openforms/js/components/form/cosign.js
Part of #3616.
The zod validation schema only allows `""`, `undefined` or a correct time `HH:mm`.
I'm not sure about the solution here, because this part is also used by the legacy builder. Will it break with this change? Otherwise `null` could also be supported as a value in the zod schema.
=> [#3616] Fix default value for cosign

src/openforms/forms/models/form_definition.py
=> [#3798] Remove unused `get_absolute_url` for form definitions

src/openforms/contrib/brp/migrations/0003_copy_config_to_haalcentraal.py
Fixes typo
Taiga dimpact-enschede-ssc-ict-1 issue 43
=> :pencil2: replace .config() with .save() (2.4.x)

src/openforms/contrib/brp/migrations/0003_copy_config_to_haalcentraal.py
Fixes typo
Taiga dimpact-enschede-ssc-ict-1 issue 43
Backport in:
- 2.5.x: https://github.com/open-formulieren/open-forms/pull/3830
- 2.4.x: https://github.com/open-formulieren/open-forms/pull/3828
=> :pencil2: replace .config() with .save() (master)

src/openforms/contrib/brp/migrations/0003_copy_config_to_haalcentraal.py
Fixes typo
Taiga dimpact-enschede-ssc-ict-1 issue 43
=> :pencil2: replace .config() with .save() (2.5.x)

src/openapi.yaml, src/openforms/forms/api/parsers.py, src/openforms/forms/api/serializers/logic/action_serializers.py, src/openforms/forms/api/viewsets.py, src/openforms/forms/tests/test_api_form_logic_bulk.py, src/openforms/submissions/logic/actions.py, src/openforms/submissions/tests/form_logic/test_modify_variables.py
=> [#3730] Part 1.1 - Things I forgot in the backend

src/openforms/registrations/contrib/objects_api/migrations/0011_create_objecttypesypes_service_from_url.py, src/openforms/registrations/contrib/objects_api/tests/test_migrations.py
=> [#3856] Fix default auth type of autocreated objecttypes client

src/openforms/formio/components/np_family_members/stuf_bg.py, src/openforms/formio/components/np_family_members/tests/responses/stuf_bg_one_partner.xml, src/openforms/formio/components/np_family_members/tests/test_family_members.py, src/stuf/stuf_bg/client.py
Fixes #3864
I think it would be nice to get a more robust solution for xml parsing. OIP uses https://github.com/tefra/xsdata which looks great. https://github.com/dapper91/pydantic-xml looks interesting as well
=> [#3864] Fix handling of StufBG responses with one partner

requirements/dev.in, requirements/dev.txt, src/openforms/conf/dev.py
Part of #3049
* Drop ddt-api-calls toolbar panel
* Upgrade django-debug-toolbar itself to a version that supports both 3.2 and 4.2
* Removed obsoleted settings/configuration
=> Django 4.2 upgrade preparations - debug toolbar changes

src/openapi.yaml, src/openforms/registrations/api/urls.py, src/openforms/registrations/contrib/objects_api/api/serializers.py, src/openforms/registrations/contrib/objects_api/api/urls.py, src/openforms/registrations/contrib/objects_api/api/views.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_list_objecttype_verions_unknown_objecttype.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_list_objecttype_versions.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypeVersionsAPIEndpointsTests/ObjecttypeVersionsAPIEndpointsTests.test_staff_user_required.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesAPIEndpointsTests/ObjecttypesAPIEndpointsTests.test_list_objecttypes.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesAPIEndpointsTests/ObjecttypesAPIEndpointsTests.test_staff_user_required.yaml, src/openforms/registrations/contrib/objects_api/tests/test_api_endpoints.py
Part of #3688
To be resolved:
- https://github.com/open-formulieren/open-forms/pull/3847#discussion_r1483237637
=> [#3688] Phase 1 - Add Objecttypes API endpoints

src/csp_post_processor/processor.py, src/openforms/prefill/contrib/demo/plugin.py, src/openforms/registrations/contrib/microsoft_graph/tests/test_backend.py, src/openforms/tests/test_csp.py
Commits cherry-picked from #3746
These should work on Django 3.2 still/too, but make the actual 4.2 upgrade PR smaller.
=> Django 4.2 upgrade fixes

requirements/ci.txt, requirements/dev.txt, src/openforms/payments/tests/factories.py, src/openforms/submissions/tests/factories.py
Part of #3049
3.0 didn't officially support django 3.2 even. 3.3 explicitly provides support up until django 4.1, but likely 4.2 will also work.
This could potentially address some aspects of fd0c764c15312d07edae1d63ef129a41eb608148
=> Bump to the latest factory-boy version

package-lock.json, package.json
This one drops the dependency on lodash entirely, resolving some open @dependabot alerts
=> :arrow_up: Bump to latest design-token-editor

src/openforms/contrib/objects_api/clients/__init__.py, src/openforms/contrib/objects_api/clients/objects.py, src/openforms/contrib/objects_api/clients/objecttypes.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesClientTest/ObjecttypesClientTest.test_list_objecttype_version.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesClientTest/ObjecttypesClientTest.test_list_objecttypes.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjecttypesClientTest/ObjecttypesClientTest.test_list_objectypes_pagination.yaml, src/openforms/registrations/contrib/objects_api/tests/test_objecttypes_client.py
Supersedes https://github.com/open-formulieren/open-forms/pull/3847
=> [#3688] Implement Objecttypes client

docs/conf.py
Default is 1. This might help with the docs test failures
=> Increase the number of docs linkcheck retries

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
`pkg_resources` still gets imported at startup, I will try to figure out where so that it can be reduced. Current import graph:
---
- I also made a PR @ `weasyprint` to reduce the import time by 0.4s, hopefully will get accepted.
- `O365` takes 0.2s because of `bs4`. One solution would be to import the module in the client class instead of at the module level
=> Upgrade dependencies to lower startup time

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Closes #1052
The final dependency (django-camunda) will be upgraded through #3886, which results in us only using defusedxml to defuse the standard library. This is still necessary because xmltodict uses xml.sax/expat as it only supports `defusedexpat` rather than `defusedxml`.
=> Remove defusedxml.lxml usage from dependencies

src/openforms/js/components/admin/form_design/registrations/index.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiSummaryHandler.js, src/openforms/js/components/admin/form_design/story-decorators.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummary.js, src/openforms/js/components/admin/form_design/variables/registration/index.js
=> [#3688] Add a new registration column in variables with summary

src/openforms/conf/ci.py, src/openforms/submissions/tests/test_models.py
weasyprint can take some extra time loading fonts when special characters need to be rendered. This isn't a big concern as realistically users will not create forms with such characters
=> ✅ Import weasyprint early and increase hypothesis deadline

src/openforms/api/fields.py, src/openforms/formio/api/fields.py, src/openforms/forms/api/serializers/logic/action_serializers.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/tests/test_serializer.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/tests/search_strategies.py
Part of #3688
This is the backend companion of https://github.com/open-formulieren/open-forms/pull/3861.
This will require validation for the mapping in the future
=> [#3688] Adapt registration options serializer

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openapi.yaml, src/openforms/dmn/api/constants.py, src/openforms/dmn/api/serializers.py, src/openforms/dmn/api/urls.py, src/openforms/dmn/api/views.py, src/openforms/dmn/base.py, src/openforms/dmn/contrib/camunda/plugin.py, src/openforms/dmn/contrib/camunda/tests/test_plugin.py, src/openforms/dmn/tests/test_api.py, src/openforms/dmn/tests/test_management_commands.py, src/openforms/dmn/tests/test_registry.py, src/openforms/dmn/types.py
Fixes #3855 (partially)
Backend part to get input/output "variables" from DMN decision definitions
=> [#3855] Retrieve variables from decision definitions

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/constants.js, src/openforms/js/components/admin/form_design/registrations/index.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectTypeSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectTypeVersionSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsForm.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.mdx, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/hooks.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Part of #3688.
To be resolved:
- https://github.com/open-formulieren/open-forms/pull/3847#discussion_r1483191636
- https://github.com/open-formulieren/open-forms/pull/3847#discussion_r1483222824
I'm having an issue right now: as the selects are now required, a default objecttype gets selected as soon as the page loads. However, it does not trigger the `useAsync` for versions, resulting in an empty dropdown for versions.
=> [#3688] Update Objects API registration options form

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Updated celery and its dependencies. `django-yubin` is currently blocking the latest Updated `django-timeline-logger`, should remove the `pkg_resources` startup import
=> Update some dependencies

src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js, src/openforms/scss/components/builder/_builder.scss
Fixes #3855 
Maybe the plugin ID field should be kept out of the boundary so that the user can select a different plugin in case of errors. Or they can just create a new action and delete the one with errors?
=> [#3855] Catch errors when DMN plugin is not working

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/registrations/contrib/objects_api/json_schema.py, src/openforms/registrations/contrib/objects_api/tests/test_json_schema.py
Part of #3688.
The end goal with this will be to iterate over this `iter_json_schema` generator, and compare[^1] each sub JSON Schema to the one from the form variable. If it matches, we keep the path as a valid one to be displayed in the UI.
[^1]: This is yet to be defined: a `as_json_schema` property/method could be defined on the `FormVariable` model along with a function that gets this form variable schema and the sub one from the iter function and returns a boolean, or a `def is_compatible_with_json_schema(self, json_schema) -> bool` function that handles everything.
=> [#3688] Add utility function to iter over JSON schema

docs/configuration/general/oidc.rst, docs/installation/config.rst, src/openforms/accounts/tests/test_hijacking.py, src/openforms/accounts/tests/test_oidc.py, src/openforms/accounts/tests/test_user_preferences.py, src/openforms/admin/tests/test_admin_login.py, src/openforms/admin/urls.py, src/openforms/admin/views.py, src/openforms/conf/base.py, src/openforms/emails/tests/test_check_email.py, src/openforms/submissions/tests/test_attachment_download_view.py, src/openforms/tests/e2e/base.py, src/openforms/utils/tests/test_urls.py
Closes #3695
* Added & documented setting to automatically do OIDC authenticate endpoint redirect
* Broke up classic username/password login screen to use different URL
* `/admin/login/` now redirects to either classic login or OIDC provider depending on value of setting
=> Add setting & support redirecting to OpenID Connect identity provider

src/openforms/conf/base.py
From: https://github.com/maykinmedia/open-inwoner/pull/1053#discussion_r1503072563
=> :lock: Obfuscate incorrect password in Axes logs

src/openforms/registrations/contrib/objects_api/json_schema.py, src/openforms/registrations/contrib/objects_api/tests/test_json_schema.py
Part of #3688
- `type` can be an array
- Exception when trying to iterate over a reference which points to a non-`object` sub schema
=> [#3688] Fix some edge cases when parsing JSON Schemas

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/formio_builder/WebformBuilder.js
Closes #3921
Needs backporting to 2.5.x, but not earlier.
=> Fix incorrect components context in component select dropdowns

src/openforms/contrib/objects_api/helpers.py, src/openforms/contrib/zgw/clients/documenten.py, src/openforms/contrib/zgw/clients/utils.py, src/openforms/contrib/zgw/clients/zaken.py, src/openforms/registrations/contrib/objects_api/models.py, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/registrations/contrib/objects_api/tests/test_utils.py, src/openforms/registrations/contrib/objects_api/typing.py, src/openforms/registrations/contrib/objects_api/utils.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/utils/date.py
Part of #3688.
This PR refactors the Objects API registration backend to split the registration logic depending on whether the registration options are v1 (legacy way, with the JSON templates) or v2 (with variables mapped individually):
- Added a `typing` module to provide TypedDicts for the options.
- Moved all the business logic in the `register_submission` method to the `submission_registration` module. A `Protocol` is defined, and an implementation for the V1 logic is provided (V2 is for another PR). This protocol is responsible for providing the object data JSON payload to be sent to the API. The `ObjectsAPIV1Handler` implements this protocol for V1, and all the utility functions that where in the plugin module are now set as staticmethods for clarity (i.e. to do some "namespacing"). …
=> [#3688] Refactor Objects API plugin to allow for v2

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/Context.js, src/openforms/js/components/admin/form_design/constants.js, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/form_design/registrations/index.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectTypeSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectTypeVersionSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.mdx, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiSummaryHandler.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.js, src/openforms/js/components/admin/form_design/story-decorators.js, src/openforms/js/components/admin/form_design/variables/StaticData.js, src/openforms/js/components/admin/form_design/variables/UserDefinedVariables.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummary.js, src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js, src/openforms/js/components/admin/form_design/variables/registration/index.js, src/openforms/js/components/admin/forms/Select.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Part of #3688
Relies on https://github.com/open-formulieren/open-forms/pull/3925 for the API request.
This PR builds on top of a previous one, where the "registration summary" was displayed, but nothing would happen when you tried editing the configuration:
To do so, the `RegistrationSummary` component (responsible for displaying the summary shown above) was tweaked to display a `FormModal`. Inside this modal:
- the variable configuration editor is rendered in a generic way (the `RegistrationSummary` doesn't know anything about it). This will allow other registration backends to provide their own edit form in the future.
- a submit button that will update the options of the matching reg. backend.
- this modal makes use of a Formik form, and the actual configuration editor form can make …
=> [#3688] Add implementation of the Objects API mapping editor

src/openforms/authentication/static_variables/static_variables.py
Now globally ignored in `setup.cfg`, thanks to https://github.com/open-formulieren/open-forms/pull/3742
=> Remove unused pragma comment

src/openforms/formio/components/custom.py, src/openforms/formio/components/vanilla.py, src/openforms/formio/registry.py, src/openforms/formio/serializers.py, src/openforms/formio/service.py, src/openforms/formio/tests/search_strategies.py, src/openforms/formio/tests/test_search_strategies.py, src/openforms/formio/tests/test_validation.py, src/openforms/formio/tests/validation/helpers.py, src/openforms/formio/tests/validation/test_bsn.py, src/openforms/formio/tests/validation/test_date.py, src/openforms/formio/tests/validation/test_editgrid.py, src/openforms/formio/tests/validation/test_email.py, src/openforms/formio/tests/validation/test_generic.py, src/openforms/formio/tests/validation/test_number.py, src/openforms/formio/tests/validation/test_phonenumber.py, src/openforms/formio/tests/validation/test_textfield.py, src/openforms/formio/utils.py
Partly closes #3977
This PR implements the conversion layer from a formio form definition (as a sequence of components) to a DRF serializer, where each component is translated into a serializer field (or nested serializer).
Each field is then capable/responsible of validating the user input, effectively running the formio validation server-side.
A future PR will be hook this up into our submissions/appointment serializers.
=> Implement formio form-to-serializer translation

src/openforms/forms/api/viewsets.py, src/openforms/forms/tasks.py, src/openforms/forms/tests/variables/test_tasks.py
=> [#3881] Update variables in reusable form definitions

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/validation/test_textfield.py, src/openforms/tests/e2e/input_validation_base.py, src/openforms/tests/e2e/test_input_validation.py
Closes #3977
Depends on #4010
Adds tests to lock in the parity between frontend and backend behaviour.
=> End to end tests for input validation

src/openforms/submissions/api/validation.py, src/openforms/tests/e2e/test_input_validation.py
Part of #3977
Part of #72 
So that the plugin validators can run in the context of the provided submission and not crash.
=> :sparkles: [#3977] Add submission context to formio data serializer

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Closes #3931
This drops the dependency on PyOpenSSL on our end
=> Upgrade to django-simple-certmanager 2.0.0

docker/docker-compose.objects-apis.yml, docker/docker-compose.open-zaak.yml, docker/objects-apis/fixtures/objects_api_fixtures.json, docker/objects-apis/fixtures/objecttypes_api_fixtures.json, docker/open-zaak/README.md, docker/open-zaak/docker-init-open-zaak-db/0001-docker-init-open-zaak-db.sql, docker/open-zaak/docker-init-open-zaak-db/0002-extensions.sh, docker/open-zaak/fixtures/open_zaak_fixtures.json, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_submission_with_objects_api_v2.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/registrations/contrib/objects_api/typing.py, src/openforms/variables/static_variables/static_variables.py
Part of #3688.
frontend part:
- https://github.com/open-formulieren/open-forms/pull/3988
Reminder on the current flow:
When a submission gets registered in the Objects API plugin:
- `ObjectsAPIRegistration.register_submission` is called
- Depending on the version (v1 or v2) of the options, a specific handler is instantiated
- `handler.save_registration_data` is called (same method for v1 and v2). This creates the documents in the Documents API, and save the urls in a temporary `ObjectsAPIRegistrationData` model.
- `handler.get_object_data` is called to get the payload sent to the Objects API. The v1 renders the JSON template, the v2 creates the object from the mapping (this is what this PR implements)
- Payload is sent to the Objects API
=> [#3688] Add base logic to register submission with v2 options

src/openforms/js/components/admin/forms/ActionButton.js, src/openforms/js/components/admin/forms/ActionButton.mdx, src/openforms/js/components/admin/forms/ActionButton.stories.js, src/openforms/js/components/admin/forms/SubmitRow.js
Closes #4000
Checked that this was not used in other screens - all other SubmitRow usage explicitly specifies the children so this button is effectively unused.
This only affects the React code, the standard Django pages remain unchanged.
=> Delete the 'save and add another' button

src/openforms/registrations/base.py, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIPaymentStatusUpdateV2Tests/ObjectsAPIPaymentStatusUpdateV2Tests.test_update_payment_status.yaml, src/openforms/registrations/contrib/objects_api/tests/test_update_payment_status_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_update_payment_status_v2.py
Part of #3688, https://github.com/open-formulieren/open-forms/issues/4019
=> Handle payment status updates

package-lock.json, package.json
Closes #3943
Closes open-formulieren/open-forms-sdk#483
This release contains the necessary fixes/features for the related tickets.
=> :arrow_up: Bump to formio-builder 0.18.0

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
=> [#4019] Mapping file uploads in Object API registration (frontend)

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/typing.py
=> [#3688] Remove `productaanvraagType` for v2 options

docker/docker-compose.open-zaak.yml, docker/objects-apis/fixtures/objects_api_fixtures.json, docker/objects-apis/fixtures/objecttypes_api_fixtures.json, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_submission_with_map_component_inside_data.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py
=> Handle map components (point coordinates) consistently.

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js
Part of #4031.
This was discussed at some point but forgot about it
=> [#4031] Add a confirm popup when switching to v2 options

src/openforms/conf/base.py, src/openforms/conf/dev.py, src/openforms/conf/local_example.py, src/openforms/conf/utils.py, src/openforms/registrations/tests/test_pre_registration.py, src/openforms/registrations/tests/test_registration_hook.py, src/openforms/submissions/tests/test_post_submission_event.py, src/openforms/utils/tests/logging.py
My console was littered with distracting log output from exceptions here and there. I managed to trace down the root cause to:
* missing root logger configuration
* the `dev.py` settings adding additional loggers that are not present in `ci.py` (nor `base.py`)
For this I did some clean up/added some helpers:
* Remove the unused performance logging
* Rely on the standard envvar mechanism to set the `handler` in dev to file or console output (`LOG_STDOUT` setting)
* Tweaked the log levels a bit for loggers that are too chatty (DEBUG -> INFO)
* Updated local example to mute logging locally entirely.
=> Fixed log output suppression when running tests locally

src/openforms/submissions/api/validation.py, src/openforms/tests/e2e/test_input_validation_regressions.py
Closes #4068
Another case that was missed
=> Don't validate step that is not applicable

src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js
=> [#4069] Fix crash when using some registration backends

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml, src/openforms/__init__.py
https://www.youtube.com/watch?v=mOn5vUQo-PU
=> Hotfix release 2.6.1

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/formio_builder/WebformBuilder.js
=>  [#4061] Use the right attribute for components array 

src/openforms/formio/registry.py, src/openforms/formio/serializers.py, src/openforms/formio/tests/validation/test_content.py, src/openforms/formio/tests/validation/test_editgrid.py, src/openforms/formio/tests/validation/test_generic.py
Reported by Bob, thanks :pray:
=> Fix another validation mismatch

INSTALL.rst, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/admin/urls.py, src/openforms/api/urls.py
This is an experiment to see which dependencies relies on `pkg_resources` and does not use `setuptools` as a dependency. In Python 3.12, `setuptools` is no longer installed by default in venvs, and people used to rely on that to use `pkg_resources` (installed along with `setuptools`) to get the version of a package. By updating the last dependencies that used to rely on this (`django-axes` and `josepy`), setuptools will no longer be present, and I can then see what packages fail:
=> ⬆️ Update dependencies to drop `setuptools`

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openapi.yaml, src/openforms/authentication/api/serializers.py, src/openforms/authentication/api/tests/test_endpoints.py, src/openforms/authentication/base.py, src/openforms/authentication/contrib/digid/plugin.py, src/openforms/authentication/contrib/eherkenning/plugin.py, src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py, src/openforms/authentication/contrib/eherkenning/urls.py, src/openforms/authentication/contrib/eherkenning/views.py, src/openforms/js/components/admin/form_design/FormConfigurationFields.js, src/openforms/js/components/admin/form_design/authentication/LoAOverrideOption.js, src/openforms/js/components/admin/form_design/authentication/LoAOverrideOption.mdx, src/openforms/js/components/admin/form_design/authentication/LoAOverrideOption.stories.js, src/openforms/js/components/admin/form_design/types/AuthPlugin.js
Fixes #3969 (partially, needs also the changes here: https://github.com/maykinmedia/django-digid-eherkenning/pull/65)
=> [#3969] Remove ability to override LoA for eHekrenning/eIDAS

src/openforms/conf/ci.py
CI is showing irrelevant logs, making it harder to debug actual test failures.
=> :mute: Mute logging during test runs in CI

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
Closes #4079
The patch is in our fork of python3-saml - this now uses `requests` to retrieve the metadata instead of `urllib.request`.
=> Bump to maykin-python3-saml patch release

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt
django-digid-eherkenning bump is required because of the updated maykin-python3-saml version which contains a necessary bugfix.
Backport-of: #4087
=> Bump maykin-python3-saml and django-digid-eherkenning

src/openforms/appointments/renderer.py, src/openforms/appointments/tests/test_pdf.py
Closes #4103
Appointment details were being retrieved using our internal database primary key, but that looks up records from the appointment system that are unlikely to match with the actual appointment ID recorded for a given appointment.
=> Use the plugin appointment ID instead of our internal DB pk

src/openforms/js/components/admin/form_design/registrations/userDefinedVariableEditHandlers.js
=> [#4099] Fix crash when using legacy Objects API registration

src/openforms/submissions/admin.py, src/openforms/submissions/tasks/pdf.py, src/openforms/submissions/tests/test_tasks_pdf.py
=> [#4005] Filter submission reports

src/openforms/submissions/form_logic.py, src/openforms/tests/e2e/test_input_validation_regressions.py
Taiga DH 671
~~If the test suite passes first try I'm eating my shoe.~~
Needs backport to stable/2.6.x
=> Fix validation issue with (dynamically) optional field

src/openforms/formio/formatters/tests/test_kitchensink.py, src/openforms/registrations/contrib/camunda/plugin.py, src/openforms/registrations/contrib/microsoft_graph/plugin.py, src/openforms/submissions/admin.py, src/openforms/submissions/mapping.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/templates/admin/submissions/submission/change_form.html, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/test_admin.py, src/openforms/submissions/tests/test_factories.py, src/openforms/submissions/tests/test_models.py
Fixes #4009, #979.
As said in the issue, I'm not able to reproduce the sdk rendering bug anymore on latest.
This PR can safely be reviewed commit per commit.
=> [#4009] Clean up usage of merged data

src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py
Closes #3890
Follow up of the patch for #3890
=> Fix Objects API JSON data for missing values

src/openforms/formio/components/vanilla.py, src/openforms/formio/serializers.py, src/openforms/formio/tests/validation/test_editgrid.py
Closes #4126
Simple conditionals which run as client-side logic are supported (not deliberatey, but here we are...) for edit grids (aka repeating groups). This works fine in the client side since the Formio.js SDK takes care of it (in some questionable ways, but it works...). Components with validation requirements don't trigger errors, because when they are hidden, all validations are ignored.
However, the backend created a simple `serializers.ListField(...)` for edit grids, with a child/nested serializer derived from the "blueprint" of nested components, which cannot take into account the show/hide-and-drop-validations behaviour. This is because the `child` instance is re-used to run the validation for each item in the data, and the nested serializer field configuration depends on the …
=> Apply client-side show/hide logic in nested components during editgrid validation

src/openforms/conf/base.py, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py
Closes #4140
Enabling the envvar DISABLE_SENDING_HIDDEN_FIELDS opts out of the bugfix that sends hidden fields to the objects API registration backend, restoring the old (but broken) behaviour. This buys organizations time to update their json schemas.
This fix will only be present in Open Forms 2.6.3+, newer versions enforce the earlier bugfix behaviour.
=> Disable sending hidden fields to objects API

src/openforms/forms/admin/form.py, src/openforms/js/components/admin/form_design/FormObjectTools.js, src/openforms/js/components/admin/form_design/form-creation-form.js
Fixes #4101
Using `pointer-events: none;` prevents `title` from showing on hoover, and using a top level `span` element with a `title` didn't help either :/
=> [#4101] Disable "Show form" button if form not active

src/openforms/formio/components/custom.py, src/openforms/formio/tests/validation/test_date.py, src/openforms/formio/typing/dates.py, src/openforms/utils/date.py
Fixes #4172
Requires a patch in the SDK too for the fixed value validation, but the existing PR will be split for that.
=> Fix date validation crash

src/openforms/forms/tasks.py, src/openforms/registrations/contrib/stuf_zds/plugin.py
Follow up https://github.com/open-formulieren/open-forms/pull/4211:
- The form logevent is an actual bug, but not that big of a deal so not really worth a test
- The zds registration is actually fine (as the callback gets called immediately afterwards) but let's stick to the best practice
=> Fix late `lambda` binding bugs

src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
=> [#4191] Add missing required `aoaIdentificatie` field to ZGW registration

src/stuf/models.py, src/stuf/service_client_factory.py, src/stuf/stuf_zds/tests/test_client.py
=> [#4146] Apply soap timeout for Stuf-ZDS client

src/openforms/submissions/attachments.py, src/openforms/submissions/tests/test_submission_attachment.py
Fixes #4197.
I got curious and saw that `ruff check --select B023 src/` ([doc](https://docs.astral.sh/ruff/rules/function-uses-loop-variable/)) caught this issue and a couple more, so I'll provide a follow up PR with more fixes.
=> [#4197] Fix late binding bug when resizing multiple images

src/openforms/conf/base.py
Closes #4215 
**Changes**
* Add delete_old_emails task to celery beat schedule
**Checklist**
=> :sparkles: [#4215] Add delete_old_emails task to celery beat schedule

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
No ticket reference, just cleaning up so our checklist below makes sense :)
**Changes**
Ran `./bin/makemessages.sh` and `./bin/compilemessages_js.sh`
**Checklist**
=> :globe_with_meridians: Re-generate translation catalogs

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/formio/components/custom.py, src/openforms/formio/tests/validation/test_iban.py, src/openforms/tests/e2e/test_input_validation.py, src/openforms/utils/tests/test_validators.py, src/openforms/utils/validators.py
=> [#72] Add backend validation for iban component

src/openforms/formio/components/custom.py, src/openforms/formio/tests/validation/test_licenseplate.py, src/openforms/tests/e2e/test_input_validation.py
=> [#72] Add backend validation for licenseplate component

src/openforms/formio/datastructures.py, src/openforms/formio/migration_converters.py, src/openforms/formio/tests/test_datastructures.py, src/openforms/formio/tests/test_simple_conditionals_converter.py, src/openforms/formio/typing/__init__.py, src/openforms/formio/typing/base.py, src/openforms/formio/utils.py, src/openforms/forms/tests/test_import_export.py
Closes #4247
**Changes**
* Added regression test
* Added some more type defs for Formio data structures (less squigly lines in my editor..., I may end up regretting this)
* Fixed/added edit grid namespacing in the component map so that these lookups work as expected
This only makes it possibly to process form configurations, data handling (and consequently server-side `is_visible_in_frontend` for components inside repeating groups) is still not solved, nor is server-side logic actions to target individual items inside a repeating group.
**Checklist**
=> Fix migration crash because of particular key-structure with repeating groups

src/openforms/conf/base.py
**Changes**
Since zgw-consumers 0.32.0, the OAS fields are not used anymore by the library. They can be removed from the UI through a setting before being dropped entirely.
**Checklist**
=> :sparkles: Hide OAS fields in zgw consumers admin

src/openforms/contrib/kvk/tests/files/vcr_cassettes/KvKRemoteValidatorTestCase/KvKRemoteValidatorTestCase.test_branchNumber_validator.yaml, src/openforms/contrib/kvk/tests/files/vcr_cassettes/KvKRemoteValidatorTestCase/KvKRemoteValidatorTestCase.test_kvkNumber_validator.yaml, src/openforms/contrib/kvk/tests/files/vcr_cassettes/KvKRemoteValidatorTestCase/KvKRemoteValidatorTestCase.test_rsin_validator.yaml, src/openforms/contrib/kvk/tests/test_validators.py, src/openforms/contrib/kvk/validators.py
Closes #4229 
**Changes**
* Cache the result of KVK search in the KVKRemoteValidatorMixin
* Add missing VCR cassette for valid RSIN
**Checklist**
=> :zap: [#4229] Cache KVKRemoteValidator result to speed up validation

.git-blame-ignore-revs, CHANGELOG.rst, docs/archive/changes-v1.rst, docs/archive/changes-v2.rst, docs/conf.py
**Changes**
So that it's easier to go back to the issue from the changelog entries. Also added extlinks for CVEs/GHSAs
**Checklist**
=> Use extlinks in docs for issue numbers

src/digid_eherkenning_oidc_generics/__init__.py, src/digid_eherkenning_oidc_generics/digid_machtigen_settings.py, src/digid_eherkenning_oidc_generics/digid_settings.py, src/digid_eherkenning_oidc_generics/eherkenning_bewindvoering_settings.py, src/digid_eherkenning_oidc_generics/eherkenning_settings.py, src/digid_eherkenning_oidc_generics/exceptions.py, src/digid_eherkenning_oidc_generics/mixins.py, src/digid_eherkenning_oidc_generics/models.py, src/digid_eherkenning_oidc_generics/utils.py, src/digid_eherkenning_oidc_generics/views.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/digid_machtigen_urls.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/digid_urls.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/eherkenning_bewindvoering_urls.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/eherkenning_urls.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/digid_machtigen/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/tests/eherkenning_bewindvoering/test_auth_procedure.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/views.py, src/openforms/authentication/tests/utils.py, src/openforms/conf/locale/nl/LC_MESSAGES/django.po
Closes #4246 partly
**Changes**
**Checklist**
=> Refactor OIDC integration for DigiD/eHerkenning - init flow

src/openforms/config/checks.py, src/openforms/config/views.py
Fixes #4280
**Changes**
- Configuration check was tied to `ConfigurationView`, now we have a separate class which can be used in possible future checks outside a view.
=> Move configuration check into its own class

src/openforms/js/lang/formio/en.json, src/openforms/js/lang/formio/nl.json
Also remove unused Dutch translations
Closes #4158
**Changes**
`invalid_time` is not defined by Formio, so the missing English translation would result in the bare key being displayed
**Checklist**
=> [#4158] Add missing English translation for `invalid_time`

src/openforms/appointments/admin.py
No ticket, I noticed this when I was debugging something and just found out I have a spare branch lying around.
**Changes**
* Optimized admin for `ApointmentInfo` model.
* Improved being able to find a particular appointment info record with some search fields.
**Checklist**
=> Add missing search fields and optimization to appointment info admin

docs/manual/templates.rst, src/openforms/authentication/service.py, src/openforms/authentication/signals.py, src/openforms/authentication/tests/test_signals.py, src/openforms/authentication/typing.py, src/openforms/authentication/utils.py, src/openforms/registrations/contrib/objects_api/registration_variables.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/submissions/api/serializers.py
Closes #4302
**Changes**
Still needs legacy Objects API registration support
Adds the necessary registration variables.
As I had to explore a bit the cosign flow (both legacy and new), noticed that the `co_sign_data` field seems to have a validator incompatible with the new cosign flow:
https://github.com/open-formulieren/open-forms/blob/e780ea782eb2264dc63cf33dd19c67d57a7a15c2/src/openforms/submissions/models/submission.py#L124-L130
`CosignDataSerializer` is defined as:
https://github.com/open-formulieren/open-forms/blob/e780ea782eb2264dc63cf33dd19c67d57a7a15c2/src/openforms/submissions/serializers.py#L12-L22
But the new flow sets this data from the auth plugin data directly:
https://github.com/open-formulieren/open-forms/blob/e780ea782eb2264dc63cf33dd19c67d57a7a15c2/src/openforms/authent …
=>  [#4302] Add cosign information for Objects API registration 

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/emails/digest.py, src/openforms/emails/tasks.py, src/openforms/emails/templates/emails/admin_digest.html, src/openforms/emails/tests/test_digest_functions.py, src/openforms/emails/tests/test_tasks_integration.py, src/openforms/logging/logevent.py, src/openforms/utils/json_logic/datastructures.py, src/openforms/utils/json_logic/introspection.py
=> [#3725] Add invalid forms (configuration and logic rules) to the email digest

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/tests/test_import_export.py, src/openforms/forms/utils.py
Closes #1906
**Changes**
- Added regression tests for import and export with a file component as an input
- Removed the dynamic rewrite_formio_components from the export flow as we don't care about the request at this point
**Checklist**
=> [#1906] Fix duplicate form definitions after importing a form

requirements/ci.txt, requirements/dev.txt, src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/formio/components/custom.py, src/openforms/formio/tests/validation/test_datetime.py, src/openforms/tests/e2e/test_input_validation.py
Partly closes #72
**Changes**
Added serializer field for min/max datetime validation of formio datetime components.
**Checklist**
=> Implement backend validation for formio datetime component

bin/report_radio_invalid_default_values.py
Closes #4262
**Changes**
- Added a script for detecting invalid default values in radio components
**Checklist**
=> [#4262] Fix invalid default values in radio component

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/config/checks.py, src/openforms/formio/utils.py
**Changes**
Apart from here:
https://github.com/open-formulieren/open-forms/blob/53a8c845fbf6aced041a2370951a0553c5e3938c/src/openforms/appointments/models.py#L87-L88
It is safe to use `TypeIs` for the other cases.
(Separate PR as I'll need it for another one)
**Checklist**
=> ⬆️ Update `typing-extensions` to `4.11.0`

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/emails/digest.py, src/openforms/emails/tests/test_tasks_integration.py, src/openforms/submissions/utils.py
Closes #4298
- Handle empty labels in certificates
- Replace admin links with the absolute ones
**Checklist**
=> [#4298] Broken admin links and certificate label in email digest

src/openforms/scss/pdfs/_submission-step-row.scss
Turns out that flexbox was the problem here (also mentioned at the end of this comment https://github.com/Kozea/WeasyPrint/issues/578#issuecomment-1058889147). I didn't want to use floats, but all the alternatives I tried were just as slow :disappointed:.
For comparison, this is what a PDF currently looks like if I enter 3500 characters in the textarea (takes about a minute to render locally, if I double the characters it exceeds the maximum): 
[original.pdf](https://github.com/open-formulieren/open-forms/files/15433138/original.pdf). I'm not sure if it's intentional that the first page does not contain any of the steps yet, but I could change that as well if needed
This is what it looks like after these CSS changes (takes about 2-3 seconds to render): …
=> :zap: [#4255] Speed up PDF generation by replacing flexbox with float

src/openforms/formio/rendering/nodes.py, src/openforms/formio/serializers.py, src/openforms/formio/tests/validation/test_fieldset.py, src/openforms/formio/utils.py, src/openforms/forms/models/form_variable.py
Closes #4241 
**Changes**
* Fix validation of field with nested key in fieldset
**Checklist**
=> 🐛 [#4241] Fix validation of field with nested key in fieldset

src/openforms/js/components/formio_builder/WebformBuilder.js
Closes #4012 
**Changes**
* remove the ckeditor node after closing the formbuilder editcomponent modal
**Checklist**
=> :bug: [#4012] Fix content component link popup in form builder

docs/manual/forms/examples/camunda7.rst, docs/manual/forms/index.rst, docs/manual/forms/logic.rst, docs/manual/forms/logic_dmn.rst, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Closes #4294
**Changes**
* Added overview of DMN action configuration
* Added warning about boolean values and requirement for checkbox components
**Checklist**
=> Add manual/documentation for DMN-evaluation actions

src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
Closes #4337 
**Changes**
* Use form name in ZGW registration Zaak.omschrijving
**Checklist**
=> ✨ [#4337] Use form name in ZGW registration Zaak.omschrijving

src/openforms/appointments/contrib/jcc/tests/mock/getGovAppointmentDetailsEmptyResponse.xml, src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py
Closes #598
**Changes**
* Add unit tests for appointments failure flow
**Checklist**
=> :white_check_mark: [#598] Add unit tests for appointments failure flow

src/openforms/js/components/admin/index.js, src/openforms/js/components/admin/login.js, src/openforms/scss/admin/_app_overrides.scss, src/openforms/templates/maykin_2fa/login.html
Closes #4347
**Changes**
Hides the form when OIDC is disabled. Note that this is not the best code, but it shows the intent of what I want. It has 2 aspects: 1) nicer and better visible -or-, 2) less nudge towards form login
**Checklist**
=> Nudge people to the organisation login if OIDC enabled.

src/openforms/conf/base.py, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py
Closes #4323
**Changes**
-  Added flag for disabling sending hidden fields to Objects API 
**Checklist**
=> [#4323] Disable sending hidden fields to objects API (v2.7)

src/openforms/contrib/brk/client.py, src/openforms/contrib/brk/tests/files/vcr_cassettes/BRKValidatorTestCase/BRKValidatorTestCase.test_pre_request_hooks_called.yaml, src/openforms/contrib/brk/tests/test_validators.py, src/openforms/contrib/brk/validators.py
Closes #4377
**Changes**
* Added test to check for pre-request context in the BRK client (this is the mechanism used by the token exchange extension)
* Ensure we set up the pre-request context when building a BRK client
**Checklist**
=> Add support for Token Exchange extension to BRK client/validator

bin/report_component_problems.py
Related to #4362
**Changes**
Extended the component problem detection to report on textfield/textarea components that have a translation for `defaultValue`, since it's being removed.
I'm not touching the JS code in this PR to remove the cause of the crash, since the missing translation extraction feature is being removed entirely in a different PR by @vaszig 
**Checklist**
=> Add detection for defaultValue translations

package-lock.json, package.json, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json
Closes #4362
**Changes**
This version removes the support for `defaultValue` translations.
**Checklist**
=> Bump to latest formio builder

src/openforms/formio/components/translations.py, src/openforms/formio/tests/test_component_translations.py, src/openforms/formio/typing/base.py
Closes #4363
**Changes**
- Added description translations of the values for components which support this (selectboxes, radio)
**Checklist**
=> [#4363] Missing translated description from the values of the components

src/openforms/js/components/formio_builder/translation.js
Closes #4362
Textfield and textarea have the multiple: true option, which turns the defaultValue into an array of strings rather than a single string, and that doesn't play well with the translations machinery or missing translation detection.
Open Forms 2.7.0 removes support for translations for this property, and older versions get a hotfix to prevent the crash from happening during detection, where we just don't look at `defaultValue` to extract missing translations.
**Checklist**
=> Prevent crash due to array-value for textfield|textarea defaultValue when multiple is true

src/stuf/stuf_bg/constants.py, src/stuf/stuf_bg/tests/test_client.py
Closes #4338
**Changes**
* Added SOAP 1.2 Envelope namespace to namespace replacements constants
**Checklist**
=> Fix incomplete namespace processing in StUF-BG client

src/openforms/conf/tinymce_config.json, src/openforms/tests/e2e/test_tinymce_configuration.py
Closes #4390
The previous patch (183a08ed7db2fcdabfd16aa595452aee8223166f) fixed the reported behaviour by making all URLs fully qualified, instead of building relative URLs to the admin if the domain happens to be the same.
However, we have some 'URLs' that are template variables and are substituted out by the backend, e.g. '{{ continue_url }}' which got mangled by this patch by taking the current location and using that as the root - the template fragment was being interpreted as a relative URL. This breaks those templates.
This patch addresses both cases by just leaving URLs untouched and doing no conversion at all - relative URLs stay literally that (and if they're template fragments, our backend properly resolves them), while absolute URLs (to another form, for example) that are …
=> :bug: [#4390] Fix URL conversion messing with templates

src/openforms/conf/tinymce_config.json, src/openforms/scss/admin/themes/_dark.scss
Closes #4350
**Changes**
* Disabled link prompt. From #1080 I couldn't find a specific requirement to enable this prompt.
* Noticed a dark-mode style issue and fixed it.
**Checklist**
=> Disable link prompt

src/openforms/submissions/templates/report/submission_report.html
Closes #4409
**Changes**
- Updated payment status text in registration pdf report from "Total amount to be paid" to "Total amount" in order to cover situations where the pdf is generated before the payment status update. 
**Checklist**
=> [#4409] Update payment status text in registration pdf report

.github/workflows/ci.yml, .github/workflows/code_quality.yml, .github/workflows/sb.yml, Dockerfile, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/conf/base.py
Noticed that our test env was down after the lxml/xmlsec upgrade and stumbled on https://github.com/xmlsec/python-xmlsec/issues/320 as the same issue.
The fix is not to downgrade the libraries, but instead manage the environment in which uwsgi is being built better.
=> Fix uwsgi crash on startup

src/openforms/logging/logevent.py, src/openforms/logging/templates/logging/events/payment_flow_start.txt, src/openforms/payments/models.py, src/openforms/payments/services.py, src/openforms/payments/tests/test_models.py, src/openforms/payments/views.py, src/openforms/registrations/contrib/objects_api/registration_variables.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/objects_api/tests/test_update_payment_status_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_utils.py, src/openforms/registrations/tasks.py, src/openforms/registrations/tests/test_registration_hook.py, src/openforms/submissions/tests/factories.py
Closes #4425 
**Changes**
* `payment.amount` is now derived from `submission.price` instead of `SubmissionPayment` record aggregation. The documentation describes this field as being the cost of a submission, not the sum of all payment attempts.
* The submission variable for payment amount is updated accordingly.
* Removed (confusing and dangerous) queryset method to aggregate the total amount in submission payments.
**Checklist**
=> Fix incorrect payment amount being sent to Objects API

src/openforms/contrib/kadaster/api/views.py, src/openforms/contrib/kadaster/clients/bag.py, src/openforms/contrib/kadaster/tests/test_api_address_autocomplete.py, src/openforms/contrib/kadaster/tests/test_bag_client.py, src/openforms/formio/tests/validation/test_addressnl.py
Closes #4430
**Changes**
- Handle empty response from bag client in combination with the backend validation of `secretStreetCity `field
When we had no data from the API call, secretStreetCity was not created and was an empty str, so it couldn't validate with the one that was created in the backend validation. Now, we create one even when no data is returned and this makes backend validation possible.
**Checklist**
=> [#4430] Handle empty response from bag client

docs/manual/templates.rst, src/openforms/authentication/tests/factories.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/templatetags/registrations/contrib/objects_api/json_tags.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py
Partly closes #4246
---
Requires #4421 to be merged first!
---
**Changes**
* Added template variable and generic `as_json` tag
* Documented shape of template var and meaning of the data
**Checklist**
=> Register authentication context data in Objects API (v1 registration)

src/openforms/emails/digest.py, src/openforms/emails/templates/emails/admin_digest.html, src/openforms/emails/tests/test_digest_functions.py, src/openforms/emails/tests/test_tasks_integration.py
Closes #4400
**Changes**
- Added regression tests
- Handle exceptions in broken JSON logic rules
**Checklist**
=> [#4400] Fix email digest concerning invalid JSON logic expressions

package-lock.json, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openapi.yaml, src/openforms/api/tests/test_validators.py, src/openforms/api/urls.py, src/openforms/api/validators.py
django-tinymce upgrade aligns the tinymce versions used in React and the admin, so that's nice. The breaking changes don't appear to affect us (but CI can say otherwise of course).
The DRF upgrade is a YOLO - we'll see what breaks in this PR :grimacing:
=> Bump DRF & tinymce dependencies

src/openforms/forms/tests/e2e_tests/test_registration_backend_conf.py
Webkit seems to make requests to some 'srcdoc' somewhere that we have no idea about... Surpressing it should be fine, but logging it to make the problem more visible in CI seems appropriate.
=> Fix another flaky test when intercepting/spying on API calls

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, src/openforms/conf/base.py
Closes #4435 
**Changes**
* Fix OIDC SessionRefresh middleware
**Checklist**
=> :bug: [#4435] Fix infinite redirect on sessionrefresh for OIDC

src/openforms/scss/pdfs/_submission-step-row.scss
previously, rows could overlap if the field labels were longer more than one line
Closes #4450 
**Changes**
* Fix submission PDF rows overlapping
**Checklist**
=> :bug: [#4450] Fix submission PDF rows overlapping

src/openforms/js/components/admin/login.js, src/openforms/templates/maykin_2fa/login.html
The JS approach to toggle this does not play well with the markup in the library templates, so we need to resort to programmatically clicking the show link. IMO this feature request was rushed and it leads to this kind of fragile code to deal with that fallout from that :/
Closes #4429 
**Changes**
* Added meta-information about login-phase to DOM
* Added JS triggers to toggle visibility depending on meta-information/state of login flow
**Checklist**
=> Keep username/password form/2fa form visible

package-lock.json, package.json, src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json
Closes #4423
**Changes**
- Update formbuilder to v0.23.0 (contains the new layout dropdown for single/double column in the addressNl component)
**Checklist**
=> [#4423] Update form builder to v0.23.0

src/openforms/contrib/zgw/clients/documenten.py, src/openforms/contrib/zgw/service.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py, src/openforms/registrations/contrib/zgw_apis/tests/test_zgw_api_config.py
Closes #4416 (first bullet)
- Added `ontvangstdatum` to the data sent to ObjectsAPI and ZGW
- Tested with both registration backends and the date is sent as expected
**Checklist**
=> [#4416] Add ontvangstdatum attribute for attachments in ZGW and ObjectsAPI backends

src/openforms/api/tests/test_error_format.py, src/openforms/api/views/views.py, src/openforms/authentication/models.py, src/openforms/submissions/tests/test_submission_status.py
Partly closes #4505
**Changes**
* Fixed a bug in the DRF exception handler - `Exception.args` can be empty
* Removed hard `assert` in `AuthInfo.to_auth_context_data`
**Checklist**
=> Fix too-optimistic assert in auth context data calculation

src/openforms/formio/formatters/custom.py, src/openforms/formio/formatters/tests/test_default_formatters.py, src/openforms/tests/e2e/test_input_validation.py
Partly fixes #4505
**Changes**
- Added missing `city` and `streetName` fields to the confirmation pdf
**Checklist**
=> [#4505] Add missing addressNL fields to the confirmation pdf

src/openforms/formio/api/views.py, src/openforms/formio/tests/test_api_fileupload.py, src/openforms/submissions/api/mixins.py, src/openforms/submissions/api/permissions.py, src/openforms/submissions/api/views.py, src/openforms/submissions/constants.py, src/openforms/submissions/tests/mixins.py, src/openforms/submissions/tests/test_temporary_uploads.py, src/openforms/submissions/utils.py
Closes #4492
**Changes**
This is no longer necessary now that we relate the temporary upload to a submission (session) - we can use the submission authorization checks for upload ownership checks.
This removes a source of race conditions, as we have one less array of UUIDs to keep track of in the session, and especially file uploads were susceptible to this when multiple uploads are performed in parallel.
Additionally, it turns out there was more dead code in the permissions (`filter_queryset`) that was never called, and coverage reports also show it never was, so I deleted it too.
**Checklist**
- Commit …
=> Remove storing upload IDs in the session

src/openapi.yaml, src/openforms/submissions/api/permissions.py, src/openforms/submissions/api/renderers.py, src/openforms/submissions/api/urls.py, src/openforms/submissions/api/views.py, src/openforms/submissions/tests/test_submission_co_sign.py, src/openforms/submissions/tests/test_submission_report.py, src/openforms/submissions/urls.py, src/openforms/submissions/utils.py, src/openforms/submissions/views.py
Closes #4488
**Changes**
* Refactored to use the PrivateMediaView generic CBV
* URL moved to non-API url
* Deleted the API-related code that is now obsolete
**Checklist**
=> Initiate download of submission report PDF

src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsForm.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js
Closes #4533
- Updated `onChange` event in the checkbox in Objects API. There was a problem for both legacy and the new version, since the value of the checkbox would always be `"false"` 
**Checklist**
=> [#4533] Fix onFieldChange in upload submission csv checkbox (ObjectsAPI)

src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
Closes #4191 
**Changes**
* aoaIdentifictie may not be empty
* handelsnaam must be an array
**Checklist**
=> Fix more ZGW registration backend issues

src/openforms/contrib/zgw/clients/catalogi.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/zgw_apis/options.py
Closes #4534
`list_eigenschappen` was left as a list as it is used in:
https://github.com/open-formulieren/open-forms/blob/2e1ca4dabe7e1e018e7bc9d2409557c646ac1eb9/src/openforms/registrations/contrib/zgw_apis/plugin.py#L413-L417
And would complicate this `partial` call even more
**Checklist**
=> [#4534] Use iterators in the `Catalogi` client

docker/docker-compose.objects-apis.yml, docker/objects-apis/README.md, docker/objects-apis/fixtures/objects_api_fixtures.json, docker/objects-apis/fixtures/objecttypes_api_fixtures.json, docker/open-zaak/fixtures/open_zaak_fixtures.json, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_auth_context_data.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_auth_context_data_not_authenticated.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_attachments.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_attachments_component_inside_fieldset_overwrites.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_attachments_component_overwrites.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_attachments_specific_iotypen.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_missing_csv_iotype.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_override_content_json.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_override_defaults.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_override_defaults_do_not_upload_csv.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_override_defaults_upload_csv_default_type.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_use_config_defaults.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_escapes_html.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_payment.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIPaymentStatusUpdateV1Tests/ObjectsAPIPaymentStatusUpdateV1Tests.test_no_template_specified.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIPaymentStatusUpdateV1Tests/ObjectsAPIPaymentStatusUpdateV1Tests.test_template_overwritten_through_options.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIPaymentStatusUpdateV1Tests/ObjectsAPIPaymentStatusUpdateV1Tests.test_update_payment_status.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_update_payment_status_v1.py
Partly closes #4267
**Checklist**
=> [#4267] Convert Objects API V1 tests to VCR

src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/email/tests/test_backend.py
Closes #4334 
**Changes**
* If wait_for_payment option is enabled and the submission is paid, immediately schedule the payment update email too
**Checklist**
=> Ensure payment email is sent, irrespective of wait_for_payment registration mode

src/openforms/appointments/contrib/jcc/tests/test_plugin.py, src/openforms/appointments/contrib/qmatic/tests/test_plugin.py, src/openforms/utils/tests/http.py
Replaced 4xx and 5xx status code fuzzy with hypothesis with factory boy fuzzing, which also has options to make it reproducible if needed. This should reveal potential issues over time the same way that hypothesis does, except it will only run one case in each CI run of course where hypothesis could potentially cover the entire range in a single test run by generating 100 (or less) samples.
=> :recycle: Reduce test flakiness

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Closes #4432
**Changes**
Not sure if this is the best place to put it
**Checklist**
=> [#4432] Add an error boundary to the registration summary

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/config/migrations/0001_initial_to_v250.py
There are more - notably `celery_once` and `stringcase` have some warnings, but both libraries have not had releases in a long time and appear unmaintained :(
=> Fix warnings produced since the 3.12 upgrade

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/authentication/contrib/digid/tests/test_auth_procedure.py, src/openforms/authentication/contrib/digid/tests/test_signicat_integration.py, src/openforms/authentication/contrib/eherkenning/tests/test_eherkenning_auth.py, src/openforms/authentication/contrib/eherkenning/tests/test_eidas_auth.py, src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py, src/openforms/authentication/contrib/tests/saml_utils.py, src/openforms/fixtures/default_admin_index.json
Closes #4442
Closes #4514
**Changes**
* Upgraded django-digid-eherkenning to version with multi-certificate support
* Upgraded django-simple-certmanager with support for encrypted private keys
**Checklist**
=> Bump django-digid-eherkenning and django-simple-certmanager

src/openforms/scss/pdfs/_submission-step-row.scss, src/openforms/submissions/templates/report/submission_report.html
previously this was a column based layout, initially it used flexbox, but this was later replaced with float due to performance issues with weasyprint
The problem with float is that there are a lot of edge cases when it comes to displaying everything properly (page breaks cause text to overlap, empty values must be accounted for, etc.) and ultimately there doesn't seem to be a proper solution to make long labels display properly if they exceed the page length.
Other layout styles like grid, tables or using `display: block` had the same performance issues as flexbox, so we decided to switch to a row based layout (displaying values under labels to avoid the performance and styling issues
Closes #4560 
**Changes**
* Use row based layout for submission report
**Checklist**
Check off the items …
=> :bug: [#4560] Use row based layout for submission report

src/openforms/js/components/admin/forms/VariableSelection.js, src/openforms/scss/_vars.scss, src/openforms/scss/components/admin/_dsl-editor.scss, src/openforms/scss/components/admin/_index.scss, src/openforms/scss/components/admin/_select.scss
Closes #4519
**Changes**
- Added class name to the `VariableSelection` in order to define `max-inline-size` for the form variable dropdowns
**Checklist**
=> [#4519] Decrease horizontal space of form variable dropdowns

src/openforms/contrib/objects_api/clients/objects.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsForm.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendVCRTests/ObjectsAPIBackendVCRTests.test_submission_with_objects_api_backend_create_and_update_object.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/registrations/contrib/objects_api/typing.py
Closes #4395
- Added `update_existing_object` flag to the ObjectsAPI (both versions). This will be used in combination with `submission.initial_data_reference` in order to update an existing object and not recreate it.
**Checklist**
=> [#4395] Add flag for updating an object to the ObjectsAPI registration

.github/workflows/ci.yml, src/openforms/conf/base.py, src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/tests/runner.py
* Report the random state of factory body - this may help in reproducing flaky tests.
* Fixed a cache isolation/reset causing flaky tests
=> Address flakiness in tests

docker/docker-compose.stuf-zds.yml, docker/stuf-zds/Dockerfile, docker/stuf-zds/app.py, src/openforms/js/components/admin/form_design/registrations/index.js
Closes #4380
Related PR in extension repo: https://github.com/open-formulieren/open-forms-ext-stuf-zds-payments/pull/1
**Changes**
* Add mock docker service for StUF-ZDS
* Add custom UI schema for StUF-ZDS payments registration options XML template
**Checklist**
=> :clown_face: [#4380] Mock docker service for StUF-ZDS

docs/installation/config.rst, src/openforms/conf/base.py, src/openforms/conf/ci.py, src/openforms/conf/dev.py
Closes #4575 
**Changes**
Added SENDFILE_BACKEND option to conf/base.py and set ci and dev defaults using the environment variable. Included update to documentation. 
Note of caution: I haven't been able to test the changes.
**Checklist**
=> :wrench: [#4575] added SENDFILE_BACKEND configuration option

src/openforms/js/components/admin/form_design/registrations/index.js, src/openforms/registrations/contrib/stuf_zds/plugin.py
added a method `get_extra_data` on the StUFZDSRegistration plugin to make it easier for extensions to override this behaviour (see stuf-zds-payments extension)
required for https://github.com/open-formulieren/open-forms-ext-stuf-zds-payments/pull/1
Closes #4380 partially
**Changes**
* Modify stuf-zds plugin to support extra data
**Checklist**
=> :recycle: [#4380] Modify stuf-zds plugin to support extra data

src/openforms/conf/base.py
Some customers request outgoing request logging to be enabled on test instances (permanently). We can parametrize this via envvars now.
**Checklist**
=> :whale: Allow configuring log-outgoing-requests through envvars

src/openforms/config/templates/admin/config/overview.html, src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/zgw_apis/plugin.py
**Changes**
Added links to configuration overview so that users don't have to find the menu items in "Overige" in admin index.
* Added missing link to objects API groups
* Added missign link to zgw API groups
* Fixed displaying multiple actions (separator was missing)
**Checklist**
=> :children_crossing: Link to all relevant configuration in overview

package-lock.json, package.json, src/openforms/forms/tests/e2e_tests/test_form_configuration.py, src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/forms/tests/e2e_tests/test_registration_backend_conf.py, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/RegistrationFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentType.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/ObjectTypeSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/ObjectTypeVersionSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/ObjectsAPIGroup.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/index.js, src/openforms/js/components/admin/forms/Field.js, src/openforms/js/components/admin/forms/ReactSelect.js, src/openforms/js/components/admin/modals/FormModal.js, src/openforms/scss/_vendor.scss, src/openforms/scss/vendor/_react-select.scss, src/openforms/tests/e2e/base.py
Related to #4577 
**Changes**
* Refactored existing selects to use react-select under the hood. This provides a search field which is useful for large lists to filter down in the options.
* Updated to new formio-builder version so we can re-use the dark-mode support styles
* Added base react-select component with some additional django-admin style overrides
* Refactored some duplicated code into single component so that we can easily deprecate it next
**Checklist**
=> Improve UX by using react-select (Objects API registration options)

src/openapi.yaml, src/openforms/contrib/zgw/api/filters.py, src/openforms/contrib/zgw/api/serializers.py, src/openforms/contrib/zgw/api/views.py, src/openforms/forms/tests/e2e_tests/test_registration_backend_conf.py, src/openforms/forms/tests/e2e_tests/vcr_cassettes/FormDesignerRegistrationBackendConfigTests/FormDesignerRegistrationBackendConfigTests.test_configuration_objects_api_group.yaml, src/openforms/js/components/admin/form_design/RegistrationFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsForm.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/CatalogueSelect.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/forms/ReactSelect.js, src/openforms/registrations/contrib/objects_api/api/filters.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/GetInformatieObjecttypesViewTests/GetInformatieObjecttypesViewTests.test_retrieve_filter_by_catalogus.yaml, src/openforms/registrations/contrib/objects_api/tests/test_api_endpoints.py, src/openforms/registrations/contrib/zgw_apis/api/filters.py, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/GetInformatieObjecttypesViewTests/GetInformatieObjecttypesViewTests.test_retrieve_filter_by_catalogus.yaml
Partially closes #4577
~~Depends on #4574~~ merged
~~Depends on #4586~~ merged
**Changes**
* Added queries to document types endpoint to populate dropdown options
* Added dropdowns to select the desired document type
* Added interaction tests
* Added reset of document types when a different catalogue is selected (or it's being unset)
**Checklist**
=> Add document type select/dropdowns

docker/open-zaak/fixtures/open_zaak_fixtures.json, docs/configuration/registration/objects.rst, docs/installation/config.rst, src/openapi.yaml, src/openforms/conf/base.py, src/openforms/contrib/zgw/api/serializers.py, src/openforms/contrib/zgw/api/views.py, src/openforms/contrib/zgw/clients/catalogi.py, src/openforms/contrib/zgw/tests/test_catalogi_client.py, src/openforms/forms/admin/mixins.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/Context.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/form_design/story-decorators.js, src/openforms/js/components/admin/forms/ReactSelect.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/GetInformatieObjecttypesViewTests/GetInformatieObjecttypesViewTests.test_allow_unpublished_document_types.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/GetInformatieObjecttypesViewTests/GetInformatieObjecttypesViewTests.test_retrieve_filter_by_catalogus.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendVCRTests/ObjectsAPIBackendVCRTests.test_allow_registration_with_unpublished_document_types.yaml, src/openforms/registrations/contrib/objects_api/tests/test_api_endpoints.py, src/openforms/registrations/contrib/objects_api/tests/test_backend.py, src/openforms/scss/components/admin/_document-type-option.scss, src/openforms/scss/components/admin/_index.scss, src/openforms/scss/vendor/_react-select.scss
Closes #4577
**Changes**
**Checklist**
=> Add feature flag for draft document types (and prepare for ZGW similar mechanics)

src/openforms/scss/pdfs/_submission-step-row.scss, src/openforms/submissions/templates/report/submission_report.html
previously these fields were marked as `(not filled in)`
Closes #4597 
**Changes**
* Leave empty fields empty in submission PDF
**Checklist**
=> :lipstick: [#4597] Leave empty fields empty in submission PDF

.github/workflows/ci.yml, src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/tests/e2e/base.py
* Enabled playwright tracing for easier debugging of flaky tests
* Fixed the cause this time of the flaky e2e tests...
=> Test flakiness - trace playwright tests and upload traces of failing tests

src/openforms/submissions/tests/test_models.py
The original reason failures happened was because the form name was used to construct the file name of the PDF, which resulted in nested paths with forward slashes.
The ambition with hypothesis was nice - whatever form name you specify should not result in broken file saving, but hypothesis comes up with some very exotic unicode characters that font libraries and/or weasyprint sometimes cannot handle. These edge cases are not worth fixing or mitigating with fancy input validating restricting the unicode range of valid characters, but we also do not want these flaky test failures.
The test is rewritten without hypothesis to illustrate the original failure, preventing similar further regressions. If the edge cases do happen for real, we'll have a stakeholder funding the extra mitigations …
=> :art: De-hypothesize regression test

src/openforms/authentication/tasks.py, src/openforms/authentication/tests/files/digid/metadata_with_slo_POST, src/openforms/authentication/tests/files/eherkenning/metadata, src/openforms/authentication/tests/test_tasks.py, src/openforms/conf/base.py
Closes #4582
**Changes**
- Added weekly celery-beat task forupdating the DigiD/Eherkenning metadata
(Used [https://github.com/maykinmedia/django-digid-eherkenning](url) library's command)
**Checklist**
=> [#4582] Weekly update SAML metadata for DigiD/Eherkenning

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/validation/test_email.py, src/openforms/formio/typing/base.py, src/openforms/js/lang/formio/nl.json
Closes #4542
**Changes**
Added formio email component validation on the server side that checks the `requireVerification` option.
**Checklist**
=> Server side email verification validation

.github/workflows/ci.yml, .github/workflows/code_quality.yml, INSTALL.rst, docker-compose.yml, docker-init-db.sql, docs/installation/ansible.rst
Closes #4648 
**Changes**
* Fixed outdated documentation saying PostgreSQL 10+ is needed - it's 12 or higher.
* Updated CI pipeline(s) to use PostgreSQL 15 instead of 14.
**Checklist**
=> Confirm postgres 15 support

src/openforms/forms/models/form.py, src/openforms/forms/tests/test_copy.py
Closes #4587 
**Changes**
* Copy Form.product when copying Form
**Checklist**
=>  🐛 [#4587] Copy Form.product when copying Form

.github/workflows/ci.yml, src/openforms/conf/tinymce_config.json
this was implemented in https://github.com/open-formulieren/open-forms/commit/103e511979080910fb98cc9d6e97500faac45f91, but that commit also introduces extra changes that we do not want to backport
partially closes #4653 
**Changes**
* Add blocks dropdown to TinyMCE toolbar
**Checklist**
=> :bug: [#4653] Add blocks dropdown to TinyMCE toolbar (2.7.x backport)

src/openforms/js/lang/formio/en.json, src/openforms/js/lang/formio/nl.json
Backport-Of: https://github.com/open-formulieren/open-forms/pull/4665
Closes #4602 partially
**Changes**
* Translation for Selectboxes minSelectedCount error
**Checklist**
=> :globe_with_meridians: [#4602] Translation for Selectboxes minSelectedCount error

bin/report_component_problems.py, src/openforms/fixtures/default_admin_index.json, src/openforms/formio/migration_converters.py, src/openforms/formio/tests/test_simple_conditionals_converter.py
Closes #4680
**Changes**
* Reproduced and fixed the crash when empty strings are used in certain simple conditional configurations.
* Expanded the component issue reporting helper script so that we can get a summary of all broken situations, if similar things happen again.
**Checklist**
=> Fix migration/import crash

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/validation/test_file.py, src/openforms/submissions/tests/test_submission_step_validate.py
Closes #4656
**Changes**
- Added regression test for the editgrid (didn't make context available to the children)
- Made parent's serializer context available to children (`EditGrid`)
- The other nested layout components work with files as expected (`fieldset` and `columns`)
**Checklist**
=> [#4656] Make parent's serializer context available to the children (FileSerializer)

src/openforms/scss/admin/_vendor-fixes.scss, src/openforms/scss/admin/admin_overrides.scss
Closes #4652 
**Changes**
Ensuring that the errorlist component is shown above the respective input.
Fixing the issues where the errorlist is shown in front of the label
**Checklist**
=> [#4652] Form builder error messages positions

src/openforms/config/migrations/0059_alter_globalconfiguration_form_upload_default_file_types.py
Closes #4701
**Changes**
- Added missing migration for the global configuration. When we define a global setting for the allowed file types we need to make sure the extra .zip mimetypes are in the list as well.
**Checklist**
=> [#4701] Add missing data migration for the global config and zip mimetypes

Dockerfile, bin/fix_globalconfig_zip.py
Hotfix for data migration being patched, but this one can easily be deployed via Ansible without needing to revert migrations.
=> Add script to fix globalconfig

src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIOptionsSerializerTest/ObjectsAPIOptionsSerializerTest.test_unknown_informatieobjecttype.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIOptionsSerializerTest/ObjectsAPIOptionsSerializerTest.test_valid_serializer.yaml, src/openforms/registrations/contrib/objects_api/tests/test_serializer.py
Backport-Of: open-formulieren/open-forms#4700
Closes #4695 partially
**Changes**
* Do not fetch all IOtypen for objects API validation
**Checklist**
=> :zap: [#4695] Do not fetch all IOtypen for objects API validation (2.7.x backport)

src/openforms/scss/admin/_vendor-fixes.scss
Closes #4711
**Changes**
Changed the .form-row styling to be more specific.
**Checklist**
=> Fix broken submission form row styling

src/openforms/payments/models.py, src/openforms/registrations/contrib/objects_api/registration_variables.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/stuf_zds/registration_variables.py, src/openforms/submissions/models/submission.py
in different places, the same query was being done to find successful SubmissionPayments, this has been moved to a method on the queryset to avoid duplication
Closes #4588 
**Changes**
* Reduce code duplication in payment related code
**Checklist**
=> :recycle: [#4588] Reduce code duplication in payment related code

docs/developers/embedding.rst, src/openforms/forms/templates/forms/sdk_snippet.html
Closes #4600 
**Changes**
Triggering a page reload after language change, using the new `onLanguageChange` property on the sdk form object. This PR requires [open-formulieren/open-forms-sdk#715]
**Checklist**
=> :bug: [#4600] Perform reload on language change

src/openforms/contrib/haal_centraal/clients/__init__.py, src/openforms/contrib/haal_centraal/tests/test_brp_clients.py, src/openforms/prefill/contrib/haalcentraal_brp/plugin.py
Closes #4713 
**Changes**
* Set up Docker mock service for HaalCentraal BRP
* Fix token exchange for BRP client
**Checklist**
=> :bug: [#4713] Fix token exchange for BRP client

src/openforms/forms/templates/admin/forms/form/change_form.html, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/form-creation-form.js, src/openforms/js/components/admin/index.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Closes #4709
**Changes**
- Updated the generic message error
- Added a link to the requests logs
**Checklist**
=> [#4709] Update generic error message text for erros in a form

package-lock.json, package.json, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json
Closes #4636
Closes #4637
**Changes**
* Upgraded bundled formio-builder from 0.28.0 to 0.30.0 which contains necessary fixes.
This also exposes the ProductPrice experimental component, which will likely be gated behind a feature flag for the full 3.0 release.
**Checklist**
=> Upgrade to formio-builder 0.30

src/openforms/forms/tests/e2e_tests/test_service_fetch.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.stories.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/constants.js, src/openforms/js/components/admin/form_design/variables/utils.js, src/openforms/js/components/admin/forms/ReactSelect.js, src/openforms/js/components/admin/forms/VariableMapping.stories.js, src/openforms/js/components/admin/forms/VariableSelection.js, src/openforms/js/components/admin/forms/VariableSelection.stories.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/js/utils/storybookTestHelpers.js, src/openforms/scss/_vars.scss, src/openforms/scss/admin/_app_overrides.scss, src/openforms/scss/components/admin/_select.scss, src/openforms/scss/vendor/_react-select.scss, src/openforms/scss/vendor/_tinymce.scss
Closes #4524
Closes #4675
I've cleaned up the commit history from the original PR
**Changes**
The variable dropdown now uses the react-select component. Allowing for searching within the options
**Checklist**
=> Improve the user experience of the form variable select/dropdown

src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/formio/tests/factories.py, src/openforms/submissions/rendering/nodes.py, src/openforms/submissions/tests/test_exports.py
Closes #3629
**Changes**
* Added regression tests for repeating group and file upload components that can cause the submission export to crash.
* Ensure that (hidden/skipped) submission steps because of logic are not skipped during export
* Ensure that editgrid components are considered a single component during export instead of recursing into them
**Checklist**
=> Ensure submissions tablib.Dataset generation doesn't crash

src/openforms/js/lang/formio/en.json, src/openforms/js/lang/formio/nl.json
Closes #4716 
**Changes**
Added a new formio translation
**Checklist**
=> :globe_with_meridians: [#4716] Added formio translations

src/openforms/conf/base.py
previously, if the session in the OIDC provider expired and the sessionrefresh middleware is triggered, the user can not automatically re-authenticate, causing to 403s (and losing changes made in the form designer). In order to avoid session synchronization issues, we remove the SessionRefresh completely, meaning that OIDC is used for logging in, but Open Forms itself is then in charge of managing the session.
Backport-Of: open-formulieren/open-forms#4528
Closes #4528 partially
=> [2.7.x backport] :bug: [#4528] Disable OIDC SessionRefresh middleware

src/openforms/conf/base.py
previously, if the session in the OIDC provider expired and the sessionrefresh middleware is triggered, the user can not automatically re-authenticate, causing to 403s (and losing changes made in the form designer). In order to avoid session synchronization issues, we remove the SessionRefresh completely, meaning that OIDC is used for logging in, but Open Forms itself is then in charge of managing the session.
Closes #4528 
**Changes**
* Disable OIDC SessionRefresh middleware
**Checklist**
=> :bug: [#4528] Disable OIDC SessionRefresh middleware

docs/manual/forms/basics.rst, docs/manual/forms/form_fields.rst, docs/manual/forms/index.rst, docs/manual/forms/soft_required_fields.rst, package-lock.json, package.json, src/openforms/forms/models/form_definition.py, src/openforms/forms/tests/test_models.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/form/softRequiredErrors.js, src/openforms/js/components/formio_builder/builder.js, src/openforms/js/formio_module.js, src/openforms/js/lang/formio/nl.json, src/openforms/scss/components/builder/_builder.scss
Partially closes #4546 - depends on https://github.com/open-formulieren/formio-builder/pull/188
**Changes**
**Checklist**
=> Enable soft-required validation in the form designer

requirements/dev.txt, src/openforms/formio/datastructures.py, src/openforms/formio/tests/test_datastructures.py, src/openforms/registrations/contrib/objects_api/submission_registration.py
Closes #4744
**Changes**
Optimized key access in the `FormioData` data structure.
Performance results - the last column are the numbers for this PR. The gains are massive compared to `master` and they improve even on 2.7.x.
| Form step                   | version: master (0ea7bfa) | version: 2.7.x | Perf patch |
| --------------------------- | ------------------------- | -------------- | ---------- |
| Inleiding                   | 1540                      | 736            | 448        |
| Verklaring van waarheid     | 1520                      | 751            | 464        |
| Uw gegevens                 | 1727                      | 879            | 551        |
| Uw situatie                 | 1730                      | 827            | 483        |
| Gezinssamenstelling         | …
=> Fix performance regression in FormioData data structure

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/test_normalization.py
Closes #4774 
**Changes**
- Added a regression test for the component's normalizer
- Implemented the `normalizer` method for the component
The `prefill` module was already normalizing the components' values but for the `textfield` component we were missing the normalizer method.
**Checklist**
=> [#4774] Normalize textfield component's value

docs/installation/config.rst, docs/manual/forms/soft_required_fields.rst, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/formio/tests/test_variables_injection.py, src/openforms/formio/variables.py, src/openforms/js/lang/formio/en.json, src/openforms/js/lang/formio/nl.json, src/openforms/submissions/tests/test_submission_report.py
Closes #4546
**Changes**
Tested this end-to-end with the SDK PR and noticed some more tweaks were needed.
* Make sure the HTML for the content is not treated as Django template
* Make sure the component is not displayed in summary page/PDF report/
registration data etc.
* Added tests
*  Added translations for accessible list label/heading
**Checklist**
=> Polish backend for soft-required validation

src/openforms/scss/components/builder/_admin-fixes.scss
Closes #4726 
**Changes**
Fixing the broken styling of delete buttons (`.deletelink`) inside the `.submit-row` element.
**Checklist**
=> :bug: [#4726] Fixing the styling for form delete buttons

src/openforms/submissions/admin.py
Closes #4763 
**Changes**
Temporary file uploads can now be deleted, solving the deletion issue of form submissions with file uploads
**Checklist**
=> :bug: [#4763] Allow temporary file uploads to be deleted

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/mocks.js, src/openforms/js/components/admin/form_design/registrations/zgw/fields/CaseTypeSelect.js, src/openforms/js/components/admin/form_design/registrations/zgw/mocks.js, src/openforms/scss/components/admin/_catalogi-type-option.scss, src/openforms/scss/vendor/_react-select.scss
Closes #4802
**Changes**
- Fixing the bug by ensuring that the `.admin-react-select` element can't grow beyond its max-inline-size
- Replaced the `DocumentTypes` and `CaseTypeSelect` select option html labels with simple text labels. The html labels are now added as a custom Option component for the ReactSelect. This means that the html labels will only be used when the option is presented in the dropdown, otherwise the simple text label will be used.
- Updated the storybook mock data to showcase large option labels for DocumentTypes and CaseTypeSelect
**Checklist**
=> Broken react select styling for large values

src/openforms/registrations/contrib/stuf_zds/plugin.py, src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py, src/stuf/stuf_zds/client.py, src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml, src/stuf/stuf_zds/tests/test_backend.py
Closes #4762 
**Changes**
- Added the cosigner's bsn to the creerzaak bericht
**Checklist**
=> [#4762] Add cosign data (bsn) to the stuf-zds creerzaak bericht

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/test_api_fileupload.py
Closes #4823
**Changes**
Allows uploaded files with leading whitespaces.
**Checklist**
=> :bug: [#4823] Allow files with leading whitespace

src/openforms/registrations/contrib/objects_api/registration_variables.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_submission_with_file_components_container_variable.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/objects_api/tests/test_registration_variables.py
Closes #4745
**Changes**
* Added registration variable to the Objects API with all the attachment URLs
* Added test
It's not a defect, but The Hague will probably very much appreciate if we backport this, and it looks very easy to do so.
**Checklist**
=> Provide registration variable containing all attachment URLs

src/openforms/analytics_tools/contrib/expoints/csp_headers.json, src/openforms/analytics_tools/contrib/govmetric/csp_headers.json, src/openforms/analytics_tools/tests/test_expoints.py, src/openforms/analytics_tools/tests/test_govmetric.py, src/openforms/conf/base.py
some of these were missing, others caused issues because we could no longer rely on defaults
Closes #4732 
**Changes**
* Add missing CSP directives for Expoints/other analytics
**Checklist**
=> :bug: [#4732] Add missing CSP directives for Expoints/other analytics

src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/submissions/models/submission.py, src/openforms/submissions/report.py
Requested by DH as they're worried about legal implications of the language used currently.
Taken from #4320 / #4838
=> Backport PDF when submissions need to be cosigned

src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_addressNl_legacy_before_of_30.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py
Part follow up of #4418
**Changes**
* Added test for registration options without nested options
* Added small compatibility layer to retain the old behaviour for old configuration
**Checklist**
=> Add test for pre 3.0 addressNL migration check / improve backwards compatibility

pyright.pyproject.toml, src/openforms/contrib/objects_api/clients/objects.py, src/openforms/contrib/objects_api/helpers.py, src/openforms/contrib/objects_api/typing.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/handlers/__init__.py, src/openforms/registrations/contrib/objects_api/handlers/v2.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/objects_api/typing.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/submissions/mapping.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/typing.py, src/openforms/variables/service.py
Part of #4431 - builds on top of #4850
**Changes**
Refactored the Objects API v2 registration data building/transformations after the mappings were implemented by @vaszig. I was also able to add more files to the type checker and finally some type definitions / hints could also be cleaned up, hurray!
This had been on my mind for a while when we were fixing the bugs specifically to the file upload types w/r to single/multiple uploads, and now the additional options lead to more :spaghetti: code in this registration handler, so I figured it was time to put my thoughts into code.
=> Refactored the record-data building + post-processing in Objects API registration v2

CHANGELOG.rst
Closes #4843 
**Changes**
- Added the patch release notes for `2.7.10` and `2.8.2`
**Checklist**
=> Update CHANGELOG with 2.7.10 and 2.8.2

src/openforms/authentication/api/tests/test_logout.py, src/openforms/authentication/api/views.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/tasks/cleanup.py
Closes #4862 
**Changes**
* Added regression test that reproduces the problem
* Added minimal bugfix that can be backported by considering the cosign status
* Refactored/cleaned up other parts of code to make use of the same centralized logic if hashing is possible or not
**Checklist**
=> Fix unintended hashing of identifying attributes when the cosigner logs out

docs/installation/index.rst, docs/installation/upgrade-300.rst, src/openforms/forms/tests/test_import_export.py, src/openforms/registrations/contrib/objects_api/config.py
Part of #3283
**Changes**
The URL to UUID convertion of the Objects API `objecttype` in the form import has been removed. The `objecttype` now has to be a UUID. Along this change, the `objects_api_group` is now again required.
**Checklist**
=> Removing objecttype URL to UUID import conversion

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/registrations/zgw/BasicOptionsFieldset.js, src/openforms/js/components/admin/form_design/registrations/zgw/LegacyOptionsFieldset.js, src/openforms/js/components/admin/form_design/registrations/zgw/ObjectsAPIOptionsFieldset.js, src/openforms/js/components/admin/form_design/registrations/zgw/OptionalOptionsFieldset.js, src/openforms/js/components/admin/form_design/registrations/zgw/ZGWOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/zgw/ZGWOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/zgw/mocks.js, src/openforms/js/components/admin/form_design/registrations/zgw/useCatalogueOptions.js, src/openforms/js/components/admin/forms/zgw/CatalogueSelect.js, src/openforms/js/components/admin/forms/zgw/index.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Required for #4606
Refactored the components and hooks so we can lift up the retrieval of available catalogues in a ZGW API group.
The parent component is now responsible for fetching the available catalogues and relays the loading/error state from useAsync. It also encapsulated the derived catalogueUrl when a valid value is available and selected, which other components need to look up related objects (like case types, document types, products and the future role types).
I've opted to pass down the error into a component that just throws for the existing error boundary behaviour and location, as it's important that you can still change the API group to trigger a new attempt and we want to keep the code nicely organised.
Finally, some more fieldsets were abstracted into their own …
=> Refactor ZGW options components structure

docs/installation/upgrade-300.rst, src/openapi.yaml, src/openforms/api/urls.py, src/openforms/conf/locale/nl/LC_MESSAGES/django.po, src/openforms/contrib/kadaster/api/views.py, src/openforms/contrib/kadaster/tests/test_api_address_autocomplete.py
Part of #3283 
**Changes**
The /api/v2/location/get-street-name-and-city endpoint has been removed, in favor of /api/v2/geo/address-autocomplete endpoint.
For the time being /api/v2/location/get-street-name-and-city will redirect to /api/v2/geo/address-autocomplete.
**Checklist**
=> Removing deprecated /location/get-street-name-and-city api endpoint

docs/installation/upgrade-300.rst, src/openapi.yaml, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/tests/admin/test_form.py, src/openforms/forms/tests/exports/formDefinitions.json, src/openforms/forms/tests/test_api_form_versions.py, src/openforms/forms/tests/test_api_formdefinition.py, src/openforms/forms/tests/test_restore_version.py
Related to #3283
**Changes**
* Make FormDefinitionSerializer.name read only
**Checklist**
=> :wastebasket: [#3283] Make FormDefinitionSerializer.name read only

docs/installation/upgrade-300.rst, pyright.pyproject.toml, src/openapi.yaml, src/openforms/forms/api/serializers/logic/action_serializers.py, src/openforms/forms/tests/e2e_tests/test_logic_tab.py, src/openforms/forms/tests/test_import_export.py
Part of #3283
Fully qualified URLs to resolve a form step have been deprecated for a while, since they're not portable across environments with different base URLs.
Now the compatibility code is removed too, which may break old exports.
**Checklist**
=> :boom: Remove conversion of form step URL to form step UUID

pyright.pyproject.toml, src/openforms/authentication/api/serializers.py, src/openforms/authentication/registry.py, src/openforms/emails/confirmation_emails.py, src/openforms/emails/templatetags/cosign_information.py, src/openforms/forms/models/form.py, src/openforms/prefill/co_sign.py, src/openforms/registrations/contrib/objects_api/registration_variables.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/stuf_zds/plugin.py, src/openforms/registrations/contrib/stuf_zds/tests/test_backend.py, src/openforms/registrations/tasks.py, src/openforms/submissions/cosigning.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/report.py, src/openforms/submissions/tasks/emails.py, src/openforms/submissions/tests/factories.py, src/openforms/submissions/tests/test_cosign_state.py, src/openforms/submissions/tests/test_models.py, src/openforms/submissions/utils.py, src/stuf/stuf_zds/client.py, src/stuf/stuf_zds/tests/test_backend.py
Closes #4320
**Changes**
This refactor sets up a dedicated interface to read the cosign state of a submission. Highlights:
* Good typing support
* Ability to deal with cosign v1 and v2 details in the proper context
* Proper factory trait to set up the necessary database state of a submission
* Prepared for cosign v3
**Checklist**
=> Refactor (accessing) the cosign state

docker/setup_configuration/data.yaml, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/conf/base.py
Closes #4788
**Changes**
* Add ConfigurationStep for Admin OIDC login
**Checklist**
=> :sparkles: [#4788] Add ConfigurationStep for Admin OIDC login

src/openforms/registrations/contrib/microsoft_graph/plugin.py, src/openforms/registrations/contrib/microsoft_graph/tests/test_backend.py
The lack of deterministic ordering when processing the submission attachments can cause tests to sometimes fail in CI.
When no explicit ordering is specified, Postgres figures out an ordering which tends to correspond to how the tuples/records are stored on disk, and on particular bad alignment of the stars the later-created record can appear before earlier ones, being returned in a non-intuitive order. For this reason, you should always make ordering explicit or if ordering doesn't matter, write assertions without assuming any ordering.
In this case, making the order explicit is the simplest fix.
=> :green_heart: Fix flaky msgraph test

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
the previous release specified oidc_op_jwks_endpoint and oidc_op_logout_endpoint outside of endpoint_config
=> :arrow_up: [#4788] Upgrade mozilla-django-oidc-db to 0.21.1

src/openforms/submissions/cosigning.py, src/openforms/submissions/tests/test_post_submission_event.py
Closes #3901 - depends on #4888
**Changes**
* Added regression test(s)
* Fixed cosign state not taking the logic/dynamic behaviour of cosign component into account
**Checklist**
=> Fix incorrect detection of cosign being required blocking the registration

src/openforms/registrations/contrib/zgw_apis/options.py
Closes #4899
**Changes**
- Allow optional url fields to receive empty string values
**Checklist**
=> [#4899] Fix optional serializer fields in ZaakOptionsSerializer

.github/pull_request_template.md, Dockerfile, docs/installation/additional_scipts.rst, docs/installation/index.rst
Closes #4874 
**Changes**
- Added `fix_selectboxes_component_default_values` scipt to the Dockerfile
- Updated issue template (reminder for such scripts)
- Added instructions for downloading and adding the script manually
**Checklist**
=> [#4874] Add missing script to the Dockerfile

src/openforms/emails/constants.py, src/openforms/submissions/tasks/emails.py, src/openforms/submissions/tests/test_task_co_sign.py, src/openforms/submissions/tests/test_tasks_confirmation_emails.py, src/openforms/submissions/utils.py
Closes #4895 
**Changes**
Add custom headers to confirmation and cosign emails
**Checklist**
=> [#4895] outgoing email logging improvements

INSTALL.rst
Closes #4907
**Changes**
Add notes about Redis server, Celery worker and CORS_ALLOWED_ORIGINS variable in .env
**Checklist**
=> [#4907] Improve developer installation documentation

src/openforms/forms/models/form_variable.py, src/openforms/js/components/admin/form_design/variables/utils.js
Closes #4884
The soft required errors component should have the same behaviour like the content component, as it holds no submission values and is purely client-side behaviour.
Formio itself excludes the content component when looping over a configuration with eachComponent, so we need to add this same logic to our own code since Formio is not aware of our custom component semantics.
In the backend, we extend the behaviour for content components to the softRequiredErrors component to ensure no variables are created in the database either.
**Checklist**
=> Ensure that no form variables are created for soft required errors

pyright.pyproject.toml, src/openforms/forms/admin/form.py, src/openforms/payments/admin.py, src/openforms/payments/api/fields.py, src/openforms/payments/api/serializers.py, src/openforms/payments/base.py, src/openforms/payments/contrib/demo/plugin.py, src/openforms/payments/contrib/ogone/constants.py, src/openforms/payments/contrib/ogone/plugin.py, src/openforms/payments/contrib/ogone/typing.py, src/openforms/payments/models.py, src/openforms/payments/services.py, src/openforms/payments/tests/test_views.py, src/openforms/payments/views.py
Part of #3457 -  doing the refactor before making the required changes
All other modules operate on the idea that the generic code populates the plugin options from the generic information and the specified options serializer, which allows plugins to be generically typed and not needing to perform additional input validation or conversion from the raw JSON data for the options to the Python/Django objects that are easier to work with.
This does change the public API of the registry/plugins to take an extra argument, but enables us to apply static type checking (which already reveals some problems) and simpler plugin code.
**Checklist**
- I have updated the translations assets (you do NOT need …
=> Refactor payments module to apply plugin mechanism consistently

src/openforms/registrations/contrib/demo/config.py, src/openforms/registrations/contrib/email/config.py, src/openforms/registrations/contrib/microsoft_graph/config.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/stuf_zds/options.py
Closes #4853
**Changes**
- Updated serializers with non required fields. When we send empty strings to the backend we need `allow_blank=True`
**Checklist**
=> [#4853] Fix non required fields in registration backends serializers

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/lang/formio/nl.json, src/stuf/stuf_zds/client.py, src/stuf/stuf_zds/tests/test_backend.py
Closes #4319
**Changes**
~- Needs open-formulieren/formio-builder#199~ (this will be handled by #4881)
~- Upgrade the formio-builder to the new version~ (this will be handled by #4881)
**Checklist**
=> [#4319] Make title of document configurable in StUF-ZDS

src/openforms/forms/api/filters.py, src/openforms/forms/tests/test_api_formdefinition.py
Part of #3283
Providing both the used_in and is_reusable filter parameters no longer returns records that match either condition, instead it applies the default AND behaviour.
**Checklist**
=> :boom: Remove OR-filter behaviour on form definitions endpoint

src/openforms/forms/tests/test_import_export.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/payments/ogone_legacy/OgoneLegacyOptionsForm.js, src/openforms/js/components/admin/form_design/payments/ogone_legacy/fields.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/payments/contrib/ogone/client.py, src/openforms/payments/contrib/ogone/plugin.py, src/openforms/payments/contrib/ogone/tests/files/vcr_cassettes/OgoneClientTest/OgoneClientTest.test_com_title_unicode_chars.yaml, src/openforms/payments/contrib/ogone/tests/test_client.py, src/openforms/payments/contrib/ogone/tests/test_plugin.py, src/openforms/payments/contrib/ogone/typing.py, src/openforms/variables/service.py
Closes #3457
**Changes**
* Added support for TITLE and COM parameter templates
* Exposed config options in the frontend
Tested this end-to-end with our Ogone test account and works as expected - the custom description is evaluated and displayed in the transaction history.
**Checklist**
=> Support custom TITLE and COM parameters in Ogone payment plugin

src/openapi.yaml, src/openforms/analytics_tools/api/urls.py, src/openforms/api/urls.py, src/openforms/config/api/urls.py, src/openforms/submissions/api/viewsets.py
Part of #3283
**Changes**
* API endpoints are now consistently using dashes rather than underscores (except for the action prefix for non-REST endpoints)
* Removed obsolete redirect - the SDK has been updated
**Checklist**
=> :boom: Normalize api endpoints to kebab case

src/openforms/contrib/objects_api/json_schema.py, src/openforms/contrib/objects_api/tests/test_json_schema.py
Closes #4832
**Changes**
This change has been made because we are not able to know if the type is the correct one when no format is defined in the variable. This is left to the user and we assume that the mapping is valid.
**Checklist**
=> [#4832] Fix json schema matcher in Objects API

docs/installation/upgrade-300.rst, src/openforms/contrib/objects_api/models.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/objects_api/typing.py, src/openforms/registrations/contrib/zgw_apis/options.py
Closes #3283
**Changes**
* Documented how to migrate registration options
* Updated comments to reflect real scheduled version for removal
**Checklist**
=> :pencil: [#3283] Document registration backend migration procedure

src/openforms/scss/components/admin/_ReactModal.scss
Closes #4949
**Changes**
The modal close button changes color based on the light/dark mode of the page.
In addition, focus now increases the button opacity, making it more visible and user-friendly
**Checklist**
=> Modal close button on dark mode

src/openforms/contrib/brk/service.py, src/openforms/contrib/brk/tests/base.py, src/openforms/contrib/brk/validators.py, src/openforms/emails/tests/test_digest_functions.py, src/openforms/emails/tests/test_tasks_integration.py, src/openforms/forms/models/form.py
Closes #4821
**Changes**
- We want the email digest to report problems (broken configuration) for the addressNL component only when a valid BRK service and the validator are defined/configured.
**Checklist**
=> [#4821] Fixed email digest for BRK and addressNL component

src/openforms/registrations/contrib/objects_api/handlers/v2.py, src/openforms/registrations/contrib/objects_api/submission_registration.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV1Tests/ObjectsAPIBackendV1Tests.test_submission_with_objects_api_backend_override_defaults.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/ObjectsAPIBackendV2Tests/ObjectsAPIBackendV2Tests.test_submission_with_objects_api_v2.yaml, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
Closes #4955
**Changes**
Changes the order of the geometry coordinates data from `[lat, lng]` to `[lng, lat]`.
The coordinates that we receive from the map component are in [lat, lng] order. This same order was used when passing the coordinates to the Objects-api and zgw apis backends, but these expect the geometry data to adhere the geoJson geometry data (i.e. the coordinates in [lng, lat] order)
**Checklist**
=> Objects-api and zgw apis geometry coordinates data order

src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/EmployeeAuthContextTests/EmployeeAuthContextTests.test_record_auth_context_employee.yaml, src/openforms/authentication/contrib/org_oidc/tests/test_auth_context_data.py, src/openforms/authentication/models.py, src/openforms/authentication/types.py
Closes #4863
**Changes**
This should solve the problem of employee login on forms with the org-oidc auth plugin.
Currently this is a WIP. I'm not sure if this is the right approach, and solves the right issue (this might be a very superficial solution, but im not sure). This currently contains:
- Test that showcases the failing scenario
- Solution for employee_id authentication
(Which is highly experimental, and probably should/will change)
This that still should be done:
- Add employee id to user
- Use employee_id as identifier for employee case in `to_auth_context_data` 
(I think this requires passing employee id from the org-oidc plugin `handle_return()`)
**Checklist**
- I have updated the …
=> org-oidc auth plugin employee login

src/openforms/prefill/sources.py, src/openforms/prefill/tests/test_prefill_hook.py
Closes #4825
**Changes**
- Updated logging to only log empty data for the authentication flow that is used in the submission.
**Checklist**
=> [#4825] Log prefill retrieve empty only for the used authentication flow

src/openforms/authentication/contrib/org_oidc/tests/data/vcr_cassettes/EmployeeAuthContextTests/EmployeeAuthContextTests.test_record_auth_context_employee.yaml
**Changes**
This is created in order to fix the stable branch and has to do with the backport of PR 4959
**Checklist**
=> Fix CI test failing in `stable/2.8.x`

src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/form_logic.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py
previously the current step was inferred by looking at the last completed step and considering the step after that the current step. This does not work however if you complete a step and go back to the previous step, so instead we explicitly pass the current form step via the serializer context
Closes #4579
**Changes**
* Ensure triggerFromStep uses the correct current_step
**Checklist**
=> :bug: [#4579] Ensure triggerFromStep uses the correct current_step

docs/configuration/authentication/digid.rst, docs/configuration/authentication/eherkenning_eidas.rst, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
Partly closes #4785 
The documentation update is independent from the [library changes](https://github.com/maykinmedia/django-digid-eherkenning/pull/83), but it would be great if both are done in one go.
**Changes**
* Removed the warnings that configuration in the admin is not possible
* Added section about CSR generation
* Updated configuration steps with moved/new fields from django-digid-eherkenning library fields
**Checklist**
=> Update eherkenning docs

src/openforms/forms/tasks.py, src/openforms/forms/tests/variables/test_tasks.py
Closes #4900
**Changes**
* Recouple SubmissionValueVars for other forms in case of reusable FormDefinitions
**Checklist**
=> :bug: [#4900] Recouple SubmissionValueVars for other forms for reusable FormDefinitions

src/openforms/forms/admin/form_statistics.py, src/openforms/forms/admin/views.py, src/openforms/forms/forms/__init__.py, src/openforms/forms/forms/form_statistics.py, src/openforms/forms/statistics.py, src/openforms/forms/templates/admin/forms/formstatistics/change_list_object_tools.html, src/openforms/forms/templates/admin/forms/formstatistics/export_form.html, src/openforms/forms/tests/admin/test_form_statistics.py, src/openforms/logging/logevent.py
Closes #4930
**Changes**
* Added custom admin page and link to it from the form statistics
* Implemented exporting submission statistics based on timeline logs
**Checklist**
=> Enable exporting (registered) submission metadata

src/openapi.yaml, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/api/serializers/form_step.py, src/openforms/forms/utils.py, src/openforms/translations/api/serializers.py
This was left-over from the previous version of component translations, but those are now baked into each component itself.
**Checklist**
=> :fire: Delete component_translations serializer fields

src/openforms/authentication/templates/of_authentication/registrator_subject_info.html, src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/email/tests/test_backend.py, src/openforms/templates/includes/forms/radio.html, src/openforms/ui/static/ui/scss/components/_index.scss, src/openforms/utils/templates/of_utils/widgets/radio_option.html
Closes #4650
**Changes**
* Fixed styling issue in registrator info template
* Fixed registration plugin issue when objects prefill is used
**Checklist**
=> Fix bugs in email registraton + objects API prefill combination

src/openforms/formio/api/validators.py
Closes #4795 (noticed the code structure when working on that ticket)
**Changes**
* Uses pattern matching for the pre/post-processing for certain edge cases
* Added support for libmagic 5.46 edge case w/r to zip files
**Checklist**
=> Restructure file validation code

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/RegistrationFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/AuthAttributePath.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/index.js, src/openforms/js/components/admin/form_design/registrations/zgw/ZGWOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/story-decorators.js, src/openforms/js/components/admin/form_design/variables/prefill/objects_api/ObjectsAPIFields.js, src/openforms/js/components/admin/forms/Field.stories.js, src/openforms/js/components/admin/forms/objects_api/AuthAttributePath.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
**Changes**
* Provide help text as prop to component instead of baking it in
* Tweak labels/help texts
**Checklist**
=> :speech_balloon: Tailor field help texts to registration/prefill context

src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/js/components/admin/form_design/data/complete-form.js
Closes #4969 (partially)
**Changes**
Fixed backend call to avoid sending stale counter data.
**Checklist**
=> Fix accidental submission counter reset

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.stories.js, src/openforms/registrations/contrib/objects_api/config.py
This is the first step towards deprecating/removing the template based configuration. Users now see the v2 configuration as default/first configuration option.
Closes #4978 (partly)
**Changes**
* Swapped around the legacy/variable mappings tab
* Made the variables (v2) registration the default instead of legacy template based config.
**Checklist**
=> :wastebasket: [#4978] Make v2 Objects API config the default

.storybook/main.js, src/openforms/js/components/admin/BooleanIcons.mdx, src/openforms/js/components/admin/BooleanIcons.stories.js
=> :pencil: Document boolean icons in admin

src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiSummaryHandler.js, src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiVariableConfigurationEditor.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
Closes #4978 (partially)
**Changes**
Variables with empty keys are not usable so these are now excluded from the `isGeometry` checks.
**Checklist**
=> Avoid empty variables being marked as geometry fields (objects API registration)

docker/ci/config.json
Removed 2.7.x from the config file that generates the docker hub description - yesterday's patch release was the final one.
=> :wrench: Remove 2.7.x from Docker hub description

.github/workflows/ci.yml, requirements/ci.txt, requirements/dev.txt, requirements/type-checking.txt
See if this allows us to run on Ubuntu 24.04 runners instead of having to pin to an older version.
=> :arrow_up: Bump playwright to latest version

src/openapi.yaml, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/PluginWarning.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/prefill/api/serializers.py, src/openforms/prefill/api/tests/test_endpoints.py, src/openforms/prefill/base.py, src/openforms/prefill/contrib/haalcentraal_brp/plugin.py, src/openforms/prefill/contrib/haalcentraal_brp/tests/test_co_sign.py, src/openforms/prefill/contrib/kvk/plugin.py, src/openforms/prefill/contrib/stufbg/plugin.py, src/openforms/prefill/contrib/stufbg/tests/test_co_sign.py, src/openforms/prefill/contrib/suwinet/plugin.py, src/openforms/prefill/fields.py, src/openforms/prefill/sources.py, src/openforms/prefill/tests/test_prefill_hook.py
Closes #4825 
**Changes**
- Run prefill plugin only when the authentication type matches the plugin's requirements. 
**Checklist**
=> [#4825] Fix prefill when authentication is needed

src/openapi.yaml, src/openforms/config/api/serializers.py, src/openforms/contrib/kadaster/api/serializers.py, src/openforms/contrib/zgw/api/filters.py, src/openforms/contrib/zgw/api/serializers.py, src/openforms/contrib/zgw/serializers.py, src/openforms/formio/components/vanilla.py, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/api/serializers/form_step.py, src/openforms/prefill/api/serializers.py, src/openforms/registrations/contrib/objects_api/config.py, src/openforms/registrations/contrib/zgw_apis/options.py, src/openforms/submissions/api/serializers.py, src/openforms/utils/checks.py, src/openforms/validations/api/serializers.py
Closes #4927
**Changes**
* Add system check for missing allow_blank on non-required charfields
**Checklist**
=> :loud_sound: [#4927] Add system check for missing allow_blank on non-required charfields

src/openforms/js/components/admin/forms/ReactSelect.js, src/openforms/js/components/admin/forms/VariableSelection.js, src/openforms/js/components/admin/forms/VariableSelection.stories.js
Part of #4908, where multi-selection of the variables is needed.
**Changes**
Add support for multi-selection in SelectWithoutFormik component
**Checklist**
=> Add possibility to enable multi-selection in SelectWithoutFormik

docs/conf.py
Fixes documentation build. Linkcheck doesn't like GitHub anchors, see https://github.com/pypa/packaging.python.org/issues/1272 and https://github.com/sphinx-doc/sphinx/issues/9016
=> :green_heart: Ignore GitHub links with anchors in linkcheck

src/openforms/forms/context_processors.py, src/openforms/forms/templates/forms/sdk_info_banner.html, src/openforms/forms/templates/forms/sdk_snippet.html, src/openforms/static/sdk-wrapper.mjs, src/openforms/utils/tests/test_sdk_urls.py, src/openforms/utils/views.py
Partly closes open-formulieren/open-forms-sdk#76 - Depends on https://github.com/open-formulieren/open-forms-sdk/pull/777
**Changes**
* Added a module entrypoint that will be used by modern browsers
* Kept the fallback for older browsers that don't support modules
I'm not yet updating the documentation for how to embed the SDK until this is out of experimental phase.
**Checklist**
=> Opt-in to ESM bundle of SDK

docker/docker-compose.referentielijsten.yml, docker/referentielijsten/README.md, docker/referentielijsten/docker-init-referentielijsten-db/0001-docker-init-referentielijsten-db.sql, docker/referentielijsten/fixtures/referentielijsten_fixtures.json, pyright.pyproject.toml, src/openforms/contrib/referentielijsten/client.py, src/openforms/formio/dynamic_config/dynamic_options.py, src/openforms/formio/dynamic_config/referentielijsten.py, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/RadioReferentielijstenOptionsTests/RadioReferentielijstenOptionsTests.test_items_not_found.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/RadioReferentielijstenOptionsTests/RadioReferentielijstenOptionsTests.test_success.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/SelectReferentielijstenOptionsTests/SelectReferentielijstenOptionsTests.test_items_not_found.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/SelectReferentielijstenOptionsTests/SelectReferentielijstenOptionsTests.test_success.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/SelectReferentielijstenOptionsTests/SelectReferentielijstenOptionsTests.test_table_with_paginated_items.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/SelectboxesReferentielijstenOptionsTests/SelectboxesReferentielijstenOptionsTests.test_items_not_found.yaml, src/openforms/formio/dynamic_config/tests/files/vcr_cassettes/SelectboxesReferentielijstenOptionsTests/SelectboxesReferentielijstenOptionsTests.test_success.yaml, src/openforms/formio/dynamic_config/tests/test_referentielijsten_config.py, src/openforms/formio/typing/base.py, src/openforms/logging/logevent.py, src/openforms/logging/templates/logging/events/referentielijsten_failure_response.txt
Closes #4993
**Changes**
* Implement fetching select(boxes) options from Referentielijsten
* Add docker-compose file and fixtures for Referentielijsten
**Checklist**
=> :sparkles: [#4993] Implement fetching select(boxes) options from Referentielijsten

src/openforms/js/components/admin/form_design/variables/VariablesEditor.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/utils.js, src/openforms/registrations/management/commands/register_submission.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/rendering/renderer.py, src/openforms/submissions/tests/test_models.py
Closes #5035 
**Changes**
* Fixed wrong `FormVariable` records being created for components inside repeating groups
* Fixed unintended mutation adding the components of step 2-end to the configuration of step 1, leading to extra keys being submitted in the Objects API registration (legacy)
* Small quality of life thing: display the variable count on each tab in the variables editor
* Small refactor: removed some code duplication
The regression test + bugfix can be cherrypicked to the stable/3.0.x branch for backport purposes, the rest is for the main branch.
**Checklist**
=> Fix accidental mutation side effect breaking the Objects API v1 registration

src/openforms/tests/e2e/test_input_validation.py
Closes #...
**Changes**
**Checklist**
=> Fix CI e2e test input validation failure in addressNL

src/openforms/tests/e2e/test_input_validation.py
Linked to SDK PR [#790](https://github.com/open-formulieren/open-forms-sdk/pull/790)
**Changes**
Fix for ci e2e test
**Checklist**
=> Fix AddressNL ci e2e test

src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v1.py, src/openforms/registrations/contrib/objects_api/tests/test_backend_v2.py
Closes #5034
**Changes**
- Added regression tests
- Updated object ownership validation to be triggered only when the object needs update 
**Checklist**
=> [#5034] Fix object ownership in Objects API

src/openforms/formio/formatters/custom.py, src/openforms/submissions/tests/test_tasks_pdf.py
Closes #5037
**Changes**
- Added a regression test for generating pdf report
- Added check for a date passed to the `DateFormatter` and it's not a string
**Checklist**
=> [#5037] Fix wrong Date type

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml, src/openforms/__init__.py
Part of #5055
**Changes**
**Checklist**
=> Prepare patch release 2.8.4

pyright.pyproject.toml, src/openapi.yaml, src/openforms/submissions/api/fields.py, src/openforms/submissions/api/validation.py, src/openforms/submissions/api/validators.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/tests/test_submission_completion.py
Partly closes #4510 - this is necessary to be able to display proper error messages in the SDK.
The completion validation + communicating the status URL back to the frontend was a weird and unconventional construct. The API documentation was also outdated with what is actually being returned.
This has now been reworked and stabilized to ensure a consistent format of validation errors that can be picked up and processed by the frontend/SDK reliably.
**Changes**
* Reworked how we run final validation of a submission before completing it and processing it
* There's now a properly documented validation error structure for steps
* The statement checkboxes validation remains as is
* The in- and output serializers are now correctly documented
* If the form is configured to not allow submissions, …
=> Refactor the submission completion validation

src/openforms/scss/pdfs/_index.scss, src/openforms/scss/pdfs/_screen-reader.scss, src/openforms/submissions/templates/report/submission_report.html
Part of #4622 #5047
**Changes**
The previous textual alternative, using `aria-label`, wasn't targetable by screen readers (tested using the macOS VoiceOver screen reader). By providing the textual alternative as real content the screen reader can find and read the content.
**Checklist**
=> Accessible textual alternative for PDF logo

src/openforms/formio/components/vanilla.py, src/openforms/formio/constants.py, src/openforms/formio/dynamic_config/dynamic_options.py, src/openforms/formio/dynamic_config/tests/test_dynamic_options.py, src/openforms/formio/dynamic_config/tests/test_referentielijsten_config.py, src/openforms/formio/migration_converters.py, src/openforms/formio/rendering/tests/test_component_node.py, src/openforms/formio/tests/search_strategies.py, src/openforms/formio/tests/test_component_json_schemas.py, src/openforms/formio/tests/validation/test_editgrid.py, src/openforms/formio/tests/validation/test_radio.py, src/openforms/formio/tests/validation/test_selectboxes.py, src/openforms/formio/typing/base.py, src/openforms/forms/tests/e2e_tests/test_form_designer.py, src/openforms/forms/tests/test_json_schema.py, src/openforms/registrations/contrib/json_dump/plugin.py, src/openforms/registrations/contrib/json_dump/tests/test_backend.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/submissions/tests/test_submission_completion.py, src/openforms/submissions/tests/test_submission_step_validate.py, src/openforms/submissions/tests/test_tasks_pdf.py, src/openforms/tests/e2e/test_input_validation.py
Closes #5044 
**Changes**
* Add constant for dataSrc options
**Checklist**
=> :recycle: [#5044] Add constant for dataSrc options

src/openforms/conf/base.py, src/openforms/formio/rendering/default.py, src/openforms/formio/rendering/nodes.py, src/openforms/registrations/contrib/objects_api/tests/test_template.py
Reverts #4759.
DH is facing challenges with legacy forms while upgrading to 3.0 on a strict timeline. Because the forms haven't been migrated to variables mapping yet, this has a huge impact on downstream systems processing the submissions.
=> :rewind: Revert removal of DISABLE_SENDING_HIDDEN_FIELDS feature flag

src/openforms/forms/api/viewsets.py
Closes #5077
**Changes**
- Logic rules list in the admin was really slow as the logic rules increase because of the same queries happening for the form and the form step. Some joins were added in order to reduce the amount of the queries.
**Checklist**
=> [#5077] Improve performance in loading logic rules in admin

src/openforms/registrations/contrib/json_dump/plugin.py, src/openforms/registrations/contrib/json_dump/tests/files/vcr_cassettes/JSONDumpBackendTests/JSONDumpBackendTests.test_components_with_form_variable_as_data_source_in_edit_grid_component.yaml, src/openforms/registrations/contrib/json_dump/tests/files/vcr_cassettes/JSONDumpBackendTests/JSONDumpBackendTests.test_file_in_edit_grid_component.yaml, src/openforms/registrations/contrib/json_dump/tests/test_backend.py
Closes #5065
**Changes**
Process edit grid components in the json dump registration backend
**Checklist**
=> Process edit grid components in the json dump registration backend

src/openforms/js/components/admin/form_design/logic/LiteralValueInput.js, src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/js/components/admin/forms/Field.js, src/openforms/js/components/admin/forms/Inputs.js
Closes #5093
**Changes**
Displaying the array fields below the `Use raw JSON input` checkbox in the form variable table.
**Checklist**
=> Wrapping array data fields in variable table

src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js, src/openforms/scss/components/admin/_fieldset.scss, src/openforms/scss/components/admin/_index.scss
Closes #5088 
**Changes**
Ensure `overflow: visible` is set for the metadata variables fieldset in the JSON Dump plugin
**Checklist**
=> Fix bug with collapsed metadata fieldset being hidden in JSON dump plugin

docs/developers/frontend/admin-styling.rst, docs/developers/frontend/index.rst, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/RegistrationFields.stories.js, src/openforms/js/components/admin/form_design/registrations/json_dump/fields/Variables.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/scss/components/admin/_index.scss, src/openforms/scss/components/admin/_json-dump-variables.scss
Closes #5066
**Changes**
Add button to quickly include all form variables in JSON dump plugin
**Checklist**
=> Add button to quickly include all form variables in JSON dump plugin

src/openforms/js/components/admin/form_design/variables/RegistrationVariables.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
Closes #4990
**Changes**
In the registration variables table, the plugin fieldset is now only hidden if there is only one configured backend, or if all the configured backends are of the same type.
**Checklist**
=> Change when plugin fieldset is hidden in registration variables table

src/openforms/formio/datastructures.py
No related issue
**Changes**
Bypass glom in `FormioData.__setitem__` for top-level keys (more info is in the commit message).
**Checklist**
=> Optimize formio data access

src/openforms/js/components/formio_builder/WebformBuilder.js
Closes #5090
**Changes**
Made `softReuiredErrors` always non required
**Checklist**
=> [#5090] Make `softRequiredErrors` component always non required

src/openforms/js/components/admin/form_design/RegistrationFields.stories.js, src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js
Closes #5039
**Changes**
- Email registration used `nonField` errors for a combination of fields and these were not shown on the frontend. Fixed these by showing them on the top of the modal.
**Checklist**
=> [#5039] Fix email registration errors

CHANGELOG.rst, docs/installation/config.rst, src/openforms/conf/base.py
**Changes**
Setting env variable EMAIL_TIMEOUT to be defined during deployment.
[It was requested by the people from Het Hogeland]
Taiga Hogeland 54
=> Adding email timeout env variable

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/submissions/admin.py
Closes open-formulieren/security-issues#34
**Changes**
The submission report content is now read-only in the admin
**Checklist**
=> Read only submission report content

src/openforms/emails/tests/test_send_mail_html.py, src/openforms/logging/constants.py, src/openforms/logging/logevent.py, src/openforms/submissions/admin.py, src/openforms/submissions/tests/test_admin.py
Closes #4518
**Changes**
Some AVG logs are needed in the submission admin inline logging so decided to return a queryset based on the included tags and not the other way around. This let us have events with multiple tags and choose which ones we need according to the context.
**Checklist**
=> [#4518] Add log entries for prefill to Submission

docker/docker-compose.referentielijsten.yml, docker/referentielijsten/fixtures/referentielijsten_fixtures.json, src/openapi.yaml, src/openforms/api/urls.py, src/openforms/api/utils.py, src/openforms/contrib/referentielijsten/api/serializers.py, src/openforms/contrib/referentielijsten/api/views.py, src/openforms/contrib/referentielijsten/client.py, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabellenEndpointTests/ReferentielijstTabellenEndpointTests.test_referentielijsten_api_returns_404.yaml, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabellenEndpointTests/ReferentielijstTabellenEndpointTests.test_returned_tabellen_have_the_right_properties.yaml, src/openforms/contrib/referentielijsten/tests/test_tabellen_list.py, src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/components/formio_builder/referentielijsten.js, src/openforms/services/api/serializers.py, src/openforms/services/api/viewsets.py, src/openforms/services/tests/test_api_list.py
Closes #5016 partially
**Changes**
* Add Referentielijsten service select to builder
* Modify Services endpoint to allow filtering by `referentielijsten`
* Add endpoint to retrieve referentielijst tabellen
**Checklist**
=> :sparkles: [#5016] Add Referentielijsten service select to builder

src/openforms/config/tests/test_global_configuration.py, src/openforms/config/tests/test_theme.py, src/openforms/utils/fields.py, src/openforms/utils/form_fields.py, src/openforms/utils/sanitizer.py, src/openforms/utils/tests/test_sanitizer.py
Closes open-formulieren/security-issues#35
**Changes**
Added svg sanitizing to `SVGOrImageField`
**Checklist**
=> svg sanitizing 

src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/admin/form_design/Tab.js, src/openforms/js/components/admin/form_design/logic/DSLEditorNode.js, src/openforms/js/components/admin/form_design/logic/actions/Action.stories.js, src/openforms/js/components/admin/form_design/logic/actions/Actions.js, src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js, src/openforms/js/components/admin/form_design/logic/actions/types.js, src/openforms/js/components/admin/form_design/variables/prefill/objects_api/ObjectsAPIFields.js, src/openforms/js/components/admin/forms/FormRow.js, src/openforms/js/components/admin/forms/VariableMapping.js, src/openforms/js/components/admin/forms/VariableMapping.stories.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json, src/openforms/scss/components/admin/_variablemapping.scss, src/openforms/scss/components/builder/_builder.scss
Closes #4871
**Changes**
Showing error messages in the variable mapping for Objects API and DMN. 
**Checklist**
=> Showing error messages in variable mapping

src/openforms/formio/formatters/base.py, src/openforms/formio/formatters/formio.py, src/openforms/submissions/templates/report/submission_report.html, src/openforms/submissions/tests/test_tasks_pdf.py
Closes #5047
**Changes**
- Added semantic relationships between field label and field content.
- When a field is left empty by the user, the submission report will display 'No information provided' in place of the missing field content.
- Removed leading and trailing whitespace in pdf metadata title
**Checklist**
=> Accessibility improvements for submission report pdf

bin/report_component_problems.py, package-lock.json, package.json, src/openforms/formio/typing/base.py, src/openforms/forms/api/serializers/form_definition.py, src/openforms/forms/sanitizer.py, src/openforms/forms/tests/test_api_formdefinition.py, src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/utils/sanitize.js, src/openforms/utils/sanitizer.py
Closes open-formulieren/security-issues#36
**Changes**
Added a simplistic sanitize function that sanitizes component label, tooltip and description when saving the component. This function allows a list of HTML tags and attributes, based on what formbuilders are currently using. Any html tags/attributes, that aren't in the allow list, are removed (only their content remains).
**Checklist**
=> Sanitizing HTML from component label, tooltip and description

src/openforms/js/components/admin/form_design/variables/RegistrationVariables.js, src/openforms/js/components/admin/form_design/variables/StaticData.js, src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js, src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/scss/components/admin/_variables-table.scss
~~Closes~~ clears up a post it on my desk - small quality of life update
**Changes**
* Group variables by step in the variables editor
* Removed the "form definition" column in variables table
* Fixed storybook stories that were missing step context
* Added `code` markup to variable key
**Checklist**
=> Group variables by step

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
Closes #5136 
**Changes**
* Upgrade to django-digid-eherkenning 0.20.0
* Upgrade to lxml 5.3.1
**Checklist**
=> Upgrade django-digid-eherkenning

Dockerfile, bin/fix_objects_api_form_registration_variables_mapping.py, bin/report_form_registration_problems.py, src/openforms/forms/tests/files/vcr_cassettes/ImportObjectsAPITests/ImportObjectsAPITests.test_import_form_with_objects_registration_backend_no_version_and_no_variables_mapping.yaml, src/openforms/forms/tests/files/vcr_cassettes/ImportObjectsAPITests/ImportObjectsAPITests.test_import_form_with_objects_registration_backend_with_valid_variables_mapping.yaml, src/openforms/forms/tests/files/vcr_cassettes/ImportObjectsAPITests/ImportObjectsAPITests.test_import_form_with_objects_registration_backend_without_variables_mapping.yaml, src/openforms/forms/tests/test_import_export.py, src/openforms/forms/utils.py, src/openforms/registrations/contrib/objects_api/config.py
Closes #5031
**Changes**
The bug was already fixed by a previous PR (https://github.com/open-formulieren/open-forms/pull/5021). This PR adds a detection and a fix script, so that we can monitor and fix affected form registration backends.
**Checklist**
=> Fix missing variables mapping in objects api registration (v2)

src/openforms/submissions/api/validators.py, src/openforms/submissions/tests/test_submission_step_validate.py
Closes #5124 
**Changes**
- When  a component (or its parent is disabled and hidden, the validation in the backend is triggered since there is no data for the specific key. This means, for our validator, that the data has been changed and raises an error.
- Additional  test for the case someone omits the submission data (affects the prefill data).
**Checklist**
=> [#5124] Hidden/disabled prefill fields trigger validation

docker/referentielijsten/fixtures/referentielijsten_fixtures.json, package-lock.json, package.json, src/openapi.yaml, src/openforms/api/urls.py, src/openforms/contrib/referentielijsten/api/serializers.py, src/openforms/contrib/referentielijsten/api/views.py, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabelItemsEndpointTests/ReferentielijstTabelItemsEndpointTests.test_empty_tabel_items.yaml, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabelItemsEndpointTests/ReferentielijstTabelItemsEndpointTests.test_invalid_tabel_item.yaml, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabelItemsEndpointTests/ReferentielijstTabelItemsEndpointTests.test_referentielijsten_api_returns_404.yaml, src/openforms/contrib/referentielijsten/tests/files/vcr_cassettes/ReferentielijstTabelItemsEndpointTests/ReferentielijstTabelItemsEndpointTests.test_returned_tabel_items_have_the_right_properties.yaml, src/openforms/contrib/referentielijsten/tests/test_tabel_items.py, src/openforms/contrib/referentielijsten/tests/test_tabellen_list.py, src/openforms/js/compiled-lang/en.json, src/openforms/js/compiled-lang/nl.json, src/openforms/js/components/formio_builder/WebformBuilder.js, src/openforms/js/components/formio_builder/referenceLists.js, src/openforms/js/components/formio_builder/referentielijsten.js, src/openforms/js/lang/en.json, src/openforms/js/lang/nl.json
Closes #5107
Closes #5105
**Changes**
- Added endpoint for retrieving the list of tabel items
**Checklist**
=> [#5107] Display referentielijsten options in component's preview

src/openforms/contrib/zgw/clients/catalogi.py, src/openforms/contrib/zgw/tests/test_catalogi_client.py
Closes #5162
Before this patch, the behaviour was to outright reject non-standard compliant responses, since the API specifications for the ZGW API's (managed by VNG) are strictly versioned according to semver. Certain features are available only starting with certain versions, and we adapt our client behaviour to be as efficient as possible based on this API version. It is nonsense for an API server to reply with a version number that is not published by VNG on the documentation site https://vng-realisatie.github.io/gemma-zaken/standaard/.
That said, Dimpact is in a pickle because a vendor is not behaving according to the standard, triggering this hard rejection in Open Forms, and said vendor is not able to patch their own systems in time for a particular release time line. We agreed to …
=> [stable/2.8.x] Don't error hard on API standard violations

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
Closes #4937
Kombu is the underlying transport library used by Celery and v5.4.0 should fix the redis stability errors where workers cannot reconnect after connection loss to redis. It should work with Celery 5.4 and we should not need to wait for Celery 5.5 to get this fix.
This problem and fix are tough to validate so we'll just have to try it out. Team Bron also bumped Kombu in Open Zaak etc.
If it's stable, we could also backport this, but let's hold off on that and validate that we don't get new issues.
**Checklist**
=> :arrow_up: Bump kombu to 5.4+

src/openforms/forms/tests/e2e_tests/test_form_designer.py
Avoids a race condition where the DB transaction was not saved yet by the API call made through the Javascript before asserting the DB state.
The page.wait_for_url was probably a no-op because the page URL is already satisfied when editing a form and reloading that same page. This is mitigated by hitting the save that redirects to the form list page, which has a different URL and provides stronger guarantees that the changes have been persisted in the database.
=> Fix test flakiness

src/openforms/formio/components/vanilla.py, src/openforms/formio/tests/validation/test_selectboxes.py, src/openforms/submissions/tests/test_submission_step_validate.py
Closes #4662 
Closes #5147
**Changes**
- Added missing check for optional field with no submitted values
**Checklist**
=> [#4662, #5147] Fix validation for `selectboxes` with no submitted values

bin/report_component_problems.py, src/openforms/formio/constants.py, src/openforms/formio/utils.py, src/openforms/js/components/form/map.js, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/tests/e2e/input_validation_base.py, src/openforms/tests/e2e/test_input_validation.py
Closes #5151
**Changes**
If a map component is `hidden` (with `clearOnHide` set to `True`), the check-logic call would return an empty value for the map component. This empty value would then in turn be merged into the SDK form data. If we then click on "next step", the form data will be validated and the empty value for the map component won't be conform the map component serializer validation, causing errors the user cannot fix (and locking the form).
The only correct empty value for a map component, is **NO** value.
These changes make sure that missing map components don't receive empty object values. Ensuring that forms cannot be locked by hidden and empty map components.
**Checklist**
- …
=> Hidden map fails form validation

docs/developers/embedding.rst, src/openforms/forms/templates/forms/sdk_snippet.html, src/openforms/static/sdk-wrapper.mjs
Closes #5155
Depends on open-formulieren/open-forms-sdk#809
**Changes**
Add initial data reference query parameter in `onLanguageChange` callback
**Checklist**
=> Add initial data reference query parameter in `onLanguageChange` callback

src/openforms/logging/models.py, src/openforms/logging/templates/logging/events/registration_debug.txt, src/openforms/submissions/admin.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/tests/test_admin.py
Closes #5186
**Changes**
* 'Fixed' the template for registration debug logs
* Avoid logging the dynamic lookup for the admin display, as this creates confusion.
**Checklist**
=> Fix excessive logging of the registration backend resolution

src/openforms/js/components/admin/form_design/variables/VariablesTable.js, src/openforms/scss/components/admin/_variables-table.scss
Closes #5184
This is a bandaid fix to hold us over until the redesign, creating sufficient space for the json widget to not overflow.
**Checklist**
=> Set a minimum width for the variable value column

src/openforms/authentication/templates/of_authentication/registrator_subject_info.html, src/openforms/submissions/templates/submissions/find_submission_for_cosign.html, src/openforms/templates/includes/cookie-notice.html, src/openforms/ui/static/ui/scss/components/cookie-notice/_index.scss
Closes #5192
**Changes**
- Applied `utrecht-button-group` to cosign, cookies and registrator buttons. All these were using the old way of structuring the buttons (toolbar).
**Checklist**
=> [#5192] Fix buttons in cosign,cookies and registrator

src/openforms/prefill/contrib/demo/plugin.py
Closes #5185
**Changes**
Added all the available auth attributes so that the plugin always runs.
**Checklist**
=> Fix broken demo prefill plugin

src/openforms/registrations/contrib/json_dump/plugin.py, src/openforms/registrations/contrib/json_dump/tests/files/vcr_cassettes/JSONDumpBackendTests/JSONDumpBackendTests.test_hidden_field_not_in_schema.yaml, src/openforms/registrations/contrib/json_dump/tests/test_backend.py
Partly closes #5205
**Changes**
Fields that are not present in the submission data are no longer added to the schema in the JSON dump plugin
**Checklist**
=> Fix hidden fields present in JSON schema

src/openforms/forms/json_schema.py, src/openforms/forms/tests/test_json_schema.py
Partly closes #5205 
**Changes**
The required property now accurately reflects the variables that are in the schema
**Checklist**
=> Fix non-existing variables being included in the required property of JSON schema

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/submissions/tests/test_submission_step_validate.py
Closes #5191 (partly)
**Changes**
Fixed the underlying bug in drf-polymorphic, and updated the version.
The polymorphic serializer was added after 3.0 was released, so no backports needed for this.
**Checklist**
=> Fix validation crash when a map component value is cleared/empty

.github/workflows/ci.yml
Use the `[skip: e2e]` fragment in the PR body or, when pushing a commit directly, in the commit message.
Note that you can't include it in a commit message for a PR, as this is not exposed in the PR context easily. So it *must* go in the body of the PR description.
=> :technologist: Allow skipping e2e tests in PRs/commits

docs/configuration/registration/camunda.rst, src/openforms/registrations/contrib/camunda/plugin.py
Partly closes #5223
**Changes**
* Added deprecation marker in code
* Added deprecation notice to the docs
**Checklist**
=> Deprecate the Camunda registration backend

CHANGELOG.rst, Dockerfile, bin/delete_empty_api_groups.py
Closes #5229 
**Changes**
* Added one-off script to remove ZGW API groups
* Added changelog instructions
There is no output if nothing was done, if groups were deleted the output looks like:
```
Deleting 1 Objects API Group(s) with IDS: 1
Deleting 1 ZGW API Group(s) with IDS: 1
```
**Checklist**
=> Distribute script to remove empty API groups

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
Closes #5060 (partially)
**Changes**
We upgraded kombu earlier, which should have fixed the reliability issues, but now Celery 5.5 is out we can finally upgrade the whole stack.
**Checklist**
=> Upgrade Celery and related dependencies

package-lock.json, package.json, src/openforms/authentication/templates/of_authentication/registrator_subject_info.html, src/openforms/submissions/templates/submissions/find_submission_for_cosign.html, src/openforms/templates/cookie_consent/cookiegroup_list.html, src/openforms/templates/includes/a11y_toolbar.html, src/openforms/templates/includes/cookie-notice.html, src/openforms/templates/includes/page-footer.html, src/openforms/templates/includes/page-header.html, src/openforms/ui/static/ui/scss/_defaults.scss, src/openforms/ui/static/ui/scss/_nlds.scss, src/openforms/ui/static/ui/scss/components/_auth-mode.scss, src/openforms/ui/static/ui/scss/screen.scss, src/openforms/ui/templates/ui/views/abstract/list.html, src/openforms/ui/templatetags/style_dictionary.py
Closes #4917 - requires the SDK PR https://github.com/open-formulieren/open-forms-sdk/pull/817
**Changes**
* Updated all our own HTML markup in Django templates to properly reflect the same markup as emitted by the react components
* Handled the subject registrator info page
* Handled the cosign submission lookup
* Fixed the cookie notice button alignment - those should not be stacked, that banner already takes up way too much vertical space
* Tweaked the styling/spacing of the subject registrator info page to be a bit more compact
* Provided some basic styles that should be overridden as soon as a theme specifies the same design token. This should cover 90% of the existing themes to be presentable.
Note: the DH logout button/link color can't be fixed from our perspective, they'll have to …
=> Ensure backwards compatibility button link styles

src/openforms/formio/components/custom.py, src/openforms/formio/tests/test_component_json_schemas.py, src/openforms/forms/json_schema.py, src/openforms/utils/json_schema.py
Closes #5027
[skip: e2e]
**Changes**
Update the JSON schema of the map component to include line and polygon shapes
**Checklist**
=> Support broader range of geojson in schema generation

docker/open-zaak/fixtures/open_zaak_fixtures.json, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/ZGWBackendVCRTests/ZGWBackendVCRTests.test_create_zaak_with_kvk_initiator_only_and_legacy_config.yaml, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/ZGWBackendVCRTests/ZGWBackendVCRTests.test_create_zaak_with_natuurlijk_persoon_initiator_and_legacy_config.yaml, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/ZGWBackendVCRTests/ZGWBackendVCRTests.test_create_zaak_with_vestiging_and_kvk_initiator_and_legacy_config.yaml, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/ZGWBackendVCRTests/ZGWBackendVCRTests.test_submission_with_multiple_eigenschappen_creation.yaml, src/openforms/registrations/contrib/zgw_apis/tests/files/vcr_cassettes/ZGWBackendVCRTests/ZGWBackendVCRTests.test_submission_with_nested_component_columns_and_eigenschap.yaml, src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
Closes #5239
[skip: e2e]
**Changes**
* Converted (some) legacy tests to use VCR.py instead of mocks, most notably the flaky test.
* Discovered a whole bunch of other issues :cry: 
* Fixed missing `kvkNummer` for `vestiging` resource
**Checklist**
=> Replace mock-based ZGW tests with VCR tests

src/openforms/formio/datastructures.py, src/openforms/formio/tests/test_datastructures.py, src/openforms/registrations/contrib/objects_api/handlers/v2.py, src/openforms/registrations/contrib/objects_api/submission_registration.py
Closes #5179
**Changes**
Remove usage of `glom` from `__getitem__` and `__setitem__` in `FormioData`
**Checklist**
=> Remove `glom` usage from `FormioData`

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt, src/openforms/conf/base.py, src/openforms/fixtures/admin_index_unlisted.json, src/openforms/upgrades/script_checks.py, src/openforms/upgrades/tests/test_upgrade_paths.py
[skip: e2e]
**Changes**
* Add django-upgrade-check, which is an iteration of `openforms.upgrades`
* Configure it for 3.2.0, but at the moment it doesn't do anything because we don't have version history
* Re-implement running our `bin` check scripts for the expected django-upgrade-check interface
For the 3.1.0/3.2.0 release cycle, this initially has no effect (not for existing, nor fresh instances) because the version/deploy
history table is empty. Once we're in 3.3.0 release, existing instances will be on 3.2.0 and then we can drop our own `openforms.upgrades` in favour of the library.
**Checklist**
- …
=> Start migration to django-upgrade-check

src/openforms/fixtures/default_admin_index.json
Closes #5202 
**Changes**
- Remove `AppointmentsInfo` from `Submission` in the admin fixture 
**Checklist**
=> [#5202] Remove AppointmentsInfo from Submission (admin fixture)

docker/json-dump/app.py, src/openforms/registrations/contrib/json_dump/plugin.py, src/openforms/registrations/contrib/json_dump/tests/test_backend.py
Closes #5263
[skip: e2e]
**Changes**
Removed the double JSON encoding in the JSON registration plugin
**Checklist**
=> Fix JSON dump plugin encodes data to JSON twice

src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js
Closes #5245
**Changes**
- Fixed index of the backend used in the registration (variables tab)
Mapping a variable to a specific registration backend was not properly saved. When we modify a variable the target of this change is the backend which is found by the name. This name contained the wrong index number of the backend so it was replacing other backends.
**Checklist**
=> [#5245] Fix wrong backend in the registration mapping (variables tab)

src/openforms/ui/templatetags/style_dictionary.py, src/openforms/ui/tests/test_style_dictionary.py
The previous code assumed values were always strings, but they can technically also be numbers, null or booleans, as those are the valid JSON primitives.
Was reported via Sentry for DH.
**Checklist**
=> :bug: Fix HTML sanitization of design tokens

src/openapi.yaml, src/openforms/formio/api/fields.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/logic/actions.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/tests/renderer/test_renderer.py, src/openforms/submissions/tests/test_submit_form_step.py, src/openforms/submissions/tests/test_variables/test_num_queries.py, src/openforms/submissions/tests/test_variables/test_variable_injection.py, src/openforms/tests/e2e/test_fill_in_form.py
Closes #5300
**Changes**
* Change the `data` field of `SubmissionStepSerializer` and `FormDataSerializer` to a `FormioDataField`
* Added missing `FormioData` when setting data to `SubmissionStep.data`
* Fix typo in name of serializer
**Checklist**
=> Fix nested submission data is not saved

src/openforms/conf/utils.py
Closes #5285
**Changes**
Disable sending log events to Sentry, but keep the breadcrumbs from logging calls that lead to an exception.
**Checklist**
=> :mute: [#5285] Silence log events in Sentry

src/openforms/registrations/contrib/objects_api/plugin.py, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingRegressionTests/JSONTemplatingRegressionTests.test_object_nulls_regression.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingRegressionTests/JSONTemplatingRegressionTests.test_opt_out_of_sending_hidden_fields.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingTests/JSONTemplatingTests.test_custom_template.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingTests/JSONTemplatingTests.test_default_template.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingTests/JSONTemplatingTests.test_submission_with_objects_api_content_json_exceed_max_file_limit.yaml, src/openforms/registrations/contrib/objects_api/tests/files/vcr_cassettes/JSONTemplatingTests/JSONTemplatingTests.test_submission_with_objects_api_content_json_not_valid_json.yaml, src/openforms/registrations/contrib/objects_api/tests/test_template.py, src/openforms/registrations/tasks.py
Closes #5285 [skip: e2e]
**Changes**
* Added more context and log entries
* Fixed non-VCR tests
* Added logs specifically for the Objects API registration
**Checklist**
=> Produce more useful logs in registrations process

src/openforms/forms/admin/form.py, src/openforms/forms/models/form.py
Closes #5283 
[skip: e2e]
**Changes**
Renamed and removed columns from forms list-view as follows:
Active and Maintenance mode columns removed - replaced with Live
Translation enabled column removed
Maximum allowed submissions column removed
Authentication backend(s) renamed to inloggen
Payment backend removed
Registration backend(s) renamed to registrations
**Checklist**
=> 🗒️ [#5283] Rename form list-view

src/openforms/forms/tests/e2e_tests/test_registration_backend_conf.py
These URLs apparently get triggered because of the WYSWIWYG editors that use a srcdoc attribute in an iframe. These must have a URL, and internally, browsers assign this the URL 'about:srcdoc' per spec.
These URLs also appear in the network calls of the browser and thus are picked up by Playwright. We are then in turn trying to resolve that URL to one of our own views, which fails of course.
These tests should no longer log that they're flaky, but let's observe for a while.
=> Ignore about:* urls when capturing requests in e2e tests

.github/workflows/ci.yml, openapitools.json, src/openapi.yaml, src/openforms/api/drf_spectacular/hooks.py, src/openforms/conf/base.py
The generation and linting of the OpenAPI spec can be replaced with a single re-usable workflow, while keeping the dependencies of the CI workflow to not push docker images until it's confirmed the API spec is valid.
[skip: e2e]
=> Replace OAS steps in CI with re-usable workflow

src/openforms/registrations/tasks.py, src/openforms/submissions/api/mixins.py
Logging these events will allow us to compare the volume over time with the success/failure registration to build monitoring dashboards.
[skip: e2e]
=> :loud_sound: Log submission completion events

docs/developers/releases.rst
Closes nothing
[skip: e2e]
**Changes**
Added information about Django Rosetta for backend translations to the release flow documentation.
**Checklist**
=> Update release flow documentation

src/openforms/contrib/haal_centraal/clients/brp.py, src/openforms/contrib/haal_centraal/data.py, src/openforms/prefill/contrib/family_members/plugin.py, src/openforms/prefill/contrib/family_members/tests/test_plugin.py, src/stuf/stuf_bg/data.py
Part of #5254
**Changes**
- Added missing field
- Make snake case to camel case for the frontend
**Checklist**
=> Fix results sent to the frontend in the family members prefill plugin

src/openforms/js/components/admin/form_design/variables/prefill/family_members/ChildrenFiltersFields.js, src/openforms/js/components/admin/form_design/variables/prefill/family_members/FamilyMembersFields.js, src/openforms/js/components/admin/form_design/variables/prefill/family_members/PersonsFields.js, src/openforms/js/components/admin/forms/Inputs.js
Formik takes care of the form state management/values - all you ideally need to do is pass the name of the form field and initialize the form values and then it handles all the change events.
Ideally you don't need to think about value or onChange anymore, and then it simplifies the prop-drilling you otherwise typically see.
[skip: e2e]
=> :art: Remove unnecessary props

src/openforms/conf/base.py, src/openforms/emails/tasks.py, src/openforms/emails/tests/test_tasks_integration.py
Closes #5326
**Changes**
- added new task copied from [yubin](https://github.com/APSL/django-yubin/blob/2dcb33d08a5c8a0001e1e5a6abd0b8d940afa0b6/django_yubin/models.py#L263) with `defer` to not fetch the `_message_data` from the db.
**Checklist**
=> Add new delete_old_emails task that does not fetch the message data.

src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/FamilyMembersPrefillPluginHCV2Tests.test_children_deceased.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/FamilyMembersPrefillPluginHCV2Tests.test_children_filtered_by_age.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/FamilyMembersPrefillPluginHCV2Tests.test_children_prefill_happy_flow.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/FamilyMembersPrefillPluginHCV2Tests.test_partners_prefill_happy_flow.yaml, src/openforms/prefill/contrib/family_members/tests/test_plugin.py
**Changes**
The tests were not reflecting what the family members plugin should do because they were testing the old functionality (user should add 2 user defined variables for enabling the family members plugin, but now the case is different. One user defined variable and the custom component partners are needed). See the docs for the plugin for all the instructions.
Of course, they were not failing because we can indeed prefill a user defined variable with a partner's data.
**Checklist**
=> Fix tests in family members prefill plugin

src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/GenericJSONBackendTests.test_partners_components_schema.yaml, src/openforms/registrations/contrib/generic_json/tests/test_backend.py
Closes #5268 partly
**Changes**
- Make sure custom partners component schema and values are correct in the Generic JSON registration
**Checklist**
=> [#5268] Test generic JSON registration with custom partners component

.github/workflows/ci.yml
* For the docs, this highlights failed link checks
* For the django tests, this may improve parsing test failures
**Checklist**
=> :technologist: Force colored output in github actions

src/openforms/payments/tests/test_e2e.py
In CI, there appears to be some label-overlap check with the checkbox sudo for the webkit browsers, which supposedly captures the click.
Verified against the webkit browser 'Browser' on Arch that clicks do properly propagate. There may be some minor overlap because the label sits flush against the border of the checkbox, while the checkbox has a padding of 2px to the right that may trigger this overlap detection.
Either way, the label is associated with the input, so that clicking the label actually toggles the checkbox anyway.
=> :green_heart: Fix e2e test on Webkit

src/openforms/js/components/admin/forms/ReactSelect.js
Partly closes #5140 
**Changes**
Allowing the ReactSelect component (with the build-in Formik support) to be used as multi select.
**Checklist**
=> Supporting multi select for the ReactSelect component

pyright.pyproject.toml, src/openapi.yaml, src/openforms/authentication/api/serializers.py, src/openforms/authentication/api/tests/test_endpoints.py, src/openforms/authentication/api/tests/test_logout.py, src/openforms/authentication/base.py, src/openforms/authentication/contrib/demo/plugin.py, src/openforms/authentication/contrib/digid/mixins.py, src/openforms/authentication/contrib/digid/plugin.py, src/openforms/authentication/contrib/digid/views.py, src/openforms/authentication/contrib/digid_eherkenning_oidc/plugin.py, src/openforms/authentication/contrib/digid_mock/plugin.py, src/openforms/authentication/contrib/eherkenning/plugin.py, src/openforms/authentication/contrib/org_oidc/plugin.py, src/openforms/authentication/contrib/outage/plugin.py, src/openforms/authentication/tests/mocks.py, src/openforms/authentication/tests/test_signals.py, src/openforms/authentication/views.py, src/openforms/js/components/admin/form_design/AuthPluginField.js, src/openforms/js/components/admin/form_design/AuthPluginOptions.js, src/openforms/js/components/admin/form_design/FormConfigurationFields.js, src/openforms/js/components/admin/form_design/FormConfigurationFields.stories.js, src/openforms/js/components/admin/form_design/PluginWarning.js, src/openforms/js/components/admin/form_design/authentication/digid/DigidOptionsForm.js, src/openforms/js/components/admin/form_design/authentication/digid/DigidOptionsFormFields.js, src/openforms/js/components/admin/form_design/authentication/digid/DigidOptionsFormFields.stories.js, src/openforms/js/components/admin/form_design/types/AuthPlugin.js, src/openforms/prefill/models.py, src/openforms/prefill/signals.py, src/openforms/prefill/validators.py
Part of #5132
[skip: e2e]
**Changes**
Widened the type of `BasePlugin.provides_auth` to a collection of auth attributes rather than a simple scalar, to facilitate Yivi.
=> Support multi-value `provides_auth`

src/openforms/authentication/contrib/eherkenning/constants.py, src/openforms/authentication/contrib/yivi_oidc/plugin.py, src/openforms/authentication/contrib/yivi_oidc/tests/test_plugin.py
Closes #5140
**Changes**
Add ``check_requirements`` method for the Yivi auth plugin.
**Checklist**
=> Add missing check_requirements for Yivi auth plugin

CHANGELOG.rst
Closes #5407 
**Changes**
Adds a warning notice for the 3.1.0 release regarding the possibility of a longer processing time when upgrading.
**Checklist**
=> [#5407] Add migration notice for 3.1.0

src/openforms/emails/digest.py, src/openforms/emails/tests/test_digest_functions.py
Closes #5340
**Changes**
* catch `StandardViolation` error during validation of `ZGWRegistration`
**Checklist**
=> [#5340] fix email_digest error

src/openforms/formio/components/custom.py, src/openforms/submissions/tests/test_submission_step_validate.py
Closes #5481
**Changes**
- The user defined variables in the partners validation were not based on the specific form (submission)
**Checklist**
=> [#5481] Fix old unmatched partners variables

src/openforms/formio/components/custom.py, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/test_children_deceased.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/test_children_filtered_by_age.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/test_children_prefill_happy_flow.yaml, src/openforms/prefill/contrib/family_members/tests/files/vcr_cassettes/FamilyMembersPrefillPluginHCV2Tests/test_partners_prefill_happy_flow.yaml, src/openforms/prefill/contrib/family_members/tests/test_plugin.py
**Changes**
- Found out that the serializer fields do not adhere to the data that we build in the `get_family_members` (BRP), so updated these to be required.
- Fixed some tests that didn't have the right component (partners)
**Checklist**
=> Make partners serializer fields more specific

src/openforms/js/components/admin/form_design/FormLogic.stories.js
The text *is* found, but not considered part of the document, which seems to not fall under the timeout requirements. Try now with waitFor, which will retry for 10s until the assertions inside pass.
[skip: e2e]
=> :green_heart: Attempt to address Chromatic flakiness

src/openforms/payments/contrib/worldline/plugin.py, src/openforms/payments/contrib/worldline/tests/test_plugin.py
Fixes the merchant reference not being saved after receiving the checkout status. Not sure how this got past[ this test though ](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/payments/contrib/worldline/tests/test_plugin.py#L161):thinking:.
[skip: e2e]
=> [#4879] save merchant reference

src/openforms/submissions/api/serializers.py, src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission_step.py, src/openforms/submissions/tests/form_logic/test_endpoint.py
Closes #5527
[skip: e2e]
**Changes**
Add flag to `SubmissionStateLogicSerializer` context to only return unsaved data
**Checklist**
=> Logic check returns all step data

bin/docker_start.sh, docker-compose.yml, docker-nginx-default.conf
Sparked by a production incident before my vacation.
Copying the static files to a volume shared with the nginx container makes it possible for nginx to serve the static files directly.
The mechanism is opt-in so that we can keep things backwards compatible. Possibly in 4.0 we remove the uwsgi --static-map option as it could mask potential issues, but that's just a thought at this time.
The recursive copy should be sufficiently safe even with race conditions between replicas:
* we use the manifest static file storage, which appends a unique hash to each static file
* the replicas deploy the same container version and the same set of static files is included in each, so even if one overwrites the other the end-result will be the same
* we don't perform file removal at all, so old versions …
=> Set up mechanism to serve static files via nginx instead of uwsgi

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/extensions.txt, requirements/type-checking.txt
Contains a bugfix for crash in anchor text processing, see Taiga Vught #100.
The breaking changes do not affect us at all.
**Checklist**
[skip: e2e]
=> Bump mail cleaner to 2.0.0

Dockerfile, bin/report_duplicate_merchant_pspids.py
Partially closes #5504
**Changes**
Adds a script which detects and outputs `Ogone Merchant`s with duplicate `pspid` values.
**Checklist**
[skip: e2e]
=> [#4879] pspid uniqueness script 3.1.x

src/openforms/config/apps.py, src/openforms/fixtures/default_map_tile_layers.json
Closes #5253 
[skip: e2e]
**Changes**
- Added more default map tile layers
- Ensured the fixtures are only loaded once when migrating the config app
**Checklist**
=> Add more default map tile layers

docker/docker-compose.redis-sentinel.yml, docker/redis/sentinel.conf, docker/redis/sentinel.primary.conf, docker/redis/sentinel.replica.conf, docs/installation/config.rst, docs/installation/redis.rst, src/openforms/celery.py, src/openforms/conf/base.py
Closes #5060
**Changes**
* Added sample docker compose for Redis Sentinel setup with 1 master and 1 replica
* Added code support for Sentinel to Celery broker and result backend configuration
* Updated the Redis documentation - restructured + added new information
- Restructured persistence configuration docs
- Added information about HA setup options
**Checklist**
[skip: e2e]
=> Support and document Highly Available Redis options

docs/manual/authenticatie.rst, src/openforms/authentication/contrib/yivi_oidc/oidc_plugins/plugins.py, src/openforms/authentication/contrib/yivi_oidc/tests/oidc_plugins/test_plugins.py, src/openforms/authentication/static_variables/static_variables.py, src/openforms/authentication/tests/test_static_variables.py, src/openforms/authentication/typing.py, src/openforms/contrib/auth_oidc/utils.py
Closes #5419 (partly)
**Changes**
Instead of processing the attributes *after* obtaining them from Yivi by replacing <kbd>.</kbd> with <kbd>_</kbd>, we transform the attributes into a nested object where each period indicates a level.
This makes them naturally available in the DTL via `{{ foo.bar }}` and in json logic with `{"var": "foo.bar"}`.
Historical data is not being updated as the Yivi feature released in 3.2 was still quite experimental.
**Checklist**
[skip: e2e]
=> Reshape Yivi attributes when storing them in the auth_info

src/openforms/registrations/contrib/generic_json/plugin.py, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_added_manually_and_selection_disabled.yaml, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_added_manually_and_selection_enabled.yaml, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_selection_disabled.yaml, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_selection_enabled.yaml, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_two_steps_and_selection_disabled.yaml, src/openforms/registrations/contrib/generic_json/tests/files/vcr_cassettes/GenericJSONBackendTests/test_children_components_schema_with_two_steps_and_selection_enabled.yaml, src/openforms/registrations/contrib/generic_json/tests/test_backend.py
Closes #5268 partly
**Changes**
- Removed unnecessary fields from the values and schema
- Added tests for both a children component and a form with 2 steps (children component and an extra step with an editgrid for the extra details)
**Checklist**
=> [#5268] Adapt generic JSON registration to custom children component

src/openforms/prefill/contrib/family_members/templates/family_members/tests/responses/stuf_bg_children.xml, src/openforms/prefill/contrib/family_members/templates/family_members/tests/responses/stuf_bg_children_incomplete_date_of_birth.xml, src/openforms/prefill/contrib/family_members/templates/family_members/tests/responses/stuf_bg_one_partner.xml, src/openforms/prefill/contrib/family_members/tests/test_plugin.py, src/stuf/stuf_bg/templates/stuf_bg/ChildrenStufBgRequest.xml, src/stuf/stuf_bg/templates/stuf_bg/PartnersStufBgRequest.xml, src/stuf/stuf_bg/utils.py
Closes #5624
**Changes**
- Added missing tag to the template of children in StUF-BG for the family members prefill plugin
- Added xsd validation to the plugin tests
- Fixed wrong mocked responses for children and partners
**Checklist**
=> [#5624] Add missing tag to the StUF-BG template for children

src/openforms/js/lang/formio/en.json, src/openforms/js/lang/formio/nl.json
Closes open-formulieren/open-forms-sdk#871 partly
**Changes**
- Added missing translations for the custom formio component (`children`)
**Checklist**
=> [OF-SDK#871] Add missing formio translations

src/openforms/js/components/formio_builder/templates/children.js
**Changes**
- Just added a missing `</div>` to the children component template in the form builder
**Checklist**
=> Add missing closing tag for div in children preview

src/openforms/submissions/api/viewsets.py, src/openforms/submissions/models/submission.py, src/openforms/submissions/tests/test_submission_suspension.py
Closes #3640
**Changes**
- Added extra validation for allowing submission to be suspended if this is allowed in the form level and if the submission is not completed.
**Checklist**
=> [#3640] Allow suspending submission only when not completed

src/openforms/scss/components/builder/_builder.scss
Closes #5429
The previous fix was for the columns preview in the formio-builder which doesn't properly vertically align if some labels wrap and others don't.
This fix is kept for the full form preview, but inside the component settings modal we can apply the regular label wrapping behaviour as the columns situation there doesn't apply.
**Checklist**
[skip: e2e]
=> Wrap label text in component preview in modal

src/openforms/prefill/contrib/objects_api/tests/test_prefill.py, src/openforms/prefill/tests/test_prefill_hook.py, src/openforms/registrations/contrib/email/plugin.py, src/openforms/registrations/contrib/objects_api/handlers/v2.py, src/openforms/registrations/contrib/zgw_apis/plugin.py, src/openforms/submissions/api/serializers.py, src/openforms/submissions/models/submission_value_variable.py, src/openforms/submissions/tests/form_logic/test_submission_logic.py, src/openforms/submissions/tests/test_get_submission_step.py, src/openforms/submissions/tests/test_variables/test_model.py
Partly closes #5134
[skip: e2e]
**Changes**
* The initial value of a submission value variable is now the empty value instead of `None`, if the related form value had no initial value
* Submission value variables and `SubmissionStep.data` are now serialized to JSON manually when saving to the DB and serializing for API response (this was done exclusively by the `DjangoJSONEncoder` before)
**Checklist**
=> Fix empty values of date related objects
